### ISSUE TITLE
Auto update doesn't work sometimes

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#10]
Related to 

> With the new version, the logs do not auto-update reliably, however. They seem to only update every few minutes. Is that a bug, or will continuous updating not work with server events?

@kmlucy I am leaving this as a placeholder until we can debug it.

**Comment by amir20** [comment]
I tried putting this behind a proxy to test it. It seemed to still work the logs showed up immediately. @kmlucy do you know how I can reproduce it?

**Comment by kmlucy** [comment]
It was a configuration issue with nginx. Apparently for eventsource, nginx needs these lines in the location block:

```
proxy_set_header Connection '';
chunked_transfer_encoding off;
proxy_buffering off;
proxy_cache off;
proxy_http_version 1.1;
```

Everything is working now.

**Comment by amir20** [comment]
Great. That makes sense.
