### ISSUE TITLE
Unraid, no containers shown

### ISSUE THREAD

**Issue by Glasti1** [amir20/dozzle#1000]
**Describe the bug**
Running on unraid 6.9 RC2. It has been running fine. But i had to recreate my containers and now dozzle is showing 0 containers active.

Running 29 containers atm. Dozzle starting streaming stats and straight after stopping streaming. see logs

**Screenshots**
![Screenshot 2021-02-10 165448](https://user-images.githubusercontent.com/57273176/107554563-68c75780-6bd6-11eb-8765-64eb19b5c1ab.jpg)

**Desktop (please complete the following information):**
 - OS: Unraid 6.9 RC2
 - Docker version 19.03.14
 - Browser & version Google Chrome Version 88.0.4324.150 (Official Build) (64-bit) Windows 10
 - Version Dozzle version 3.2.2

**If applicable include logs with `--level debug` and browser logs**

https://pastebin.com/bcpSSaX3

**Comment by Glasti1** [comment]
```docker run -d 
        --name='Dozzle' 
        --net='proxynet' 
        -e TZ="Europe/Berlin" 
        -e HOST_OS="Unraid" 
        -e 'DOZZLE_BASE'='/' 
        -e 'DOZZLE_LEVEL'='debug' 
        -e 'DOZZLE_TAILSIZE'='300'
        -p '8888:8080/tcp' 
        -v '/var/run/docker.sock':'/var/run/docker.sock':'ro' 
        'amir20/dozzle'```

**Comment by amir20** [comment]
@Glasti1 there is no errors at all in the logs. There should be an exception if Dozzle is stopping. 

Is there an error on the browser?

**Comment by Glasti1** [comment]
@amir20 Sorry! i didnt add the console message. 

I only see this `EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.`

**Comment by amir20** [comment]
Oh that would be a bad error. It explains why the connection is being aborted. Hmmm...

**Comment by Glasti1** [comment]
I am not sure if it's an unraid or dozzle issue.. not to experienced troubleshooting at this level. 

But for me it feels it's a unraid issue

**Comment by amir20** [comment]
I was doing some research and it's weird because Dozzle does return with `text/event-stream` and I confirmed that the code does set it to `text/event-stream`. 

So one of your extensions must be overwriting it.

**Comment by amir20** [comment]
I don't have a windows box so I can't test :(
