### ISSUE TITLE
Make it possible to set default settings using flags/env vars

### ISSUE THREAD

**Issue by c2h5oh** [amir20/dozzle#1037]
**Is your feature request related to a problem? Please describe.**
We use Dozzle as a part of local dev environments. Dev environments tend to break a lot, so containers are often failing and when they do they disappear from the list and time is wasted until developer finds settings and toggles "show stopped containers".

**Describe the solution you'd like**
Add an option to set default settings using flags/environment variables.

**Comment by amir20** [comment]
This is an interesting one! 

The problem is that all the settings are done on client side and stored via `localstorage`. 

How would you imagine happening with flags changing `localstorage`? I can't think of a simple solution right now.

**Comment by c2h5oh** [comment]
Distinguish between value being false and value not being set in localstorage. If not set fetch default value from api.

**Comment by amir20** [comment]
That won't work because the flag will always be set and overwrite localstorage every time. 

I've been thinking about this and it's more complicated than I thought.

**Comment by c2h5oh** [comment]
Why not? false and undefined are two distinct values. If localstorage returns undefined (no value set) fallback to api. if it returns true/false then value is set.

**Comment by amir20** [comment]
Because Dozzle writes the default values the very first time to localstorage. Next time you load Dozzle, the values be defined and it won't read from API. That's at least how it works now. If you think there is a simpler way that is more elegant then you can send a PR.

**Comment by amir20** [comment]
I took closer look at this. The way settings are written right now would make hard to sync previous config and new config. 

I think to solve your problem a better approach would be to show recent containers running or exited above all other containers. This would be easy to do. And only filter containers in the last 15 mins.

**Comment by amir20** [comment]
Not going to work on this.
