### ISSUE TITLE
RFE - Login via oAuth Google or Duo MFA

### ISSUE THREAD

**Issue by ansred** [amir20/dozzle#1085]
**Is your feature request related to a problem? Please describe.**
RFE - Login via oAuth Google so logs are not public

**Describe the solution you'd like**
Here is example from Portainer # https://documentation.portainer.io/v2.0/auth/oauth/

**Describe alternatives you've considered**
To configure HTTP Authentication from Proxy Nginx Manager.

**Additional context**
Or even better to implement Due for 2FA
https://duo.com/resources/videos/set-up-two-factor-authentication-with-duo-s-web-sdk

**Comment by amir20** [comment]
This is not something I ever plan to support. Authentication should be done through a proxy. It would make Dozzle too big if I support things that can be easily be handled through a reverse proxy.
