### ISSUE TITLE
RFE - Setup SMTP for sending alert from the logs based on entered keyword

### ISSUE THREAD

**Issue by ansred** [amir20/dozzle#1086]
**Is your feature request related to a problem? Please describe.**
RFE - Setup SMTP for sending alert from the logs based on entered keyword when it's found from a selected container

**Describe the solution you'd like**
Sending alert via SMTP or Telegram API 

**Describe alternatives you've considered**
None yet available 

**Additional context**
Here is a good example # https://github.com/Tautulli/Tautulli/wiki/Notification-Agents-Guide

**Comment by amir20** [comment]
Dozzle is not always streaming logs. Only when the UI is open. So this wouldn't happen with current architecture. 

Dozzle is focused more on debugging and seeing logs in real-time.
