### ISSUE TITLE
Support for using non-Google fonts in air-gapped deployments

### ISSUE THREAD

**Issue by tomac** [amir20/dozzle#1117]
**Is your feature request related to a problem? Please describe.**
We have some air-gapped deployments that cannot connect to the Internet. Dozzle is unable to load the app because it cannot connect to Google Fonts.

**Describe the solution you'd like**
A switch that will indicate whether we want to use Google Fonts or not.

**Comment by amir20** [comment]
Hey @tomac, I think that’s a fair ask. I want to minimize external dependencies. I had hope to some how embed google fonts but it doesn’t seem worth it. So I am going to just remove google fonts in favor using native fonts. 

I’ll release something today.

**Comment by tomac** [comment]
That's is great @amir20. Thanks for your help! I really love dozzle :)

**Comment by amir20** [comment]
Latest version should be updated and deployed. Thanks @tomac for the feedback. These edge cases are things I don't really think about.

**Comment by amir20** [comment]
@tomac just a heads up. I did a few releases. After a few tests, I found some of the fonts weren't great. I ended up doing set of fonts Github uses. `font-family: SFMono-Regular, Consolas, Liberation Mono, monaco, Menlo, monospace;`. Let me know what you think.
