### ISSUE TITLE
Long log lines are not shown, but previous line repeatedly shown

### ISSUE THREAD

**Issue by azubanov** [amir20/dozzle#1135]
**Describe the bug**
There is a long line of about 150k chars.
Instead of this line, the previous line is repeatedly shown

**To Reproduce**
Steps to reproduce the behaviour:
1. Log long line
2. Notice this behaviour

**Expected behaviour**
line is shown

**Screenshots**
Shown data
![image](https://user-images.githubusercontent.com/4849791/114165996-de7d4480-9935-11eb-92f4-4e4d6785f95f.png)
Original data
![image](https://user-images.githubusercontent.com/4849791/114166129-079dd500-9936-11eb-8c8b-4424f30f4f91.png)

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Docker version 19.03.13
 - Browser & version chrome
 - Version Dozzle 3.4.8

**Comment by amir20** [comment]
Could you copy / paste that original data so that I can try it out locally? It could either be too long (which I don't know why because I have similar data) OR one of the characters is breaking something.

**Comment by azubanov** [comment]
[87ed0f0daedc.log](https://github.com/amir20/dozzle/files/6288347/87ed0f0daedc.log)

**Comment by amir20** [comment]
Thanks. Reproduced. I'll have a fix soon.

**Comment by amir20** [comment]
Releasing 3.5.1 that should fix this.
