### ISSUE TITLE
Add seconds to timestamps

### ISSUE THREAD

**Issue by ksurl** [amir20/dozzle#1136]
**Is your feature request related to a problem? Please describe.**

Currently only displays hour:minute. troubleshooting is harder to figure when multiple changes are in the same minute in the logs

**Describe the solution you'd like**

append seconds to the timestamp

**Comment by amir20** [comment]
This was asked before. I just haven’t had time. Send a PR. It should be easy.

**Comment by ksurl** [comment]
is it [here](https://github.com/amir20/dozzle/blob/70a40cd7e40458d5fb2b4e2297039d4473bb2cd9/assets/components/RelativeTime.vue#L14)?

**Comment by amir20** [comment]
Almost. https://github.com/amir20/dozzle/blob/70a40cd7e40458d5fb2b4e2297039d4473bb2cd9/assets/components/RelativeTime.vue#L38


I use format relative from date-fns. Now I am remembering why I didn’t do this. I couldn’t figure out how to make date-fns show seconds with relative dates.

**Comment by amir20** [comment]
https://github.com/date-fns/date-fns/issues/1218#issuecomment-599182307
