### ISSUE TITLE
Horizonal scrollbar always showing on desktop

### ISSUE THREAD

**Issue by Hukuma1** [amir20/dozzle#1137]
**Describe the bug**
<img width="528" alt="dzscroll" src="https://user-images.githubusercontent.com/54511555/114283291-dee11280-99fd-11eb-8314-64d083f081e0.png">

Changing the window size larger does not make it go away. It works properly on mobile. Also slight scrolling possible vertically, but the vertical scrollbar is hidden.

Turning on use smaller scrollbars shows the small amount possible to scroll in vertical direction too:

<img width="543" alt="dzscroll2" src="https://user-images.githubusercontent.com/54511555/114283464-bf96b500-99fe-11eb-81c9-265f72a72ada.png">

Google Chrome Version 89.0.4389.114 (Official Build) (64-bit) (latest version)
Windows 10
Dozzle 3.5.1

**Comment by amir20** [comment]
My CSS is rusty and I don't a windows machine. I thought I had fixed this. Could you try to play with the css and see if you can fix it?

**Comment by Hukuma1** [comment]
<img width="818" alt="padding" src="https://user-images.githubusercontent.com/54511555/114311819-266ea980-9aa5-11eb-8e3b-fd995efe213e.png">

I'm no expert either, but removing the `-0.75rem` from `margin-left` and `margin-right` seems to do the trick. At least for desktop. Not sure if it breaks something else?  `class="columns is-centered section"`

**Comment by amir20** [comment]
Nice. I’ll play around with it. This is a good start at least. 

Sent via my iPhone
