### ISSUE TITLE
Panic: runtime error: index out of range on RHEL 7

### ISSUE THREAD

**Issue by nugut** [amir20/dozzle#1145]
**Describe the bug**
Fail when try to run on RHEL 7 with error:
```
level=info msg="Dozzle version v3.5.3"
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/amir20/dozzle/docker.(*dockerClient).ListContainers(0xc00000cae0, 0xc6b0a0, 0xc00000cae0, 0x11, 0xc00025fee8, 0x1)
        /dozzle/docker/client.go:103 +0x5cf
main.main()
        /dozzle/main.go:90 +0x111
```

**To Reproduce**
1. Run docker container on RHEL 7:
docker run --name dozzle -d --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:8080 amir20/dozzle:latest
2. See error in container log:
docker logs dozzle

**Expected behavior**
Expect normal running.

**Desktop (please complete the following information):**
 - Red Hat Enterprise Linux Server release 7.4 (Maipo)
 - Docker version 19.03.7, build 7141c199a2
 - Dozzle version: 3.5.3
 - SELinux disabled

**Comment by amir20** [comment]
@nugut The line that is erroring is

https://github.com/amir20/dozzle/blob/master/docker/client.go#L103

I don't it's related to RHEL. Can you try `docker ps`? Show me what it says there. I am going to guess that some where no names are assigned to a container. But I am not sure how to treat that when it happens. I need to show some name on UI.

**Comment by nugut** [comment]
I found that one of the containers on the host was stuck in the "Removal In Progress" state. It looks like it was the state of this container or the abnormal state of the Docker daemon that caused the problems, because after restarting the Docker daemon, the container was deleted and Dozzle started up.
After that I was unable to repeat the problem.
Thanks for your help.
