### ISSUE TITLE
Docker failing

### ISSUE THREAD

**Issue by Hukuma1** [amir20/dozzle#1160]
```
panic: runtime error: invalid memory address or nil pointer dereference,level=info msg="Dozzle version v3.6.0",
level=info msg="Accepting connections on :8080",
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x791164],
goroutine 21 [running]:,
github.com/amir20/dozzle/analytics.SendStartEvent(0xc0000220b0, 0xc, 0xc1064c, 0x6, 0x0, 0x0, 0x12c, 0x1, 0x0, 0x0),
	/dozzle/analytics/ga.go:43 +0x5c4,
main.doStartEvent(0x9c7ebe, 0x5, 0x9c545c, 0x1, 0x9c8773, 0x4, 0x12c, 0x0, 0x0, 0xc00002600b, ...),
	/dozzle/main.go:148 +0x1ce,
created by main.main,
	/dozzle/main.go:108 +0x898
```

Btw what's the analytics stuff? And it's not opt-out by default? D:

**Comment by amir20** [comment]
I think I fixed it with that commit. 


> Btw what's the analytics stuff? And it's not opt-out by default? D:

You can see the [README](https://github.com/amir20/dozzle#analytics-collected) on what I use it for. For 99%, it probably won't affect them. I collect only [anonymous](https://github.com/amir20/dozzle/blob/master/main.go#L140-L147) data like is authentication enabled, is port changed, are there any filters. 

I looked at other tools and Brew has [similar](https://docs.brew.sh/Analytics) model.  It is opt in by default. 

I do have some interesting data point now on what I should remove or improve. Of the thousands install so far, no one has changed the port, less than 1% use custom base and so far only 1% using authentication. 

This is good data point for me to know what to work on next.

**Comment by Hukuma1** [comment]
Works! Thank you.

Gotcha. I just get a bit skiddish with GA in general. Google ain't the Google from when GMail first launched. ;(

**Comment by amir20** [comment]
I did look at a bunch of alternate options for analytics but they all cost money. 

I do work for Google. :) 👀 

All of the data stored by Dozzle is anonymized though.

**Comment by Hukuma1** [comment]
> I do work for Google. :) 👀

And the penny drops!! ;)

Have you checked out Matomo? But that's probably just for website stuff, huh?

**Comment by amir20** [comment]
According to their website, in the cloud would cost me $100/month. Other option is to host it myself which will still cost me money.
