### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by direkt** [amir20/dozzle#1162]
Hello,

I keep seeing the crash below and the docker container stops.

panic: runtime error: slice bounds out of range [:12] with length 11

```
goroutine 73 [running]:
github.com/amir20/dozzle/docker.(*dockerClient).Events.func1(0xc000420000, 0xc68b80, 0xc000406240, 0xc0000980c0)
        /dozzle/docker/client.go:209 +0x22f
created by github.com/amir20/dozzle/docker.(*dockerClient).Events
        /dozzle/docker/client.go:197 +0xda
```
Any help is appreciated.

Thanks

**Comment by amir20** [comment]
Hi @direkt,

This error is occuring at https://github.com/amir20/dozzle/blob/master/docker/client.go#L209 which means that the id of the container is shorter than 12 chars. I don't know how that would happen. AFAIK, it is not possible to change the ID to something else. 

1. Is there something different about your docker configuration? 
2. Can you show `docker ps`? 
3. Can you enable `--level debug` for logs and provide that too. 

If none of those help, then I will update debugging to include the ID and have you try again.

**Comment by direkt** [comment]
Thanks for the reply.

Debug logs - 

level=info msg="Dozzle version v3.6.1"
level=debug msg="filterArgs = {map[]}"
level=info msg="Accepting connections on :8080"
level=debug msg="streaming logs for container" id=45fdf997f08e since="2021-04-20T03:00:05.275648898Z"
level=debug msg="starting to stream stats for: 45fdf997f08e"
level=debug msg="starting to stream stats for: 98ad55cb566a"
level=debug msg="starting to stream stats for: b5328c32adc0"
level=debug msg="starting to stream stats for: 236de410dca4"
level=debug msg="starting to stream stats for: 74e58af47b08"
level=debug msg="starting to stream stats for: 1319825c5bbb"
level=debug msg="starting to stream stats for: 675ac6bcbf7f"
level=debug msg="starting to stream stats for: 5da3b015b346"
level=debug msg="starting to stream stats for: 825d96096067"
level=debug msg="starting to stream stats for: 6d5b71ee7614"
level=debug msg="starting to stream stats for: 39867a92f4a2"
level=debug msg="starting to stream stats for: 37c42a394dd4"
level=debug msg="starting to stream stats for: 266a6dc537b3"
level=debug msg="starting to stream stats for: b1291792db50"
level=debug msg="starting to stream stats for: 2792f7b91ce9"
level=debug msg="starting to stream stats for: 1bc54bdbc065"
level=debug msg="starting to stream stats for: 28458ed6821d"
level=debug msg="starting to stream stats for: ec8ca40059eb"
level=debug msg="starting to stream stats for: 04feec05cf37"
panic: runtime error: slice bounds out of range [:12] with length 11

goroutine 99 [running]:
github.com/amir20/dozzle/docker.(*dockerClient).Events.func1(0xc0000986c0, 0xc27760, 0xc000406240, 0xc000098180)
        /dozzle/docker/client.go:209 +0x22f
created by github.com/amir20/dozzle/docker.(*dockerClient).Events
        /dozzle/docker/client.go:197 +0xda

Ouput of docker ps -aq

39867a92f4a2
660ee7ac3f52
74e58af47b08
6d5b71ee7614
266a6dc537b3
675ac6bcbf7f
45fdf997f08e
98ad55cb566a
2792f7b91ce9
b5328c32adc0
5da3b015b346
825d96096067
b1291792db50
1319825c5bbb
04feec05cf37
28458ed6821d
1bc54bdbc065
236de410dca4
37c42a394dd4
ec8ca40059eb

Thanks

**Comment by amir20** [comment]
Seems like `660ee7ac3f52` is the culprit.  I have no idea what the problem could be because `660ee7ac3f52` is 12 characters. 

I have update the code to ignore cases like these for now. You should see a debug log with `"Ignoring docker event with action..."`. 

It should take 15 minutes to build on Docker. Please try `latest-dev` tag then and let me know what the debug statement is. 

Thanks

**Comment by amir20** [comment]
Ready to test https://hub.docker.com/layers/amir20/dozzle/latest-dev/images/sha256-908fe94db766afbdf92068a7c9b6c12081c4c7cfa2ed61bcd55a86b4656f766b?context=repo

**Comment by direkt** [comment]
Thank you for the quick reply.  I spun it up and now I see this in the debug logs.   Will let you know if I see any more crashes.  

today at 1:50:43 PM  level=debug msg="Ignoring docker event with action: pull and actorId: postgres:10"
today at 1:50:43 PM  level=debug msg="Ignoring docker event with action: pull and actorId: postgres:10"

**Comment by amir20** [comment]
Oh! That's a good bug. I shouldn't be paying attention to pull. I'll have a better fix.

**Comment by direkt** [comment]
I see watchtower trying to do a pull at the same time of the debug message.  Let me know if you need me to test further.

Thanks

**Comment by amir20** [comment]
I should have a fix now. Going to release a new build.

**Comment by amir20** [comment]
Try `3.6.2`. It should be good now. Thanks for this. I would have never guess a pull event.

**Comment by direkt** [comment]
Looks good.  Watchtower did a pull and not seeing that message anymore.
