### ISSUE TITLE
[FR] Host logs?

### ISSUE THREAD

**Issue by Hukuma1** [amir20/dozzle#1175]
Would it be possible to add the host system logs? Ran into an issue today where I wanted to check my host machine logs (running OpenMediaVault in my example) and loaded up Dozzle. :P

**Comment by amir20** [comment]
I don't think Docker is aware of anything in the host. But you could try something like `docker run -v /somefile.log:/file.log alpine tail -f /file.log` or something like that? I haven't tested it.

**Comment by Hukuma1** [comment]
Ah I see. Thank you!
