### ISSUE TITLE
Direct link by conatiner name

### ISSUE THREAD

**Issue by 123dev** [amir20/dozzle#1199]
**Is your feature request related to a problem? Please describe.**
No

We have a use case where containers are created and destroyed on demand, however they always get created with the same names.
The flow is as follows

Scheduled runs:
1- Delete container if it already exists
2- Create container
3- Run stuff
4- Stop container

Many such scheduled runs per docker host.
The logs of each container at run time or until deletion are valuable, hence the usefulness of Dozzle.

Because these containers are re-created, their container IDs are different on each run, however their names are always constant.
Looking for a feature (a direct link) that would take us directly to the container logs by name instead of (or in addition to) id
Currently we have something like this:
`container/7e94167cb197`
Would like something like this
`container?name=container1` or `container/conatiner1`

Not sure if this is feasible or even worth the effort if it is an isolated use case.

Thanks in advance.

**Comment by amir20** [comment]
Hey @123dev this is actually already implemented. 😎 see #471. Basically you should be able to send your tools to `show?name=xxx` and it will find the container by name and redirect to id.

**Comment by amir20** [comment]
I should find a place to document this though.

**Comment by 123dev** [comment]
Love it, many thanks.
