### ISSUE TITLE
[Feature Request] Menu auto-collapse after selecting container

### ISSUE THREAD

**Issue by subatomiq** [amir20/dozzle#12]
When viewing on mobile I'd really like to see the menu auto-collapse after selecting a container to view
- currently with a large number of containers, it's a quite difficult to quickly switch between containers (this is only a problem for me when viewing on mobile)

**Comment by amir20** [comment]
I am working on this. It should be done this week. 

Sent via my iPhone

**Comment by amir20** [comment]
Actually that was easier than I thought. Checkout `v1.5.4` for the fix

**Comment by subatomiq** [comment]
nice one Amir - that's heaps better
