### ISSUE TITLE
Error combining --base and --username

### ISSUE THREAD

**Issue by stefansielaff** [amir20/dozzle#1205]
**Describe the bug**
When using --base in combination with --username/--password/--key the request is redirected incorrectly

**To Reproduce**
1. Define e.g. --base /logs and "login" parameters in combination
2. Go to example.com/logs
3. A redirect to example.com/logslogin occurs, answering 404
4. Define e.g. --base /logs/ and "login" parameters in combination
5. Go to example.com/logs
6. An infinite redirect to example.com/logs/login occurs

**Expected behavior**
The login page

**Desktop (please complete the following information):**
 - OS: Windows / Arch Linux Docker Host / nginx reverse proxy
 - Docker version 20.10.6
 - Browser & version Chrome / Firefox
 - Version latest

I think there's somethin wrong here in routes.go but unfortunately I'm not skilled enough in go to provide a pull request. 

if !isAuthorized(req) && req.URL.Path != "login" {
	http.Redirect(w, req, h.config.Base+"login", http.StatusTemporaryRedirect)
	return
}

Thanks for your great work!

**Comment by amir20** [comment]
Yea this is a bug. I’ll see if I can do a quick fix.

**Comment by amir20** [comment]
Should be fixed with that commit. Going to release a new version.

**Comment by stefansielaff** [comment]
Confirmed working now in my environment, that was fast!
