### ISSUE TITLE
Development tag and Log Level

### ISSUE THREAD

**Issue by ajhorvath20** [amir20/dozzle#1236]
Hi is there any `development` tag which I can use other than `:latest`.

Also is there any other log levels we have in dozzle apart from `info`?

Thanks

**Comment by amir20** [comment]
Development tag is `latest-dev` and you can see [releases](https://hub.docker.com/r/amir20/dozzle/tags?page=1&ordering=last_updated) here.  I'd be careful using dev as it is not stable. 

For logs, there is `warn`, `info` and `debug`. I use debug often. 

Close if you are good.

**Comment by ajhorvath20** [comment]
Thanks @amir20 much appreciated.
