### ISSUE TITLE
Can't view logs when container is set as `tty: true`

### ISSUE THREAD

**Issue by j0hnm4r5** [amir20/dozzle#126]
Using `docker-compose`, if I set a container to `tty: true`, none of the logs are visible on the web GUI (I can however see that the container does exist).

**Comment by amir20** [comment]
tty will redirect stdout and stdin to terminal. So I wouldn’t expect it to work unless you configure loggers too. Therefore, it works as expected.

**Comment by amir20** [comment]
Haven't heard back, so closing.
