### ISSUE TITLE
Environment variable to set "Show stopped containers" as true

### ISSUE THREAD

**Issue by lclc** [amir20/dozzle#1296]
**Is your feature request related to a problem? Please describe.**
I'd like to have this set as True by default from my docker-compose.

**Describe the solution you'd like**

Flag | Env Variable | Default
-- | -- | --
--show-stopped-containers | DOZZLE_SHOW_STOPPED | false

Or default _true_. I think true would be good for debugging when the containers didn't start and I forgot to enable this, but that would be a change of the defaults.

Thanks for developing and maintaining dozzle! It's really helpful and simple to use.

**Comment by amir20** [comment]
@lclc I had looked at this in the past. It would be difficult to implement something like this. All settings are stored on client side with local storage. Overriding something like this would have conflict after first time dozzle is viewed. It would also be confusing to allow settings to be forced for all users. 

I think a better solution would be to have a group on top called “recently stopped”. That way anybody can jump to any recent containers regardless of settings.  

I just had a baby so I don’t have much time. 

If you know JavaScript then my proposed solution should be simple for a PR.

**Comment by lclc** [comment]
Congratulations on the baby!


Thanks for taking the time to explain. What about changing the default to _true_ in general?   I guess it depends on how many containers people have on their server/system, but I imagine it isn't too many. Then you see immediately if a container is stopped that should actually be running.

I'm at constant war with JavaScript, and usually, I'm losing 😅

**Comment by amir20** [comment]
I don’t think that would work. I have personally 100s of containers while only running a dozen.

**Comment by amir20** [comment]
Closing since I won’t work on this.
