### ISSUE TITLE
[Question] Hide Container-Selection Sidebar

### ISSUE THREAD

**Issue by Kippenhof** [amir20/dozzle#1338]
Hey there :)

I want to hide the sidebar for the Container-Selection [Screenshot bellow], since i just want to monitor one container, and just have the Logs.

i want to put it behind an Reverse-Proxy & Authelia.

Is there any way to do that?

# IMG-1
![Sidebar](https://user-images.githubusercontent.com/54744977/124338967-139ed900-dbab-11eb-9842-a5468b2596dd.png)

## Why should somebody do something like that?
I want to give People access to the logs of [streetmerchant](https://github.com/jef/streetmerchant)

**Comment by amir20** [comment]
You could use filter flag to only show logs for a specific container but visually you can’t hide it by default.

**Comment by Kippenhof** [comment]
Is there something in the source code, that i can change to hide it? If so i can change it and recompile the image for me.

**Comment by amir20** [comment]
Writing from phone. 

Look for App.vue. You can remove the menu there. 

But how would users find the container to click on? Don’t you need a way to still show the container page?

**Comment by Kippenhof** [comment]
> Writing from phone.
> 
> Look for App.vue. You can remove the menu there.
> 
> But how would users find the container to click on? Don’t you need a way to still show the container page?

They Simply shouldn't. You wrote in the docs that you can get a redirect when you make a query with the containers name in the url. I will put that into my nginx config and you will only see the container thats relevant.

**Comment by Kippenhof** [comment]
For me it was enough to change the collapseNav value in the App.vue to true. It's not perfect, but enough for me

**Comment by amir20** [comment]
Nice. Still make sure you use filter for security.

**Comment by Kippenhof** [comment]
> Nice. Still make sure you use filter for security.

Okay, how can i do that?

And is that even relevant behind Authelia 1 Factor Auth?

**Comment by amir20** [comment]
It’s one of the cli command args. You can look it up in the read me. Still on phone. 

Of course you still need it. Without it anybody can look at all of your logs by changing the url.

**Comment by amir20** [comment]
https://github.com/amir20/dozzle#security

**Comment by Kippenhof** [comment]
> It’s one of the cli command args. You can look it up in the read me. Still on phone.
> 
> Of course you still need it. Without it anybody can look at all of your logs by changing the url.

ah okay, thats what you're meaning. The Reason why i was trying to disable the Menu in the First place was non Security Related since i only Create Logins for People that i trust in my LDAP Container.it should only be for not confusing them.

But it looks really easy to do, so i will do that.

Thanks :)
