### ISSUE TITLE
Don't run as root

### ISSUE THREAD

**Issue by yscialom** [amir20/dozzle#1352]
**Is your feature request related to a problem? Please describe.**
A security good practice is to not run docker containers as root. Dozzle runs as root.

**Describe the solution you'd like**
Dozzle would run as `dozzle` user, ideally with an uid and gid defined by environment variables `PUID` and `GUID`. See all linuxserver.io images for reference.

**Describe alternatives you've considered**
Dozzle would run as `dozzle` user, created at image creation.

**Comment by amir20** [comment]
What’s a good example? Can you send a PR? I looked at one or two linuxserver but they didn’t have any users.

**Comment by yscialom** [comment]
Yes it's all in their base image (see their [adduser script](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/10-adduser)), but it's probably a bit too much for your minimal image. I've just cloned your repo, I might do a PR tonight if I don't fall asleep on my desk.

**Comment by amir20** [comment]
This blog seems like a good way to do it. 
https://blog.cubieserver.de/2021/the-ideal-dockerfile-for-a-minimal-go-container-image/

Can you send a PR @yscialom?

**Comment by amir20** [comment]
I won’t have time to do this.
