### ISSUE TITLE
Feature Request - Ability to add custom log files

### ISSUE THREAD

**Issue by samcro1967** [amir20/dozzle#1385]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would it be possible to add the ability to add any log that is mounted to the container and not just Docker container logs?  I would like to mount a folder at say /docker and then add a custom log file at "/docker/plex/logs/Plex Media Server.log" with a name of "Plex Media Server Log" that is displayed along with the containers so I can select it and see the log file in the browser.

**Describe alternatives you've considered**
I was using [Logarr](https://github.com/Monitorr/logarr), but it has not been maintained in several years.  Trying to find a similiar self-hosted replacement that provides an easy way to present application log files via a browser.

**Comment by amir20** [comment]
No, because Dozzle uses Docker API to get `stdout`. You could spin up something like a tail with `tail -f /this/other/file.log` but the prefered way is to just have it in stdout.

**Comment by samcro1967** [comment]
Ok.  Was hoping it might be an easy extension for that use case.  Does not seem to be a good solution out there to replace Logarr.  I will probably just setup a browse option on my reverse proxy and then add links to the log files in Heimdall, not elegant, but functional.
