### ISSUE TITLE
Need a build for linux/arm/v6

### ISSUE THREAD

**Issue by hemna** [amir20/dozzle#1394]
Do you have a docker image built for linux/arm/v6 ?   I'm trying to use it on a raspberry pi zero w

**Comment by amir20** [comment]
There is armV7. That works on my RsPi. Is it not working? I don’t think it would be hard to add v6. What’s the error message?

Sent via my iPhone

**Comment by amir20** [comment]
Any update @hemna? I’ll close if I don’t hear back because I think it should already work.
