### ISSUE TITLE
Duplicate log entries

### ISSUE THREAD

**Issue by oliroe** [amir20/dozzle#1404]
**Describe the bug**
Duplicate entries appear when looking at any container
![image](https://user-images.githubusercontent.com/4500141/128601232-c6e8bc31-b252-41e8-9429-a14d081e4c5e.png)

**To Reproduce**
View any container and wait, the previous entry will appear over and over again. Refreshing the browser removes the duplicates. Duplicates do not exist in the log of the container

**Expected behavior**
Dozzle log reflects the container log without duplicates

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/4500141/128601289-c6805d1d-1f75-4fa5-9a6a-88f7666c06e6.png)

After refreshing Chrome
![image](https://user-images.githubusercontent.com/4500141/128601298-59d79c07-9fb4-4d55-9b69-248b1a7b82e3.png)

**Desktop (please complete the following information):**
 - OS: Synology NAS
 - Docker version 20.10.3 (API: 1.41)
 - Browser & version [Chrome]
 - Version [3.7.1]

**If applicable include logs with `--level debug` and browser logs**

**Comment by oliroe** [comment]
Hoping this may help, these entries appear in the Chrome console when the duplicate appears

![image](https://user-images.githubusercontent.com/4500141/128601797-d5ae4b9e-23e4-43f7-9fe0-7f7d1ef468f6.png)

**Comment by amir20** [comment]
I don't know what that error means. 

Can you check to following?

1. Is Dozzle showing any errors? 
2. Are you in some kind of corp env? I don't know why EventSource failed. 

I read some where the EventSource failed might be a server side error. So hopefully you can see some kind of error logs.

**Comment by oliroe** [comment]
Hi

Dozzle is showing no errors whatsoever but it appears the issue is only present when viewing through a reverse proxy. If I use localhost or the internal IP of the server there's no issue

It's weird because however else I view the logs I don't see the issue (using portainer, directly in the container or the Synolody Docker GUI). The issue only exists with Dozzle behind a reverse proxy.

**Comment by amir20** [comment]
Ah that makes sense. Event streams are like web sockets. They stay live forever. Your proxy is probably not handling it correctly. 

What is your proxy and how is it configured? For nginx there is a section in README that you can see for examples.

**Comment by oliroe** [comment]
Thanks. Looks like it's a local issue with my set up then.

I'm using Synology's built in reverse proxy which is based on nginx. I've got about 30 docker apps running and the basic settings have never been a problem. Guess I'll need to look into event streams.

I'll post back if I manage to sort it but can always just use Dozzle when on the same network

Thanks again

**Comment by amir20** [comment]
I also have a Synology server. But I haven’t seen this issue. I am hitting the server directly, though. Let me know what you find or how I can reproduce.

**Comment by oliroe** [comment]
Think I'm going to have to admit defeat on this one, spent a couple of days but don't seem to be able to get rid of the issue

https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate

The link above seemed to be the closest to my issue but adding those settings haven't helped. In summary, no issue when not using reverse proxy but see duplicate log entries when I do.

**Comment by oliroe** [comment]
Definitely getting beyond my area of expertise here. Set up NPM specifically to try and fix this issue but I get the same problem using Nginx directly. Not worth the hassle for me to completely change reverse proxy and export/import SSL certs so I think I'll stick to looking at Dozzle internally.

If anyone does have dozzle working behind Nginx without duplicate log entries could your post your config here?

Thanks

**Comment by amir20** [comment]
Did you see the readme? https://github.com/amir20/dozzle#troubleshooting-and-faqs I already pass those headers from Dozzle. 

I can try on my Synology this week. 

What proxy are you using? I didn’t know Synology had built in one.

**Comment by amir20** [comment]
Hmm I couldn't find a proxy option in my Synology.

**Comment by oliroe** [comment]
Have you upgraded to DSM7 because the reverse proxy settings have moved since DSM6 (and the guide linked above)

![image](https://user-images.githubusercontent.com/4500141/128641913-93574952-c64e-4d78-895e-47a688e03fae.png)

Synology have a simplified reverse proxy based on nginx, apache and the ability to register and renew letsencrpt SSL certs. It's really straightforward and does the job for all my other containers so I'm reticent to move to another reverse proxy.

Having said that I hate being beaten so I'll probably spend all night trying to fix it :)

**Comment by amir20** [comment]
I do have DSM7. Thanks for the screenshot. I’ll try again. 

Sent via my iPhone

**Comment by amir20** [comment]
@oliroe I was able to reproduce this. Sadly, Synology Nginx cannot be configured. The reason you are seeing this error is because it has a default timeout of 60 seconds. You can find this setting in the Advanced settings. This doesn't work with "always live" connections because the proxy shuts down the connection and then the browser tries to reconnect, which is why you are seeing that error. 

I was able to set the timeout to `1000s` which is roughly about 14 minutes. See below. 

<img width="603" alt="Screen Shot 2021-08-08 at 1 27 03 PM" src="https://user-images.githubusercontent.com/260667/128644769-dd6cd54c-0edf-4390-a017-2d350091c00e.png">

14 minutes is better than 1 minute but still not perfect. I did some research and there doesn't seem to be an option to completely disable this. 

I am not sure how technical you are, but my advice would be to use something like Traefik instead. Here is an [example](https://www.smarthomebeginner.com/synology-docker-media-server/). It supports http2 and does automatic SSL configuration. HTTP2 is important as it handles live connections better. 

I don't think you can use the Synology default proxy.  Your only option is to create your own proxy via traefik, nginx or something else. 

Good luck!

**Comment by oliroe** [comment]
@amir20 
Awesome bit of detective work there, really appreciate it. Randomly it looks like you can actually set the values to 79,999 which is more than enough for my purpose. No doubt I'll come across another issue where it would be easier using Nginx or Traefik but I'll settle for what I have right now.

Thanks again for pointing me in the right direction

**Comment by amir20** [comment]
That's funny. I tried 99999 with no luck. That is a random number. Glad you found a solution.

**Comment by EDIflyer** [comment]
Just to add, for those using [nginx proxy manager](https://github.com/NginxProxyManager) you can add `proxy_read_timeout 30m;` in the advanced/custom settings for the proxy (found in https://github.com/NginxProxyManager/nginx-proxy-manager/issues/257#issuecomment-893490986) - seems to do the trick!

![image](https://user-images.githubusercontent.com/13610277/178593456-91d51562-8294-4196-b7d3-605167515aef.png)
