### ISSUE TITLE
Color coding of logs like lnav?

### ISSUE THREAD

**Issue by hemna** [amir20/dozzle#1414]
**Is your feature request related to a problem? Please describe.**
Some log files are hard to read with a single font color

I frequently use lnav https://lnav.org/ for log file viewing on the filesystem outside of containers.
It would be a great feature to add to dozzle to make reading the logs much easier.

**Describe the solution you'd like**
lnav has a nice system in place to extend supporting different log formats such as these formats json files here:
https://github.com/tstack/lnav/tree/master/src/formats

Maybe some of the same config/tooling can be used for dozzle to make the log files easier to read.

**Additional context**

![Screen Shot 2021-08-12 at 11 04 34 AM](https://user-images.githubusercontent.com/672207/129220896-d85ff706-86df-4a2b-a5d8-d1cba541787b.png)

vs lnav output here:

![Screen Shot 2021-08-12 at 11 04 53 AM](https://user-images.githubusercontent.com/672207/129220694-c7b284f8-cfc1-4ca6-a54e-05f82abd3df0.png)

**Comment by amir20** [comment]
Hey @hemna, thanks for the idea. I usually focus on features that are more popular amongst all users. I haven't seen many people asking for this feature and the effort is fairly high.  I don't plan to do it and maybe someone else can offer a PR. 

By the way, colors are support if you do decide to print with colors. But you need to have `interactive` mode enabled.
