### ISSUE TITLE
Is possible to show stopped time point?

### ISSUE THREAD

**Issue by NobeKanai** [amir20/dozzle#1415]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, the timestamp of the ‘Container stopped’ log is the time when I opened the logging page. Is possible to show container's real stopped time point?
I use crontab to execute programs periodically, the exact time of program exit is important to me.

**Describe the solution you'd like**
As said above.

**Describe alternatives you've considered**
I have no idea, maybe I should ask the developer of the application container to print the log at the end of the program.

**Comment by amir20** [comment]
This has bothered me too. Unfortunately, Docker API doesn't provide when a container was shutdown. See [here](https://docs.docker.com/engine/api/v1.24/#31-containers). I only see created datetime.
