### ISSUE TITLE
Log Filtering

### ISSUE THREAD

**Issue by lukou31** [amir20/dozzle#1441]
It will be interresing for me not only to find keyword but also to have a filtering field to dispaly only what i need during the execution of the containered app.

**Comment by amir20** [comment]
I am not sure what you mean. Can you explain? Do you mean parse JSON logs?

**Comment by lukou31** [comment]
When you are looking for something in the log from the aplication, it could be difficult to find the information. So by adding a function to filter (like ctrl+F to find), you can add  criteria (a string) to display only what do you want to check. It's like a " cat file.log | grep something" in a unix command line.

**Comment by amir20** [comment]
That's already done. You can search with regex using ctrl+f.

**Comment by lukou31** [comment]
I suppose it's new because it's not the behaviour I have seen in a earlier version.  So it's cool to have it now. Thanks for your message.
