### ISSUE TITLE
List of containers not refreshed

### ISSUE THREAD

**Issue by lukou31** [amir20/dozzle#1450]
In the home page, the container list (container tile) is not refreshed when you swith from running/full. 
1) There is no the entire list of deployed containers 
2) There is no adjusted list of running/stopped containers.

![image](https://user-images.githubusercontent.com/89322267/132128170-2e114cb9-5209-4935-a5e7-5f809ae0733d.png)

In the left pane, no issues.

Version 3.8.0
Docker / Synology DSM7

**Comment by amir20** [comment]
Just looking at this. @lukou31 why would you expect to see the entire list here? It's just a landing page. 

Adjusting running/stopped does nothing because there is already an option to toggle.
