### ISSUE TITLE
Dozzle on Kubernetes/Openshift?

### ISSUE THREAD

**Issue by ckocyigit** [amir20/dozzle#1471]
**Is your feature request related to a problem? Please describe.**
Iam using Dozzle personally and presented this tool on a team meeting for a IT-Project. We have a lot of people in the project who are not familiar enough with tools like Kibana and really liked the simplicity of Dozzle. However Dozzle connects to the local docker socket and our project is based on Openshift which is a Kubernetes based enterprise solution for containers. 

**Describe the solution you'd like**
Is it possible to run dozzle as a Daemon Set or is the another effective way to run Dozzle on Kubernetes

**Comment by amir20** [comment]
Hi there,

It is possible to use Dozzle with a remote host using DOCKER_HOST. 

However, that doesn't mean k8s will be supported. Docker API is different than k8s, so it wouldn't be compatible. 

I am glad your team like the simplicity. I have tried hard to keep that way. If your team knows Golang and family with k8s API then perhaps you can send a PR.
