### ISSUE TITLE
[Feature Request] Move Tail's length to environment variable

### ISSUE THREAD

**Issue by lorsabyan** [amir20/dozzle#15]
https://github.com/amir20/dozzle/blob/e06d6a111affc4996cd50c5c567a98c12590a996/docker/client.go#L77

**Comment by amir20** [comment]
This should be easy to do. I'll see if i can make it really quick.

**Comment by amir20** [comment]
@lorsabyan checkout the latest version deployed. I added env variable `TAIL_SIZE` and you should be able to override it now. Note that if the value is really large, it will degrade performance.

**Comment by amir20** [comment]
You'd want `v1.5.10`

**Comment by myrison** [comment]
@amir20 , thank you for your awesome tool.  I noticed this parameter was removed in a later commit.  Is it still possible to configure the tail length in the current version?  Thank you.

**Comment by amir20** [comment]
> @amir20 , thank you for your awesome tool.  I noticed this parameter was removed in a later commit.  Is it still possible to configure the tail length in the current version?  Thank you.

It is not possible. Mostly because the tail parameter is no longer needed. Dozzle automatically loads scrolling up. Loading too much will freeze the browser.

**Comment by myrison** [comment]
Thanks @amir20 , I didn't realize the scroll back works indefinitely without limits, thanks for clarifying.
