### ISSUE TITLE
Possibility to clear/hide old logs per container / globally

### ISSUE THREAD

**Issue by maio** [amir20/dozzle#1547]
When working on my services a lot of times I want to see what logs are produced
by an action which I'm going to perform next (e.g., when I run some end to end test).

In order to quickly see what did get logged I often clear my console before I execute
such action. In dozzle it's not possible to do so and I have to remember/figure out
which log messages are 'old' and which are new - produced by the action.

I would love if there would be some way to clear/hide these old logs (e.g. by hitting some
button) - globally and/or per service.

PS: thanks for dozzle! It's really nice.

**Comment by Coteh** [comment]
Added a [PR](https://github.com/amir20/dozzle/pull/1584) for the change :) 

Also want to comment about the jump to line, this is something I would like to have as well when searching for logs and context surrounding it. Perhaps a separate issue can be created, and I would like to take a stab at that as well if possible.

**Comment by amir20** [comment]
Excellent work @Coteh. I provided some feedback. 

The search toggle is a little harder. But if you like to take a jab at it then why not. 

If you are really up to it, I have been waiting to migrate to Vue 3. I am going to create some feature asks and let you go at 'em.

**Comment by amir20** [comment]
I created a bunch of other bugs that have been thinking about.
