### ISSUE TITLE
Dozzle fails to load stream for Docker-compose with flag `tty:True`

### ISSUE THREAD

**Issue by IAMtheIAM** [amir20/dozzle#157]
The dozzle output remains blank and the network tab of the browser shows the `/stream?id=######` API call to never start nor finish. It receives no data back.

Steps to reproduce
- Start any [gekkobot](https://github.com/askmike/gekko) container
- Start Dozzle
- Try to connect to the gekkobot container output in Dozzle

I really want this to work, because Dozzle is perfect for viewing the output of an automated trading bot.

This is an example of the output from a Gekko container straight from docker CLI
```
Creating gekkobot_gekko-cli-test ... done
Attaching to gekkobot_gekko-cli-test
gekko-cli-test  | 
gekko-cli-test  |     ______   ________  __    __  __    __   ______
gekko-cli-test  |    /      \ /        |/  |  /  |/  |  /  | /      \
gekko-cli-test  |   /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
gekko-cli-test  |   $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
gekko-cli-test  |   $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
gekko-cli-test  |   $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
gekko-cli-test  |   $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
gekko-cli-test  |   $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
gekko-cli-test  |    $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/
gekko-cli-test  | 
gekko-cli-test  | 	Gekko v0.6.8
gekko-cli-test  | 	I'm gonna make you rich, Bud Fox. 
gekko-cli-test  | 
gekko-cli-test  | 
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):	Setting up Gekko in realtime mode
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):	
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):	Setting up:
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):		 Candle writer
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):		 Store candles in a database
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):	
gekko-cli-test  | 
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):	Setting up:
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):		 Trading Advisor
gekko-cli-test  | 2019-10-29 15:22:40 (INFO):		 Calculate trading advice

```
Dozzle is working for any other container and shows the output, but strangely I do see a console error
```
Firefox can’t establish a connection to the server at https://dozzle.domain.com/api/events/stream. main.b644d699.js:12:278
The connection to https://dozzle.domain.com/api/logs/stream?id=################ was interrupted while the page was loading.
```

Even with that error, it still loads the stream for the non gekko containers. Any idea why it won't load the gekko container stream, with no response from the API?

And, what is the meaning of the console error for the containers even when it loads fine?

**Comment by amir20** [comment]
Hmmm. I don't have a sample config file so I wasn't able to run it correctly. But I was able to run it for a moment just to see the error. 

<img width="1259" alt="Screen Shot 2019-10-29 at 8 27 43 AM" src="https://user-images.githubusercontent.com/260667/67782485-120c2d80-fa26-11e9-927a-f8d7c058ed4b.png">

It seems to work for me. I am using latest version of chrome. 

I am guessing that you may shut down the server and that's why firefox complains. 

What docker command are you using to run this docker container and can you share your config file?

**Comment by IAMtheIAM** [comment]
Wow, thanks for the fast reply. And hmmmmm, you got it working. Now I'm scratching my head.

I ran `docker-compose -f docker-compose.test.yml up`

What command did you run to get that basic output with no config file?

**Comment by amir20** [comment]
I just did `docker run s73vink/gekko`. Can you try that too? I wonder if there is something different with your compose file.

**Comment by amir20** [comment]
Hmm ok. Let me know! Because I have a couple other people have similar problems but I was never able to help them as I could reproduce.

**Comment by IAMtheIAM** [comment]
Alright, I was able to reproduce the error usually a completely stock gekko install.

- Clone gekko `git clone https://github.com/askmike/gekko.git`  - use `stable` branch
- Modify package.json - remove all `^` from package prefixes, particularly `talib`. The latest version of talib 1.1.3 is broken, so use dont take latest. 1.0.2 works.
- Run `docker build --tag me/gekko:1.0` any tag name works
- Create a simple compose-file called `docker-compose.macd.yml` linking the image to the tag and the default config.
```
version: '3'
services:
  gekko-cli-macd:
    image: me/gekko:1.0
    command: ["--config", "sample-config.js"]
    volumes:
      # Add all configs here so they can be changed without rebuilding docker
      - ./sample-config.js:/usr/src/app/sample-config.js
    tty: true
    restart: always
```
- Run `docker-compose -f docker-compose.macd.yml up`

Now notice that the gekko but is running, but Dozzle won't show any output for it. 

So, I don't know why that image `s73vink/gekko` works with Dozzle, but it is 2 years old afterall, so something must have changed in the image which is causing conflict with Dozzle. Let me know if you can reproduce now.

**Comment by IAMtheIAM** [comment]
Oh jeez. I just figured it out... `tty: true` that busts Dozzle. When I removed it... it worked!

I wonder why that breaks it?

**Comment by amir20** [comment]
That’s to be expected. When you enable tty you are telling docker to not forward all logs to the driver and instead send it to screen. 

I haven’t been able to figure it out how to make it work because this is how docker works. 

Sent via my iPhone

**Comment by IAMtheIAM** [comment]
Interesting, thanks for telling me. Just curious, what is the purpose of enabling TTY then? because the output went to the screen when it was on, and also when its off.

I'll mark this as closed since it's resolved.

**Comment by IAMtheIAM** [comment]
@amir20 I just realized something. The only way I know of getting docker-compose to output colorized logs is to use `tty: true` See https://github.com/docker/compose/issues/2231#issuecomment-165137408

Without tty:true, all docker-compose logs are just white text. But with tty:true, I get colorized logs in docker's log, but dozzle doesn't work.

How can I get colorized logs in docker while still using dozzle?

**Comment by amir20** [comment]
Hi @IAMtheIAM, TTY and colors are two different things. Most likely, your logging library is detecting if TTY is enabled and uses colors if it is. You can force this. For example, in logrus you can do [ForceColors](https://github.com/sirupsen/logrus#formatters). 

I have yet to figure it out how to support TTY. So if you know of a way, we can add it.

**Comment by IAMtheIAM** [comment]
Ohh that's interesting. I guess I was equating TTY and Colors.  I'm just using javascript `console.log` with a wrapper that uses [Chalk](https://github.com/chalk/chalk). like this `console.log(chalk.blue('Colors!'));`

 From what I gather, chalk just inserts terminal string styling. So I don't really need TTY, just need to spoof `chalk` into thinking it's there or forcing it to work. I will see if there's a force option and update.

**Comment by IAMtheIAM** [comment]
HA! It works! 

I can force it with a docker-compose environment variable `FORCE_COLOR=2` or by appending `--colors` to the nodejs process. Thanks for helping me figure that out! You are so helpful @amir20  :-D

**Comment by amir20** [comment]
Nice. Good to hear. I was able to read more on TTY and there might be a way to make it work. But sounds like a lot of extra work as the format completely changes when TTY is enabled.

**Comment by IAMtheIAM** [comment]
Cool. Might not be necessary if we can just force color output. Thanks again.

**Comment by amir20** [comment]
@IAMtheIAM With #168, I may have been able to add TTY support. Can you try `v1.16.0`?

**Comment by IAMtheIAM** [comment]
You da man! Dozzle works with TTY now, and my colors got enabled as expected even when I disabled the FORCE flag. Thanks! I'll switch to TTY instead since libraries often detect that and behave differently.

**Comment by amir20** [comment]
That's great to hear. Funny when tty is true, it even captures inputs. But I guess that's how TTY interactive works. 

Good to hear everything else works.

**Comment by IAMtheIAM** [comment]
Interesting. You mean the dozzle interface will pass through commands like ctrl+c? It didn't work when I tried.
