### ISSUE TITLE
Dozzle doesn't escape angle brackets <> resulting in missing text

### ISSUE THREAD

**Issue by taavi223** [amir20/dozzle#158]
A lot of my log text contains angle brackets <> and dozzle just pipes it directly into the page source without escaping it, resulting in my browser treating a lot of my log text as HTML tags. Can you update the ansi-to-html converter to use the escapeXML option, or at least add an option to do so?

**Comment by amir20** [comment]
I added https://github.com/amir20/dozzle/commit/e8ab871efbe0d20789502b66332a1e2483ca2ec9. But have no way of testing it right now. I should be released with `v1.15.9` in a few minutes. Can you give it a try? 

You can also send me a PR since it's pretty easy to change the js file.

**Comment by taavi223** [comment]
I'll test it out tomorrow and let you know. Thanks for such a fast response!

**Comment by taavi223** [comment]
Tested out the v1.15.9 release and I can now see logs with angle brackets in them. Thanks so much for the quick resolution.
