### ISSUE TITLE
Show container image tag in log view

### ISSUE THREAD

**Issue by dodgex** [amir20/dozzle#1582]
**Is your feature request related to a problem? Please describe.**
We use dozzle to show view logs of our containers, often it would be nice to see the image tag/version the container is running

**Describe the solution you'd like**
It would be cool if dozzle would show the image tag in the top bar, eg after the container name

e.g: "your_awsome_container (awesome/image:v1.2.3)"

**Comment by amir20** [comment]
3.8.4 is live

**Comment by dodgex** [comment]
Hey amir,

I just updated our dozzle containers to 3.8.5. And you where right, there is an issue when the title is too long. :(

On short container and image names it works fine:
![image](https://user-images.githubusercontent.com/204013/139650998-c2cb1780-dbaa-438a-a427-347b1b492c46.png)

But for containers within our in-house registry the tag is not visible
![image](https://user-images.githubusercontent.com/204013/139651177-e3f0aa46-03d3-44f5-ac95-c780fb257a9c.png)

I checked the DOM to see what is happening:
![image](https://user-images.githubusercontent.com/204013/139651403-ff7d1973-3765-4eb8-ba04-e209221e0277.png)

You have the `span` that contains the container name and the new `span` with the image/tag, the outer span has `overflow: hidden`and `text-overflow: ellipsis`, which where OK for just the container name, but here are cutting the whole `span` with the image/tag.

Without having tested how easy it is or how good it might work, maybe make the container info (running; mem; load) right aligned to free more space for the name and tag. From my testing in dev tools, changing the `is-clipped` from the status div to `is-narrow` should be enough.

![image](https://user-images.githubusercontent.com/204013/139652564-78592996-3478-4f6f-bee5-20571f0bd329.png)

What do you think?

**Comment by amir20** [comment]
That might be a good idea. @Coteh is making some changes in #1547 that might remove the download button to another location. Let's see what happens with that and i can update it to possibly do what you suggested.

**Comment by amir20** [comment]
@dodgex try master for now because i think the change was simple enough.

**Comment by dodgex** [comment]
@amir20 I just tested the master tag on one of our test machines. works like a charm!

Thank you for the fast fixes.
