### ISSUE TITLE
Need help: Move icons to antfu/unplugin-icons

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#1587]
I recently used https://github.com/antfu/unplugin-icons for a different project. It's a great project which could replaces the icons in dozzle. 

See webpack integration.

**Comment by Coteh** [comment]
I believe dozzle currently uses IcoMoon Free pack for all its icons, correct? Seems like Iconify (which unplugin-icons uses) has IcoMoon available (see [this link](https://icon-sets.iconify.design/icomoon-free/). Should IcoMoon continue to be used, or do you have a different icon set in mind?

**Comment by amir20** [comment]
I used IcoMoons because that's what was free at the time. I am open to using a new set of icons as long it's consistent. I do like the thinner looking icons personally. The only important thing is for the icons to be included with the html or Js. Some people use dozzle inside a private network.

**Comment by Coteh** [comment]
Seems like the chevron icons are not part of IcoMoon Free. Do you recall where you got them?

Perhaps we can find an icon set that has both chevron icons and thinner icons, or we could mix and match icon sets. What do you think?

**Comment by amir20** [comment]
I was never a fan of the icons I chose. I am open to using new icon sets. 

By the way, I have a branch working with vue3 and vitejs. It removes webapxk completely. So very soon we can leverage the latest. 

Sent via my iPhone
