### ISSUE TITLE
Ability to provide name (and timestamp) to downloaded logs

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1589]
**Is your feature request related to a problem? Please describe.**
It would be nice if downloaded logs could either contain a custom name, or a timestamped name based on container name. I often download numerous logs per day using this tool, and I would prefer not to have to do as much cognitive work to figure out which log belongs to which container.

**Describe the solution you'd like**
Suppose my container has the name "my-service". Currently the log downloaded is named just its container ID (ie. not its container name). I would prefer if the downloaded log name is something like "my-service-2021-11-03-11-44-00" (wouldn't be that exact datetime format but you get the idea).

**Describe alternatives you've considered**
Could also allow user to input the name they'd like to call the log file. But I think it'd be easier on both an implementation and user perspective if we just automatically name it based on container name (or container id if unavailable) and timestamp it.

**Additional context**
Would like to pick this up myself after I complete the clear logs issue.

**Comment by amir20** [comment]
That would be easy enough to do. Just one line change. Send a pr or I'll get to it later this week.
