### ISSUE TITLE
Toolbar should be hidden when searching

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#1592]
I think it's weird to have a download button and reset when searching. We can hide it since search is temporary and clearing the messages will be done to everything. 

@Coteh what do you think?

**Comment by Coteh** [comment]
I agree that the download button is not necessary when searching. Clear button, however, I think would be useful when searching. If I'm trying to reproduce a certain bug, and there's lots of irrelevant messages in the logs that get in the way, it would still be useful to filter then clear logs and that way I can watch for certain events to appear much easier.

Perhaps we can move clear button off to the side when searching, and hide actions such as Download that are not important when searching. What do you think?

**Comment by amir20** [comment]
Maybe we can close this since the toolbar is gone.
