### ISSUE TITLE
Support for multiple hosts

### ISSUE THREAD

**Issue by modem7** [amir20/dozzle#1593]
In line with #1559 I'd like to request support for multiple hosts.

However, the feature request is slightly different. 

Instead of re-writing to access logs on multiple hosts, do it much like Netdata does, which is just presents a link to other hosts. 

E.g. a dropdown where you can choose another server, and either in a frame/container or via a new tab, it goes to the other host. 

At minimum, I propose just a favourites list which goes to a specific url. At most, maybe a favourites list w/ a heartbeat that pings a healthcheck endpoint (or simply the IP address + port of the dozzle instances, and just says "Up/Down").

This would hopefully require minimal reconfiguration for the basic feature set, and a slight change to the compose file to map a directory with a URL list.

Dozzle would not access another host directly in any way in this particular case.

This would make it easier for people running multiple instances across multiple servers that aren't on high availability container platforms (e.g. VM's or just multiple bare metal installs) to go to different instances, without adding additional complex backend features to Dozzle.

**Comment by amir20** [comment]
> At minimum, I propose just a favourites list which goes to a specific url. At most, maybe a favourites list w/ a heartbeat that pings a healthcheck endpoint (or simply the IP address + port of the dozzle instances, and just says "Up/Down").

Heartbeat is too complicated to get right. There might also be auth and proxies that might not allow me to do that so it's not worth supporting a feature that could break. 

> This would hopefully require minimal reconfiguration for the basic feature set, and a slight change to the compose file to map a directory with a URL list.

This is an interesting idea. What is exactly your setup? Are you using swam or just a set of independent hosts to setup docker.

**Comment by modem7** [comment]
> This is an interesting idea. What is exactly your setup? Are you using swam or just a set of independent hosts to setup docker.

So my setup at the moment is pretty "simple" with two hypervisors, and a few VM's with Docker installed for one reason or another. 

No K8, no Swarm, very much a KISS principle which should reflect most home user/home lab scenarios that haven't gotten to the prosumer level. 

![Untitled-12](https://user-images.githubusercontent.com/4349962/140556314-b7c564aa-73ef-415e-b296-55643beda9ad.jpg)

So for example, I'd always have Dozzle on 192.168.50.20, 192.168.50.239 and 192.168.40.76 on three different VM's, regardless what physical hypervisor they live on. 

Most other peeps would have a bare metal install (or UnRAID etc), and would have similar static IP address constraints which would make this perfect. 

To make things potentially simpler, a simple ENV var with a set of IP addresses + ports would eliminate the requirement for a bind mount + would increase portability. 

E.g. REMOTE_SERVERS: "192.168.50.20, 192.168.50.239, 192.168.40.76"

**Comment by amir20** [comment]
I have been thinking about this for a few days. 

I think the right approach would be to set up something like consul or etcd. Are you familiar with these technologies? This way Dozzle can manage as many as nodes as possible. 

However, that is a pretty big task. 

I wonder if your suggestion would be good enough. My concern with it is that it doesn't scale. Not everybody uses static IP addresses. Many of Dozzle users have been small companies or startups. I haven't target home servers. 

Since this is a common ask: I'd like to understand use cases. If I have to put in the effort of supporting multi-node setup, I rather just leverage swarm API which already let's you read logs from any container.

**Comment by amir20** [comment]
There hasn't been enough traction on this issue for me to think people really need it. Therefore, I won't implement. PRs are welcomed though. There are other solutions outside of Dozzle that might work better. There are dashboards for creating shortcuts for different app.

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/issues/1608

**Comment by amir20** [comment]
It is not possible to set up remote hosts. See https://github.com/amir20/dozzle/#connecting-to-remote-hosts and https://github.com/amir20/dozzle/pull/2059

**Comment by agneevX** [comment]
I keep getting this... the Docker host does not need a cert

```
level=info msg="Dozzle version v4.8.0"
level=info msg="Creating a client for tcp://xxxxx:2375"
level=fatal msg="failed to create tls config: could not read CA certificate \"/certs/ca.pem\": open /certs/ca.pem: no such file or directory"
```

**Comment by amir20** [comment]
Looks like you are not using tls?

**Comment by agneevX** [comment]
That's correct, TLS is not used to connect to the socket.

**Comment by amir20** [comment]
Ok I think I know the problem. I thought docker client will ignore Ca files if not needed. Guess not. I need to figure out how to detect TLS or introduce another flag. 😕

**Comment by amir20** [comment]
Created a new issue to track. I have a fix but need to test it.
