### ISSUE TITLE
Buttons with tooltip shake when hovered over in Safari

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1596]
**Describe the bug**
Noticed this while working on #1595. On Safari Version 15.0 (15612.1.29.41.4, 15612), if you move your mouse over one of the buttons that has a tooltip, they will move to the right slightly. When moving your mouse away, the button will slide back over to where it was before.

Decided to create an issue for this because I think it's out of the scope of #1595 specifically. I was able to verify that this bug exists on master currently as well.

**To Reproduce**
1.  Open dozzle on Safari
2. Click on container log
3. Hover over clear or download button

**Expected behavior**
Should not shake.

**Screenshots**
![result](https://user-images.githubusercontent.com/3276350/140660808-56cd0f01-c084-4f58-8f72-2eb5fa081862.gif)
(seems like there's a slight discoloration on the gif making things look blue - ignore this)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7 (19H1419)
 - Docker version: N/A (working on dev server)
 - Browser & version: Safari Version 15.0 (15612.1.29.41.4, 15612)
 - Version: master

**Comment by Coteh** [comment]
When I get the time, I'd like to work on fixing this as well. :)

**Comment by amir20** [comment]
Probably also fixed.
