### ISSUE TITLE
New download and clear buttons hide log

### ISSUE THREAD

**Issue by Nikos410** [amir20/dozzle#1597]
Hey there! 

I really like the new clear button, but I think the positioning is not ideal - because it hovers above the log content it sometimes gets in the way.

For example, if there is important information in the first two lines it is pretty hard to read. Also selecting text behind these buttons is a little clumsy. This is a problem especially for devices with smaller screens, like tablets:

![image](https://user-images.githubusercontent.com/20876882/141098176-08e5759d-6b83-41d8-9e03-011c9c0163b0.png)

**Comment by Nikos410** [comment]
I'm not sure where a better position would be. The top bar is already pretty crowded, especially with long container/image names. Maybe at the bottom right where the "scroll to bottom" button is?

**Comment by amir20** [comment]
Hey thanks @Nikos410. Also adding @Coteh as we worked on this issue together. 

I am open to putting the "toolbar" anywhere but we couldn't find a better spot.  

Another idea, would be to create a menu icon on the top right with some of these options.

**Comment by amir20** [comment]
<img width="1140" alt="Screen Shot 2021-11-10 at 11 23 52 AM" src="https://user-images.githubusercontent.com/260667/141179537-6342954c-4b76-4206-8859-a6635f358e04.png">


Maybe something like that instead?

**Comment by Coteh** [comment]
I do like the ability to clear the logs by one click (rather than two clicks that would likely occur above).

Perhaps we can move the actual log view down a bit so that the floating buttons still appear where they are now, but they're not covering any text.

**Comment by amir20** [comment]
> I do like the ability to clear the logs by one click (rather than two clicks that would likely occur above).

Could a power user use the keyboard shortcut? There does need to be a better way to show shortcuts.

**Comment by Coteh** [comment]
Yeah perhaps we can give that a try. Have the menu in top right like you suggested, and then have a help icon on the top left positioned beside the settings cog button that, once clicked, would present the keyboard shortcuts in a modal.

Alternatively, the keyboard shortcuts for each action could be displayed beside the action in the menu bar in small text.

Once we figure out what this will look like, I can tackle it myself when I get the time.

**Comment by amir20** [comment]
Sounds good. @Coteh I am doing a major rewrite to vue3. We can look at this when done.

**Comment by amir20** [comment]
You can return to this feature now. Vue3 migration is complete.

**Comment by amir20** [comment]
This is fixed now. We moved to drop down.
