### ISSUE TITLE
"dev" command not bringing up server like it did pre-Vue3

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1601]
**Describe the bug**
I'm not exactly sure what happened, but when I run `pnpm dev` after installing the Vue3 update, it builds the assets but does not bring them up when the server comes up. It seems like the fake build overwrites the index.html so it says "assets build was skipped" when I navigate to the server port. (I do not use the other port, at 3000, because I need to see actual logs when working on features)

Also, unrelated, for some reason if I create an `.env` file, put the following contents in it:

```
DOZZLE_ADDR=:8888
```

and run `source .env`, it will not use the port when running the server. It will default to 8080, which I cannot use because my project uses that port. I need to work around this by running `DOZZLE_ADDR=:8888 pnpm dev`. (ie. inlining the variable directly. Maybe this is a macOS/zsh-specific issue, not exactly sure)

**To Reproduce**
1. Pull from master
2. `pnpm install`
3. `pnpm dev`
4. Go to localhost:8080 (or localhost:8888 in my case)

**Expected behavior**
See built assets on the page

**Actual behaviour**
"assets build was skipped"

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Version: master

I can work around this for now by doing production build and running watch:server with my desired port prepended to beginning of command.

Btw nodejs 15.0.0 is required now for this project because of `replaceAll` function in `vite.config.ts`.

**Comment by amir20** [comment]
Try `rm -rf node_modules`.  Then repeating everything else. 

I did 

```
gh repo clone amir20/dozzle
pnpm i
pnpm dev
```

It should automatically open `localhost:3000`

Let's start with that, and then figure out how to fix your port. You might have to do something else since Vite proxies to :8080.

**Comment by Coteh** [comment]
Yup I redownloaded all modules and get localhost:3000. I can't work with this though so I close the tab and open localhost:8888 instead (I needed to change my port by running `DOZZLE_ADDR=:8888 pnpm dev`, it won't read my environment variable). It still says "assets build was skipped";

![image](https://user-images.githubusercontent.com/3276350/142476338-8c375770-3ba8-4cd4-8ddf-187970533d51.png)

Maybe there's a way I can add fake logs into localhost:3000 and work like that instead? Is that what you do?

**Comment by amir20** [comment]
So `:3000` is the front end server. Before it was webpack and now it is vite. That shouldn't have changed. 

`:8080` is the Golang's server. The dev server proxies everything from `/api` to :8080. It's the default port. Why do you need it to be `8888`?

When you see "assets build was skipped" it is because in dev, all assets are in memory. So it doesn't really build anything. But go needs a fake file so it can compile. 

> I can't work with this though so I close the tab 

Why can't you work with this? I don't understand. 

> Maybe there's a way I can add fake logs into localhost:3000 and work like that instead?

I don't understand what you mean. I do `docker run -d --name test amir20/random-logger 100 200` which is just a simple docker container that prints logs. Is that what you mean? 

Can you clarify what is not working? I am not understanding some stuff.

**Comment by amir20** [comment]
By the way, port 3000 does show you actual logs. So something is a miss.

**Comment by Coteh** [comment]
Sorry, I was in a rush when I typed that. Let me try to clarify:

The reason why I need :8888 is because I did not know about your random-logger, and I’ve been using my side project simpleimage (I’m on mobile, but it’s on my pinned repositories if you’re curious) to generate some logs since I’ve been doing some work on that lately anyways. The main node app in that project runs on port 8080 as well, and I wanted to have both my project and yours run concurrently, thus the port change. 8888 I chose because that’s also the Docker port you use, but it could have been anything instead of 8080.

I figured that the dev server was compiling in-memory because I didn’t see any files built. When I get to my computer, let me try everything over again, all defaults, and I’ll use your random-logger this time. If it works, I’ll close this issue, thanks. :)

**Comment by Coteh** [comment]
Things are working now. :) Just need to make sure 8080 is not in use when the golang server comes up. I'll use the random-logger now and this issue can be closed.

**Comment by amir20** [comment]
Sounds good. Port 8080 is common so maybe I'll change it to something random.

**Comment by amir20** [comment]
@Coteh I changed default port 8080 to 3100 for dev. There shouldn't be any conflicts any more.
