### ISSUE TITLE
Can Dozzle work with Cloud Hosted (Azure) Docker containers?

### ISSUE THREAD

**Issue by CodeJuggernaut** [amir20/dozzle#1605]
**Is your feature request related to a problem? Please describe.**
Dozzle is awesome and works great for docker containers running on a Virtual Machine. But in the case where we want to use Azure App Services (Cloud Hosted), the docker containers are run without an obvious way to connect Dozzle to them.

Getting into the Log Stream for a cloud hosted docker container is cumbersome and only shows the logs of a single container.

**Describe the solution you'd like**
It would be nice to have the ability to point dozzle to a remote log stream and display that.

**Describe alternatives you've considered**
LogDNA is similar, but also doesn't have Azure or Cloud Integration.

**Comment by amir20** [comment]
This has been asked before. Multi-host dozzle integration is a huge task. 

I am not familiar with Azure App Services. Is it like kubernetes? Is there an API to get logs? 

I don't plan to work on this but PRs are welcomed.

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/issues/1608
