### ISSUE TITLE
Dozzle behind Teleport tunnel takes 60 seconds to show available containers.

### ISSUE THREAD

**Issue by MRIIOT** [amir20/dozzle#1607]
Dozzle behind Teleport tunnel takes 60 seconds to show available containers.
Dozzle works fine when connecting directly to http://host:8888.

The host running Dozzle connects back to a Teleport proxy node.  Dozzle is exposed as a Teleport application accessible via https://dozzle.teleport.domain.com.

Browser console shows below when connecting to Dozzle via Teleport.

```
Refused to load manifest from 'https://teleport.domain.com/web/launch/dozzle.teleport.domain.com' because it violates the following Content Security Policy directive: "manifest-src 'self'".
```

On load.

![image](https://user-images.githubusercontent.com/48079336/142733929-a926cfff-e49c-41d2-8fc5-c852b6edb073.png)

General
```
Request URL: https://dozzle.teleport.domain.com/api/events/stream
Remote Address: 1.2.3.4:443
Referrer Policy: strict-origin-when-cross-origin
```

Request Headers
```
:authority: dozzle.teleport.domain.com
:method: GET
:path: /api/events/stream
:scheme: https
accept: text/event-stream
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: __Host-grv_app_session=f4094317d564fb2741a6650cfbc4e9a3f99e8b1ce706acfc27df9247004a1111
referer: https://dozzle.teleport.domain.com/
sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

After 60 seconds.

![image](https://user-images.githubusercontent.com/48079336/142734007-679f6e5d-a424-48c4-acda-4663f3a777bd.png)

Response Headers

```
cache-control: no-transform
cache-control: no-cache
content-security-policy: default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; manifest-src 'self'; connect-src 'self' api.github.com; require-trusted-types-for 'script'
content-type: text/event-stream
date: Sat, 20 Nov 2021 20:52:28 GMT
x-accel-buffering: no
```

**Comment by amir20** [comment]
@MRIIOT I am not too familiar with Teleport. I looked a little bit to understand what is happening but the documentation for Server Sent Events doesn't exist. 

You might want to look at Dozzle's [help](https://github.com/amir20/dozzle#troubleshooting-and-faqs) which talks about proxies. Since Dozzle works without Teleport, this isn't a bug on Dozzle.  You need to make sure whatever proxy in front of Dozzle is not limiting the eventstream.  Dozzle sends `cache-control` headers so that proxies don't control this. Doesn't seem like Teleport is respecting these headers. 

Let me know if you find something and I can update the documentation.

**Comment by MRIIOT** [comment]
Found the issue.  Upgraded Teleport on the tunneled node to 7.2.0 and everything works as expected.

```
2021-11-21T17:24:35Z INFO             Round trip: GET /api/events/stream, code: 200, duration: 54.675045ms tls:version: 304, tls:resume:true, tls:csuite:1303, tls:server:74656c65706f72742e6c616464657239392e636f6d.teleport.cluster.local forward/fwd.go:185
```

https://github.com/gravitational/teleport/releases/tag/v7.2.0

https://github.com/gravitational/teleport/pull/8385

**Comment by amir20** [comment]
Nice. Thanks for letting me know.
