### ISSUE TITLE
[Feedback requested] Dozzle to support multi-node environments 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#1608]
### Feature Ask

The most requested feature for Dozzle has been to support a multi-node setup like kubernetes, swarm or cloud provides like Azure. 

I am creating this issue to request feedback. The complexity of supporting this use cases is really hard. Here are the options that I have been thinking about: 

### 1. Dozzle to support Docker Swarm 

This is would be a natural change for Dozzle as it is already reading all Docker APIs. Docker provides swarm APIs as well to read all logs for services. 

Cons: 
* There are bugs with swarm. Some times logs don't work correctly or they are out of order. 
* Not everybody uses Swarm 

### 2. Support kubernetes 

This is hard as I don't know too much about k8s APIs. It would make sense to support Docker and k8s like other services. For example, I think Traefik does a good job of this. You can configure to with k8s or swarm and it just works. 

Cons: 
 * I don't know anything about k8s setup
 * It might still not work for cloud provider k8s 
 * Requires to be installed on every host. Possibly using k8s's headless mode to act as a distributed services.  

### 3. Create Dozzle agents to support any setup 

This is the most amount of work. But it would work for everybody. Dozzle would have to be installed everywhere with "agents". Each agent can listen to all Docker services and send logs to a central place. This would work with all environments. 

Cons:
* Setup would be hard
* Testing is even harder to support all use cases. I don't use multi-node setups so I had to spend a lot of time learning about how to make this work. 
* I might do all this work and no one will use it. 

If you like Dozzle but want multi-node support then please upvote this issue. Please comment on what your setup looks like so that I can understand which of these options are best suited. 

Thanks!

**Comment by neographophobic** [comment]
My use case would need option 3 - I have standard docker running on different hosts, not setup in a multi-node operation. Currently I just run multiple Dozzle instances, which is not ideal but solves my problem in a mostly manageable way. 

If you wanted to look at the agent option, have you looked at how Portainer does it? In my setup I use the Portainer agent (all of my installs are on the same network). This doesn't aggregate all of the items into one single view, but does let me easily switch between my hosts and has worked well for me, but I also don't know enough about multi-node to know if this helps or not.

**Comment by amir20** [comment]
> If you wanted to look at the agent option, have you looked at how Portainer does it? In my setup I use the Portainer agent (all of my installs are on the same network). This doesn't aggregate all of the items into one single view, but does let me easily switch between my hosts and has worked well for me, but I also don't know enough about multi-node to know if this helps or not.


Thank you for this @neographophobic. This is the right kind of guidance I needed. I wasn't too familiar with options out there. I looked at Portainer and they have implemented they own agent on top of [serf](https://www.serf.io/) which uses gossip protocol. I also went through the documentation for k8s, swarm and custom solutions. This is a good start for me. 

I have a question for you: For the Portainer setup, did you install the agent using [these](https://docs.portainer.io/v/ce-2.9/start/install/agent/docker/linux) instructions? Seems like an easy install then follow some directions through the UI to add the IPs of agents. Is that correct?

**Comment by neographophobic** [comment]
I'm pleased that helped. I did follow those instructions to setup the agent (well I converted them to a docker-compose file and used it but it is the same thing). To do the setup in Portainer I then followed Method 2 [here](https://docs.portainer.io/v/ce-2.9/admin/environments/add/docker#method-2-connecting-via-the-portainer-agent). You basically add the IP:port of the box you installed the agent on, give it a friendly name and you are done. There are more advanced options around TLS verification, but I haven't enabled them.

The way this then works in Portainer is that when you login you see a list of environments. You pick one and then the UI and functionality is all pointed towards that. If you want to look at a different environment, you go back to the environment picker and pick the new one to work with. Environment picker / home screen is shown [here](https://docs.portainer.io/v/ce-2.9/user/home).

**Comment by amir20** [comment]
This issue hasn't gotten as much as attention as I had hoped. I'll leave it open until after the holidays and close based on interest.

**Comment by tessierp** [comment]
I would definitely like to see multi-node support. There is a "dumb" workaround which is FAR from ideal but, if I set replicas to two, I know that dozzle will be installed on my two nodes and every time I refresh I will hit the next server and so on and so forth but this is far from ideal.

**Comment by amir20** [comment]
@tessierp what's your setup like? k8s, swarm or custom? I am guessing swarm from your description.

**Comment by tessierp** [comment]
> 

That is correct, I am using docker swarm.

**Comment by amir20** [comment]
Going to close this. Minimal interest was shown. Not worth my time.

**Comment by youngt2** [comment]
I'm a little late, but I would love this feature as well. I have separate docker instances on a local network. I currently use portainer to have a single point of access.
Using https://github.com/Tecnativa/docker-socket-proxy I can access each instance of docker across the local network without an agent. I just basically bind my socket proxy to the local IP with `-p 10.20.1.10:2375:2375` and then I can 'direct connect' to that remote instance in portainer with the corresponding tcp address.

**Comment by vutsalsinghal** [comment]
hey @amir20 , first of all - love Dozzle! Really appreciate such an amazing tool. I would like express my support for the aforementioned feature.

My setup is similar to @neographophobic  and @youngt2 . I've an EC2 machine and an local raspberrypi. I use ssh tunnel to forward ec2 docker socket to portainer (running on raspberrypi) and also mount raspberry socket to the portainer container. I do not use the agent based approach... Like @youngt2, I bind 2 sockets to portainer and then on the UI I can switch between the two environments.

Maybe something similar could be done with Dozzle? You mount "_n_" no.of sockets to get "_n_" no.of views. Not sure if this will help, but here is my docker-compose definition of porainer

```
portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/ec2_docker.sock:/var/run/ec2_docker.sock
      - ./portainer:/data
    ports:
      - 9000:9000
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
```

**Comment by rafaelreis-r** [comment]
I also would love this or https://github.com/amir20/dozzle/issues/1593 to be implemented. I have about 5 docker hosts spread out across different devices, cloud and bare metal, not in swarm mode. I'd have to have an instance of Dozzle running locally on each of those instances. 

If I could centralize them all (as I can with portainer) in a main instance, and connect to them over docker proxy, TCP socket, API, or whatever mean, that would save a lot of jumping around.

+1 for the feature.

**Comment by amir20** [comment]
Thanks @rafaelreis-r. I might come back to this in the future when I have more time. For now, this feature is a lot of investment and complexity that would be more difficult for one person. :)

**Comment by IrwenXYZ** [comment]
hey Amir, I was wondering if you ever explored allowing Dozzle to connect to another `docker.sock`?

The docker daemon allows for remote connections, which can be easily configured<sup>[[docker documentation](https://docs.docker.com/engine/install/linux-postinstall/#configure-where-the-docker-daemon-listens-for-connections)]</sup>. From there, Dozzle would just need to connect to it over HTTP(s), after which Dozzle should be able to read the remote host's `docker.sock`.

As an example, [Uptime Kuma](https://github.com/louislam/uptime-kuma) implements this, and I'm using it right now.

Perhaps you could consider this method, since it seems like it would be less work than the other three options listed.

**Comment by amir20** [comment]
@IrwenXYZ that's already possible. I use [NewClientWithOpts](https://pkg.go.dev/github.com/docker/docker/client#pkg-overview) to connect to Docker which respects any ENV variables. I believe you need to set `DOCKER_HOST`. 

Please give it a try. And of course update the README file if it works. :)

**Comment by IrwenXYZ** [comment]
So it works, but it doesn't take the ENV as an additional host. Instead, it replaces the docker.sock volume that was mounted through docker compose, so with the ENV, it only displayed the remote host's docker containers.

Briefly looking through the `FromEnv` function suggests that it only takes one host URL, so it's not possible to pass multiple hosts to it. Not sure how complicated it would be to configure dozzle to read from multiple sources at the same time.

For reference, this was what I set in docker compose
```
environment
    - DOCKER_HOST=http://192.168.0.4:2357
```

**Comment by amir20** [comment]
> So it works, but it doesn't take the ENV as an additional host. Instead, it replaces the docker.sock volume that was mounted through docker compose, so with the ENV, it only displayed the remote host's docker containers.

That is correct. It only allows for a single host. I thought that's what you meant from your previous comment. 

To allow multiple hosts, it is non-trivial work. I see two options. 1) Combine all containers across all hosts which is super hard. 2) Have a drop down which allows to choose a host. Second option is easier but it breaks all the metrics and a lot of UI work to switch hosts and send host id back API which needs to support multiple env vars.

At the end, it wasn't worth my time to implement.

**Comment by amir20** [comment]
I am reopening this as I think it's possible to have a simple solutions with out agents.  Both @youngt2 and @rafaelreis-r solutions work but connecting Dozzle remotely to a different host. I feel it's a little more manual work that I had hoped to configure but it should work well for most set ups. 

I did a little investigation and I can open multiple clients to different hosts. Then via a drop down select which one to use. 

It will take me some time to make the changes though.

**Comment by amir20** [comment]
Work has started on https://github.com/amir20/dozzle/pull/2059

I was able to test it with a remote URL like `ssh://root@1.1.1.1` and it seems to work! But it is just soooo slow. So I'll need to add the UI and figure out what optimizations I can do before it is ready for testing.

**Comment by rafaelreis-r** [comment]
Agent / client structure is pretty neat. Basically same architecture Portainer implements.

Wouldn't using Docker API SDK be easier? They have a native Go lib maintained by them: https://docs.docker.com/engine/api/sdk/

I use the API instead of agents in portainer since it is easier to deploy.

**Comment by amir20** [comment]
> Wouldn't using Docker API SDK be easier? They have a native Go lib maintained by them: 

I already use that.  https://github.com/amir20/dozzle/pull/2059/files#diff-f1ef9327f5221a5033b488aff515048cba276bbe407ca1db8d0cc58faa765a9fR13 

Dozzle has always used the Docker API SDK in Go.  However, as you can see in the PR, I had to use some of their helper files to parse urls correctly for `ssh://...`. 

For all those who are active on this issue, what URL connection do you plan to use? I know SSH will work from Docker CLI. But TLS will be extra work since I have to pass a directory to Dozzle. 

@rafaelreis-r thoughts?

**Comment by amir20** [comment]
Woohoo it works! 🎉

Can everybody try to test it?

**Comment by rafaelreis-r** [comment]
tcp://ip:2375 (non TLS) and 2376 TLS

I can live with non TLS since I have an overlay VPN using tailscale
connecting the hosts.

But the canonical docker way is using TLS.


Will try that tomorrow, I’m afk right now!

Thanks Amir!!!!!




Em ter., 21 de fev. de 2023 às 20:58, Amir Raminfar <
***@***.***> escreveu:

**Comment by amir20** [comment]
Thanks @rafaelreis-r.  TLS easy to implement. The hard part is how to configure it as it requires keys, env variables and configuration per host. 

I am still working on ssh so let me know if you can test it with just the proxy and I can add more security options later.

**Comment by amir20** [comment]
I did some testing tonight @rafaelreis-r. Looks like TLS is the way to go. SSH doesn't work very well with scratch Docker image since it is not available. TLS is also much faster. 

Now I just have to figure out how to configure TLS certs directory configured via CLI in Dozzle. Any suggestions?

**Comment by rafaelreis-r** [comment]
Ideally:

Bind mount to store conf file and certs (optional, only for multihost):

Volume:/conf

Ui helper to add endpoints, where you enter ip, port, and upload the 3
certs per host.

As you add hosts it creates a folder in the /conf dir for each host and
saves its certs.
On /conf/main.conf you store the env settings passed over container
creation + added hosts.

If you reload the image with an existing mount it checks for the conf file
and sets up accordingly.

Harder way:

Yaml or .conf in a that bind mount where you manually add the settings and
point to the certs. Needs documentation to go along with it.


As a test you can release a partial version with only TCP (non TLS)
support.



Em qua., 22 de fev. de 2023 às 01:36, Amir Raminfar <
***@***.***> escreveu:

**Comment by amir20** [comment]
I am thinking of a hybrid approach. Something like 

```
docker run  -v=/var/run/docker.sock:/var/run/docker.sock -v /path/to/certs:/certs --hosts tcp://1.1.1.1:2376 -p 8080:8080 
amir20/dozzle
```

Where `/certs` is a directory with either `/certs/{ca,cert,key}.pem` or `/certs/1.1.1.1/{ca,cert,key}.pem`

I shy away from UI work since it's a one time configuration and Dozzle is stateless. No data is stored.

**Comment by rafaelreis-r** [comment]
Works.

Keep in mind the 3 certs are different across each host, since the url is
different for each host and the TLS cert must match the request url.

I mentioned ip:port (local hosts) but remote cloud hosts I use
domain.tld:port.

As long as the run command supports multiple hosts in different subfolders
(not only ip, but domain.tld as well) should be fine:

-v /path/to/certs:/certs -e HOSTS “tcp://1.1.1.1:2376 tcp://domain.tld:2376 …”

Or -e HOST1 “” -e HOST2 “”


Em qua., 22 de fev. de 2023 às 14:24, Amir Raminfar <
***@***.***> escreveu:

**Comment by rafaelreis-r** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/57492577/220724411-74766d2e-2406-4d7a-af9f-2157a5978c65.png">

It does work indeed. 

Let's try with multiple hosts and no localhost:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/57492577/220725103-31ce9aab-e89b-41e6-9336-27668dbb9ab2.png">

no dice.

With localhost and multiple hosts:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/57492577/220725583-ef8bb95e-c28e-4a70-bdac-61fdf597402a.png">

Works partially. When switching hosts in the list, it still lists the containers on localhost (dozzle container).

**Comment by amir20** [comment]
> Let's try with multiple hosts and no localhost

Right now, `localhost` is required. I am debating of making it optional but it breaks a lot of other things that I'll have to do later. 

> Works partially. When switching hosts in the list, it does not filter each hosts containers. It shows all of them, except when they have the same name

I still have work to do. I am actually surprised it works because I only tested `ssh`. 

Edit: Oh you don't have TLS. That makes more sense.

**Comment by amir20** [comment]
@rafaelreis-r try #2059 again. I have pushed TLS support. 

Can you give it a spin to see how it works for you? Logs, metrics, etc...

**Comment by amir20** [comment]
For anybody following this issue. It is not complete! Almost 1.5 years ago I started this issue and I am happy that we were able to come up with a solution that would work for most without introducing a lot complexity. 

I will do a quick round of tests and release.

**Comment by amir20** [comment]
See this part in README on instructions https://github.com/amir20/dozzle/#connecting-to-remote-hosts
