### ISSUE TITLE
remove explicitly defined expose 

### ISSUE THREAD

**Issue by demorphica** [amir20/dozzle#1616]
**Is your feature request related to a problem? Please describe.**
Thank you for working on Dozzle. 

I want to use Dozzle with https://github.com/nginx-proxy/nginx-proxy 
Since 8080 is a very common port & usually already in use, i run it on 18080, 28080 etc. depending on what's available on the system i plan to run it on. Given the problem Dozzle solves, i have it running pretty much everywhere....

quoting from nginx-proxy's documentation

```
To run it:

docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro nginxproxy/nginx-proxy
Then start any containers you want proxied with an env var VIRTUAL_HOST=subdomain.youdomain.com

docker run -e VIRTUAL_HOST=foo.bar.com  ...
The containers being proxied must expose the port to be proxied, either by using the EXPOSE directive in their Dockerfile or by using the --expose flag to docker run or docker create and be in the same network.
```

Since there's already an EXPOSE statement in Dozzle's Dockerfile, using ```--expose``` with another port does nothing. Also looks like https://github.com/moby/moby/issues/2210 was eventually closed after ~7 yrs , which probably means its never going to happen

**Describe the solution you'd like**
I wish Dozzle would not explicitly define an EXPOSE statement in it's Dockerfile, then i would not need edit your Dockerfile to build your entire repo every time i need to use Dozzle

**Describe alternatives you've considered**
I've forked your repo to remove the EXPOSE & will be submitting a PR soon

**Additional context**
On some of my systems, some containers run with HTTPS & some with HTTP. With current versions of Chrome (used by most of my users) HTTPS is "sticky", 
i,e lets say you open your browser & try to go to ```http://example.com:8080``` in a tab, 
if you go on & open ```http://example.com:8081``` in another tab - you will be able to open the page successfully
lets say now in the same window you go on an open ```https://example.com:<some_port>```, - you will be able to open the page successfully as well
however if you now try to go to any HTTP link on example.com on a any port, it will automatically redirect to HTTPS & now
the only way to access ```http://example.com:8080``` & so on will be via an incognito window or you will have to clear your browser cache.

Since we use Dozzle everywhere, people usually get confused & we're now moving all our containers to use SSL with nginx-proxy/nginx-proxy vs. try to fix Chrome.

**Comment by amir20** [comment]
@demorphica This topic was discussed in https://github.com/amir20/dozzle/issues/23 and at first I thought removing it was the right decision. But others convinced that is the wrong decision. 

> Since 8080 is a very common port & usually already in use, i run it on 18080, 28080 etc. depending on what's available on the system i plan to run it on. Given the problem Dozzle solves, i have it running pretty much everywhere....

I am not sure what you need to do that. Port 8080 inside a container is never exposed externally unless you choose to. You can run Dozzle on port 8080 and have nginx route to dozzle with port 8080. Other containers can also use port 8080 without any problems. I use traeffik and it works like that.  You might want to create a network in Docker and just use all your networking inside that the network.

**Comment by amir20** [comment]
Also noticed in https://github.com/nginx-proxy/nginx-proxy#docker-compose that they expose `8000` but it will not be exposed externally. 

```
CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS         PORTS                NAMES
a51a8a688fa7   nginxproxy/nginx-proxy        "/app/docker-entrypo…"   6 seconds ago   Up 4 seconds   0.0.0.0:80->80/tcp   desktop_nginx-proxy_1
4efe66fe7ec4   jwilder/whoami                "/app/http"              6 seconds ago   Up 4 seconds   8000/tcp             desktop_whoami_1
```

So you shouldn't need to change the default port and there shouldn't be any concerns.
