### ISSUE TITLE
Allow to customize Dozzle's page Title

### ISSUE THREAD

**Issue by carlos-sarmiento** [amir20/dozzle#1623]
**Is your feature request related to a problem? Please describe.**
I run dozzle on a bunch of machines in my homelab and love it, but sometimes I'm trying to explore the logs on a few machines at the same time and it becomes a mess because all the tabs have only the number of containers on the title. 

This forces me to click on a few of them until I discover the right tab.

**Describe the solution you'd like**
It would be great if we could customize the title for a tab of dozzle to include a "hostname". That way one of my tabs could be "Home Assistant Host" and another one "Net Services" 

**Describe alternatives you've considered**

**Additional context**

**Comment by amir20** [comment]
Hey @carlos-sarmiento. Thanks for the suggestion. It's not a bad idea and probably easy to do. Also look at https://github.com/amir20/dozzle/issues/1608 as I think that might be related to your set up. 

I am taking some time off so I won't have time to work on this. But I think the better way is for Dozzle to always read the hostname from docker. Then you could just use Docker's `--hostname ` option.
