### ISSUE TITLE
Logs question

### ISSUE THREAD

**Issue by RefineryX** [amir20/dozzle#1635]
How do I handle logs which do not show in docker logs but instead in another location? For these services I only get a one line in my logs:

``time="2022-01-11T11:53:28Z" level=info msg="Configuration loaded from file: /service.yml"``

Also, am I able to add logs from different locations?

**Comment by amir20** [comment]
Hi @RefineryX, Dozzle doesn't know anything about filesystem. All Docker logging utilities capture sysout or syserror. 

You could do one of the following: 

1. You should forward all logs to sysout (depending on your logging framework this can be done in many different ways) 

or 

2. spin a new process inside the container and do `tail -f /path/to/log` 

or 

3. mount the logging location and run `docker run alpine:latest "tail -f /path/to/log"` 

Up to you how you do it. Stackoverflow might be a good place to ask for help on sending lots to sysout.
