### ISSUE TITLE
Add smooth scroll setting

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1638]
**Is your feature request related to a problem? Please describe.**
While working on #1586, I was playing around with the scroll behaviour and realized I can pass `smooth` into [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) as well. Would be cool if this were an option in the settings menu.

**Describe the solution you'd like**
Instead of `instant` being hardcoded in, it can be configured between `instant` or `smooth` in Settings.

**Describe alternatives you've considered**
It's a nice-to-have for me.

**Additional context**
I'd like to add it in if you think it's a good idea.

**Comment by amir20** [comment]
Hey thanks for the idea. I had originally used smooth. But I found a bug. When the page first loaded it also scroll smooth to the bottom. If there is a way to not scroll smooth initially then it would be better experience. I want the first page load to be snappy.

**Comment by Coteh** [comment]
Gotcha, when I get the chance I'll take a look into making the first load be instant and smooth for the rest.

Also, I assume for the button that takes you to the bottom, we could have it be smooth if it's close to the bottom and instant if it's above a certain threshold (e.g. 50%).

**Comment by amir20** [comment]
That's a great idea. Enough of a good idea to not make it a setting. I say make the default experience great until someone complains about it. 😆
