### ISSUE TITLE
Question: Collecting logs from multiple hosts?

### ISSUE THREAD

**Issue by neo-neo1** [amir20/dozzle#1643]
Sorry if this isn’t the proper place to ask, I searched for existing Dozzle communities. 

Question: Can Dozzle collect logs from multiple hosts? I have 3 Rasp Pi’s all running containers and would like a centralized WebUI to view them (not using swarm or k8s). I read all the docs and saw no mention of multiple hosts? I’m aiming for extremely lightweight which I see Dozzle is.

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/issues/1608

Long story short, I have a lot going on and this would be a lot of work. I created the issue above hoping more people would show interest. I scrapped the idea when not many people cared about multihost support.

**Comment by amir20** [comment]
@neo-neo1 didn't hear back. If interested then provide some comments in #1608. Or even better, you can help me implement it. 

Closing this issue for now.
