### ISSUE TITLE
Nice to have: Copy line from context menu

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1672]
**Is your feature request related to a problem? Please describe.**
It would be cool if I could instantly copy a line via a menu option. My in-progress PR (#1639) contains a new context menu for each line where this kind of option could be a great fit.

**Describe the solution you'd like**
The context menu will have an option to copy that specific line to clipboard.

**Describe alternatives you've considered**
Nice to have feature but can definitely come handy for especially long lines.

**Comment by amir20** [comment]
That would be awesome. You can also use https://vueuse.org/core/useclipboard/#useclipboard since I have it already included in package.json

**Comment by amir20** [comment]
Let's keep this open

**Comment by Coteh** [comment]
I wonder if clicking on the timestamp part of the line would be a nice compromise to allow for easy copy but without cluttering up the view with dropdown icons. What do you think?

**Comment by amir20** [comment]
That's an interesting idea. But probably confusing as one wouldn't expect clicking timestamp to copy. Maybe this is not worth doing since people could just select and copy?

**Comment by Coteh** [comment]
Yeah I would say select and copy is sufficient at the moment, and I would be ok with this issue being closed.
