### ISSUE TITLE
Disable word wrap

### ISSUE THREAD

**Issue by youngt2** [amir20/dozzle#1673]
**Is your feature request related to a problem? Please describe.**
Only the problem that long log entries can be difficult to read and follow.

**Describe the solution you'd like**
Would love to see an option in the settings menu that disable word wrap from the log. In some instances this makes long log entries easier to follow and find.

**Describe alternatives you've considered**
N/A

**Additional context**
Portainer has this feature, but I much prefer dozzle for log viewing :)

**Comment by amir20** [comment]
Duplicate of #1646 

PRs welcomed! I haven't had time to work on this.

**Comment by youngt2** [comment]
ok thanks. I searched but didn't try 'unwrap' as a search term.. 🤷
