### ISSUE TITLE
Specify Search filter via URL

### ISSUE THREAD

**Issue by rkodey** [amir20/dozzle#1677]
Hi-  I think it'd be very useful to have the ability to specify a search filter via the URL bar.
That way, we could bookmark certain filters for quick access within a more complicated log stream.
Thanks for the great (and simple) tool!

**Comment by amir20** [comment]
I am not sure if I understand this. It wouldn't be useful if the log is moving fast. right? 

I think an idea would be to save current view with all filters and split panes. But I don't have time.
