### ISSUE TITLE
Soft Wrap

### ISSUE THREAD

**Issue by brintal** [amir20/dozzle#1696]
**Is your feature request related to a problem? Please describe.**
When Lines in the Log are too long, dozzle automatically wraps those lines which sometimes results in harder to read log files.

**Describe the solution you'd like**
It would be great if dozzle allows disabling soft warp in the settings. Meaning if the lines are too long a horizontal scrollbar is displayed instead if the lines being wrapped.

**Comment by amir20** [comment]
See #1673 #1646 

This has been asked a few times. I just don't have time to add it. Hopefully someone can take a quick look and send a PR.

**Comment by amir20** [comment]
Adding pinned since this is a common ask.
