### ISSUE TITLE
Is it possible to add custom tailing?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [amir20/dozzle#170]
I would also like to add some other things that I can watch in the list. For example, inside of the LetsEncrypt (Nginx) container there are `access.log` and `error.log` that reside inside `/config/log/nginx`.

Is there some way I can specifically add `/config/log/nginx/access.log` and `/config/log/nginx/error.log` to the list of logs?

thanks!
Kacey

**Comment by amir20** [comment]
Hi @YouveGotMeowxy. No that is not possible. While you can easily just create a process that does `tail -f access.log`, I do not recommend that at all. Docker containers [follow the 12-factor design](https://12factor.net/logs). This is cleaner as orchestration tool can figure out what to do with the logs. If you can modify the container the I would suggest redirecting all [nginx to stdout](https://stackoverflow.com/questions/22541333/have-nginx-access-log-and-error-log-log-to-stdout-and-stderr-of-master-process). 

Good luck.
