### ISSUE TITLE
Chrome Page Unresponsive while viewing logs

### ISSUE THREAD

**Issue by mmontminy** [amir20/dozzle#1700]
**Describe the bug**
While viewing a container with fairly active logging I frequently get Page Unresponsive errors from Chrome.

**To Reproduce**
1. Select a container with log activity. Something that generates 50 lines every minute or so.
2. Simply watch the logs, every so often Chrome will display a Page Unresponsive popup. It will eventually clear, then come back again later. 

**Expected behavior**
Logs to stream without issue

**Desktop (please complete the following information):**
 - OS: Windows 10 desktop. CentOS docker host
 - Docker version 20.10.14
 - Browser & version Chrome 95
 - Version 3.10.2 and 3.11.0

**If applicable include logs with `--level debug` and browser logs**
I have Dozzle running behind an Nginx proxy using the proxy_buffering and proxy_cache directives as suggested.
Possibly related... if I go directly to the Dozzle container/port and bypass the Nginx proxy, the dozzle page immediately appears, but I get no containers listed for ~ a minute or so.

I've enabled debug logs for Dozzle and saw nothing to indicate an issue.

**Comment by amir20** [comment]
I have done 100s per minute. How long does it take for the error?  If the page is open for a while, there might be so much logs that the page runs out of memory. I have to do some trimming. 

Questions: 

1. How long does it take to show error? Is the tab open for a while?
2. It's weird that you get no containers without proxy. That should never happen. Is there anything else running behind a proxy? 
3. How big is each log? Is it a lot of characters?

Let me know how I can reproduce it. I use `docker run  amir20/random-logger 500 1000` which emits a log every 500ms to 1s.

**Comment by mmontminy** [comment]
1. For the 2 noisiest containers usually only a minute or two from the time I start viewing the logs
2. I've got about 10 containers behind the same proxy
3. After the recent container restart it seemed better until it hit ~10M and 65k lines. This is crudely going by the containerid-json.log file directly on disk.

It certainly seems related to size and rate. These 2 containers are throwing a lot of logs while we're trying to stabilize some API work. The containers that aren't blowing chunks all over work great.

I'll try reducing the size further in the json driver.

**Comment by amir20** [comment]
I tried doing 4 logs per second for up to 5 minutes and I didn't see anything. 

Since you're on Chrome, can you go to `Window > Task Manage` when it is freezing?

**Comment by amir20** [comment]
I assume you mean MB not K? 300 MB is a lot. 

So then it is probably what I expected. There is just too much logs. I imagine it is much more than 100s per minute. Maybe 1000s. 

I am not sure of a good way to solve it. Perhaps limit it to top N logs and drop the rest.

**Comment by mmontminy** [comment]
I suspect you're right which is why only these 2 containers are seeing this. The API between them is generating a LOT of errors about once a minute. 

While it's not a problem with Dozzle, maybe a future feature might be a configurable to limit how many lines are retained as you suggest.

It's still proving to be a valuable tool, we just need to not watch the logs for too long until we fix our API so it's not throwing so many (ideally any) errors.

I appreciate the time.

**Comment by mmontminy** [comment]
I'll close this. I think we were simply logging at a rate/volume that was too much for the browser. Once we solved the bugs causing the excessive logging Dozzle seems to be working fine for us.
