### ISSUE TITLE
favicon bad URL

### ISSUE THREAD

**Issue by greenpeas** [amir20/dozzle#1714]
3.11.0
![image](https://user-images.githubusercontent.com/3856344/163327332-cb697ac7-faaf-4b8c-b132-d61ba1f0861f.png)

**Comment by amir20** [comment]
Yea, this does seem to be a bug. I never noticed.

**Comment by amir20** [comment]
I fixed this for now by inlining the favicon. Not the best solution but it's the best I can do with my vitejs.
