### ISSUE TITLE
Sum up mem/CPU loads in the "main" page?

### ISSUE THREAD

**Issue by JaneJeon** [amir20/dozzle#1715]
Just a small little feature request, but on the main page, would it be possible to have a simple sum of cpu + mem usage across containers? Just as two numbers, no need for any special charts or graphs or anything.

<img width="1770" alt="Screen Shot 2022-04-14 at 6 42 36 PM" src="https://user-images.githubusercontent.com/24810585/163489495-d2687ea8-1f93-42aa-9eaa-cfcc31cf685d.png">
 
In this screen, maybe between "Running" and the version numbers?

**Comment by amir20** [comment]
That's a great idea. For the longest time, I have been meaning to update this dashboard to have more resources. Something like top for docker. 

I'll leave this open for now and hopefully I'll have a better solution.

**Comment by amir20** [comment]
@JaneJeon I have been thinking about this...

What kind of number do you think would be helpful? I have CPU load and memory usage OR mem load. 

I was thinking some options could be:
1. Total load of all CPUs. Could be greater than 100%
2. Total memory used as in `1.2GB`
3. Total memory used as a % Value between 0 - 100. 

Let me know your thoughts and if any other tools has a good dashboard on this. I can try to copy some ideas.

**Comment by JaneJeon** [comment]
For CPUs, yeah, core-based percentage would probably be fine, and mem, obviously total MB would be the one.

Basically, just a *sum* of the numbers that dozzle shows for individual containers (with the same units that dozzle shows for individual containers). Nothing more.

The reason I'm advocating for something as simple as possible is because most of the time, people will use dedicated monitoring setup for drilling down into things (whether it be by container, or for time graphs or whatever), so just quick 2 numbers to glance at is absolutely more than enough for this kind of usage.

**Comment by amir20** [comment]
I agree. I think ultimately I'd like to try something like an animated [sparkline](https://www.essycode.com/posts/create-sparkline-charts-d3/) to show all containers and their usage. But that's not so easy. 

So I might just try showing total CPU and Mem for now.

**Comment by amir20** [comment]
<img width="1237" alt="Screen Shot 2022-04-20 at 12 49 43 PM" src="https://user-images.githubusercontent.com/260667/164311374-43cb2fc6-a543-4bf0-b119-739cd777f7fb.png">

In master now...

**Comment by JaneJeon** [comment]
Oh Jesus that was fast

**Comment by amir20** [comment]
I already had all the data :) 

I am going to test a little and release. 

Maybe come to that sparkline again. It would be neat to see a history I think.

**Comment by amir20** [comment]
Releasing a new build now. Looks good with my tests.

**Comment by yllekz** [comment]
Does this by any chance offer the ability to sort the list of containers by CPU usage?

**Comment by amir20** [comment]
Not right now. It's something I want to do when time permits
