### ISSUE TITLE
Cannot scroll horizontally when soft wrapped turned off

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1720]
Almost had this bug fixed on my local copy, but noticed some regressions with the infinite scroll feature so I'm going to hold off on pushing it for now. I can give it another shot in a couple weeks or so if you haven't already started taking a look yourself by then.

**To Reproduce**
1. Ensure soft wrap is turned off in settings.
2. Open any log with lines that go past the view bounds. Split view can be used as well to shrink the pane horizontally.
3. See that you can't scroll horizontally.

**Expected behavior**
You can scroll horizontally

**Screenshots**
![image](https://user-images.githubusercontent.com/3276350/164133036-e3445121-dfeb-416c-9cd7-e851089b6ff9.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7 (19H1419)
 - Docker version [e.g. `docker version`'s output] `Docker version 20.10.7, build f0df350`
 - Browser & version [e.g. chrome, safari] Firefox 99.0.1 (64-bit) - also observed on Chrome Version 100.0.4896.127 (Official Build) (x86_64)
 - Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`] 038e2dee88c97cebbe9fd57beccbadd96f31acef

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
Ah interesting. I misunderstood the bug before. Yea this is a bug. I'll wait to release a build.

**Comment by amir20** [comment]
I think this is fixed now.

**Comment by Coteh** [comment]
Yup, looks good. Sorry didn't have the chance to look until now.

I originally wanted to do more than just removing the `overflow: hidden`, I also wanted to make the horizontal scrollbar always appear at the bottom of the pane. But I was running into issues with the scroll to bottom button not appearing and other regressions so I held off on it for now - but I can attempt adding it again at a later point if that's something you're interested in.

Also I noticed that horizontally scrolling the pane on Firefox snaps back to the left side of it. Didn't notice this on Chrome. I may file another issue later.

**Comment by Coteh** [comment]
Filed the issue here #1728
