### ISSUE TITLE
Settings page looks for latest release from dozzle/dozzle on GitHub

### ISSUE THREAD

**Issue by mbentley** [amir20/dozzle#1732]
**Describe the bug**

**To Reproduce**
1. Go to the `/settings` page
2. Check out what pages it is trying to load
3. See that it is trying to retrieve `https://api.github.com/repos/dozzle/dozzle/releases/latest`
4. See 404 error

**Expected behavior**
I'm assuming it should be `amir20/dozzle` unless there are plans to move it.

**Screenshots**

<img width="719" alt="screenshot 2022-05-02 at 6 25 33 AM" src="https://user-images.githubusercontent.com/414445/166220315-5a5c29ff-8abe-46ea-bc99-090a7a034daf.png">

Seems like it might be set here: https://github.com/amir20/dozzle/blob/038e2dee88c97cebbe9fd57beccbadd96f31acef/assets/pages/Settings.vue#L160

**Comment by amir20** [comment]
Good find. I have no idea how that happened. Adding a quick fix now.
