### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by chriseaton** [amir20/dozzle#1749]
**Is your feature request related to a problem? Please describe.**
Our docker system has a lot on it, sometimes it takes a bit of time for dozzle to load in the containers.

**Describe the solution you'd like**
It'd be great to have a bit of visual feedback, such as a spinner on the UI while the data is waiting to be loaded from the server request. Without it, the initial thought is "something's wrong", when in reality you just need to stick around for a few seconds.

**Describe alternatives you've considered**
A progress bar? but that's so 2000's.

**Additional context**
Nop

**Comment by amir20** [comment]
How many containers are you running?

**Comment by amir20** [comment]
Did you see my question @chriseaton? I have done tests with a lot of containers. Maybe 500. How many do you have and what is the latency you are seeing?
