### ISSUE TITLE
Log text not readable (white on white and gray)

### ISSUE THREAD

**Issue by jicho** [amir20/dozzle#1752]
**Describe the bug**
The logs of Nginx Proxy Manager are not readable in Dozzle, the (info) log text is white text on a almost white background.
I don't have this issue with logs from other containers

**To Reproduce**
1. Install nginx proxy manager (https://nginxproxymanager.com)
2. View the logs
3. "See" te log lines

**Expected behavior**
Readable text :)

**Screenshots**

<img width="974" alt="image" src="https://user-images.githubusercontent.com/610740/169655114-a6ac75c4-0e9d-49b5-b8ea-0776486ed89a.png">

**Desktop (please complete the following information):**
_Browers_
* Safari (latest)
* Chrome (latest)

_Dozzle_
v3.12.6

Hope anything can be done about this :)

And besides that... Keep up the nice work!

**Comment by amir20** [comment]
It looks like you are starting the container in interactive mode. In that mode, docker sends colors which will affect the output. 

Can you confirm? And disable it if so.

**Comment by amir20** [comment]
<img width="1646" alt="Screen Shot 2022-05-21 at 8 36 46 AM" src="https://user-images.githubusercontent.com/260667/169658806-ff868a38-5c7a-4717-ac00-4253a5b5468b.png">

Confirmed.

**Comment by jicho** [comment]
A "confirm" also from this side.

**Comment by grant-davidson** [comment]
I had the same problem and fixed it by simply changing to the "Dark" color mode
![image](https://user-images.githubusercontent.com/804371/176359710-f2852d65-1f59-412f-aa32-e69c99dd8266.png)
