### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by BadFoo** [amir20/dozzle#1774]
Is there any way to have dozzle over https rather than http? 
If so, how?
If not, are there any plans to add support for https?

**Comment by amir20** [comment]
Hi @BadFoo. There is no support for HTTPS. The actual implementation is easy but the certifications need to be generated correctly which is quiet complex.  https://letsencrypt.org/ makes it easier. 

I recommend setting up a reverse proxy with something like [Caddy](https://caddyserver.com/docs/quick-starts/reverse-proxy) or nginx.  Dozzle focuses on being the right tool. HTTPS is outside of the scope.
