### ISSUE TITLE
Msg fatal in Authentiction

### ISSUE THREAD

**Issue by CarlosPinedaT** [amir20/dozzle#1789]
hello,

I have added the authentication described in the documentation and it throws me the following error:

`level=fatal msg="Key is required for authentication"`

With this line I run the Dozzle :

`docker run --name dozzle  --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:4444 amir20/dozzle:latest --username "app" --password "pass"`

someone help with the issue

**Comment by amir20** [comment]
The `README` file was updated for master because key was removed. Let me release a new version. That should fix it.

**Comment by amir20** [comment]
OK try  3.12.7
