### ISSUE TITLE
Disable update checking

### ISSUE THREAD

**Issue by agneevX** [amir20/dozzle#1798]
Currently, an API request is made to `api.github.com` to check for updates. 

It would be nice if this could be disabled.

**Comment by amir20** [comment]
Why would you want to disable it? If it's a common issue then I can consider it.

**Comment by agneevX** [comment]
Since this is self-hosted, I would not like for it to communicate with servers on the Internet.

**Comment by amir20** [comment]
I see. A lot of people use it for self hosted but not many people have requested to block it. Dozzle only sends a request on the settings page so I don't think it is urgent. And there is also no way for me to check the original request as github doesn't make the logs available. 

I am trying to limit all the configurations for now. I don't plan to do make this a configuration unless more people find it useful.
