### ISSUE TITLE
Please don't pack with UPX

### ISSUE THREAD

**Issue by 0xBAADF0OD** [amir20/dozzle#1818]
When this is packed with UPX, it gets picked up as malware based on heuristics and potentially breaks everything. Please reconsider and don't use a packer.

**Comment by amir20** [comment]
Did that actually happen to you? I was looking at their documentation and they said it shouldn't be a problem with malware. 

I don't think 25% compression is worth the trouble. So I'll revert it if it actually happened.

**Comment by 0xBAADF0OD** [comment]
Yes, it's currently breaking an entire pipeline because a NGAV is trying to kill it, while it tries to restart it

**Comment by amir20** [comment]
Ouch. 

Ok let me revert it.

**Comment by amir20** [comment]
Ok should be fixed with `v3.12.12`

**Comment by amir20** [comment]
Can I close?

**Comment by 0xBAADF0OD** [comment]
Yes, thank you!
