### ISSUE TITLE
Display glances logs with dozzle?

### ISSUE THREAD

**Issue by EDIflyer** [amir20/dozzle#1823]
Love dozzle and in particular how it just automatically works with new containers :)

I've been playing about with glances though and only finding critical level errors show in dozzle:
![image](https://user-images.githubusercontent.com/13610277/180614535-64e195c8-dec7-4cf4-a3eb-67396fb2b5a5.png)

In the internal logs are there lots more:
![image](https://user-images.githubusercontent.com/13610277/180614525-be1d0b83-671c-4015-bcb5-0c9c3e9c7f90.png)

Looking at [their documentation](https://glances.readthedocs.io/en/latest/config.html#logging) it's possible to create your own custom log output (which I presume it what I need to do), but where would I need to put the resulting log for dozzle to pick it up? (assuming this is even possible!)

**Comment by amir20** [comment]
Nice. Glad you like it. 

You just need to print them to `console`. If you `docker logs <id>` can see it then so can Dozzle. Dozzle reads both `stdout` and `stderr`.

**Comment by EDIflyer** [comment]
Thanks, @amir20 - yep, definitely a great app :) Running in via nginx proxy manager and Authelia so works very nicely.

Thanks for the suggestion re `stdout` and `stderror`.  I hadn't realised that was what you picked up.  I had a bit more of a read at https://docs.docker.com/config/containers/logging/ and also the suggestion they made re nginx Dockerfile, which had
```
# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
```
I tried `ln -sf /dev/stdout /tmp/glances-root.log` from a shell within the container and it seemed to link them OK in that I could `echo` items to the logfile adn they showed when I did a cat of `/dev/stdout`, however they didn't then show up in `docker logs glances` (and of course nor in Dozzle).  If I'm doing something obviously stupid please let me know, but clearly not a Dozzle issue in the slightest so am just taking advantage of you knowledge around how logs work :)  It's not a major issue if I can't access them, just would be a 'nice to have'. Thanks 😃

**Comment by amir20** [comment]
Sorry for the reply. 

I looked at the official [Dockerfile for nginx](https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile-alpine.template#L108-L110) and they are doing something similar. So I think that part is right. 

You might be doing something else wrong. Sharing your whole Dockerfile might help. 

Closing for now and we can keep discussing if needed.

**Comment by EDIflyer** [comment]
Hi @amir20 I wasn't putting it in the Dockerfile as I was trying not to create a custom on (as then Watchtower wouldn't be able to update it automatically), I was just trying to run the command from within the container.
