### ISSUE TITLE
Total cpu usage always 0%

### ISSUE THREAD

**Issue by grambas** [amir20/dozzle#1829]
**Describe the bug**
TOTAL CPU USAGE is always 0%

**To Reproduce**

1. start dozzle service with docker compose
2. open dozzle url

**Expected behavior**
TOTAL CPU USAGE expexted to show cpu usage, but  showing always 0%

**Screenshots**
![image](https://user-images.githubusercontent.com/5207343/182092352-b47cffd0-4ab2-4830-8617-c7d8602869d2.png)

http://localhost:8090/api/events/stream  answers, but always with  "cpu" :0

![image](https://user-images.githubusercontent.com/5207343/182093468-fa097168-87ec-4d19-925b-4e333921a68e.png)

**Desktop (please complete the following information):**

* Ubuntu 21.10
* Docker version 20.10.13
* docker-compose version 1.29.2
* firefox 103.0 (64-Bit) / Chromium 103.0.5060.134 
* Dozzle version 3.12.13

**Comment by alexdelprete** [comment]
I was about to open the exact same issue. Thanks.

Great work on Dozzle.

**Comment by amir20** [comment]
I am on build `Docker version 20.10.17, build 100c701` and it works. Not sure what could be broken and I can't debug since I can't reproduce it. I am also on Ubuntu.

Do any of your containers show CPU usage? It should be at the top right. 

What does `docker stats` show? 

Is it only with compose?

**Comment by alexdelprete** [comment]
I have 2 docker instances, both on Proxmox, the 1st is a Ubuntu Jammy VM:

```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

Docker 20.10.17 build 100c701:

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:15 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker stats shows CPU usage:

```
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
1e441b2e06e6   frigate                 10.12%    321.3MiB / 7.759GiB   4.04%     2.21GB / 279MB    29.8MB / 407MB    77
1301baf7ddda   nextcloud               0.01%     83.71MiB / 7.759GiB   1.05%     112MB / 9.98MB    46.3MB / 11.3MB   21
1cc9f347dcbb   traefik-logrotate       0.00%     900KiB / 7.759GiB     0.01%     9.39kB / 0B       770kB / 2.71MB    3
ce4330a5ca65   ecowitt2mqtt            0.20%     28.38MiB / 7.759GiB   0.36%     4.16MB / 24.8MB   10.6MB / 6.03MB   7
f27383a0ebac   traefik-hub-agent       0.00%     25.34MiB / 7.759GiB   0.32%     22.1MB / 9.35MB   35.3MB / 16.7MB   10
a0951d36ad3a   traefik-whoami          0.00%     5.961MiB / 7.759GiB   0.08%     256kB / 270kB     9.85MB / 0B       7
1207bae9c984   traefik                 8.42%     59.31MiB / 7.759GiB   0.75%     990MB / 1.25GB    30.9MB / 39.2MB   17
3c94413624c4   webtop                  0.31%     754.2MiB / 7.759GiB   9.49%     1.59GB / 423MB    763MB / 171MB     292
28cd4d3ac740   dashy                   0.04%     336.7MiB / 7.759GiB   4.24%     1.6GB / 186MB     271MB / 197MB     67
2eeed7ccf020   homeassistant           7.57%     543.5MiB / 7.759GiB   6.84%     0B / 0B           1.11GB / 1.75GB   76
```

Dozzle shows 0% on total and on every container:

![image](https://user-images.githubusercontent.com/7027842/182201696-55436df8-80ed-4720-927c-c7d76f3264ac.png)

![image](https://user-images.githubusercontent.com/7027842/182201985-f08431ca-8784-4735-886d-766914a3178c.png)

![image](https://user-images.githubusercontent.com/7027842/182202083-60654639-9903-4aac-93ef-f519241dbe48.png)

The 2nd Docker instance is a Debian 11 LXC, same docker version, with same problem.

If you need further info, I'd be happy to help. Thanks.

**Comment by amir20** [comment]
Hmm I am on `Ubuntu 20.04.4 LTS`. I _doubt_ that could be it. But let me try bringing up an ubuntu box with same version and trying. If I can't reproduce it then I have no way of fixing it.

**Comment by alexdelprete** [comment]
Same thing happens with Debian 11. I doubt it could be it, but you never know...

**Comment by amir20** [comment]
I was able to reproduce this with a branch new Ubuntu 22 LTS. Now I just need to figure out what is happening 🤔

**Comment by amir20** [comment]
This should be fixed on master. Can you try `amir20/dozzle:master`? 

It was related to how live CPUs were counted. I saw the issue at https://github.com/bcicen/ctop/issues/276

**Comment by amir20** [comment]
I can release a build fixed.

**Comment by alexdelprete** [comment]
It's working fine. :)

![image](https://user-images.githubusercontent.com/7027842/182256522-d93428ea-ac28-4504-bfad-a91eeef7e5fa.png)

**Comment by amir20** [comment]
Alright releasing a new build `3.12.14`

**Comment by alexdelprete** [comment]
Thanks a lot Amir.

**Comment by grambas** [comment]
appreciate it!

**Comment by amir20** [comment]
Thanks for finding. It's not often I have a "real" bug. haha.
