### ISSUE TITLE
Cloudflare causing duplicate lines

### ISSUE THREAD

**Issue by wildyaboku** [amir20/dozzle#1831]
**Describe the bug**
Related to #1404 but more specific to the underlying issue on Dozzle's side.

The log stream (`stream?id=...&lastEventId=`) is failing each 100,000 milliseconds for unknown reasons. The end result is that the last line is duplicated once the stream reconnects... every 100,000 milliseconds.

This is because the request is automatically resent by the client with the `last-event-id` header. In response, the new stream immediately sends back the log line matching the `last-event-id`, causing that line to be duplicated.

Regardless of what's causing the stream to fail, it should not cause duplicate lines upon a successful reconnection.

**To Reproduce**
Environment:
- Cloudflare (proxy enabled)
- Nginx (reverse proxying to dozzle)

1. Load a container's logs
2. Open inspect element (network tab)
3. Observe failing request each `100000 ms` on the timeline
4. Observe the new stream's payload and confirm it has resent the last (duplicate) line

**Expected behavior**
The line should never be duplicated, either by:
- Changing the client to ignore the first event from a stream if it matches `last-event-id`, or
- Changing the stream to only send events **after** the `last-event-id` (basically change `>=` to `>`)

**Screenshots**
Duplicate log entries:
![image](https://user-images.githubusercontent.com/499470/182512677-731a1b40-bbac-4b65-9c2a-4895a59b8dde.png)

Failing requests (interestingly the first `stream` is working fine, the others fail at exactly 100000 ms intervals):
![image](https://user-images.githubusercontent.com/499470/182510197-d8c8677d-e2ab-4eec-85fa-b5ac2cdd52b2.png)

Example retried request with `last-event-id` header:
![image](https://user-images.githubusercontent.com/499470/182512295-852e9c43-b2b4-4e2c-b098-f83946d06290.png)

Payload in same request as above showing the duplicate line:
![image](https://user-images.githubusercontent.com/499470/182512337-57bed2f5-e7fa-4160-94c8-f2a588e25809.png)

**Desktop (please complete the following information):**
 - OS: `Windows`
 - Docker version: `20.10.16`
 - Browser & version: `Chrome 103`
 - Version: `3.12.14`

**Comment by amir20** [comment]
Thanks for details. 

Generally I agree. But if the connection is resetting every 100 seconds then that is a bigger problem that needs to be resolved. 

> Changing the client to ignore the first event from a stream if it matches last-event-id

I tried this a while back but because it is timestamps then direct comparison doesn't work. They need to be converted to date objects. A little more complicated than I had hoped. 

> Changing the stream to only send events after the last-event-id (basically change >= to >)

This is the right solution. But Docker API doesn't allow inclusive vs exclusive. 


Did you want to give it a try with the first option and send a PR?

**Comment by wildyaboku** [comment]
Thanks @amir20. After further investigation it seems that Cloudflare kills any requests after 100 seconds of inactivity, which explains why the stats event stream survives but the logs do not. Unfortunately there's no way to fix that without implementing some sort of heartbeat. 100 seconds isn't very frequent, if we can fix the duplication I'd say it's fine.

With respect to a PR - I'm on windows at the moment and won't be able to get a linux machine up with docker for a while, I will be more than happy to do it when I can though.

I gave a quick look through the code and couldn't actually find where the `last-event-id` header was sent 😅 but it looks like this part of the code is a prime candidate for such a check:

https://github.com/amir20/dozzle/blob/72fd31f85b88c75f6da8fbc47db7cbd40428f1f2/assets/components/LogEventSource.vue#L64-L70

We could do something simple like checking if `lastEventId !== e.lastEventId` -- the only issue is that it seems the very first event in a container's logs has a blank ID? So it might be better to set `lastEventId` to undefined/null by default to avoid skipping the first line. What do you think?

**Comment by wildyaboku** [comment]
Option  1 surely sounds better. It seems Docker reports timestamps with nanoseconds precision, so it would be more reliable to add 1 ns instead. This can also be done on the client side, although `Date` does not support that level of precision so it would need to be done manually (I can cook that up for you if interested). I've sadly not had a chance to mess with Go yet.

As for an equivalent nginx setting, I was able to reproduce it at a much smaller interval with this:

```
proxy_read_timeout      5s;
```

**Comment by amir20** [comment]
So I tried option 1. You can see the commit here 9bcc0af. 

But unfortunately something weird is happening. I am testing in Chrome. It reconnects and works as expected. No duplicate log event. But after the second time, it just fails with 504 error and doesn't reconnect. 

<img width="1746" alt="Screen Shot 2022-08-04 at 9 37 20 AM" src="https://user-images.githubusercontent.com/260667/182905254-b7530d15-9e63-49ba-9843-d3c5e6abf04e.png">


I tested in Firefox and even before the change it doesn't reconnect. So I suspected reconnecting is up to the browser. It may decide to not reconnect if there was no data with last timestamp id. 👎 

Unfortunately, I don't think this will work. 

I am thinking maybe a heart beat would be better. What do you think?

**Comment by wildyaboku** [comment]
Hi @amir20, good morning and thanks for your work on this.

The behavior you see is not new, actually it is expected. When opening prior versions of dozzle to a container who has no output, it seems to wait for logs before responding, we just need it to behave properly when the connection is reset. For this reason perhaps merging both changes might be a good idea?

**Comment by amir20** [comment]
Ok so we are good on heartbeat. 

I am confused what you mean merging. Do you mean it should do both? Wouldn't the heartbeat alone fix the problem? Or are you thinking there could be other reasons besides timeout that should behave properly.  

The time fix is at https://github.com/amir20/dozzle/pull/1838. It seems to work, but again, no way to test it. Which is why I think heartbeat might be enough.

**Comment by wildyaboku** [comment]
At this point it's just to cover edge cases – if the connection drops for any reason then the duplication will reoccur, even with the heartbeat. I see websocket connections get randomly reset by Cloudflare a few times each day, there are also possibilities like a short loss of connection or possibly switching VPNs, which should produce the same issue.

I was just able to reproduce log duplication again by disabling my network adapter for a second to emulate a connection loss. 🤔

**Comment by amir20** [comment]
Deploying a minor version (instead of patch) because I consider the heartbeat a feature.  Version `3.13.0` should be live soon.

**Comment by wildyaboku** [comment]
Hooray! 🎉 Thanks so much for your attention to this, I really appreciate it! Version `3.13.0` is working beautifully, and it's like a breath of fresh air being able to leave this open on an extra monitor. :grin: Thanks again & cheers!

**Comment by amir20** [comment]
You had a compelling argument. And I agreed. 😬
