### ISSUE TITLE
Can't scroll down container list view on mobile Safari

### ISSUE THREAD

**Issue by robflate** [amir20/dozzle#185]
When viewing Dozzle in mobile Safari (iOS 12.4.2 / iPhone 6) I can only see 15 containers in the list. I am unable to scroll further down the list to see my other containers.

**Comment by amir20** [comment]
Yup, this is a bug for sure. I am working on adding https://github.com/amir20/dozzle/pull/186 split panes. If you think of a quick fix, send me a PR. It doesn't look like Bulma's menu support super long items.
