### ISSUE TITLE
Selected container does not show a background color in light/auto mode

### ISSUE THREAD

**Issue by agneevX** [amir20/dozzle#1855]
**Describe the bug**

Selected container does not show a background color in light/auto mode

**To Reproduce**

_Reproduced on Windows_

1. Set OS color scheme to light
2. Open Dozzle in incognito window
3. Observe that the background is not present

**Expected behavior**

Background present

**Screenshots**

![image](https://user-images.githubusercontent.com/19761269/185739904-186da35d-be16-41ff-b058-4099b7f17357.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows or Mac Os]
 - Docker version [e.g. `docker version`'s output]
 - Browser & version: Edge v104
 - Version: 4.0.1

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
> Selected container does not show a background color in light/auto mode

This works for me in Chrome v104.

<img width="748" alt="Screen Shot 2022-08-20 at 8 31 59 AM" src="https://user-images.githubusercontent.com/260667/185754869-f81d836d-77fc-4aca-90bb-d99e66ee774f.png">


To be honest, the rest of your bug is incomplete and I have no idea how to reproduce. 

Please edit your bug and provide better details.

**Comment by agneevX** [comment]
I've updated the body above.

Please note that the issue cannot be reproduced if system color scheme is set to dark mode and Dozzle's color scheme is manually changed to light.

**Comment by amir20** [comment]
Thanks. I don't have Windows. Let me see if I can reproduce it with system theme changing on Max OS. 

The code doesn't change on different OS so I am not sure what it can be. It's even in the same CSS.

**Comment by amir20** [comment]
Thanks for filing @agneevX. I was able to reproduce. Both on Windows and Mac os with default theme to light. Interestingly it only happens when default is set to light. I'll have to look at it Monday.

**Comment by amir20** [comment]
Should be fixed with `4.0.2`

**Comment by agneevX** [comment]
Thanks @amir20!
