### ISSUE TITLE
Reverse Proxy Security

### ISSUE THREAD

**Issue by 1liminal1** [amir20/dozzle#1856]
Hi there, 

Just getting started and trying to secure this behind a RP 

docker run --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:1224 amir20/dozzle:latest --addr localhost:1224
will bind to localhost on port 1224. You can then use a reverse proxy to control who can see dozzle.

How? I've added my reverse proxy network to the docker and tried using the name of the docker.  But I just get a bad gate way. If I use the IP 

Can you explain what the settings would look like? 

Thanks :)

**Comment by amir20** [comment]
What reverse proxy are you using? Can you post your whole configuration?

**Comment by 1liminal1** [comment]
nginx proxy manager 

If I use the IP for the docker; bad gateway 
If I use the docker name: bad gateway 
If I add the nginx proxy manager manager to the network and use the IP that creates: bad gateway

Thanks :)

**Comment by amir20** [comment]
Hey @1liminal1,  I never saw your configuration so I won't be able to help. Besides it is outside of scope for Dozzle to set up reverse proxy. 

I recommend asking this question on sites like stackoverflow.
