### ISSUE TITLE
Skip start screen

### ISSUE THREAD

**Issue by eyalcha** [amir20/dozzle#1858]
Add support to skip the first screen and show first found docker logs or pre-defined docker 

Skip this screen when start
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/64679987/186880166-33330323-80eb-48ba-9204-2dd6986da731.png">

**Comment by amir20** [comment]
You can already go to a specific container as outlined in [FAQ](https://github.com/amir20/dozzle#troubleshooting-and-faqs).  You can send the browser to `/show?name=foo` and Dozzle will automatically forward to the first found container with `foo`.
