### ISSUE TITLE
Multilingual translation support

### ISSUE THREAD

**Issue by AmadeusGraves** [amir20/dozzle#1867]
The translation in several languages of this application is needed due to the fact that the other languages are being ignored so that the people who use or try to use this application will have the problem that it is not translated in their language which is unproductive for the application itself since those users will not use this.

**Comment by AmadeusGraves** [comment]
I apologize if I have misspelled or misunderstood, English is not my first language, I also put this task so that when the internationalization is done, help with the translation of this application.

**Comment by AmadeusGraves** [comment]
I can translate spanish

**Comment by amir20** [comment]
@AmadeusGraves That is great feedback. I did some research. I can extract all english messages to configuration files and use Vue's [i18n module](https://vue-i18n.intlify.dev/). Then I could use your help to translate to Spanish. 

I have to make sure everything works before sending it your way.  Does that sound ok?  Would you be able to help with that translations then?

**Comment by AmadeusGraves** [comment]
Of course, it sounds perfect, I'll keep an eye out for when you upload the internationalization and I'll start translating into Spanish.

**Comment by amir20** [comment]
@AmadeusGraves I have created an initial example of _most_ my translations.  You can find `es.yml` at https://github.com/amir20/dozzle/tree/master/locales. 

Can you try translating and send a PR? 

We can test it and see what else is missing. I don't think dates will be updated correctly.

**Comment by AmadeusGraves** [comment]
Perfect, i'll start translating and i help with portuguese, i know a little about this language

**Comment by amir20** [comment]
That would help a lot! 

I am not sure about the dates and numbers. So help me there if you can.

**Comment by AmadeusGraves** [comment]
I have created a pull request, you already have the Spanish and Portuguese translations. Cheers

**Comment by AmadeusGraves** [comment]
Strange, it seems that the dockerhub user and password have not been specified in the tests.
![image](https://user-images.githubusercontent.com/18572939/189460089-74473e8e-681d-46ad-9f85-1a9872987945.png)

**Comment by amir20** [comment]
That's right. I think I added secrets and GitHub doesn't give access to forks. I need to fix it later.

**Comment by amir20** [comment]
Thanks for the PRs! Will check em out.

**Comment by amir20** [comment]
@AmadeusGraves Thanks for the PR. I have merged it for now. You can try `amir20/dozzle:master` to test it. 

Currently, Dozzle automatically picks the locale based on `navigiation.locale`. This might seem confusing to some, so I plan to have a drop down in settings. 

Please let me know how it works out. I have to do another scrub to make sure I didn't miss any translations.

**Comment by AmadeusGraves** [comment]
Thanks @amir20, when the release is available I will test it on my docker instance.

**Comment by amir20** [comment]
It should already be available. 

I think the date format is not localized though. I need to do bit more research there. Let me know if you have ideas.

**Comment by amir20** [comment]
Related to #1835

**Comment by amir20** [comment]
Alright master should have better date time formatting

**Comment by AmadeusGraves** [comment]
Perfect!

**Comment by amir20** [comment]
@AmadeusGraves were you able to test it? I noticed I had missed a couple translations. I have fixed some bugs too.

I plan to release a new build and have us improve more translations. 

To come: 

- [ ] Drop down to choose language

**Comment by amir20** [comment]
Sorry, I am confused. You can use amir20/dozzle:master to test it. Have you not done that? If no, please do.

**Comment by AmadeusGraves** [comment]
Yes, that's what I've done, I'll show you some screenshots.

![image](https://user-images.githubusercontent.com/18572939/190180947-9d6c9407-4811-4cf4-9a81-2f310cfcbc28.png)

![image](https://user-images.githubusercontent.com/18572939/190180983-f5325815-1f03-48f4-804c-34706e9b7031.png)

**Comment by amir20** [comment]
Great! Looks like it is working. I will release an official build today. Hopefully the community can provide other languages.
