### ISSUE TITLE
Latest version breaks Ctrl+K shortcut on Chrome

### ISSUE THREAD

**Issue by leadwolf** [amir20/dozzle#1886]
**Describe the bug**
Using the ctrl+k shortcut to open the container search also opens the chrome google search in the omnibar.

**To Reproduce**
1. On any page of the app
2. Press ctrl+k
3. Observe that the omnibar and dozzle search both open

**Expected behavior**
Only the dozzle search should open

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser & version: Chrome 105.0.5195.127
 - Version: v4.1.5
 
 It worked properly on the previous version 4.1.4. I opened the same issue a while ago #1245 .

**Comment by amir20** [comment]
Does `4.1.7` fix it?

**Comment by leadwolf** [comment]
Yes, thank you very much for such a quick fix, for something so small. 🙌
