### ISSUE TITLE
The dozzle showed current memory consumption is not right. 

### ISSUE THREAD

**Issue by gelleson** [amir20/dozzle#1891]
**Describe the bug**
The dozzle showed current memory consumption is not right. 
**To Reproduce**
I do know how to reproduce it but looks like just deploy some application in Golang, and they should allocate some memory, and it should free it. 

**Expected behavior**
It should show 30 mb, but it shows 444 mb 
**Screenshots**
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/44272887/192817755-4b8ba0b1-48ed-4a0e-b6e1-f1a93bc64046.png">

**Desktop (please complete the following information):**
 - OS: LINUX
 - Docker version
 ```bash
   Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

 ```
 - Browser & version safari 
 - Version: You are using Dozzle 4.0.2

**Comment by gelleson** [comment]
docker stats output

```bash
38b79ba4548d   krisha-action-1           0.00%     38.54MiB / 23.43GiB   0.16%     86.3MB / 7.5MB    3.54MB / 422MB    8
```

**Comment by gelleson** [comment]
Additional info of the arch is arm

**Comment by gelleson** [comment]
If you know where it can be fixed, just write down. I will do it by myself

**Comment by gelleson** [comment]
I need to say it is wonderfull app if you need some help with that just ping me :)

**Comment by amir20** [comment]
Assuming there are no errors, then I am not sure what could be the problem. `docker stats` does seem to be accurate based on what you've said. 

The code that does the memory computation is https://github.com/amir20/dozzle/blob/master/docker/client.go#L132-L166. 

I have no idea what could be causing this. Dozzle is also a golang app and I am using Apple's silicon ARM. I don't see this. Although, it doesn't match `docker stats` exactly, which is interesting.

**Comment by amir20** [comment]
I see in Docker CLI the math is a little different. https://github.com/docker/cli/blob/53f8ed4bec07084db4208f55987a2ea94b7f01d6/cli/command/container/stats_helpers.go#L227-L249

Try to see if you can match it and send me a PR please.

**Comment by gelleson** [comment]
@amir20 please take a look to https://github.com/amir20/dozzle/pull/1892. Looks like it can fix current behavior.

**Comment by gelleson** [comment]
<img width="1119" alt="СIM" src="https://user-images.githubusercontent.com/44272887/192870313-e3a3ace1-a285-4d40-b478-f76dede83def.png">

**Comment by amir20** [comment]
Amazing. Thank you for the quick PR. Releasing a build soon.  Waiting for builds to be green.

**Comment by amir20** [comment]
`v4.1.9` being deployed.

**Comment by gelleson** [comment]
Noice! Fastest release in my life!
