### ISSUE TITLE
404 page not found when accessing dozzle locally by port

### ISSUE THREAD

**Issue by jlw4049** [amir20/dozzle#1900]
I have qBittorrent installed and it defaults to port 8080. I swap the port to 8086. 

I can access this on the web via swag, but cannot access this via the webui. 

![image](https://user-images.githubusercontent.com/48299282/194737050-810461bc-c0b8-4c43-b40d-3fba87116fbc.png)

![image](https://user-images.githubusercontent.com/48299282/194737057-09c75524-1c97-4d5d-b23b-e3b72c602040.png)

**Comment by amir20** [comment]
Hi @jlw4049 I am not really sure what you are asking. There is no question or for me to reproduce. Please do not delete the template when creating an issue. 

I won't be able to help until I understand your problem.
