### ISSUE TITLE
Dozzle will not work locally, only will work remotely. 

### ISSUE THREAD

**Issue by jlw4049** [amir20/dozzle#1902]
**Describe the bug**
Dozzle does not work with the local WebUI once base URL is set. 

![image](https://user-images.githubusercontent.com/48299282/194969840-e257734f-75db-4118-980a-5a8cf15f2378.png)

If I manually input the address with the base URL it WILL allow me to login
http://192.168.1.5:8085/dozzle/ 

Dozzle does work over a reverse proxy

![image](https://user-images.githubusercontent.com/48299282/194969912-821eb22b-e5d3-4b12-944f-4c4e6ffd7e2a.png)

**The bug is:**
Dozzle does not work locally when I attempt to access the WebUI in UnRaid. The template doesn't allow me to add /dozzle to the webui link from within UnRaid

**To Reproduce**
Install Dozzle in UnRaid, attempt to use the local webui. 

**Expected behavior**
The WebUI to open up without a 404 error message

**Screenshots**
See above and 

![image](https://user-images.githubusercontent.com/48299282/194970457-f1a44585-85f5-4765-8ad9-a6966d682e98.png)

**Desktop (please complete the following information):**
 - OS: UnRaid
 - Docker version: 20.10.18
 - Browser & version: Chrome, Edge, and Firefox against multiple PC's on the network
 - Version: 4.1.9

**If applicable include logs with `--level debug` and browser logs**
level=info msg="Dozzle version v4.1.9"
level=info msg="Accepting connections on :8080"

**Comment by amir20** [comment]
I have never used unraid and I think it would be hard to set it up. I don't know what is webui. 

Is there a different way for me to test it? 

It seems like from your screenshots that Dozzle is working so it's possibly just a configuration issue with the UI. 

One other point, it seems like you are mounting it on `/dozzle`. I do not redirect right now. Maybe you expected that to work? 

Do you know what kind of reverse proxy unraid uses? That could help me debug too.

**Comment by jlw4049** [comment]
UnRaid would take a little while for you to configure just to work on this. 

WebUI is Dozzle opening in a web browser. 

Dozzle is 100% working fine, just the link that's hard coded in the container is not working.

Once you add a base_url (which I set to /dozzle) the webui will no longer work because it's hard coded to only work with ip:port/dozzle. 

**Removed base_url = /**
![image](https://user-images.githubusercontent.com/48299282/194980074-0d43ab4f-a6b0-409c-9b93-c59477b47a01.png)

**Added base_url = /dozzle** (This is needed for my reverse proxy)
![image](https://user-images.githubusercontent.com/48299282/194980143-d51e85e2-fc28-42da-8a6f-ad0d7f8cc06d.png)

It **still** attempts to go to the local only WebUI location. Which would be fine but it appears dozzle isn't coded to accept incoming connections once the base_url is hard coded in. 

**Adding /dozzle** 
Allows it to work locally once a base url is set
![image](https://user-images.githubusercontent.com/48299282/194980260-e91be5e3-b050-4f8e-9809-1a9e3f67e9e1.png)

This should be ignored for local access most likely.

**Comment by jlw4049** [comment]
This isn't a big issue. Generally once a base url is added the app can still be accessed via the local ip/port. 

This is the case with radarr or sonarr. 

But not a big issue as I can access it via my reverse proxy no problem.

Thank you!

**Comment by amir20** [comment]
Oh I see. I like check them out. Probably keep it as is for now.

**Comment by jlw4049** [comment]
Np. Thanks for taking the time to check things out.
