### ISSUE TITLE
Activity Monitor colors are faded on light mode theme

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#1918]
I'm not sure what this change adds? If I mouseover I can't read the numbers now and although there's a pointer it doesn't seem to do anything?

Mouse not over:
![image](https://user-images.githubusercontent.com/13610277/196965704-36af7941-0f87-41ea-9170-f9f96fca499e.png)

Mouseover:
![image](https://user-images.githubusercontent.com/13610277/196965665-7f934eb7-11ca-42c2-903d-c0da47252feb.png)

_Originally posted by @EDIflyer in https://github.com/amir20/dozzle/issues/1914#issuecomment-1285570393_

**Comment by amir20** [comment]
Some colors updated in https://github.com/amir20/dozzle/pull/1919

**Comment by amir20** [comment]
@EDIflyer try `amir20/dozzle:pr-1919`

**Comment by amir20** [comment]
I merged and released a new build. The orange accent isn't my favorite color but it works for now.

**Comment by EDIflyer** [comment]
confirm works really well now, thanks @amir20 - given the orange is only for text I think it looks fine too :)
