### ISSUE TITLE
DOZZLE_FILTER env is not working

### ISSUE THREAD

**Issue by TUNER88** [amir20/dozzle#192]
`DOZZLE_FILTER` is not working for me. Any Idea what I'm doing wrong?

Here how I use it:
```bash
docker run -e DOZZLE_FILTER='nginx' --volume=/var/run/docker.sock:/var/run/docker.sock -p 8081:8080 amir20/dozzle:latest
```

Container is immediately crashing with following error:
```bash
time="2019-12-02T09:30:25Z" level=info msg="Parsing nginx"
level=info msg="Dozzle version 1.17.0"
level=fatal msg="Could not connect to Docker Engine: Error response from daemon: Invalid filter 'nginx'"
```

**Comment by TUNER88** [comment]
In meanwhile I found my error, my filter value format was wrong.
Could we add some hints to the config options?

In this case we can add am reference to filter usage in official docker docs:
https://docs.docker.com/engine/reference/commandline/ps/#filtering

What do you think?

**Comment by amir20** [comment]
Hi @TUNER88! Yep, you are right. The format is `key=value`. I thought it was documented but I now see that it was missed. I can try to add it this week. I am surprised no one else has brought this up. If you get a chance can you send a PR to the README file?

**Comment by TUNER88** [comment]
I've added some hints in #194, I thinks we can close this issue
