### ISSUE TITLE
Aw, Snap! Error code: SIGILL - This seems to happen at high volume 

### ISSUE THREAD

**Issue by Rudy2315** [amir20/dozzle#1921]
**Describe the bug**
Aw, Snap! Error code: SIGILL - This seems to happen at high volume.  Postgres log is being monitored during a high volume number of inserts.  where it happens in the insert stream is not consistent.  Sorry, I wish I could provide more information 

**To Reproduce**
Run a high volume of inserts into a Poagres database 

**Expected behavior**
no SIGILL 

**Screenshots**
The Aw, Snap! 

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Docker version
 -  [Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
]
 - Browser & version [Chrome, Version 106.0.5249.119 (Official Build) (64-bit)]
 - Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`]

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
I have no idea. There isn't much details. I have tested Dozzle with 20 or 40 logs per second. 

I am not sure what postgres insert rate has to do with it.

**Comment by Rudy2315** [comment]
It is a Postgres container Dozer is monitoring the log 
What do you need?  I can recreate this pretty consistently.

**Comment by amir20** [comment]
I need a way to reproduce this without setting up postgres. I don't have much time TBH. 

Maybe create a compose file that just inserts a lot and I can see the problem. 

Or even better, see if you can debug Dozzle. Maybe there is a memory leak.

**Comment by amir20** [comment]
I was able to log an event every 10ms and it seems to work fine. I am going to close this until you can giving me minimal example where it breaks. I won't have time to go through setting up postgress and doing a lot of inserts.

**Comment by Rudy2315** [comment]
Sounds good. I cloned the repository and will try to debug.  Like you I have little time but hope to get to it Best Regards, Dean. On Oct 25, 2022, at 1:23 PM, Amir Raminfar ***@***.***> wrote:﻿
I was able to log an event every 10ms and it seems to work fine. I am going to close this until you can giving me minimal example where it breaks. I won't have time to go through setting up postgress and doing a lot of inserts.
