### ISSUE TITLE
Docker secrets

### ISSUE THREAD

**Issue by dima-bzz** [amir20/dozzle#1927]
Hello. Can I use [docker secrets ](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose)to not be explicit in the docker-compose file? If not, is it possible to add such functionality.

**Comment by amir20** [comment]
Not a bad idea.

It doesn't seem to be supported right now. Docker secrets are exposed as files. Dozzle only looks at ENV variables. 

What is your use case? Is it for user/pass config? 

Do you know Go? I think it would be easy to support `DOZZLE_USERNAME_FILE` and `DOZZLE_PASSWORD_FILE` respectively for username and password. 

Alternately, leave this open and I get to it when I have free time.

**Comment by amir20** [comment]
#1929 fixes this

**Comment by dima-bzz** [comment]
@amir20 Which version of go is used?

**Comment by amir20** [comment]
[Release 4.2.3](https://github.com/amir20/dozzle/releases/tag/v4.2.3) is released now. 

I use version 1.19.2 and auto update when ever a new one comes out.
