### ISSUE TITLE
Dozzle as Docker Extension

### ISSUE THREAD

**Issue by ivan-curkovic** [amir20/dozzle#1943]
**Is your feature request related to a problem? Please describe.**
Dozzle could simply fit in the Docker Desktop as an Extension. Beginner users could just install the app via Extensions Marketplace without configuring or typing commands in the terminal.

**Describe the solution you'd like**
If you aren’t familiar with Docker extensions, Docker Extensions are a way for our partners to include their products' functionality in our Docker Desktop application.
- There is an [SDK available](https://github.com/docker/extensions-sdk) 
- as well as [docs on how to integrate](https://docs.docker.com/desktop/extensions-sdk/)
Creating a Docker Extension also gives you access to our user base for developers to discover a potential new tool if our users aren't already using your product. 

I'm also including two blogs that also help better explain [how to build an extension](https://www.docker.com/blog/build-your-first-docker-extension/) and one that [shows the marketplace and our initial launch partners](https://www.docker.com/blog/docker-extensions-discover-build-integrate-new-tools-into-docker-desktop/).

**Comment by amir20** [comment]
Thank you @ivan-curkovic. Coincidentally, a few weeks ago I was researching Docker extensions. I was thinking Dozzle would be a great extension. However, I wasn't sure what the value to the user would be.

In your opinion, what would be some good reasons to install Dozzle as an extension? 

I have reviewed some of the docs but not all. I am sick so might be slow to respond.

**Comment by ivan-curkovic** [comment]
Hi @amir20, I hope you get well soon.

The extension would be a different use case for Dozzle.
Users could install the app from the marketplace and use it locally, directly in Docker Desktop.
It should be a one-click install, suitable for junior developers—no need to type anything in the terminal.

There is already an extension for Logs https://hub.docker.com/extensions/docker/logs-explorer-extension, but we would like to have a larger ecosystem for developers. 

BTW. I am Engineering Manager in Docker Extensions Team, and I can help you solve any potential technical problems. 

Let me know if you need more info.

**Comment by thelubomir** [comment]
@amir20 We need dozzle for k8s and helm!

**Comment by amir20** [comment]
Given the lack of interest for this issue, I am going to close it.

**Comment by amir20** [comment]
k8s support is implemented https://dozzle.dev/guide/k8s#kubernetes-setup
