### ISSUE TITLE
Do not have access to more than 1 log

### ISSUE THREAD

**Issue by kBraDrs** [amir20/dozzle#1951]
I am currently running a plex server and have just started using Dozzle. It is not giving me the option to view the many logs that Plex has within the container, and only has the one showing. From what I can see, I can not select which log I want to view.

**Comment by kBraDrs** [comment]
It is only showing to docker log for it, can it view the logs within the /docker/Plex/ folder aswell?

**Comment by amir20** [comment]
Dozzle doesn't have access inside the container. Only what is sent to stdout.
