### ISSUE TITLE
No container or status are present when deploy in EC2 AWS machine

### ISSUE THREAD

**Issue by alabrashJr** [amir20/dozzle#1960]
I tried the image on different platforms and it worked without any extra effort. However, when I run it on an EC2 AWS machine it shows nothing as follows, 

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/9295206/203080985-2fc7936b-fbba-4a04-871b-c0506015075b.png">

Docker version: Docker version 20.10.17, build 100c701
Linux version: 5.10.147-133.644.amzn2.x86_64
image : amir20/dozzle:latest

**Comment by amir20** [comment]
Hi @alabrashJr. There isn't any information to help debug the issue. There could be so many things wrong. I would look for errors on Dozzle container first. Then look for browser errors. 

If I had to guess, this might be a reverse proxy problem. If the UI cannot get an update, then it never reloads the UI. Try reading https://github.com/amir20/dozzle#troubleshooting-and-faqs. 

Let me know when you have more infor.

**Comment by alabrashJr** [comment]
Hi @amir20, 
Thanks for your following, 
When I check the log of Dozzle container, there is no error 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/9295206/203256910-23249c7f-f1e3-4b78-92e5-5b9d08a51bff.png">
The browser console shows no error either.
<img width="685" alt="image" src="https://user-images.githubusercontent.com/9295206/203258235-410a649b-e229-44ec-ae7d-2c9bc8a37e46.png">

I think the problem is similar to this [problem](https://stackoverflow.com/questions/59096335/docker-socker-at-var-run-docker-sock-with-aws)

**Comment by amir20** [comment]
Hm. If Dozzle couldn't connect then there would be a lot of errors. I haven't been able to reproduce though. Can you share steps to reproduce with AWS?

Also, are you accessing Dozzle directly or through some proxy?

**Comment by alabrashJr** [comment]
I did nothing special on the AWS machine, I installed docker and docker-compose.
create my container instances and run Dozzle.
I even included Dozzle in the docker-compose yml to be in the same network did not work either.

I'm accessing Dozzle directly without any proxy.

You can reproduce the case by doing the following:
* Create an EC2 machine with amazon linux 2 
* Install docker. [Here is](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-container-image.html#create-container-image-install-docker) a guide to do this on aws linux instance.
* Reboot the instance.
* Then install docker-compose using this [guide](https://docs.docker.com/compose/install/compose-plugin/#install-the-plugin-manually)
* `docker run --name dozzle -d --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:8080 amir20/dozzle:latest`

**Comment by amir20** [comment]
Ah you are using Amazon Linux. Never tried that. Maybe that is the problem. I'll have to look after the holidays.

**Comment by alabrashJr** [comment]
let me know if you need any help :)

**Comment by amir20** [comment]
@alabrashJr 

Seems like I still can't reproduce it. I created a new instance of Amazon Linux with the latest kernel. 

Installed docker with `sudo amazon-linux-extras install docker`. 

Finally, `docker run --detach --volume=/var/run/docker.sock:/var/run/docker.sock -p 80:8080 amir20/dozzle`

<img width="1695" alt="Screenshot 2022-11-26 at 1 06 39 PM" src="https://user-images.githubusercontent.com/260667/204108964-29197408-a89b-43cf-86a3-1e644e5d9dc9.png">

For me it worked the very first time and I didn't have to do anything. 

This might be something related to your environment which I cannot replicate.

**Comment by amir20** [comment]
Haven't heard back. Marking as invalid. Will close soon.
