### ISSUE TITLE
json logs don't render

### ISSUE THREAD

**Issue by endquote** [amir20/dozzle#1963]
I started using dozzle on a new homelab setup recently and it's been great! No issues at all, thanks for such a helpful tool. However I added a new container recently and have one bug:

**Describe the bug**

This application spews logs in json format, like so:

```
{ level: 'debug', created: 2022-11-23T00:26:01.834Z, title: 'http', text: 'http', meta: { msg: 'http', req: { url: 'https://stuff', params: { q: 'things' }, headers: { Authorization: 'etc' } }, duration: 691 }, url: 'bar', washer: { id: 'id', name: 'stuff' }, saved: 2022-11-23T00:26:01.834Z }
```

Dozzle can't render these, I just see a bunch of gray lines.

**Expected behavior**

It would be nice to see the logs. It's not necessary to parse the json, just print it.

**Screenshots**

![dozzle-json-log](https://user-images.githubusercontent.com/330010/203570500-7e81cd2c-7139-4c98-b1ee-3898f57b8581.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Docker version: `20.10.3`
 - Browser & version: tried current versions of Chrome and Safari
 - Version: `v4.4.1`

**Comment by amir20** [comment]
Hmm. That might be a bug. I am guessing a json parsing error. Are there any browser errors? 

I'll have to try to reproduce.

**Comment by endquote** [comment]
Thanks for the reply!

Yes it looks like there are a bunch of browser errors.

![dozzle-console](https://user-images.githubusercontent.com/330010/203572514-347a9c88-48ff-4d16-ac8d-7375b7f00f54.png)

This container is running a program I wrote so it's probably my bug 😆

The logs get dumped into mongodb which works fine, but what's spewing on the console is actually invalid JSON.

So maybe if dozzle did a try/catch around JSON.parse and displayed the string when it failed, that would be fine.

Or ignore this issue, since it'll probably never happen to anyone else!

**Comment by endquote** [comment]
I fixed my bug -- so now my logs have valid json and dozzle is showing them.

But still, dozzle may want to handle garbage data better.

Thanks again!

**Comment by amir20** [comment]
Sounds good. For now I won't do anything because I am sick 😔

But perhaps if there is an error Dozzle can fall back to regular logs with an error.

**Comment by amir20** [comment]
I tested this locally and it turns out Dozzle was throwing errors:

```
ERROR json unmarshal error while streaming invalid character 'l' looking for beginning of object key string

```

So it is less confusing than I thought. I still think it should fail gracefully but good to know error was being shown.
