### ISSUE TITLE
Version support 

### ISSUE THREAD

**Issue by amd020398** [amir20/dozzle#1964]
Hi, Do you have versioning support in dozzle image? In the compose file it is showing latest and I want to use some previous version. Can you please guide me on this ? 

Thanks,
Akshat

@amir20

**Comment by amir20** [comment]
Yes. They are all published on docker hub. You should be able to pull any version. 

I am on vacation. Won't be on computer until after.

**Comment by amir20** [comment]
All the versions are here https://hub.docker.com/r/amir20/dozzle/tags
