### ISSUE TITLE
Show only 1 or some container in left side bar

### ISSUE THREAD

**Issue by pimpmypants** [amir20/dozzle#1968]
hey, i love your app, it really help my backend and frontend engineer for tracing log container, bcus before that i need to create user login to server for backend and frontend engineer so they can access to server without sudo but also have priviladge to docker service, im bit worried cus maybe they can do something that they didnt know and breaks a things

now i just have to send them this url and let them watch their container logs without go to server, but i have a lot service/container and it will be good additional if this app can filter/sort only 1 or some container to show live logs. so my BE only can saw their container logs only, and same as FE.

thanks

**Comment by amir20** [comment]
I am not 100% sure if I understand your question. But you probably want `--filter` which is well documented in the README file. It let's Dozzle only show a filtered set of containers.

**Comment by pimpmypants** [comment]
ah yes,  thank you, i miss that part. but i tried using compose when create this service and i want to add this filter to compose, i there any example using flag filter in compose btw ? thanks
