### ISSUE TITLE
application not showing all log 

### ISSUE THREAD

**Issue by pimpmypants** [amir20/dozzle#1969]
hi amir, i want to ask something again, so i did using your app about a day, and i loveit, and i tried using to watch all my log in my container, even from the container start

what i did usually is 
`docker logs containername > log.txt`

and i will get a big size of txt file, usually around 20-30mb 

![image](https://user-images.githubusercontent.com/116715052/204213260-90e9cd1b-b0b8-4ddc-b822-ad7a7a8e3626.png)

but dozzle only shows me about 1,6k line of log, i didnt know exactly how much size is, but i assure you that i cant get logs from 8 hour earlier now. cuz i need to see logs around 1am.

do you have anywork around ?

**Comment by amir20** [comment]
There is a download link. You can use that. I can't show all the logs. It would break the browser.
