### ISSUE TITLE
Enhancement to resources label

### ISSUE THREAD

**Issue by STaRDoGG** [amir20/dozzle#1985]
**Is your feature request related to a problem? Please describe.**

Currently fighting with my ISP telling me I'm eating data like crazy on a non-unlimited plan, and so far I've tracked it down to Docker. Problem is, I run like 100 containers, and it's hard to tell which one(s) are to blame.

I know I could add another container and go through all the micro-config to setup stuff for something like Grafana with Prometheus, etc., but having this info right at a glance in the log viewer I use daily, would be immensely helpful.

**Describe the solution you'd like**

Over here:

![image](https://user-images.githubusercontent.com/1524526/207219668-9bbf835b-3f8f-46c8-8e94-a7477212a581.png)

It would be great to have dozzle simply add a "max" stat to each. For example, for Mem, it would show the current, plus the most it ever was logged as using (dynamically updating as necessary).

Like: 

Memory: `MEM 128.16 MB / MAX 928.10 MB`
Load:       `LOAD 0% / MAX 110%`

(the graph itself doesn't need to change; current is good. Just a label next to the current label stating the max stats)

and the big one in my case right now, a total data I/O label. So it could show the current I/O, plus the running total so far:

DATA: `I/O 400KB / TOTAL 3TB`

**Describe alternatives you've considered**
Grafana, etc. All those rather complicated to setup log viewer type containers.

**Comment by amir20** [comment]
This was a fun read.  I was amused by the use case. Let me respond inline. My time is limited with the holidays but perhaps something we can keep open. 

> I know I could add another container and go through all the micro-config to setup stuff for something like Grafana with Prometheus, etc., but having this info right at a glance in the log viewer I use daily, would be immensely helpful.

Have you tried `docker stats`? That shows I/O and probably easier than any other solutions. 

> It would be great to have dozzle simply add a "max" stat to each. For example, for Mem, it would show the current, plus the most it ever was logged as using (dynamically updating as necessary).

So the problem with this is that Dozzle has the majority of stats calculation done on the browser. This means that the max value would only be accurate for as long as Dozzle has been open in the browser. If you close the tab and open another one, it is lost. 

One thought I have had was to move this logic to the backend. Then historical data for all containers and meta data like max CPU, avg and other stats could be persistent until Dozzle container is restarted. 

I assume you would want the max value to be tracked in the backend for this to be really valuable to the user. Right? 

Everything else sounds aligned with I have been thinking of Dozzle. I think Dozzle is meant to debug and what you suggest would be nice to have.

**Comment by amir20** [comment]
@STaRDoGG ☝️

**Comment by amir20** [comment]
Sad. Didn't hear back.

**Comment by STaRDoGG** [comment]
Sorry @amir20 , if I'm not activly workiing on a project hosted on GH I usually don't login much, but yea, that sounds good. Maybe just a small sqlite to keep track, or even a text file?

**Comment by amir20** [comment]
I am back from the holidays. SQLlite is a bit of an over kill. I was planning to keep everything in memory so that I can track containers that get OOM. 

However, to be honest, I haven't had much time to work on this time and moving all the stats to API is more work than I have time. I was originally doing it because there was a performance bug that has been fixed on client.
