### ISSUE TITLE
How stop dozzle?

### ISSUE THREAD

**Issue by Barolina** [amir20/dozzle#1986]
I run like  docs 

```docker run --name dozzle -d --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:8080 amir20/dozzle:latest```

But now  dont remove or stop  images .

**Comment by amir20** [comment]
You probably want to learn more about Docker. `docker stop` and `docker rm`. 

In the future, try stackoverflow.com

**Comment by Barolina** [comment]
When i  do ```docker stop and  docker  rm```  dozzle   rises anew
