### ISSUE TITLE
Persistent storage and retention

### ISSUE THREAD

**Issue by daviddanko** [amir20/dozzle#1997]
Is there a way to create a persistent storage, so after a server reboot I don't lose all the collected logs? Additionally, a retention function also would also be really good.

**Comment by amir20** [comment]
Integrating a persistent storage is actually pretty complicated. I try to keep Dozzle to a minimal complexity and having to worry about storage, retention, expiration, disk space, etc... is beyond the scope I am willing to commit for Dozzle.

**Comment by m1212e** [comment]
Following up on this, would it be possible to persist logs across restarts of containers but not restarts of dozzle? E.g. simply setting an env var like RETENTION_TIME= 7d which results in dozzle showing some kind of history table where container logs are available after the container got removed? This way nothing would be saved to disk and usage/setup still would be easy but one could access crashes/error logs which might have occurred without the need to constantly actively monitor!

**Comment by amir20** [comment]
No, because that would require Dozzle to store the data. Just don't delete the containers until after 7 days they have been stopped. Simple!
