### ISSUE TITLE
Blank html page on startup, no output at all

### ISSUE THREAD

**Issue by anowak-ct** [amir20/dozzle#2008]
This app is not working at all. I tried it on 2 different ubuntu servers. After starting dozzle docker and accessing the dashboard, the page is blank.  It's basically the index.html page with no content injected by the app.

**Reproduce:**

1. Start a docker container, which I would like to monitor with dozzle
2. Start dozzle container

```docker run --name dozzle -d --volume=/var/run/docker.sock:/var/run/docker.sock -p 4444:8080 amir20/dozzle:latest --level trace```

3. Test output with httpie on server `http :4444`
--> Output:  Content of [index.html](https://github.com/amir20/dozzle/blob/master/index.html) with no data

4. Output of `docker logs -f dozzle`
```
level=info msg="Dozzle version v4.6.2"
level=debug msg="filterArgs = {map[]}"
level=info msg="Accepting connections on :8080"
```

**Environment:**
 * Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-135-generic x86_64)
 * Running docker as user, not root
 * Output of `docker version`
```
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:08 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:58 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I also tried to access dozzle with nginx rev proxy, same problem. Blank page with content of index.html:
```
location /dozzle {
        proxy_pass http://HOSTNAME:4444;
        proxy_buffering           off;
        proxy_cache                 off;
   }
```

**Comment by amir20** [comment]
The page is completely populated with javascript. Do you see any browser errors in the console?

**Comment by anowak-ct** [comment]
Ah, I missed `--base /dozzle` to work with my rev proxy.  It's working now.  Great tool, btw! Kudos!
