### ISSUE TITLE
Can anyone help with this

### ISSUE THREAD

**Issue by blassley** [amir20/dozzle#2017]
**Describe the bug**
Dozzle cpu% is very wrong

**To Reproduce**
N/a
**Expected behavior**
Real cpu usage 

**Screenshots**
![image](https://user-images.githubusercontent.com/49504228/215137547-73b8aae1-d579-47c0-a3e7-4017aa83e33c.jpeg)

**Desktop (please complete the following information):**
 - OS: unraid 
 - Docker version [e.g. `docker version`'s output]
 - Browser & version [e.g. chrome, safari]
 - Version 4.7.0

**If applicable include logs with `--level debug` and browser logs**

**Comment by blassley** [comment]
I have 2 Xeon e5 cpus

**Comment by blassley** [comment]
> How many CPUs do you have?

2 Xeon e5

**Comment by amir20** [comment]
I should have asked how many cores you have. I would run `lscpu` to be sure. But according to https://en.wikichip.org/wiki/intel/xeon_e5, there could be up 12 core. Which means a number 1180% makes sense. Each core can consume up to 100%.

**Comment by blassley** [comment]
> I should have asked how many cores you have. I would run `lscpu` to be sure. But according to https://en.wikichip.org/wiki/intel/xeon_e5, there could be up 12 core. Which means a number 1180% makes sense. Each core can consume up to 100%. 
> 
> 
> 
> 

Ahh I didn't know that's why it read, I figured it was complete cpu % not adding by core.. can this be changed?

**Comment by amir20** [comment]
That is the defintion used commonly. So to reduce confusion I want it to be consistent. If you run `htop` or `top` you will see similar numbers.
