### ISSUE TITLE
Allow to store/pin searches

### ISSUE THREAD

**Issue by obriat** [amir20/dozzle#2036]
Hi,
It would be nice to save searches and pin them in the sidebar, e.g; : CONTAINER/SEARCHNAME
On a dev machine, it's very useful to have on sight only your application logs (and not the container or middleware one)

**Solution I'd like**
Add a save button on the end of the search bar, that save the request search  and pins it on the side bar (under the container name)

**Alternatives**
Another way would be to pass these searches on the command line: `--saved_searches="/^DRUPAL"`. 

This would provide a way to commit the option in the docker compose so all your dev team could use it.

**Comment by amir20** [comment]
Hm interesting idea. 

So what be the flow? Something like 

* Click some container 
* Search "foobar" 
* See the results and click save 
* Would get added to the side bar as "[Container name] foobar"

Next time, user clicks on "[container name] foobar" and sees the same results?

I like the idea of saving, but I don't know where it would go. The current list is just containers. Maybe a drop down of saved searches and favorites?

**Comment by amir20** [comment]
Or even saved views with multiple panels too would be a good idea

**Comment by obriat** [comment]
and an unique url so it can easilly be boomarked

**Comment by EDIflyer** [comment]
Interesting idea! I can see how it could be handy during development work where you want to search for a known error message, etc.

**Comment by YouveGotMeowxy** [comment]
> Maybe a drop down of saved searches and favorites?

I'd really love to be able to save favorites. I run lots of containers, but there are only a small handful that I use frequently (i.e. SWAG, Authelia), and it can get cumbersome to have to search it half the time if it's not already in the main list.

Perhaps just add another link here entitled something like Favorites, next to the "All", you click it and it shows your favorites.

![image](https://user-images.githubusercontent.com/39491297/231236413-3a7dfbab-8908-4efb-8448-de757f1634d5.png)

**Comment by amir20** [comment]
That's a better idea. I actually plan to redesign the home page to most frequently used containers, and support for favorites. So maybe a better idea would be to allow for favorites in that view?

**Comment by EDIflyer** [comment]
bump due to @stale

**Comment by EDIflyer** [comment]
Just bump for stale, still think this could be handy :)

**Comment by amir20** [comment]
@EDIflyer Agreed. I have actually been thinking about this. As far as I can tell, there are three requests in this issue: 

- [ ] Store searches 
- [ ] Store panel setup
- [ ] Pin/favorite containers 

To do some of that, there were some prerequisites. The dashboard/homepage had to be redone. That's done now and I have been thinking how to provide more customization like saving searches or containers. 

A few things on my mind that is blocking this for better experience: 

* All user settings are saved on browser in `localstorage`. Meaning they won't carry over for multiple users or browsers. 
* There is only one user, so would there be value to even implement these? 

I thinking "pinning" containers makes sense right now. But I am still thinking about multi-user experience. I can keep all settings on `localstorage` but I don't know how valuable that would be.

**Comment by amir20** [comment]
Another option would be for Dozzle to support OAuth with something like Google and then I would have true user profiles. 

Right now I feel Dozzle is a great fit for small teams. But I do wonder if larger teams would find more value in have a multi-user option with each user having their own profile and saved searches.

**Comment by EDIflyer** [comment]
Thanks for looking into this @amir20 ! 👍 

Personally I tend to access Dozzle from multiple machines so would be keen for the option to remember preferences either per user (but appreciate you might not want to have the hassle of logins) or even to be able to save a couple of dashboards onto the server so I could then pick it when I'm accessing it rather than having to sort out my settings each time.  So I guess that would allow multi-user but without any of the login requirements, so some degree of trust between users (I guess a bit like Netflix/Amazon Prime where you can switch between users freely but people want to keep to their own so they get all their preferences/watch history)?

**Comment by amir20** [comment]
@EDIflyer 

> even to be able to save a couple of dashboards onto the server so I could then pick it when I'm accessing it rather than having to sort out my settings each time.

Thanks for the data point. Good to know I have some multi-host users. 

I'll have to think about it more to make it easy.

**Comment by amir20** [comment]
For everybody else #2350 has been merged in to master and it add pinning as an option! :) I also added a little animation. 

Try it with `amir20/dozzle:master` and provide feedback. It's look pretty good right now. 

🚀

**Comment by EDIflyer** [comment]
Looks nice, smooth animation and handy to be able to favourite/pin a container 👍

**Comment by amir20** [comment]
It does look nice. It is released now with a few other changes.

**Comment by EDIflyer** [comment]
Bump just as pinning sorted but perhaps still possibility of storing searches? :)

**Comment by amir20** [comment]
Thanks. I don't know why it keeps doing this. 

I am rethinking search so hopefully yes.

**Comment by amir20** [comment]
I think my work is done on this feature. I was planning to move search to backend which could in theory support a lot more features, but it's too much work.
