### ISSUE TITLE
Telegram Notification System 

### ISSUE THREAD

**Issue by nomanaziz** [amir20/dozzle#2038]
Assalamu alikum Dear Amir Brother,
First of all thanks for dozzle, 
I have a new feature request, Could you please add a telegram notification system based on keyword.
like "Error", "disconnected" ,"Other" at least 5 keyword Support When Keyword found trigger the notification.

Notification Info: "time" "container name" ,  "Keyword"

Thanks
-Noman

**Comment by amir20** [comment]
Hi @nomanaziz,

The focus on Dozzle is to help with debugging in real-time. Notifications and alerts is outside of my scope. You can of course send PRs. 

I'll close this as I won't have time to work on it.
