### ISSUE TITLE
Panic on the IBM s390x platform

### ISSUE THREAD

**Issue by p0vidl0** [amir20/dozzle#2041]
**Describe the bug**
Just builded a docker image at the linux/s390x platform and run a container. Can it be a bug caused by unsupported platform?

**To Reproduce**
Some containers' logs are not streamed to the frontend because the container is crashed with the error:
```
# docker logs -f dozzle_dozzle.1.wo0jhddkcamg6l19gwg8thxvd
level=info msg="Dozzle version dev"
level=info msg="Accepting connections on :8080"
panic: interface conversion: interface {} is float64, not string

goroutine 128 [running]:
github.com/amir20/dozzle/docker.guessLogLevel(0xc0002d3700)
        /dozzle/docker/log_iterator.go:149 +0x228
github.com/amir20/dozzle/docker.(*eventGenerator).consume(0xc000414a20)
        /dozzle/docker/log_iterator.go:115 +0x5b8
created by github.com/amir20/dozzle/docker.NewEventIterator
        /dozzle/docker/log_iterator.go:23 +0x112

```

**Environment:**
 - OS: Ubuntu at the IBM s390x platform
 - Version 4.7.4 (commit a03d83676fc057545d094c2966677f87185e57a5)
 - Docker version 
```
# docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:50 2022
 OS/Arch:           linux/s390x
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/s390x
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:
 runc:
  Version:          1.1.0-0ubuntu1~20.04.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

```

**Comment by amir20** [comment]
I think I know what the problem is. I was assuming `level` in a JSON to always be a string. You probably had something like `{level: 1.23}` which broke this logic. 

I have fixed that in https://github.com/amir20/dozzle/pull/2042 and merging soon. You can try the latest code and see if that works for you. 

A question for you, I am not too familiar with `IBM s390x`. What is it is used for? Is it a common arch? 

I wonder if Dozzle should also build for IBM s390x. 

Thanks!

**Comment by p0vidl0** [comment]
Thanks for the fast fix.
Yes, `level` field is integer like `10`/`20`/`30`/etc... And Dozzle works with it fine on traditional x64 platform.
[s390x](https://en.wikipedia.org/wiki/IBM_System/390) is a platform built by IBM for mainframes and enterprise application. The valuable difference is that CPU uses [big-endian](https://en.wikipedia.org/wiki/Endianness).

Docker image can be built using official s390x/node:19-alpine and s390x/golang:1.20.0-alpine images.

Thanks again, it works fine now!
