### ISSUE TITLE
Memory graph always at 0 under raspberry pi

### ISSUE THREAD

**Issue by Enissay** [amir20/dozzle#2044]
**Describe the bug**
I am running an instance of Dozzle on RPI 4B, Debian 11 x64. While the CPU graph shows some usage, the MEM is always nul

**Expected behavior**
Clearly the MEM graph is not properly working

**Screenshots**
![image](https://user-images.githubusercontent.com/794673/218313045-c0f94916-f105-4a6d-9c50-c18d91ddf910.png)

**Desktop (please complete the following information):**
 - OS: Debian 11 x64
 - Docker version: 20.10.22
 - Browser & version: Chrome, Version 110.0.5481.77 (Official Build) (64-bit)
 - Version: Dozzle 4.7.4

**Comment by Enissay** [comment]
I went and investigated the reasons and it seems to be an issue with docker on arm64: https://github.com/docker/for-linux/issues/1112

Which is confirmed when testing on my RPI4:
```
$ docker stats CONTAINER_ID
CONTAINER ID   NAME                                       CPU %     MEM USAGE / LIMIT   MEM %     NET I/O        BLOCK I/O    PIDS
2daa465456f1   blah_app.1.wsel6v0x                        0.01%     0B / 0B             0.00%     274kB / 44kB   120MB / 0B   33

```

I simply fixed it by adding `cgroup_memory=1 cgroup_enable=memory ` to the end of line in `/boot/cmdline.txt` followed by a reboot... If anyone had issues still, please refer to the link for more details...

**Comment by Enissay** [comment]
Okay, I just found out it is a duplicate of https://github.com/amir20/dozzle/issues/1965... Grrrr...

**Comment by amir20** [comment]
Yep. It is also in the README at the bottom in the FAQ section.
