### ISSUE TITLE
Add healthcheck for Docker container

### ISSUE THREAD

**Issue by JaneJeon** [amir20/dozzle#2045]
Hello, it would be nice to have a healthcheck for the Docker container itself.

Unfortunately it's not as simple as curl/wget'ing the endpoint as the container doesn't have curl/wget installed.

Thank you.

**Comment by amir20** [comment]
This is already possible. Did you see https://github.com/amir20/dozzle#enabling-health-check?

**Comment by JaneJeon** [comment]
It's been a while since I read the docs, seems like it's been updated since then. Thank you.
