### ISSUE TITLE
filter for dozzle

### ISSUE THREAD

**Issue by StephanKrauss** [amir20/dozzle#205]
Hello, is there a way to filter the messages of a container ?
For example, we use in the log messages a level and the message is a json object.

------------------
{ ... ,"level": 400, ... }

------------------------------

I will find all log messages with level >= 400.

Is there a way ?

Your sincerly

Stephan

**Comment by amir20** [comment]
No, there is no support of actually parsing JSON. Dozzle assumes everything is plan text.  The search box does support regex. So you can do `[45]\d\d` to find all 400..599 levels. 

Let me know if that helps.

**Comment by amir20** [comment]
Make sure you use `v1.17.3` because I had to fix a bug regarding regex. It should be live in a few minutes.

**Comment by amir20** [comment]
Closing this since regex should work. You can use the search box with `ctrl/command+f` in Dozzle.

**Comment by StephanKrauss** [comment]
Hello, thanks for the info.
Yesterday i can not find a filter.
I will test again.

Thanks.

Your sincerly

Stephan

**Comment by StephanKrauss** [comment]
Hello, is dozzle in version 1.17.3 on 'docker hub' ?

Greetings Stephan

**Comment by amir20** [comment]
Yup, it is here https://hub.docker.com/r/amir20/dozzle/tags?page=1&ordering=last_updated
