### ISSUE TITLE
Connections fails without TLS

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2066]
I keep getting this... the Docker host does not need a cert

```
level=info msg="Dozzle version v4.8.0"
level=info msg="Creating a client for tcp://xxxxx:2375"
level=fatal msg="failed to create tls config: could not read CA certificate \"/certs/ca.pem\": open /certs/ca.pem: no such file or directory"
```

_Originally posted by @agneevX in https://github.com/amir20/dozzle/issues/1593#issuecomment-1445119921_

**Comment by amir20** [comment]
@agneevX FYI should have fix now

**Comment by amir20** [comment]
@agneevX try master now. Should be fixed.

**Comment by agneevX** [comment]
Thank you, it works fine now.
