### ISSUE TITLE
How to get certs for tcp connections?

### ISSUE THREAD

**Issue by henryxrl** [amir20/dozzle#2090]
**Is your feature request related to a problem? Please describe.**
Complete noob here. I'd like to connect to multiple hosts but have zero knowledge of how to start with tcp and certificates. 

**Describe the solution you'd like**
Is it possible to provide or link to a simple tutorial on that?
Or, can we support Docker Socket Proxy? That can be a safe way to expose the docker socket on a more restricted and secure API.

**Comment by amir20** [comment]
If you look at Dozzle.dev there is documentation on how to set docker socket proxy. 

I use docker machine which sets up the certs for me. Hope that helps.

**Comment by henryxrl** [comment]
Ah! How can I miss that! Thank you so much!
Everything is running flawlessly now.

**Comment by amir20** [comment]
Great. Closing. If you find better introductions please send a pr to update docs.
