### ISSUE TITLE
Can't download packages for Docker

### ISSUE THREAD

**Issue by Audiotech70** [amir20/dozzle#2094]
Tried using docker CLI to install and got the following errors:

sudo docker pull amir20/dozzle Using default tag: latest Error response from daemon: manifest for amir20/dozzle:latest not found

Error if using 'sudo docker run -d' command:

Unable to find image 'amir20/dozzle:latest' locally docker: Error response from daemon: manifest for amir20/dozzle:latest not found.

Also tried using the tag: v4.8.2
sudo docker pull amir20/dozzle:v4.8.2
With the same manifest error.

I did notice that everything recently (except 'Master-Hub') has been pushed by "amirraminfar" instead of amir20.
Could this be the source of the manifest problem?

**Comment by amir20** [comment]
I was not able to reproduce this. I was able to `docker pull` successfully on my laptop and multiple linux machines. 

I also checked my analytics and 100+ have been installed with version `4.8.2` so it is working. 

It might be related to https://github.com/amir20/dozzle/issues/2015

**Comment by amir20** [comment]
What's your CPU architecture? Could it be that it not a compatible architecture?

**Comment by amir20** [comment]
Hmm ok so that should work....


Just for my own entertainment...can you try on a new computer or locally with a new version of Docker? I want to rule out any proxy issues. 

You can also try `amir20/dozzle:master` at https://hub.docker.com/layers/amir20/dozzle/master/images/sha256-3a4a0a44604f1a0a7cae3089602321390eba3828c6003da7425f5881a244c3f8?context=repo

Aside from that, I am running out of ideas.

**Comment by amir20** [comment]
I did some research and am still not finding anything. The best solution I can offer is enabling `debug` mode.  Instructions can be found here https://docs.docker.com/engine/reference/commandline/dockerd/ to enable debug mode with `dockerd`. 

After debug mode is enabled, `docker pull` should print extra logs.

**Comment by crebuh** [comment]
Hey @amir20 got the same issue on a remote server, where Docker version 17.09.1-ce, build 19e2cf6 is still running. But updating is currently not an option. 

> Error response from daemon: manifest for amir20/dozzle:latest not found

really weird because I'm able to pull other images from docker hub

**Comment by amir20** [comment]
@crebuh I won't be able to help much since I can't reproduce. Try enabling debug mode and see if that prints any helpful messages. I don't think I can install v17 either.

**Comment by amir20** [comment]
I spent a lot of time trying to install docker 17 with no success. I don't think I can help anymore.

**Comment by amir20** [comment]
That's amazing find. I had never heard of `dev.aliyun.com` until today. I also have a local Synolgoy at home but I was able to pull dozzle successfully. 

> Went back into the TNAS unit, changed the repo from dev.aliyun.com to hub.docker.com, and it was paydirt!

How were you able to change the repo? I want to test it to see if I can make it work for everybody else but I am not able to figure that out.

**Comment by amir20** [comment]
Oh I think I see it now. 

But even after switching the repo `docker pull amir20/dozzle` works for me. 


<img width="1336" alt="Screenshot 2023-04-10 at 8 54 57 AM" src="https://user-images.githubusercontent.com/260667/230940433-edd5c4af-6f1f-41b7-9fc5-a389c0e8484e.png">
