### ISSUE TITLE
[Feature Request] Display container health status

### ISSUE THREAD

**Issue by ericrafalovsky** [amir20/dozzle#2096]
# Description
One of our uses cases for `dozzle` is to look at logs to understand why a container may be unhealthy.  Docker has a [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck) feature that is exposed in `docker ps` that can point developers to what continer's logs may be interesting to investigate, but this requires using both the docker CLI and dozzle. It would be great if `dozzle` was able to surface this information to avoid needing to use the docker CLI. 

## Potential solutions
- Display a red icon in the left sidebar if a container is not healthy (per docker)
- Display some green/red indicator at the top of the UI to indicate if all containers are healthy / unhealthy

Thanks for all your work on this awesome project ❤️ !

**Comment by amir20** [comment]
This is an excellent idea. Let me see what the API returns and see if this is possible. I was thinking of showing different colors when CPU is too high. But maybe healthcheck is better.

**Comment by amir20** [comment]
@ericrafalovsky soo I did a quick investigation. Unfortunately, `docker list` does not return healthcheck status. But `docker inspect` does. Which means that I would have to inspect every single running container to get that status. 

That's going to be slow :( 

I have to do more research to see how `docker ps` shows it really fast without N calls. Let me know if you know....

**Comment by ericrafalovsky** [comment]
Hmm that's an interesting finding! I'm unfamiliar with how `docker ps`  works under the hood but perhaps utilizing the filter functionality of `docker ps` (ie ` docker ps --filter health=unhealthy`) is a way to grab the relevant minimal information quickly

**Comment by amir20** [comment]
This has been merged in master. Will deploy later today. @ericrafalovsky can you give it a try? 

<img width="297" alt="Screenshot 2023-03-29 at 8 54 21 AM" src="https://user-images.githubusercontent.com/260667/228598200-1d29f18d-9555-4613-ad08-054f762992f7.png">

**Comment by ericrafalovsky** [comment]
Tried it out and it works great!! 💯

**Comment by amir20** [comment]
Version is live now.
