### ISSUE TITLE
Explain healthcheck better

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2104]
Would it be worth adding something explaining this within the app?  Perhaps in the about section in the settings page there could be a wee explainer? It's just I was looking at Dozzle today and was confused why some containers had green ticks and others didn't - I hovered over the icon but of course it just changed to show the 'pin as column' option. Had a search through the changelogs and came across this, then cross-referenced in Portainer to see it was indeed the ones with status 'healthy' rather than just 'running' that got the ticks!

(PS as ever thanks for such a nice app for viewing log files!!)

_Originally posted by @EDIflyer in https://github.com/amir20/dozzle/issues/2099#issuecomment-1491010340_

**Comment by EDIflyer** [comment]
Great work - just tried the new version and looks ideal, tooltip works a treat 👍
