### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by nlznakub** [amir20/dozzle#2117]
When use --remote-host

![Screen Shot 2566-04-10 at 17 58 42](https://user-images.githubusercontent.com/22055458/230889254-e76121bd-a348-47cb-afba-4d55ec776a33.png)

Thank you.

**Comment by amir20** [comment]
There isn't any details for me to help. Please improve your description. `invalid character '<' looking for ...` is an error thrown when the application expects JSON. So something might be mis-configured.

**Comment by kavemang** [comment]
I also get this exact issue when using environment variables in docker for dozzles remote hosts @amir20 

![Capture](https://github.com/amir20/dozzle/assets/66108693/4b51d449-9393-47c6-9810-11c351fea79f)

**Comment by kavemang** [comment]
@amir20 @nlznakub is there additional info I can add that could reopen this?

**Comment by amir20** [comment]
@kavemang I don't think this is related to Dozzle. The error `invalid character...` means that the Docker isn't returning a proper response.  I wish there was a better error I could see but that's all I have. 

What is `tcp:10.0.0.129:9999`? Are you using TLS? I recommend [testing it with curl](https://docs.docker.com/engine/api/sdk/examples/). 

Sorry I can't provide more help as I don't know what the problem could be on your side.

**Comment by kavemang** [comment]
@amir20 

Well whatever it is related to the remote host function will not work in dozzle, the ips are other instances of dozzle im trying to connect to

**Comment by amir20** [comment]
> Well whatever it is related to the remote host function will not work in dozzle, the ips are other instances of dozzle im trying to connect to

Wait what? That's your problem. Remote hosts aren't other Dozzle running instances. They are the Docker API as described [here](https://dozzle.dev/guide/remote-hosts#connecting-to-remote-hosts).  

You need to create certs and export the Docker API. Alternately, you could use a [socket proxy](https://dozzle.dev/guide/remote-hosts#connecting-with-a-socket-proxy) which opens up the port publicly.  Do this if you are in a private network.

**Comment by thehijacker** [comment]
Had same issue. For start do no use Dozzle GUI port :). Indeed you need to export the docker API on port 2375. Here is how I've done it. Using this page as guide:

https://medium.com/@ssmak/how-to-enable-docker-remote-api-on-docker-host-7b73bd3278c6

Edit Docker systemctl service file:

`vi /lib/systemd/system/docker.service`

Append to the ExecStart line:

`-H=tcp://0.0.0.0:2375`

Reload systemctl:

`systemctl daemon-reload`

And restart docker:

`systemctl restart docker`

And I now see all the docker hosts:

![image](https://github.com/amir20/dozzle/assets/13857043/4f1f4d1d-561f-405d-8ff1-8026b1b69b16)

With this in docker compose file:

```
    environment:
      DOZZLE_HOSTNAME: Docker
      DOZZLE_REMOTE_HOST: tcp://192.168.28.56:2375|Mailu,tcp://192.168.28.54:2375|Seafile,tcp://192.168.28.55:2375|Video
```
