### ISSUE TITLE
No containers or anything loading

### ISSUE THREAD

**Issue by hunterwinterton** [amir20/dozzle#2118]
**Describe the bug**
I am running Dozzle, but the page looks like it is just infinitely loading, no containers are showing up or logs.

**To Reproduce**

1. Install dozzle using the default docker-compose https://dozzle.dev/guide/getting-started
2. Try and load webpage
3. See that nothing loads

**Expected behavior**
To see the logs of all of my docker containers

**Screenshots**
<img width="1775" alt="Screenshot 2023-04-10 at 5 30 16 PM" src="https://user-images.githubusercontent.com/68767432/231018339-cb372730-0024-4099-9b16-3566a95f06b4.png">

**Desktop (please complete the following information):**

- OS: Synology DSM
- Docker version 20.10.3
- Browser & version Safari and Edge
- Version 4.9.3

**If applicable include logs with `--level debug` and browser logs**
Safari: No logs
Edge:
<img width="650" alt="Screenshot 2023-04-10 at 5 56 08 PM" src="https://user-images.githubusercontent.com/68767432/231021260-1ae02e85-2d15-4e1b-b7e1-66babae3c5f4.png">

Container logs:
level=debug msg="starting to stream stats for: b17422ff8918"
794
level=debug msg="starting to stream stats for: d0da13de20e0"
795
level=debug msg="starting to stream stats for: 2454b6f6c371"
796
level=debug msg="starting to stream stats for: 8eb4e8863083"
797
level=debug msg="starting to stream stats for: 7dd2991a8d94"
798
level=debug msg="starting to stream stats for: 9bf9bd3a189b"
799
level=debug msg="starting to stream stats for: 6692ec793c09"
800
level=debug msg="starting to stream stats for: bcd510a3d81b"
801
level=debug msg="starting to stream stats for: 227eafe22bac"
802
level=debug msg="starting to stream stats for: 7ac3fa042d6f"
803
level=debug msg="stopping stats streaming for container 41bf74740c47"
804
level=debug msg="stopping stats streaming for container b6ba9c6d7bb2"
805
level=debug msg="stopping stats streaming for container e0e1461a6862"
806
level=debug msg="stopping stats streaming for container 69501e449d5c"
807
level=debug msg="stopping stats streaming for container b320ffc903e2"
808
level=debug msg="stopping stats streaming for container f5086819ddca"
809
level=debug msg="stopping stats streaming for container 7ac3fa042d6f"
810
level=debug msg="stopping stats streaming for container 2454b6f6c371"
811
level=debug msg="stopping stats streaming for container 6636199d6d68"
812
level=debug msg="stopping stats streaming for container a3c5fd52fa0b"
813
level=debug msg="stopping stats streaming for container fd3cdc4742ff"
814
level=debug msg="stopping stats streaming for container 6538f3e47ab3"
815
level=debug msg="stopping stats streaming for container 0e3803614315"
816
level=debug msg="stopping stats streaming for container 3133745439da"

**Comment by amir20** [comment]
I don't think those JavaScript errors are related. Could this be your problem? https://dozzle.dev/guide/faq#i-installed-dozzle-but-logs-are-slow-or-they-never-load-what-do-i-do

**Comment by hunterwinterton** [comment]
> I don't think those JavaScript errors are related. Could this be your problem? https://dozzle.dev/guide/faq#i-installed-dozzle-but-logs-are-slow-or-they-never-load-what-do-i-do

I'm currently not using a reverse proxy to access it, would that still cause this problem?

**Comment by amir20** [comment]
I don't think so. But I have seen Synolgy have its own proxy. I just tried it this morning on my Synolgy and it worked. 

Can't think of anything else. I'll try again tomorrow.

**Comment by amir20** [comment]
@hunterwinterton I was able to use everything on my Synology with Safari. I don't have Edge but it worked with Chrome. Here are a couple of things you can try to make sure everything is working....

1. Let's make sure the stream is working correctly. Go to `view > developer > developer tools` and open the network tab. You should see something called `stream?host=localhost` that will look like 


<img width="1805" alt="Screenshot 2023-04-11 at 8 33 36 AM" src="https://user-images.githubusercontent.com/260667/231214732-46229c71-6021-4991-95cc-c7dc04721b4e.png">

You should see `container-stat` being streamed. 

2. You can also go to `http://host:port/api/events/stream?host=localhost` that should show something similar. 


I can't think of any other way to debug so let me know if you find any other error logs. For some reason, your data is not loading so we need to figure that out.

**Comment by YouveGotMeowxy** [comment]
I've been getting the same thing:

![image](https://user-images.githubusercontent.com/39491297/231231162-3a4961ba-e441-4e88-b182-d256a55139f1.png)

I do think it has something to do with Nginx or the reverse proxy, because if I access it directly (no reverse proxy) it loads fine, but I have the buffering off stuff as well as my cloudflare set to dns only for it's domain, so I cant figure out why?

I'm using WSL2 native docker (not docker desktop), LSIO's SWAG, and their Dozzle Reverse Proxy as well, which has this:

```
## Version 2023/02/05
# make sure that your dozzle container is named dozzle
# make sure that your dns has a cname set for dozzle

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name dozzle.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app dozzle;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # Add Theme
        set $app dozzle;
        include /config/nginx/theme-park.conf;
        proxy_hide_header "x-webkit-csp";
        proxy_hide_header "content-security-policy";
    }

    location /api {
        include /config/nginx/authelia-location.conf;
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app dozzle;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_buffering off;
        proxy_cache off;
    }
}
```

Just a note, I have also already tested with commenting out both the themes lines and authelia lines, but same thing.

**Comment by hunterwinterton** [comment]
> @hunterwinterton I was able to use everything on my Synology with Safari. I don't have Edge but it worked with Chrome. Here are a couple of things you can try to make sure everything is working....
> 
> 1. Let's make sure the stream is working correctly. Go to `view > developer > developer tools` and open the network tab. You should see something called `stream?host=localhost` that will look like
> 
> <img alt="Screenshot 2023-04-11 at 8 33 36 AM" width="1805" src="https://user-images.githubusercontent.com/260667/231214732-46229c71-6021-4991-95cc-c7dc04721b4e.png">
> 
> You should see `container-stat` being streamed.
> 
> 2. You can also go to `http://host:port/api/events/stream?host=localhost` that should show something similar.
> 
> I can't think of any other way to debug so let me know if you find any other error logs. For some reason, your data is not loading so we need to figure that out.

Here is my network tab. It looks like it is streaming..
<img width="1789" alt="Screenshot 2023-04-11 at 8 13 37 PM" src="https://user-images.githubusercontent.com/68767432/231330205-c873bde5-9bf1-4443-8a2b-1454fff19f49.png">

**Comment by amir20** [comment]
> Dunno if this is related, but in Dozzle 4.9.3 I'm getting this error right now in my log:
> 
> 
> 
> ```
> 
> 04/12/2023 3:24:25 AM
> 
> level=error msg="error encoding containers to stream: write tcp 10.0.36.205:8080->10.0.36.3:41118: write: broken pipe"
> 
> ```
> 
> 
> 
> MAH PIPE IS BROKEN! lol
> 
> (I really have no clue what that actually means)


I think I have seen that error. It might be when the browser tab is closed the stream breaks. I don't think it's actually a bad thing.

**Comment by amir20** [comment]
@hunterwinterton that actually looks correct. I am not sure what your problem is. I can't help much. Usually in situations like this I would add more logging and ask you to retry but I don't even know what is broken to know where to add more logs. 

I hope you can try Dozzle on a different host to see if that works at least.

**Comment by hunterwinterton** [comment]
I got mine to work.

For some reason, it worked on my phone remotely while connected through Tailscale. It also works after I just tried through a reverse proxy, so it's just not working locally. Problem solved for me!
