### ISSUE TITLE
Some text not showing unless in json view?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [amir20/dozzle#2120]
For example, the logs for Authelia,:

![image](https://user-images.githubusercontent.com/39491297/231237775-103d7e6f-a38b-405d-92ed-0ff494d070cc.png)

I don't know if maybe in the code the `<` and `>` need to be escaped for it to show?

**Comment by amir20** [comment]
Oh that's weird. Can you figure out the exact value by using `docker logs` so that I can use it for my own testing? 

Thanks for the find.

**Comment by amir20** [comment]
I see the problem now. Hmm have to think of this one how to fix it.

**Comment by YouveGotMeowxy** [comment]
Confirmed fixed. Thanks!
