### ISSUE TITLE
Memory issue with version 4.9

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2121]
**Describe the bug**
For my own use cases, I am seeing Dozzle sometimes taking up to 1GB. This should never happen because I start throwing old logs away. But for some reason that is not working.

Something to investigate. 

**Expected behavior**
Should never use more than XXX RAM. 

**Screenshots**

**Desktop (please complete the following information):**

Reproduced in latest Chrome 112.

**Comment by amir20** [comment]
I am not able to reproduce this consistently so it might be something on the client.

**Comment by amir20** [comment]
@YouveGotMeowxy I don't think it is related to this issue. I found this memory issue on the browser which was hitting 1 gb ram at some point.  

Dozzle itself is written in golang and I have never seen it use more 15 MB. 

Most likely what fixed your issue was that you restarted everything and something else happened. I have actually seen this before where restarting all containers fixes proxy issues.

**Comment by YouveGotMeowxy** [comment]
I have never seen it use more 15 MB

Now ya have! LOL
![image](https://user-images.githubusercontent.com/39491297/231755033-56cf8215-4e4f-4bac-b35a-5d7a12897579.png)

I've seen it go up to about 25-30 (when i've been paying attention).

I think you're right though about the restarts. It has gone back to essentially freezing on refresh. I have no idea why, but it's driving me absolutely bonkers.

**Comment by amir20** [comment]
Ha. You must have more than a dozen containers? 

You said earlier that when not using a proxy, everything works fine, right? Maybe for a way to isolate the problem use the Dozzle without proxy and see if you noticed any slow down. I am guessing you won't. 

If you have the option, use a different proxy, like traefik, caddy or squid. We can open a new bug if you do think it is related to Dozzle. I already send some http headers to force no caching. But I guess not all proxies support it.

**Comment by amir20** [comment]
So this seems not related to Dozzle. I was getting `net::ERR_NETWORK_CHANGED` errors which took me a while to hunt down. It looks like it is related to IPv6. Chrome has a bug which doesn't work well with SSE connections. More info [here](https://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome).
