### ISSUE TITLE
Check for image updates

### ISSUE THREAD

**Issue by marcusique** [amir20/dozzle#2124]
**Is your feature request related to a problem? Please describe.**
Feature request.
I know it's not a scope of this app, but it can be useful for many.

**Describe the solution you'd like**
Show a prompt if there's an image update available (could be an icon similar to the health check icon) or info on the container page.
![Screenshot 2023-04-13 at 12 09 54](https://user-images.githubusercontent.com/23212368/231727783-eddbab7c-66d8-439a-a65c-f28867406eac.png)
Maybe something like this
`amir20/dozzle:latest  current: 4.9.3  new: 4.9.4`

**Describe alternatives you've considered**
N/A

**Additional context**
It could be a hassle to check if there are updates for tens of images, so it would be quite useful to add this functionality to the app. 

Thanks!

**Comment by amir20** [comment]
Good idea. But I think it would be out of scope for Dozzle. I would have to make an additional http request per container which get complicated if you think how often people switch logs. 

I also don't think this feature helps in diagnosing or debugging their application.
