### ISSUE TITLE
Idea: don't show hash in container names

### ISSUE THREAD

**Issue by YouveGotMeowxy** [amir20/dozzle#2144]
**Is your feature request related to a problem? Please describe.**

When having lots of containers, it can look like word salad, and cluttered or "noisy" trying to look through the list. (I know there's a search but sometimes I just want to quickly scan with my eyes), and make finding the container you want more "eye-fatiguing" than necessary.

**Describe the solution you'd like**

Since hashes aren't often necessary for cases like this, it would be nice to have an option for users who don't choose to see the hashes. Perhaps default that option to show the full hash as it currently does, and then the user can go into the settings and choose to hide them.

Then you'd be left basically with just the name of the container, and if in a swarm, the swarm name and container name, both of which are actual "human readable" words rather than random chars.

**Additional context**

Here's an example screenshot of my list. Look at all that noisy, unhelpful, ugly random hashing in each container. :)

![image](https://user-images.githubusercontent.com/39491297/233873210-10a6b4bd-d4d5-4255-bc3f-da196d50483d.png)

As an example, I drew a line through the hashes to show what to hide. IN the case of more than 1 of the same container, an idea may be to only show the 1st letter of the hash to distinguish it (see the second item with a line through it that shows only the first letter of the hash).

**Comment by amir20** [comment]
Wow you are running a lot of containers. 

> Since hashes aren't often necessary for cases like this, it would be nice to have an option for users who don't choose to see the hashes. Perhaps default that option to show the full hash as it currently does, and then the user can go into the settings and choose to hide them.


I generally avoid multiple options in settings. The reason being maintenance. It's just hard to support different combinations of settings for all users. So I try to keep Dozzle as simple as possible.  Instead, I try for best defaults that makes everybody happy and only introduce different flags when really needed. 


Perhaps, Dozzle should just be smart to _dim_ the hash. So not completely hide it, but make it darker so that it is easier for the eye to scan.  That way it just works for everybody. 

What do you think? 

I'll try to make something up.

**Comment by amir20** [comment]
Something like this 

<img width="721" alt="Screenshot 2023-04-24 at 8 48 46 AM" src="https://user-images.githubusercontent.com/260667/234049265-072bd886-e2e1-418a-81dc-199c3f3ee77b.png">

**Comment by YouveGotMeowxy** [comment]
That's not too bad, I think I could live with that! lol

lol, yea, I run lots of containers. I do both a HTPC setup, ebooks, and even some development type stuff. Actually, it always kinda surprises me when people tell me that I run a lot of containers, because I'm just like, wait.... how come you DON'T?? haha

**Comment by amir20** [comment]
This is being released now as `4.10.1`.

**Comment by YouveGotMeowxy** [comment]
This is working great so far; one question though, is this a bug or intended?

Some containers still show the hash. It seems like if it starts with something like .gb1 (or some part of it) causes the hash to "still come through"?

![sshot-4](https://user-images.githubusercontent.com/39491297/236373653-67b2b2a4-3f65-4ddb-861c-4924b1b5b369.png)
![sshot-3](https://user-images.githubusercontent.com/39491297/236373655-0468772f-251d-4f5b-89c9-7bc7e9464da5.png)

**Comment by amir20** [comment]
Also, it's weird that you screenshot doesn't show the hash at all. Did you do something to your colors.  It should like 

<img width="267" alt="Screenshot 2023-05-05 at 8 27 51 AM" src="https://user-images.githubusercontent.com/260667/236501401-bc6f1900-2e7f-4bd0-afc7-37a2cd26c953.png">

**Comment by amir20** [comment]
@agneevX see screenshots here to understand why it is bold. Open to suggestions but on my three laptops it looks fine.

**Comment by agneevX** [comment]
I'm not familiar with hashes since none of my containers have those :(

**Comment by amir20** [comment]
Can you share a screenshot where you think the bold is too strong? I am on retina display so it's pretty minimal.

**Comment by YouveGotMeowxy** [comment]
I was playing in the dev inspector and the hashes may not be showing because i was playing with their transparency, I forget offhand, but here is a screenshot of the list right now:

![image](https://user-images.githubusercontent.com/39491297/236565797-5ba52309-758d-4a9c-83b6-5bf97ce53578.png)

Also just noticed that some (highlighted) hashes also have "2 hashes". 

I haven't done any inspecting yet, but' Ill see if I can spot anything.

**Comment by YouveGotMeowxy** [comment]
After a little thought, since I'm running swarm and some containers get spread to other nodes (which I think might be the ones with "2 hashes") that might be the reason for that, as well as the regex length requirement, But again, this is after just some quick thought and literally no looking into yet (I'm at work).

**Comment by amir20** [comment]
Oh wow. There is the explanation. What's causing two hashes?  If it is because of other nodes then that might be a good reason because I didn't test for that. 

Let me know and we can update the regex.  Perhaps there is a docker page about the logic behind this.

**Comment by YouveGotMeowxy** [comment]
> We could also use (\.[a-z0-9]{25})+$ that would capture any repetition of 25 hashes.

That regex looks perfect!

**Comment by agneevX** [comment]
> Can you share a screenshot where you think the bold is too strong? I am on retina display so it's pretty minimal.

I'm using a Retina display as well, it's only bold to me because I do not have hashes next to container names. So it just looks plain bold for no apparent reason.

**Comment by YouveGotMeowxy** [comment]
@amir20 Hi Amir, I really hate being the bearer of bad news :( but after updating it seems the new regex isnt working for some reason. Now it looks liek this in my running container:

![image](https://github.com/amir20/dozzle/assets/39491297/49ed941f-fe9d-4f8c-a5cb-6b6b32774675)

Looking at the commit I cant really understand why, since when I tried the regex at regex101 it was working perfect.

**Comment by agneevX** [comment]
Thanks @amir20, the fix looks good!

**Comment by amir20** [comment]
@YouveGotMeowxy Can you provide exact example of some of the container names so I can test? Don't use Dozzle. Use `docker ps` in case of another bug.

**Comment by amir20** [comment]
Wait, I see something funky going on for me too.

**Comment by YouveGotMeowxy** [comment]
> @YouveGotMeowxy Can you provide exact example of some of the container names so I can test? Don't use Dozzle. Use `docker ps` in case of another bug.

I'm still seeing issues with the regex in `4.10.7`:

![image](https://github.com/amir20/dozzle/assets/39491297/29ba9372-7c2d-407e-8fdd-889fde9094dc)

Here's my entire list of container names: https://pastebin.com/be0q31Mt

Sorry this is being such a pain!

**Comment by amir20** [comment]
I'll look at it again today but the latest push fixed some of the problems I was seeing.

**Comment by amir20** [comment]
I was able to reproduce it with your `pastebin` link. Let me see if I can figure out what is not working.
