### ISSUE TITLE
Improvement: add action button for non existing containers on mobile

### ISSUE THREAD

**Issue by marcusique** [amir20/dozzle#2147]
**Is your feature request related to a problem? Please describe.**
Improvement of UI.

**Describe the solution you'd like**
I keep a lot of tabs open in my mobile browser with container logs that I'm most interested in checking from time to time. Sometimes I need to update an image of the container and its id changes after the update, meaning that my already open tab for that container turns completely blank on mobile.

![IMG_0782](https://user-images.githubusercontent.com/23212368/234216871-2425e188-3453-4d95-a185-544420243130.PNG)

It's not a problem on desktop as there's a list of containers on the left side that I can quickly select, but I can't do that in mobile view. It would be great to add an action button for non-existent container id that would lead to the home page of dozzle, something like:
`Container does not exist, **click here** to see the list of containers.`
This would save people many taps on the screen and more importantly – time :) 

**Describe alternatives you've considered**
N/A

**Additional context**
iOS 16.4.1
Safari and Firefox

**Comment by amir20** [comment]
>  container turns completely blank on mobile.

Something doesn't feel right here. What happened to your top nav bar? 

![clashleaders_worker 1 - Dozzle @ clashleaders com](https://user-images.githubusercontent.com/260667/234412626-9f6ec705-4e27-40d7-ab34-5f6c2635f0d0.jpeg)

> Sometimes I need to update an image of the container and its id changes after the update, meaning that my already open tab for that container turns completely blank on mobile.

Shouldn't that just find the old container with some data? Or are you also removing the old container? 

Fixing the top bar should be more important than forwarding to a 404 page.

**Comment by marcusique** [comment]
@amir20 

> What happened to your top nav bar?

My nav bar is there on existing pages, once it's 404 then the navbar is gone. Try opening a container log and add an extra letter or number to the container id in the address bar. I could live with the nav bar on 404 pages as tapping on it leads to the main page.

> Shouldn't that just find the old container with some data? Or are you also removing the old container?

I'm running all my containers with `docker compose` and here's what I do to update them

```
docker compose pull
docker compose down
docker compose up -d
```
This results in new container id.

**Comment by amir20** [comment]
Fixed the issue in 8325945 but used the wrong issue. Going to release a new version.

**Comment by amir20** [comment]
Try `4.10.2`

**Comment by marcusique** [comment]
I can confirm it's fixed now. The reason the logs aren't being pulled for the updated containers is that I remove the old container once the update has been completed, so it's a false alarm there.
Thank you!
