### ISSUE TITLE
Merging and viewing multiple container logs in a single view

### ISSUE THREAD

**Issue by audibleblink** [amir20/dozzle#2150]
**Is your feature request related to a problem? Please describe.**
In cases where one is dealing with multiple closely related containers, it would be helpful to view a subsection of all available logs. For example, given a pub/sub application, it may be necessary to see that the different consumers are taking tasks from a queue in a specific order. Or perhaps that multiple replicas of a single consumer are consuming the tasks equally. 

**Describe the solution you'd like**
Either being able to shift+click containers, or a multi-select mode where multiple containers can be selected.
When multiple containers are selected, the log view should insert the container name between the timestamp and log line.

**Describe alternatives you've considered**
`docker compose logs` works in a terminal if the application was deployed that way. If the app is deployed on something like docker swarm, this feature would fill that void and then some since dozzle adds so much more than just logs on a terminal.

**Additional context**

docker compose logs example
![image](https://user-images.githubusercontent.com/4605783/234333430-8b69af81-db67-45da-b909-6e89d70aabbe.png)

**Comment by amir20** [comment]
Hello @audibleblink -- So this was discussed probably a year ago when Dozzle was gaining traction. At the time, some users were asking for split screen and others for a way to merge logs into one view. Both are feasible. I eventually opted in for split screen because it was consistent with other logging tools. It also allows for more customization like scrolling back only one screen or following logs that are completely unrelated to each other. 

So I wonder what value this brings to just split screen. 

Also, I am the only developer implementing all these features, which makes it hard to say 'yes' to all requests. I have been prioritizing top asks that feel more useful to majority of users. This feels more specific to a small group. But I am biased.

**Comment by audibleblink** [comment]
Hey @amir20 !
IMO, the benefit of a single view is the preservation of the timeline. With timestamps, one can see how their containers are interacting with each other and ensure that the order of operations is what's expected of their own application. 

I can't speak to the majority of your users' needs however, you would know that better than me. 
But I appreciate the default way that `docker compose logs` or `docker compose up` (without the `-d` flag)  already does this.
It would be a very familiar view for users of those commands. I just wish you could do the same with a `stack` on Swarm.

**Comment by amir20** [comment]
Let's leave this open for a while. I would rather just implement split screens or merged logs. But not worth both because then that's so much work to maintain. 

Meanwhile, does split screen just not work for you?

**Comment by audibleblink** [comment]
Not in this instance, because of the timestamps, but that's OK. I don't mean to impose work, I know this is OSS. I just thought it might be a useful feature. I'm still using dozzle for other less complicated applications

**Comment by amir20** [comment]
Ok so I took a little look. Right now the javascript is setup to only have one data source per log view. It would be a re-architecture to support such use case. 

My general thought process is if the cost is heavy then it should be a valuable feature for all users. If the cost is low then it's ok to make it happen for some users.  As an example, so many people had asked for multiple remote hosts feature, but sadly only `0.5%` have used that feature.  Was definitely not worth my time 🤔

This is a pretty big change so I am going to say not worth doing right now.

**Comment by webysther** [comment]
> Ok so I took a little look. Right now the javascript is setup to only have one data source per log view. It would be a re-architecture to support such use case.
> 
> My general thought process is if the cost is heavy then it should be a valuable feature for all users. If the cost is low then it's ok to make it happen for some users. As an example, so many people had asked for multiple remote hosts feature, but sadly only `0.5%` have used that feature. Was definitely not worth my time 🤔
> 
> This is a pretty big change so I am going to say not worth doing right now.

Yeah, I think the js need to be precise to have this kind of performance, maybe a background work to detect the stack and send the docker-compose logs to the front, just a ideia. I will look around in the code.

**Comment by webysther** [comment]
> 

First search response in google images.

But looking around I saw that Docker Desktop have a official extension that support this kind of behavior:

![image](https://user-images.githubusercontent.com/750007/236342670-04231bd9-9fc8-4d07-b651-f90eaa4ce519.png)

**Comment by amir20** [comment]
Yup. I use that extension to steal a lot of ideas. 😂

Did you see my other comment? For stacks to work Dozzle would need to support services too.

**Comment by webysther** [comment]
> 

Yeap, I need time to process all that information, but LGTM, I used swarm when docker compose included on v3 but stoped after all bugs that explode in my face. I tried k3s too but for a simple mortal trying to create a functional self-hosted env sounds too much.

I look the code and now I have a better view how works, you open a WS and stream all flow, cleaver.

**Comment by amir20** [comment]
> I look the code and now I have a better view how works, you open a WS and stream all flow, cleaver.

It's actually Sever Side Events. Like WS, but one directional. It works real well.
