### ISSUE TITLE
Host switching/container stats missing on mobile viewports

### ISSUE THREAD

**Issue by agneevX** [amir20/dozzle#2157]
Host switching, MEM/CPU views are currently missing from mobile... it would be very useful if it were added. Especially host switching.

**Comment by amir20** [comment]
- [ ] Adds hosts to mobile view
- [ ] Adds stats to top title

**Comment by amir20** [comment]
Added to mobile for host drop down. Can you give `amir20/dozzle:master` a try?

**Comment by agneevX** [comment]
It appears to hide the name of the container:

<img src="https://user-images.githubusercontent.com/19761269/235115475-789aad82-95de-4ce2-8622-5f93578b35c0.png" width="350">

**Comment by amir20** [comment]
Yea, I had to remove the container name. If I put the drop down in the expandable menu then it pushes everything down too much. 

It's hard to get the right space on mobile since everything is so jammed together.

**Comment by agneevX** [comment]
I think putting the switcher inside the hamburger menu is a good idea, it'll look similar to how it is on desktop.

**Comment by agneevX** [comment]
Hey, would it be possible for you to revert the bold text for containers in the sidebar? Feels very weird to use now since the emphasis looks out of place.

**Comment by amir20** [comment]
There needs to be some differentiation between actual name and hash. Can you follow up on #2144? It was discussed in depth there and why we needed to add it. 

I am open to suggestions as long there isn't all kind of settings to enable or disable it :)

**Comment by amir20** [comment]
<img width="499" alt="Screenshot 2023-05-22 at 3 32 45 PM" src="https://github.com/amir20/dozzle/assets/260667/e7473506-9004-47e8-8c86-5adc87c6b8ff">


Currently in the works....

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/pull/2212

**Comment by amir20** [comment]
Released
