### ISSUE TITLE
Graphical usage in home

### ISSUE THREAD

**Issue by webysther** [amir20/dozzle#2169]
The same usage graph in every container but in the home, the numbers is great, but a graphic will be nice, maybe as a feature flag.

**Comment by amir20** [comment]
Didn't hear back.

**Comment by webysther** [comment]
> I plan for the home page to be redesigned. So maybe I'll revist this.
> 
> Are you asking for one graphical usage across all containers or one per container on the home page?

Sorry for late response, I lost myself in notifications. Both sounds nice, but for me the same as the actual (all containers) but with graphics.
