### ISSUE TITLE
Unreadable text on light theme with ANSI colors

### ISSUE THREAD

**Issue by PaoloConte** [amir20/dozzle#2175]
Hello,
it seems that, when using ANSI colors, the text with no color is always rendered white regardless of theme. In a real terminal, instead, the color is correctly white of black background and black on white background.

This is the color pattern I use, in particular the last part has no specific color:
```
 <pattern>%gray(%d{YYYY-MM-dd HH:mm:ss.SSS,Europe/Rome}) %highlight(%-5level) %cyan(%logger{50}) - %msg %n</pattern>
```

Here screenshots from the terminal
<img width="341" alt="Screenshot 2023-05-06 at 12 23 30" src="https://user-images.githubusercontent.com/4893669/236618595-86897b59-c84d-4153-a3ca-2c109e98ff06.png">
<img width="357" alt="Screenshot 2023-05-06 at 12 23 15" src="https://user-images.githubusercontent.com/4893669/236618597-0ad5fe74-1019-422b-92e9-6d70626f1dac.png">

Here screenshots from dozzle with light theme
<img width="906" alt="Screenshot 2023-05-06 at 12 15 22" src="https://user-images.githubusercontent.com/4893669/236618598-ae3faaf1-1c45-41a5-b604-dff38c6ec556.png">

Thanks

**Comment by amir20** [comment]
Hi @PaoloConte,

A few a people have asked me this. Dozzle doesn't handle the colors at all. The ansi colors as passed to https://www.npmjs.com/package/ansi-to-html. It might be possible that `ansi-to-html` has a bug and assumes white when not color is specified.

**Comment by amir20** [comment]
According to https://github.com/rburns/ansi-to-html#options, `The default foreground color used when reset color codes are encountered` so it might be that your logging utility is emitting a reset color code. 

Can you check what the color code your outputting?

**Comment by PaoloConte** [comment]
Hi @amir20 ,
yes, the logged string is as follows:
```
[34mINFO [0;39m [36mMain[0;39m - Starting 
```
The last part uses code 39 which is DEFAULT color. So, I would expect that the default color is black on light theme and not white.

Thanks

**Comment by amir20** [comment]
If I can tell `ansi-to-html` to use my css colors then it should be possible. I'll test really quick with your exmaple.

**Comment by amir20** [comment]
Well that worked that out really well. I was able to use CSS `var(--text-color)` and reuse my styles. I wonder if I should do the same with background but I imagine background color should be ignored.

**Comment by amir20** [comment]
@PaoloConte try `amir20/dozzle:pr-2180` 

I can merge later and deploy....

**Comment by PaoloConte** [comment]
Thanks! Great news :)
I don't personally use background colors in my logs, but it seems it would be safe to use `transparent` as default background.

**Comment by PaoloConte** [comment]
I'm going to test it and let you know

**Comment by PaoloConte** [comment]
Confirmed working! Maybe the color palette could be optimized for dark and light themes, but that's another story...

<img width="636" alt="Screenshot 2023-05-08 at 19 05 41" src="https://user-images.githubusercontent.com/4893669/236886234-bdbba1e2-df3a-4bff-8f02-cf3069bd95c1.png">
<img width="821" alt="Screenshot 2023-05-08 at 19 03 56" src="https://user-images.githubusercontent.com/4893669/236886238-614884a7-0c80-4c46-bec0-072c15e0a495.png">

**Comment by amir20** [comment]
I don't have control over the color palate. Just foreground and background. I also noticed `INFO` is really ugly.

**Comment by PaoloConte** [comment]
According to the library you have control over colors

> colors Object/Array (with values 0 - 255 containing CSS color values). Can override specific colors or the entire ANSI palette

**Comment by amir20** [comment]
Yea it allows you to override specific CSS colors. I don't think allowing Dozzle to configure all the different colors would be the right way to go.

**Comment by PaoloConte** [comment]
As far as I'm concerned, I'm happy with it.  Thanks :)
