### ISSUE TITLE
Feature request: add non-Docker log files though ENV var?

### ISSUE THREAD

**Issue by elisimpson** [amir20/dozzle#2224]
It would be awesome to be able to use Dozzle to monitor arbitrary non-Docker logs. As an example maybe you'd mount /var/log as a read-only volume and then pass paths to specific logs you want to monitor via an ENV var? Would make Dozzle even more useful then it already is.

**Comment by amir20** [comment]
I don't think this is within the scope of Dozzle. Dozzle uses Docker APIs to fetch all logs, stats and other meta data for each container. To support files, I'll have to recreate Docker APIs for filesystem. That's a lot of work. But there is a way around it...

If you just want to mount files you could use `alpine` with `tail` to basically do anything.

```
docker run -v /var/log/system.log:/var/log/test.log alpine tail -f /var/log/test.log
```

I tested this and on my machine it only takes `~300KB` of memory. Really cheap way to mount any file and start printing its content. These best part is that `tail` is smart to follow up on the file if it is recreated. 

Hope this helps! 

Ps. It would be awesome to update documentation if you think this would be useful for other people.

**Comment by amir20** [comment]
Haven't heard back. Closing.

**Comment by amir20** [comment]
Added https://dozzle.dev/guide/log-files-on-disk
