### ISSUE TITLE
Allow to only show stdout or stderr logs

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#2225]
**Is your feature request related to a problem? Please describe.**

I would like to **be able to only see the stdout logs or the stderr logs generated by a docker container**.

A concrete use case is when viewing a nginx container logs.
Nginx docker container redirects its access.log to stdout and its error.log to stderr (see https://stackoverflow.com/questions/61564018/in-nginx-docker-how-do-we-see-log-only-from-error-log)

Trying to find the error log lines is really complicated as 99% of the genrated logs are access logs.

**Describe the solution you'd like**

I think a little combobox or some radio buttons allowing to choose between these 3 values would be nice and really useful : 

- 'Show ALL'  --> Applys no filter (default value)
- 'Show STDOUT only' --> Will apply a filter to only show the stdout logs.
- 'Show STDERR only'  --> Will apply a filter to only show the stderr logs.

PS: Thanks a lot for your great project :)

**Comment by omasseau** [comment]
Here is a concrete example of logs generated by nginx.
In red is the stderr logs, in green the stdout logs : 

![image](https://github.com/amir20/dozzle/assets/11772429/9ded94fe-6958-4844-9e69-36021a9e44a8)

**Comment by amir20** [comment]
This has been asked before but I never felt there was a valid use case. I think your use case is actually pretty valid. Docker multiplexes both `err` and `out` streams in the socket. So I'll have to figure out how much work it is to do this. 

I think overall it makes sense to support this feature. Most likely the menu on the top right corner would be the right places to select streams. I'll think about it. 

Let's keep it open for now.

**Comment by amir20** [comment]
I have started this work on https://github.com/amir20/dozzle/pull/2229

Looking promising. It turns out to be a lot of work. So I'll have to do testing before merging.

**Comment by amir20** [comment]
This is implemented now and I am releasing new version. There might be little bugs. I noticed the dropdown isn't sticky so I'll have to come back to that later. 

Let me know what you think....

**Comment by omasseau** [comment]
> This is implemented now and I am releasing new version. There might be little bugs. I noticed the dropdown isn't sticky so I'll have to come back to that later.
> 
> Let me know what you think....

Wow that was fast :)
Thanks a lot, I will test this and give you my feedback.

**Comment by omasseau** [comment]
Sorry for the delay. I was very busy.
Just tested today and so far it is working really well :)
