### ISSUE TITLE
dozzle 4.10.12 no logs visible

### ISSUE THREAD

**Issue by PoepieFloepie** [amir20/dozzle#2243]
**Describe the bug**
After updating to 4.10.12 no more logs visible

**To Reproduce**
update from 4,10.11 to 4.10.12

**Expected behavior**
no logs text visible anymore

synology 220+ latest DSM 7.2-64561

docker

**Comment by amir20** [comment]
There isn't enough details to help here. I have been using `4.10.12` without problems. 

Are there any errors? Perhaps something unique to synology or something else. 

The latest version added support for `syserr` and `sysout` so might be something there. But I would expect an error message.

**Comment by PoepieFloepie** [comment]
level=panic msg="unknown std type [202] with message [2023-06-04T12:24:31.166870573Z Info SqliteUserRepository: Sqlite compiler options: ATOMIC_INTRINSICS=1,COMPILER=gcc-10.3.0,DEFAULT_AUTOVACUUM,DEFAULT_CACHE_SIZE=-2000,DEFAULT_FILE_FORMAT=4,DEFAULT_JOURNAL_SIZE_LIMIT=-1,DEFAULT_MMAP_SIZE=0,DEFAULT_PAGE_SIZE=4096,DEFAULT_PCACHE_INITSZ=20,DEFAULT_RECURSIVE_TRIGGERS,DEFAULT_SECTOR_SIZE=4096,DEFAULT_SYNCHRONOUS=2,DEFAULT_WAL_AUTOCHECKPOINT=1000,DEFAULT_WAL_SYNCHRONOUS=2,DEFAULT_WORKER_THREADS=0,ENABLE_COLUMN_METADATA,ENABLE_DBSTAT_VTAB,ENABLE_FTS3,ENABLE_FTS3_PARENTHESIS,ENABLE_FTS3_TOKENIZER,ENABLE_FTS4,ENABLE_FTS5,ENABLE_GEOPOLY,ENABLE_MATH_FUNCTIONS,ENABLE_PREUPDATE_HOOK,ENABLE_RTREE,ENABLE_SESSION,ENABLE_UNLOCK_NOTIFY,ENABLE_UPDATE_DELETE_LIMIT,LIKE_DOESNT_MATCH_BLOBS,MALLOC_SOFT_LIMIT=1024,MAX_ATTACHED=10,MAX_COLUMN=2000,MAX_COMPOUND_SELECT=500,MAX_DEFAULT_PAGE_SIZE=8192,MAX_EXPR_DEPTH=1000,MAX_FUNCTION_ARG=127,MAX_LENGTH=1000000000,MAX_LIKE_PATTERN_LENGTH=50000,MAX_MMAP_SIZE=0x7fff0000,MAX_PAGE_COUNT=1073741823,MAX_PAGE_SIZE=65536,MAX_SCHEMA_RETRY=25,MAX_SQL_LENGTH=1000000000,MAX_TRIGGER_DEPTH=1000,MAX_VARIABLE_NUMBER=250000,MAX_VDBE_OP=250000000,MAX_WORKER_THREADS=8,MUTEX_PTHREADS,OMIT_LOOKASIDE,SECURE_DELETE,SYSTEM_MALLOC,TEMP_STORE=1,THREADSAFE=1\r\n]"
08-06-2023 06:19:53
panic: (*logrus.Entry) 0xc000178230



level=panic msg="unknown std type [202] with message [2023-03-20T13:53:39.966881604Z [2023-03-20 14:53:39.964 UTC+1] [INFO] Connected to database\r\n]"
08-06-2023 06:20:57
panic: (*logrus.Entry) 0xc000137b90

**Comment by PoepieFloepie** [comment]
only dozzle giving info ,if i click a other docker then i see nothing

and my question is if it is working with you are you on the latest dsm because they change the docker app

**Comment by amir20** [comment]
Thanks. Those errors help. I have an idea what is causing it. 

Last night, I tried on my Synolgy with a few containers. I couldn't reproduce it. 

Just a guess, but I think what is happening is `strerr` or `stdout` is not properly being passed to the API. 

I'll create a PR and have you test it.

**Comment by amir20** [comment]
Try `amir20/dozzle:pr-2247` @PoepieFloepie . It should fix it. I still dunno why Docker is not returning the right stream. But at least for now it should fall back to the previous behavior. 

> and my question is if it is working with you are you on the latest dsm because they change the docker app

I'll try updating my DSK when I get a chance this week.

**Comment by PoepieFloepie** [comment]
oke i tryed the amir20/dozzle:pr-2247 and this one works..
big thanks for fixing it ...waiting for the official next release..

**Comment by amir20** [comment]
Great. I'll merge the PR for now. Waiting for another bug fix to release.

**Comment by amir20** [comment]
Releasing now...
