### ISSUE TITLE
Ctrl+F cannot query Chinese

### ISSUE THREAD

**Issue by hausen1012** [amir20/dozzle#2246]
Ctrl+F cannot query Chinese

**Comment by amir20** [comment]
Yea you are right. It doesn't look like it is working. I'll check to see if it is something that can be fixed.

**Comment by amir20** [comment]
I think I found it. It was because chinese characters were escaped.

**Comment by amir20** [comment]
Try `amir20/dozzle:pr-2248`

**Comment by amir20** [comment]
I tested a few times more. I think it works. So I'll merge and release.

**Comment by hausen1012** [comment]
Thanks
