### ISSUE TITLE
[FEATURE REQUEST] Support regular expression in Find

### ISSUE THREAD

**Issue by anvk** [amir20/dozzle#225]
First of all thanks a lot for this great project!

I was wondering if it is hard to add an option to do regular expression searches? This would be super helpful especially when you are searching for more generic patterns within the logs.

Thanks!

**Comment by jasonw-rr** [comment]
100% agree on such a lightweight and elegant solution.
Enabling regular expression search would make this project astonishing.

**Comment by amir20** [comment]
Regular expression support is already implemented! You can do things like test-\d+.  

I should probably change the placeholder text to make this more obvious.

**Comment by amir20** [comment]
I just tried it again it works. So let me know if it doesn't work for you. Here is a screenshot.  
<img width="1792" alt="Screen Shot 2020-01-07 at 8 11 44 AM" src="https://user-images.githubusercontent.com/260667/71909697-6538e580-3125-11ea-8760-b6d26d092c4f.png">

**Comment by jasonw-rr** [comment]
You are right, it does work.
Sorry for the false request.
I probably made a mistake with my regex when I tested it out.

Thanks again for the wonderful project 👍🏻

**Comment by anvk** [comment]
Oh this is great! Thanks again for such a prompt reply. Probably worth mentioning this amazing feature somewhere in the README as well. I'm going to close this. Thanks again.

**Comment by amir20** [comment]
Sounds good. The fact that so many people upvoted is impressive. I have changed the placeholder in `v1.20.10`.
