### ISSUE TITLE
Can't search for HTML-escaped characters: < > " ' &

### ISSUE THREAD

**Issue by mmorearty** [amir20/dozzle#2250]
**Describe the bug**
A search for any string containing any of these characters does not work: `< > " ' &`

I think the problem is that it is searching the **html-escaped** contents of the log. For example, a search for these strings will find those characters:

* `<`: `&lt;`
* `>`: `&gt;`
* `"`: `&quot;`
* `'`: `&apos;`
* `&`: `&amp;`

**To Reproduce**

1. Log any string containing `<` or `>`. For example, `<button>`
2. View it in Dozzle, and try to search for `<` or `<button` or `<button>` or `>`

**Expected behavior**
It will find the line with `<button>`

**Desktop (please complete the following information):**

- OS: macOS
- Docker version: 24.0.2
- Browser & version: Chrome and Safari
- Version: v4.10.6

**Comment by amir20** [comment]
Can you try the latest version? This might be fixed as part of another bug.

**Comment by mmorearty** [comment]
Yes, it looks like this is fixed as of v4.10.13. Thanks!
