### ISSUE TITLE
Extend 'container search' to all remote hosts

### ISSUE THREAD

**Issue by vvarga007** [amir20/dozzle#2258]
Hi,

I noticed that when I add multiple remote hosts, the 'container search' bar only searches for containers on the actively selected remote hosts.
Would be great to have a search feature that finds the containers on any remote host.
I am planning to add many remote hosts(16 at least for now, but I can see adding 50+), and currently, there is no easy way to find the container that I am looking for.

Thanks,

**Comment by amir20** [comment]
This would be a good improvement. However, very complicated to build. There was a lot of discussion prior to implementing remote hosts.  Right now, the UI chooses which host to use and all requests are routed to that remote host. Another way would be to listen to all hosts for all events and send all that information to the browser. That is so hard. Each host streams all events and monitoring events. In your case, with 16 hosts that would slow down the browser. 

Perhaps a better way is to remove all the events and just do the container names for ease of searching. But my data show majority of people have one or two remote hosts. So I don't think it's worth effort.

**Comment by BillySchwartz16** [comment]
+1 

A common use case (for me, at least) is the ability to view two or more containers, on different hosts, side by side.  This functionality is already available for viewing multiple containers running on a the same host.  Extending this to allow containers running on a remote hosts to be viewed side by side would be great. This would help monitor the logs of each node in a clustered application, simultaneously.

Could the (filtered) container names on each remote host be retreived/cached periodically and added to the list of searchable containers?

This could allow a streamlogs to be called on a remote host/container without needing the eventstream to list them, first.

I don't think this would sacrifice the events stream for the chosen host.  It would add quicker search functionality for remote hosts / containers and the ability to split view containers running on different hosts.

Let me know your thoughts.

**Comment by amir20** [comment]
Yes, for sure this feature request is fair and probably very helpful. Your use case of split screen multiple containers across hosts is an interesting one I didn't think about. It is not possible right now but I have been thinking about how to support that. 

> Could the (filtered) container names on each remote host be retreived/cached periodically and added to the list of searchable containers?

The issue of this would be stale data. Personally, I spin up new containers all the time and jump to Dozzle to see if anything broke. If it is cached, then it might take some time for that container to show up. Which wouldn't be so "real-time" anymore. 😆

Anyway, what I am thinking requires a re-design of some of the core APIs so it will take some thinking...

**Comment by amir20** [comment]
Working on this https://github.com/amir20/dozzle/pull/2269

Looks promising so far...

**Comment by amir20** [comment]
Alright folks, I think `amir20/dozzle:pr-2269` is ready for testing. I stream all events from all hosts to the client. There were some major refactors for this to work. 

I have tested searching and showing multiple containers across different hosts. 

I think some improvements can be done to improve labels for each container. 

Please give it a try.

**Comment by vvarga007** [comment]
I gave it a try. I think it looks good at first glance.

- [x] Extended search on all remote hosts works
- [x] Streaming logs from different remote hosts in a split window works

Thanks!

**Comment by BillySchwartz16** [comment]
Wow this looks great.  Thanks!!

**Comment by amir20** [comment]
Yea I am pretty happy with it. @vvarga007 I don't know how well it will work with 16 hosts. But I guess we can optimize when someone tries it out. 

I am going to merge after a few more tests and release.

**Comment by amir20** [comment]
This has been released. There might be bugs since I couldn't test with a lot of hosts. Hoping one of you who has a more complicated setup can test.

**Comment by vvarga007** [comment]
@amir20 
Hi,

I am sorry for the late answer. I was super busy in the past few days.
I am testing it with 16 hosts right now. It looks good and responsive at first glance.
The only odd thing that I found is how the search field works. I'm searching for "mesh-gateway" why does it show other containers like "ingress-gateway" too?
Probably too much to ask, but could we sort the remote hosts alphabetically?
![Screenshot 2023-06-27 at 4 24 51 PM](https://github.com/amir20/dozzle/assets/59172780/0a8edd7e-18a2-404e-99cb-a2feb4c56b35)

**Comment by amir20** [comment]
> The only odd thing that I found is how the search field works. I'm searching for "mesh-gateway" why does it show other containers like "ingress-gateway" too?

I use [fusejs](https://fusejs.io/) which uses a searching algorithm to match against best results. It's pretty smart so searching for `fbar` would also find `foo bar`. I wonder if there is a way to limit really bad matches. 

> Probably too much to ask, but could we sort the remote hosts alphabetically?

I think eventually I will do that. Could you create a different issue now that this is closed.
