### ISSUE TITLE
container stream often stuck in 'pending'

### ISSUE THREAD

**Issue by vincentjanv** [amir20/dozzle#2267]
**Describe the bug**
We use Dozzle in a lot of environments. In a single environment, Dozzle is acting strangely, even though we have already completely reinstalled Docker etc. We can (most of the time) see the running containers, but often when we click on a container, we don't see any logs. Network inspector shows us the eventsource to /stream is stuck in a pending state (see screenshot below, showing succesfull and stuck requests). Quickly navigating to another container sometimes works, but more often it doesn't. This problem occurs on all the containers running on this host. The problem occurs intermittent, which is really strange.

We use  Dozzle 4.10.1 and Nginx as a proxy
We deploy the environment using Docker compose, with the follow config (which uses the correct network):

```
logs:
    container_name: logs_dozzle
    restart: always
    image: amir20/dozzle:latest
    command:
      - "--base=/logs"
      - "--no-analytics=true"
    networks:
      - spp_internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
The relevant NGINX conf
````
 location ~* ^/logs(/.*)?$ {
            proxy_pass http://logs:8080;
            chunked_transfer_encoding off;

            # We don't want any delays for realtime logging
            # Skip some TCP ACK/SYN buffering for achieving full package sizes
            # on transport level
            tcp_nodelay on;

            # Caching and buffering
            proxy_cache             off;
            proxy_redirect          off;
            proxy_buffering         off;
            proxy_request_buffering off;

            #Timeout if the real server is dead
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

            # Set timeouts higher for websockets / SSE
            send_timeout            1d;
            proxy_read_timeout      1d;
            proxy_send_timeout      10s;
            keepalive_requests      100;
            keepalive_timeout       1d;


            # Basic Proxy Config
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Ssl on;
            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header Proxy "";

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_cache_bypass true;
            proxy_no_cache true;

            proxy_headers_hash_bucket_size 128;
            proxy_headers_hash_max_size 1024;
        }
````
<img width="500" alt="Scherm­afbeelding 2023-06-21 om 12 08 13" src="https://github.com/amir20/dozzle/assets/3436975/434805a6-2243-4239-80c2-a8944a79b702">

**Comment by amir20** [comment]
Ah one other thing. Is Nginx using Http1 or 2? Http1 has a limited of number eventsource that can run in parallel? If you are opening multiple tabs of Dozzle, then you might see pending.

**Comment by amir20** [comment]
Any update on this?

**Comment by vincentjanv** [comment]
Hi Amir,

it is http1.1 but we only test with 1 tab open. Again, 5+ other projects are working perfectly, so we are trying to pinpoint the differences. 
We don't see anything with the debug, and given the request is stuck in pending, nothing is shown when clicking the connection. The times it does work, of course we see the expected results. 

We will investigate it further internally and try to replicate it in a minimal setup.

**Comment by vincentjanv** [comment]
Follow-up: 

after installing the latest version AND applying authentication (via user/pass/key), we're no longer facing any issues. I'm baffled on how this could make a difference (the auth part) but I'm just happy it works as expected now.

Thanks for thinking along.

**Comment by amir20** [comment]
Good to hear. I haven't changed much that could make a difference. With each release I do update the dependencies so perhaps there was a down stream fix.
