### ISSUE TITLE
Dozzle itself shows info logs as STDERR

### ISSUE THREAD

**Issue by gleruzh** [amir20/dozzle#2268]
**Describe the bug**
Seems wrong behaviour: info logs from Dozzle in STDERR

**To Reproduce**
Dozzle behind reverse proxy (I did try only lsio swag image)

**Expected behavior**
such logs in STDOUT

**Screenshots**
![image](https://github.com/amir20/dozzle/assets/5059760/2730ae43-b613-4d84-ae86-6c561467985b)

**Desktop (please complete the following information):**

- OS: Raspi OS (Debian 11)
- Docker version:
```
$ docker version 
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:50:59 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Browser & version Firefox 114.0.1 (Google Chrome 114.0.5735.133 same problem)
- Version v4.10.14

**Comment by amir20** [comment]
Dozzle uses https://github.com/sirupsen/logrus which by default logs to `stderr`. Why do you think this is a bug?

**Comment by gleruzh** [comment]
I expect errors and warnings (and debug messages) in STDERROR, and info messages in STDOUT
So you mean it's not a bug, ok.

**Comment by amir20** [comment]
No, it should all go to `stderr` or `stdout` but _not_ both. But I think it really depends. If my program was a command line tool that can pipe like `foobar | grep ...` then I think it would make sense to split the two. 

For now, it is not a bug. :)
