### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by dnslin** [amir20/dozzle#2280]
debian 11 
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -p 11113:8080 amir20/dozzle --username "key" --password "passwd"
```
level=info msg="Dozzle version v3.10.1"
level=fatal msg="Key is required for authentication"

**Comment by amir20** [comment]
That's a really old version. Pull the latest one.

**Comment by dnslin** [comment]
> That's a really old version. Pull the latest one.

Thank you. I found the problem. My dockerhub mirror synced an old version of dozzle

**Comment by amir20** [comment]
Great. This is a common question so I wonder what I can do to help people get the latest version.
