### ISSUE TITLE
Could not connect to remote host tcp://xxx:2375: error during connect: Get \"http://xxx:2375/v1.24/containers/json?all=1\": EOF

### ISSUE THREAD

**Issue by ilxqx** [amir20/dozzle#2283]
**Describe the bug**
The dozzle container could not connect to the specified remote docker engine host when the `--remote-host` parameter was specified.
The dozzle container logs:
```log
level=info msg="Dozzle version v4.10.17"
level=info msg="Creating client for tcp://192.168.10.207:2375"
level=warning msg="Could not connect to remote host tcp://192.168.10.207:2375: error during connect: Get \"http://192.168.10.207:2375/v1.24/containers/json?all=1\": EOF"
level=info msg="Connected to 1 Docker Engine(s)"
level=info msg="Accepting connections on :8018"
```
But when i try curl http://192.168.10.207:2375/v1.24/containers/json?all=1 on my local ternimal, it is fine.
It's also fine when i execute `docker -H tcp://192.168.10.207:2375 ps` on my local ternimal.
So I suspect it's not my network issue.
This may also be my own problem, but I don't know how to solve it anymore. Can you help me?

**To Reproduce**
run conatiner command:
```shell
docker run -d --restart=unless-stopped --name dozzle --network=host -v /var/run/docker.sock:/var/run/docker.sock amir20/dozzle:latest --username=admin --password=admin --addr=":8018" --remote-host tcp://192.168.10.207:2375
```

**Expected behavior**
Could connect to the remote `tcp://192.168.10.207:2375`

**Desktop (please complete the following information):**

- OS: [Mac Os]
- Docker version
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           orbstack
- Dozzle version v4.10.17

**If applicable include logs with `--level debug` and browser logs**
```log
level=info msg="Dozzle version v4.10.17"
level=debug msg="filterArgs = {map[]}"
level=debug msg="Connected to local Docker Engine"
level=info msg="Creating client for tcp://192.168.10.207:2375"
level=debug msg="filterArgs = {map[]}"
level=debug msg="/certs/ca.pem does not exist, using plain HTTP"
level=warning msg="Could not connect to remote host tcp://192.168.10.207:2375: error during connect: Get \"http://192.168.10.207:2375/v1.24/containers/json?all=1\": EOF"
level=info msg="Connected to 1 Docker Engine(s)"
level=info msg="Accepting connections on :8018"
level=debug msg="streaming logs for container" id=1937eefb40e3 since=1688006562335 stdType=all
level=debug msg="streaming logs from Docker with option: {ShowStdout:true ShowStderr:true Since:1970-01-20T12:53:26.563335Z Until: Timestamps:true Follow:true Tail:300 Details:false}"
level=debug msg="starting to stream stats for: 44f04ff30e64"
level=debug msg="starting to stream stats for: 1937eefb40e3"
level=debug msg="starting to stream stats for: 4a036fbb5f16"
level=debug msg="starting to stream stats for: 62eaac566a3b"
level=debug msg="starting to stream stats for: 53f3a5c63784"
level=debug msg="starting to stream stats for: b40d57e5d6d6"
```

**Comment by amir20** [comment]
Hi can you try version `v4.10.18`? There is a lot that has changed so I want to make sure we are testing the latest. 

I wonder if internally Dozzle container has a network problem. 

I can try to add a bit of logging to figure out what the issue might be.  I use docker proxy for my regular testing. You can see the configuration at https://github.com/amir20/dozzle/blob/901785dc207559fe40aa5f1fd1c7572d9c3ed4e4/docker-compose.yml#L53-L60. So I am hoping it's something simple. 

For now, please latest everything to latest.

**Comment by ilxqx** [comment]
@amir20 Hi, i have upgraded version from `v4.10.17` to `v4.10.18`, But problems remain.
And in order to rule out the problem of my docker server machine, I changed another cloud server (opened docker communication port 2375) to test, and the result was the same, dozzle could not connect to it
Here is my opeartion log:
```shell
docker -H tcp://42.193.17.186:2375 ps
CONTAINER ID   IMAGE              COMMAND                   CREATED       STATUS         PORTS                                       NAMES
f765f8d7b9d9   halohub/halo:2.7   "sh -c 'java ${JVM_O…"   4 hours ago   Up 3 minutes   0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   halo2
➜  ~ docker -H tcp://42.193.17.186:2375 version
Client:
 Version:           24.0.2
 API version:       1.41 (downgraded from 1.43)
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:43:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker run -d --restart=unless-stopped --name dozzle --network=host -v /var/run/docker.sock:/var/run/docker.sock amir20/dozzle:latest --username=admin --password=admin@123 --addr=":8018" --remote-host tcp://42.193.17.186:2375 --level debug
21abfb0b447d5c579221b09b030522647c72b9c70abe03178e9f0cb907bcda24
➜  ~ docker logs -f dozzle
level=info msg="Dozzle version v4.10.18"
level=debug msg="filterArgs = {map[]}"
level=debug msg="Connected to local Docker Engine"
level=debug msg="Creating remote client for 42.193.17.186 with {Name:42.193.17.186 ID:tcp:42.193.17.186:2375 URL:tcp://42.193.17.186:2375 CertPath:/certs/cert.pem CACertPath: KeyPath:/certs/key.pem ValidCerts:false}"
level=info msg="Creating client for 42.193.17.186 with tcp://42.193.17.186:2375"
level=debug msg="filterArgs = {map[]}"
level=debug msg="No valid certs found, using plain TCP"
level=warning msg="Could not connect to remote host tcp:42.193.17.186:2375: error during connect: Get \"http://42.193.17.186:2375/v1.24/containers/json?all=1\": EOF"
level=info msg="Connected to 1 Docker Engine(s)"
level=info msg="Accepting connections on :8018"
level=debug msg="streaming logs for container" id=53f3a5c63784 since=1688006566661 stdType=all
level=debug msg="streaming logs from Docker with option: {ShowStdout:true ShowStderr:true Since:1970-01-20T12:53:26.567661Z Until: Timestamps:true Follow:true Tail:300 Details:false}"
level=debug msg="starting to stream stats for: 21abfb0b447d"
level=debug msg="starting to stream stats for: 1937eefb40e3"
level=debug msg="starting to stream stats for: 4a036fbb5f16"
level=debug msg="starting to stream stats for: 62eaac566a3b"
level=debug msg="starting to stream stats for: 53f3a5c63784"
level=debug msg="starting to stream stats for: b40d57e5d6d6"
level=debug msg="Post \"https://www.google-analytics.com/mp/collect?api_secret=7FFhe65HQK-bXvujpQMquQ&measurement_id=G-S6NT05VXK9\": net/http: TLS handshake timeout"
```
I will leave this server `42.193.17.186:2375` open for now, you can use it for testing

**Comment by amir20** [comment]
Thanks! This helps a lot to test. Let me give it a try right now.

**Comment by amir20** [comment]
It looks like it is using `https` when it should be `http`. Weird. Let me debug a little more.

**Comment by ilxqx** [comment]
> It looks like it is using `https` when it should be `http`. Weird. Let me debug a little more.

Thanks, This is probably possible, because the logs show that it couldn't find the certificate in the first place

**Comment by amir20** [comment]
Yep, you are right. I think it is because certs are there but not valid. Let me keep digging.

**Comment by ilxqx** [comment]
I didn't map(using `-v` param) the certs directory for the container, and it shouldn't be able to find it. Is there a default certs inside the container?

**Comment by amir20** [comment]
No, I am testing locally and it just uses `./certs` which I have set for testing. I can focus on this again. So let's see what I find.

**Comment by amir20** [comment]
Hmm so that's weird.... Everything works for me when connecting http. 

<img width="1970" alt="Screenshot 2023-07-06 at 11 34 53 AM" src="https://github.com/amir20/dozzle/assets/260667/b554194c-a3e3-4243-bcdd-b0fb97c442bd">

**Comment by ilxqx** [comment]
So what's my problem?

**Comment by ilxqx** [comment]
I didn't specify any parameters to use https, shouldn't it connect to the remote server using http by default?

**Comment by amir20** [comment]
HTTPS was my problem. I had certs that were invalid locally. From your logs, it is using `http` correctly. 

I do not know what your problem could be.  Looking at this https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi suggests that the connection is being reset. 

Can you check your proxy logs on remote host to see if there any errors there?

**Comment by ilxqx** [comment]
@amir20 Thank you, I found the problem, I am using MacBookPro, using the container software is Orbstack, when I switch to DockerDesktop and run the above command works fine
Maybe this is a bug of Orbstack
