### ISSUE TITLE
Allow Dozzle to pick up container logs automatically by defined container label

### ISSUE THREAD

**Issue by vvmruder** [amir20/dozzle#2305]
**Is your feature request related to a problem? Please describe.**
Filtering by available options make Dozzle need to be restarted every time a change on the filter is set up.

**Describe the solution you'd like**
A nice solution would be a label based approach of configuration, so that Dozzle can pick up containers automatically when they match a defined label. This makes it more easy to spin off/on some containers for debugging but keep a Dozzle instance there. It would also match behavior of other docker based services like e.g. Traefik.io 

I think of something like Dozzle introduces a docker container label match like `dozzle.enable=true` and `dozzle.enable=false` where the last one would be default. On every selected service in a docker composition or a swarm or a basic docker run I can then set the label `dozzle.enable=true` which makes the service picked up by Dozzle.

**Describe alternatives you've considered**

...

**Additional context**

...

**Comment by amir20** [comment]
I think this is already possible.  Have you tried `--filter "label=dozzle"`? The labeling system matches Docker's labeling which can be found at https://docs.docker.com/engine/reference/commandline/ps/#filter so you could set it to anything you want.

**Comment by amir20** [comment]
Haven't heard back. Closing since there is nothing to do.

**Comment by vvmruder** [comment]
Sorry for that late response. But I can confirm it works like described :)
