### ISSUE TITLE
Dozzle doesn't show log in case of log driver explicitly specified

### ISSUE THREAD

**Issue by RainM** [amir20/dozzle#2309]
**Describe the bug**
Dozzle doesn't show log in case of log driver explicitly specified

**To Reproduce**
1. Run dozzle container
2. Run any other container with explicitly specified log driver like 
`docker run --log-driver syslog --log-opt syslog-address=tcp://127.0.0.1:5140 --log-opt syslog-format=rfc5424 ....`
3. Open dozzle -> no logs from container from (2)

**Expected behavior**
Logs present in dozzle

Looks like it's just isn't implemented yet. Some functionality to add additional log driver if non-default log driver is specified.

**Comment by amir20** [comment]
I haven't tested this but according to [documentation](https://docs.docker.com/config/containers/logging/dual-logging/) from Docker, you should be able to do dual logging with log-drivers. You do need docker `Docker Engine 20.10` or later. 

Can you try that seeing if it works? 

Dozzle uses the same api as `docker logs ...` so if they show up using the CLI but not Dozzle, it is possibly a bug.

**Comment by RainM** [comment]
I expected root cause is absence of some logging driver. I'll try to add default log driver.
BTW, I think dozzle could check if default log driver is present and warn if not. Or just add default log driver under the hood.

**Comment by amir20** [comment]
No, Dozzle can't change any log drivers. That would be a security restriction. :) 

IMO, it's up to the engineer to make sure it is.

**Comment by RainM** [comment]
I see quite strange behavior of dozzle. I see no logs but can download them. But non-default log driver isn't enabled for this container. Which logs should I provide for detailed investigation?
<img width="1714" alt="dozzle_issue" src="https://github.com/amir20/dozzle/assets/3684891/888208da-012f-445b-998f-2d66e9bed43d">

**Comment by amir20** [comment]
Interesting. Maybe help me reproduce it first. What are the exact configurations? 

Is Dozzle itself showing any errors?

Finally does "docker logs" command work?

**Comment by RainM** [comment]
It's linux AWS VM.
1. Ubuntu 22.04.2.
2. $ docker --version
Docker version 24.0.4, build 3713ee1
3. Dozzle's log has nothing except "level=info msg="Accepting connections on :8080""
4. docker logs works

As far as I see dozzle calls '/api/logs/stream?id=' from backend. And for some containers this call works perfectly. For some I see:

<img width="849" alt="dozzle2" src="https://github.com/amir20/dozzle/assets/3684891/efdffd61-e8cd-4e8e-884b-51348500c721">

$ docker logs c1cb656827d7 | wc -l
21109 <<< Logs present

**Comment by RainM** [comment]
BTW, network logging isn't enabled for this container:

```
$ docker inspect c1cb656827d7
        "HostConfig": {
...
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
```

**Comment by amir20** [comment]
Alright, I am bringing up Ubuntu on DigitalOcean right now. Will let you know what I find. Hopefully it is something on my side I can fix.

**Comment by amir20** [comment]
Oh so you are using the default log driver? And that's still not working?

**Comment by RainM** [comment]
Initial issue was reproduced with syslog. But not I can reproduce this is any container on host uses syslog. In example above container uses default log driver. But some containers uses syslog on this host.

**Comment by amir20** [comment]
So do you have syslog enabled in Docker `/etc/docker/daemon.json`

```
{
  "log-driver": "syslog"
}
```

Or is your setup just default install with some containers using `--log-driver syslog`?

**Comment by RainM** [comment]
Just pass log driver arguments during container run

**Comment by RainM** [comment]
So, in understanding is this issue somehow related if some containers on host uses syslog driver.

**Comment by amir20** [comment]
So I setup `syslog` in `daemon.json` and it seems to work. Hmmm...

<img width="1911" alt="Screenshot 2023-07-14 at 3 20 02 PM" src="https://github.com/amir20/dozzle/assets/260667/b05d7545-aea2-4bff-8893-c82221ec7255">

I am running out of time for the day, I'll have to try again using AWS perhaps. 

Could you help me and create a brand new Ubuntu instance without any containers to see when it stops working? I am wondering if this bug is not related to syslog at all.

**Comment by RainM** [comment]
I think there is no difference if you use aws or digital ocean. Ok, I'll try to make clean environment and reproduce this bug (and write reproducer). Thank for your fast response. 
P.S. We use dozzle and really enjoyed this! Thanks.

**Comment by RainM** [comment]
may be it's related to ansible deploy somehow.... Let me try to reproduce in clean environment.

**Comment by amir20** [comment]
Any updates?

**Comment by amir20** [comment]
Ok closing. No response.
