### ISSUE TITLE
Expand json: characters are not decoded within an array

### ISSUE THREAD

**Issue by B-Katheryne** [amir20/dozzle#2325]
**Describe the bug**
when I use the "expand json" option, when a key points to an array, characters within it are not decoded (in my case those are Cyrillic symbols)

**To Reproduce**
1. sent a post request via fastapi (the request body contains Cyrillic characters (both within an array and within a dictionary))
2. log it with structlog ("message" passed into the logger as a dict instance)
3. check the logs in dozzle (looking great!)
4. click expand json. 
**Expected behavior**
I expected the Cyrillic characters to be displayed in a readable way

**Screenshots**
￼￼Making a post request with a request body that contains Cyrillic characters (both within an array and within a dictionary):
![image](https://github.com/amir20/dozzle/assets/108027587/f8c3bbdc-84b5-402f-8a6e-05b76f2b15e3)

Whenever a message is sent, I log it with structlog
![image](https://github.com/amir20/dozzle/assets/108027587/ecbb81f6-738a-47d9-845a-a2f37483cd81)

Here's how logs look in Docker (I run the application in a container):
![image](https://github.com/amir20/dozzle/assets/108027587/d57d8c49-e81b-4dbb-94a0-4e6b657d80df)

Here how they look like in Dozzle:
![image](https://github.com/amir20/dozzle/assets/108027587/d9474659-f87f-426b-8bc3-4f9c53360044)

As you can see, everything fine in the log message itself, but when I click "expand json", the dictionary's key that points to the array that has cyrilic symbols within it has them displayed encoded. 

**Desktop:**
- OS:  Linux, Windows, Mac Os
- Docker version:
![image](https://github.com/amir20/dozzle/assets/108027587/d86cec3e-9cfe-4613-81da-730945d95301)

- Browser & version: chrome, safari, microsoft edge
- Version: 4.10.19

**Comment by amir20** [comment]
Can you copy and paste the json? That way I can test it locally. I think I know what the problem could be.

**Comment by B-Katheryne** [comment]
{
  "message": {
    "not_an_array":  {"name": "Иван", "lastname": "Иванов"}, 
    "array": [
      {"name": "Иван", "lastname": "Иванов"}, 
      {"name": "Иван", "lastname": "Иванов"}
    ] 
  },
  "queue_name": "sendProcess",
  "exchange_name": "messagesExchange"
}

**Comment by amir20** [comment]
Great, I was able to reproduce it. Let me see if I can figure out what is happening.

**Comment by amir20** [comment]
Thanks for the details. I have found the bug. Should be fixed in #2327. Will test a little and release next few days.

**Comment by amir20** [comment]
Merged into master. For now, you can try `amir20/dozzle:master` to see if it is fixed. Can you give it a try? Thanks.

**Comment by B-Katheryne** [comment]
I did give it a try. Look at these beautiful logs! Thank you for your work!  
![image](https://github.com/amir20/dozzle/assets/108027587/9130da7f-573d-49d5-86e7-75244e0b1324)

**Comment by amir20** [comment]
This is now released.
