### ISSUE TITLE
precentage reporting seem broken

### ISSUE THREAD

**Issue by Mentat836** [amir20/dozzle#2336]
![image](https://github.com/amir20/dozzle/assets/141462309/8b9e9fcc-ff38-4ad7-bc0b-5ad3ab5669e5)

**Desktop (please complete the following information):**

- OS: ubuntu server
- Docker version:  24.0.4
- Browser & version latest-firefox
- Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`]

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
What's broken?

**Comment by Mentat836** [comment]
i'm guessing misunderstanding the information provided, but usually percents top at 100%, and "total" CPU usage is higher than per-process usage

**Comment by amir20** [comment]
It's possible to go above 100% if you have multiple CPUs. A process using more than 100% means it is using more than one CPU.

**Comment by amir20** [comment]
No response.

**Comment by Mentat836** [comment]
> 

Thanks for the clarification, might be obvious to someone more familiar
