### ISSUE TITLE
Hope to add container update reminder

### ISSUE THREAD

**Issue by kokojacket** [amir20/dozzle#2372]
It is hoped that monitoring of whether the container has a new image on the hub can be added to facilitate manual selection of whether to update the container.

**Comment by amir20** [comment]
Hi @kokojacket. Thank you for the suggestion. This was mentioned a few times. Something I have thought about but haven't had time to do it. Perhaps I'll come back to it if I can think of an easy way to do it.

**Comment by amir20** [comment]
I looked into this a little more. It's not easy to support all repositories. I don't want to deal with authentication and private repos. 

I'll close this.
