### ISSUE TITLE
Dozzle via nginx proxy_pass problem

### ISSUE THREAD

**Issue by filatov0120** [amir20/dozzle#2374]
Hello! I very excited your app. But i have a problem.
I run dozzle. Added env DOZZLE_BASE=/docker_logs
Proxyed by NGINX below my location block
```
location /docker_logs {
    proxy_pass http://127.0.0.1:8080/docker_logs/;

    proxy_buffering             off;
    proxy_cache                 off;
}
```
But when i try to open app in browser i had 
```
Refused to apply style from 'https://my-site.com/docker_logs/assets/main-aeb02c57.css' because its 
MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
MIME type included in my general nginx.conf. And when i opened app by `ip_address:8080/docker_logs` it's work well. 
Can you help me with solution?

**Comment by amir20** [comment]
I am not too familiar with nginx so I don't think I can help you. Especially since Dozzle seems to be working. I personally use traefik which is a little bit easier than nginx. 

However, I can guess that your proxy is not set up correctly. If you go to `https://my-site.com/docker_logs/assets/main-aeb02c57.css` you see an html page instead of CSS. That's the root that needs to be fixed.  Some configuration seems to be missing with nginx which doesn't seem to work.

**Comment by filatov0120** [comment]
Sorry, maybe someone test dozzle with nginx? 
I created test server install nginx, setup dozzle base_url / 
But i have a same issue. I try to change MIME types, but it's not resolve my problem(((

**Comment by amir20** [comment]
Try googling dozzle and nginx. There is a lot of examples like https://github.com/linuxserver/reverse-proxy-confs/blob/master/dozzle.subfolder.conf.sample

**Comment by filatov0120** [comment]
I tried it, not help.
Now i have a new info sorry previous was not clear.
When i config dozzle as `/` it's works well with nginx. 
And files like https://docker-logs.blaize.technology/assets/main-299e3767.js opened as text on direct link.
```
location /docker_logs {
    proxy_pass http://127.0.0.1:8080/docker_logs/;

    proxy_buffering             off;
    proxy_cache                 off;
}
```
When i change config on `/test`
```
    location /test {
        proxy_pass            http://127.0.0.1:8080/test/;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;

        proxy_buffering             off;
        proxy_cache                 off;
    }
```
I still can open `https://docker-logs.blaize.technology/assets/main-299e3767.js` on this link
but i can't open it on `https://docker-logs.blaize.technology/test/assets/main-299e3767.js`
It's seems like routing issues, but where?

**Comment by amir20** [comment]
I believe you want 

      proxy_pass            http://127.0.0.1:8080/;

even with `location /test`. Nginx will append /test. If you search for `proxy_pass` in the issues, you can see other examples.

**Comment by filatov0120** [comment]
yes sorry it was my mistake with NGINX conf. That's working
```
    # reverse proxy
    location /test {
        proxy_pass            http://127.0.0.1:8080;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;
    }
```
and 
```
    environment:
      - DOZZLE_BASE=/test
```
