### ISSUE TITLE
pass multiple filters via docker-compose env

### ISSUE THREAD

**Issue by suzjack** [amir20/dozzle#2380]
**Is your feature request related to a problem? Please describe.**

Docker only allows to set a variable once, setting it multiple times will only set the single value to the last one set in the yml file. 

**Describe the solution you'd like**
Maybe another variable  like DOZZLE_FILTERS with ; seperated value

Example:

DOCKER_FILTERS="name=review;name=debug;name=elastic;name=kibana"

**Describe alternatives you've considered**
Remove the filter for now

**Additional context**

Your project is great thanks!

**Comment by amir20** [comment]
Thank you :)

This should already work with commas. I just tested `DOCKER_FILTERS="name=review;name=debug;name=elastic;name=kibana"` 

and I see 

      DEBUG filterArgs = {map[name:map[debug:true elastic:true kibana:true review:true]]}

Can you confirm?

**Comment by suzjack** [comment]
Added commas, 
I see the same debug message as you do but no containers show up. What logic is applied to the filters ? AND, OR ? (I'm not great at reading go) I was expecting OR (applied multiple independent filters)

thanks!

**Comment by amir20** [comment]
It is `AND`.  I pass the filters directly to Docker. So it's whatever the help files would be for Docker CLI.

**Comment by suzjack** [comment]
Thanks for the feedback, could that be a feature request then ? 
A list of filters to apply independently ?

Thanks again!

**Comment by amir20** [comment]
Just use labels. :) Again, I send this directly to Docker so it would be more of an ask for Docker. :) 

For now, I suggest you use labels.
