### ISSUE TITLE
Is it possible to send emails on a pattern?

### ISSUE THREAD

**Issue by frederikhors** [amir20/dozzle#2384]
I do not understand if it's possible to send emails with dozzle when such a pattern is matched on logs.

Example: if an `ERROR` log is printed it should send me an email.

Is this possible?

**Comment by amir20** [comment]
Sorry for the late response. No, this is not possible right now. Dozzle doesn't process any logs in the background so alerts would not be possible.  A few people had asked for this but a lot would need to change before this is possible.
