### ISSUE TITLE
Containers are not showing

### ISSUE THREAD

**Issue by Kieta** [amir20/dozzle#2393]
**Describe the bug**
I don't see my containers or stats on dozzle

my docker compose file:

version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      DOZZLE_LEVEL: trace
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

![image](https://github.com/amir20/dozzle/assets/3050203/e5e0bfd4-6c94-45c6-a551-f246587ac7e4)

**Comment by amir20** [comment]
Which browser? And are there any errors in your browser console? 

Any more info would help.

**Comment by Kieta** [comment]
Firefox and edge
No errors in console or dozzle logs

**Comment by amir20** [comment]
I tested with those browsers. They all work. Not too sure how to help with limited data. Something must be unique to your environment. I get millions of downloads per month so perhaps someone else also has this problem. I'll keep this open for a little. 

Meanwhile, try:

1. Installing on other hosts to see if they work 
2. See if `docker ps` works as expected 
3. Update browsers and docker to latest 
4. Try going to `{dozzlehost}/api/events/stream`. If that doesn't return any data then that's what the UI is not working. 

I am all out of ideas after that....

**Comment by Kieta** [comment]
It turned out a network issue, works fine, thank you for the great work.
