### ISSUE TITLE
How can I change the 'localhost' in the host list?

### ISSUE THREAD

**Issue by dp-sonn** [amir20/dozzle#2394]
How can I change the "localhost" instance in the host list to a hostname? I've added some remote hosts, for better overview I'd like to change it to the hostname.

Is that possible?

**Comment by amir20** [comment]
`Localhost` is a special kind of connection and changing the name is not possible right now. I think in the future I'll make the `--hostname` flag to overwrite the localhost name.

**Comment by amir20** [comment]
This is implemented in https://github.com/amir20/dozzle/pull/2412.

**Comment by amir20** [comment]
Tested and works. Releasing a patch.

**Comment by amir20** [comment]
Documentation updated https://dozzle.dev/guide/healthcheck
