### ISSUE TITLE
logs are hold back for minutes, then suddenly appear

### ISSUE THREAD

**Issue by eiksch** [amir20/dozzle#2411]
**Describe the bug**
So sometimes, I have a few containers which are holding back logs for f.e. 5 minutes.. then suddenly, all the logs appear. It is a NodeJS application which is not blocked or frozen in any kind. I can still access the server and interact, but the logs are frozen/hold back. Then suddenly at some point, they appear. Unfortunately, I don't know if its related to dozzle or the docker engine.

**To Reproduce**
I cannot reproduce.

**Expected behavior**
That logs run smoothly.

**Screenshots**
In my case, it seem to be 7 minutes every time. Left timestamp is from dozzle, right timestamp is from the application.
![image](https://github.com/amir20/dozzle/assets/3394406/813613e2-5936-4613-ad97-d171e87e83c9)

**Desktop (please complete the following information):**

- OS: Linux Docker CE
- Docker version newest
- Browser & version chrome newest
- Version 5.0.4

**Comment by amir20** [comment]
Hmm I have seen sometimes 2 or 3 seconds if there is a lot of logs. But never minutes. 

Maybe if you can create a test container and push it to Docker hub. Then I can test it to see if it also happens for me. 

I don't know of any other way to help.

**Comment by amir20** [comment]
This might have been fixed in master. Try `amir20/dozzle:master`.

**Comment by eiksch** [comment]
Will test, thanks in advance for your work

**Comment by amir20** [comment]
I was ignoring an exception before and it should be fixed now. So I am going to close this. Let me know if you can reproduce and enable debug logs if it happens again.
