### ISSUE TITLE
Loading logs can sometimes take a long time

### ISSUE THREAD

**Issue by devioa** [amir20/dozzle#2416]
![动画](https://github.com/amir20/dozzle/assets/38558065/ccd17dce-19ab-401a-93de-512a19452785)

**Comment by amir20** [comment]
This happens to me too. 

I know what the problem is but I don't know how to fix it. If you look at the JavaScript console you should see an error. Because there is no clean way to recover from the error I have to clear the logs. But the reconnect takes some time. 

I haven't figured out what causes the exception because I don't get an error message. 

I'll keep investigating but hoping to figure out what the root cause is.

**Comment by devioa** [comment]
> This happens to me too.
> 
> I know what the problem is but I don't know how to fix it. If you look at the JavaScript console you should see an error. Because there is no clean way to recover from the error I have to clear the logs. But the reconnect takes some time.
> 
> I haven't figured out what causes the exception because I don't get an error message.
> 
> I'll keep investigating but hoping to figure out what the root cause is.

well, good luck
this is a great utility and I sincerely hope it can become better

**Comment by amir20** [comment]
Looking at the code I think I figured a way to improve it. Instead of clearing the logs on error, I can clear on connect. That should fix the logs disappearing for a few seconds. But I won't be able to test it until next week. So stay tuned.

**Comment by amir20** [comment]
I believe I found the problem. :) When Docker was providing incorrect headers, I was silently closing the connection. That's not good. 

@devioa can you try `amir20/dozzle:pr-2423`? 

It should fix the issue with some other minor improvements. Hopefully no other bugs.

**Comment by amir20** [comment]
My testing looks good 🎉

Will merge when others test.

**Comment by devioa** [comment]
> I believe I found the problem. :) When Docker was providing incorrect headers, I was silently closing the connection. That's not good.
> 
> @devioa can you try `amir20/dozzle:pr-2423`?
> 
> It should fix the issue with some other minor improvements. Hopefully no other bugs.

I just tried and now it seems loading fast, and I haven't observed other issues yet. I think this issue has been resolved!
Thanks for your work!

**Comment by amir20** [comment]
Thanks for the quick test! 

I will merge to master and do some more testing tomorrow.
