### ISSUE TITLE
Support for More Specific Locale Codes (e.g., en-US, zh-TW)

### ISSUE THREAD

**Issue by PeterDaveHello** [amir20/dozzle#2417]
**Is your feature request related to a problem? Please describe.**
The current locale support only includes two-letter language codes like `en` and `zh`. This doesn't account for more specific locale codes such as `en-US`, `zh-CN`, or `zh-TW`.

**Describe the solution you'd like**
I would like the project to extend its locale support to include more specific locale codes. This would make the application more versatile and better suited for international audiences.

**Additional context**
I am looking forward to this feature being implemented and would be happy to provide a `zh-TW` translation to supplement the existing `zh` (which is actually `zh-CN`).

**Comment by PeterDaveHello** [comment]
I've prepared a patch that might help solve this issue as below. Please let me know if you would like to take a look, and maybe I can submit a pull request for review?

```diff
diff --git a/assets/modules/i18n.ts b/assets/modules/i18n.ts
index 2d2cb1b..52ea64a 100644
--- a/assets/modules/i18n.ts
+++ b/assets/modules/i18n.ts
@@ -10,9 +10,15 @@ export const install = (app: App) => {
       },
     ),
   );
+
+  const userLang = navigator.language;
+  const shortLang = userLang.slice(0, 2);
+
+  const locale = messages.hasOwnProperty(userLang) ? userLang : (messages.hasOwnProperty(shortLang) ? shortLang : 'en');
+
   const i18n = createI18n({
     legacy: false,
-    locale: navigator.language.slice(0, 2),
+    locale: locale,
     fallbackLocale: "en",
     messages,
   });
```

**Comment by amir20** [comment]
Yes please send a PR. You don't need to provide EN. It's already set as fallback. 

I am away this week will check Monday. 

Thanks!

**Comment by amir20** [comment]
Also try reading https://kazupon.github.io/vue-i18n/guide/fallback.html#explicit-fallback-with-decision-maps. It might be better solution.

**Comment by PeterDaveHello** [comment]
Sent here: #2418, thanks.
