### ISSUE TITLE
Support ISO8601 Time Format

### ISSUE THREAD

**Issue by My-Random-Thoughts** [amir20/dozzle#2419]
Can you look to support the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format for dates please.

yyyy-MM-dd

It would help in sorting and understanding dates correctly.

**Comment by amir20** [comment]
@My-Random-Thoughts Can you explain a little more your use case? The only date I parse right now is the timestamp from docker. Which timestamp are you wanting?

**Comment by amir20** [comment]
Oh you mean the dates on the page. Dozzle will automatically use the right formatting based on your locale.  For `en-US` the formatting is MM/dd but for `en-GB` it uses `dd/MM`. So it's possible you don't have the right locale set. I use javascript's `Intl.DateTimeFormat` which does this automatically.
