### ISSUE TITLE
If there are log level info with placeholders, the log level symbol on left side may not be displayed

### ISSUE THREAD

**Issue by devioa** [amir20/dozzle#2439]
I thought it was a problem with the container itself, but it wasn't until you fixed https://github.com/amir20/dozzle/issues/2431#issuecomment-1773322653 last time
that I realized it might be a bug(?) or unexpected situation
It looks like this:
![image](https://github.com/amir20/dozzle/assets/38558065/8eb9b713-35bd-4e1c-bee0-31a5fdd3fef3)
the placeholder may be a space, a tab, either before or after. I have observed it before
but I have now lost this part of the log
so I can't provide such log for you to reference

**Comment by devioa** [comment]
And there may be multiple placeholders in different logs

**Comment by devioa** [comment]
Oh! There is another form of log level that goes like this:
![image](https://github.com/amir20/dozzle/assets/38558065/54e2be59-64a4-455b-8ab8-5f7154d4bf96)
I guess it should be something like I=Info, W=Warning, E=Error, etc

**Comment by devioa** [comment]
and these:
![image](https://github.com/amir20/dozzle/assets/38558065/59966f86-8622-4aca-8288-95ec7817256e)
![image](https://github.com/amir20/dozzle/assets/38558065/359ba517-0cb1-483e-8840-3707d3b0e166)

**Comment by amir20** [comment]
Hi @devioa. This is not a bug. More like a feature request :) 

The logic to identify the log level is a guess. It is here: 

https://github.com/amir20/dozzle/blob/2881f25a1a39ed777a2782387af371e0bc1885ba/docker/level_guesser.go#L16-L32


I check for `[INFO]`, `[info]`, `INFO....` I do not check for `[ warn]` no WRN and `INF`. There possibilities are limitless. These logs are not structured so I have to really do my best to guess. 

I think the only one that makes sense to do is `[ WARN]` or `[WARN ]`. I can do this with RegEx pretty easily. But the other ones like `INF` aren't very standard. 

What do you think?

**Comment by devioa** [comment]
> Hi @devioa. This is not a bug. More like a feature request :)

That's right, so when I chose the issue template, I chose `Feature request` instead of `Bug report`

> I think the only one that makes sense to do is [ WARN] or [WARN ]. I can do this with RegEx pretty easily. But the other ones like INF aren't very standard.
What do you think?

well, you may be right. If these non-standard log level formats are forcibly matched, it may cause words containing such characters in the log to be hit, resulting in recognition errors

**Comment by amir20** [comment]
Exactly. That's what I haven't aggressively tried labeling levels. 

I'll see if I can improve the levels this week by checking for spaces.

**Comment by devioa** [comment]
No, I don't think so.
I pulled the latest source code and built it, but when I ran it, I found that the previously identified label were missing and still couldn't identify the ones with placeholders.
![image](https://github.com/amir20/dozzle/assets/38558065/08246d12-c8ac-4f1f-bc34-fcbe40a1b0f1)
![image](https://github.com/amir20/dozzle/assets/38558065/8d91164a-f31f-415c-b09b-5856fb65384a)

**Comment by amir20** [comment]
I think I know what it is. I didn't realize you have a timestamp in beginning.

**Comment by amir20** [comment]
OK. Added some tests. And I think fixed it. 

Can you try `amir20/dozzle:master`?

Also these are my checks 

https://github.com/amir20/dozzle/blob/be11c32139be3a3be9cac1e14c3a8d70f6374e3d/docker/level_guesser_test.go#L12-L25

**Comment by devioa** [comment]
Great! Now it's working properly! Thank you for your work!👍

**Comment by amir20** [comment]
Yey. I will release a new build tomorrow.
