### ISSUE TITLE
Add leading space/zero to the Timestamp when hour is single digit

### ISSUE THREAD

**Issue by dodgex** [amir20/dozzle#2450]
**Is your feature request related to a problem? Please describe.**
The Timestamp in the logs has inconsistent sizing depending on the hour. as soon as the hour gets double digits, the log messages are indented a bit more compared to single digit hours. this affects both 24hr and 12hr formats obviously

**Describe the solution you'd like / Describe alternatives you've considered**
I would either suggest to add a space or zero in front of the hour if it is single digit or at least ensure, that the actual log messages start exactly at the same possition

**Additional context**
![image](https://github.com/amir20/dozzle/assets/204013/4c497983-7cd6-4b35-88b7-07b55812c2d4)
(7:58 entry with added space; red lines for better visibility of the issue)

**Comment by amir20** [comment]
Hmm interesting point. Yea that seems bad. However, I don't control this. I pass it on to the browser via `Intl.DateTimeFormat` to format the date and times.  Looks like there is an option to make it always 2-digits for hour. Would you say that should be the case? eg. Always be 2 digits to make sure everything is aligned. I assume so.

**Comment by amir20** [comment]
PR at #2452 which can be test with `amir20/dozzle:pr-2452`. Let me know if it looks good and I'll merge.

**Comment by dodgex** [comment]
Looks good ! Thank you for this project and your incredibly fast response times :)

**Comment by amir20** [comment]
Merged. Will release later.

**Comment by amir20** [comment]
Deployed.
