### ISSUE TITLE
[Bug] Search results sometimes flash and disappear

### ISSUE THREAD

**Issue by ericrafalovsky** [amir20/dozzle#2451]
**Describe the bug**
Sometimes when searching logs (command - F) we observe that the results flash and then disappear. Clearing the search bar and trying again with the same search term usually results in the correct behavior

**To Reproduce**
I've been unable to come to a definitive way to reproduce this :/, but thought I would report this regardless in case others are also running into this. I have been able to see this behavior on several different containers and with a variety of search terms, and don't have good leads on why this only happens sometimes

**Expected behavior**
When searching, the search results stay on the screen and do not disappear

**Screenshots**
https://drive.google.com/file/d/1scYMsPEPezS8mXvEfQEXv1U7EGpxdC12/view?usp=drive_link

**Desktop (please complete the following information):**

- OS: MacOS 14.0
- Docker version: Docker version 24.0.2, build cb74dfc
- Browser & version: Chrome Version 118.0.5993.117
- Version: v5.0.5

**Comment by amir20** [comment]
First thing I would try is upgrade to the latest version since there was bug fixes recently that improved the errors. 

Next time, if it happens again check js console and see if there is an error there.

**Comment by amir20** [comment]
@ericrafalovsky I was on my phone. Here is the fix that was in 5.0.9. https://github.com/amir20/dozzle/pull/2434 I was reading the headers incorrectly and closing the connection prematurely. 

Looking at the video, that might fix it. Aside from that, let me know if you see anything in js console.

**Comment by ericrafalovsky** [comment]
Great - I've updated to latest, and will let you know if the issue continues! I'll close this issue in that case.

**Comment by ericrafalovsky** [comment]
Okay it seems like we're running into this still on 5.1.0. This is from the js console. Let me know if there's any other telemetry that would be helpful to share

![Screenshot 2023-11-03 at 9 51 06 AM](https://github.com/amir20/dozzle/assets/88681631/32438c55-dc6f-4685-a202-a0b815f84fab)

**Comment by amir20** [comment]
Was there any other errors before that? Especially a network error?

**Comment by amir20** [comment]
Hmm I think I was able to use that stacktrace to find some thing that might be causing this.

**Comment by amir20** [comment]
Ok so here is what I did in #2469. 

- I added js map to make the stack traces better
- According to the above error, `flattenJSON` function has a null object. This should never happen. But I added some warnings and if null is found I try to handle it. 
- Finally, I also print the path to the json object this happening. This could help me figure out which part of your log might be breaking. 

Please try `amir20/dozzle:pr-2469` and let it run for a while. The page should never disappear anymore, but errors should show up in js console. When that happens paste the error for me. It would be better to have text and not screenshot.

**Comment by david-chour** [comment]
Hey @amir20 ,

I was able to use your new dozzle and the search results look like they are persisting now. Instead of type error above, there is now a warning

```
flattenJSON: obj is null for path:

  | ta | @ | index.ts:21
-- | -- | -- | --
  | (anonymous) | @ | LogEntry.ts:71
  | run | @ | reactivity.esm-bundler.js:178
  | get value | @ | reactivity.esm-bundler.js:1135
  | get message | @ | LogEntry.ts:85
  | (anonymous) | @ | search.ts:39
  | (anonymous) | @ | search.ts:35
  | run | @ | reactivity.esm-bundler.js:178
  | get value | @ | reactivity.esm-bundler.js:1135
  | w | @ | reactivity.esm-bundler.js:1018
  | (anonymous) | @ | LogViewer.vue:60
  | ci | @ | runtime-core.esm-bundler.js:821
  | H | @ | runtime-core.esm-bundler.js:5812
  | run | @ | reactivity.esm-bundler.js:178
  | g.update | @ | runtime-core.esm-bundler.js:5862
  | hn | @ | runtime-core.esm-bundler.js:158
  | If | @ | runtime-core.esm-bundler.js:362
  | Promise.then (async) |   |  
  | Rf | @ | runtime-core.esm-bundler.js:275
  | Ua | @ | runtime-core.esm-bundler.js:269
  | (anonymous) | @ | runtime-core.esm-bundler.js:5858
  | qc | @ | reactivity.esm-bundler.js:373
  | Ni | @ | reactivity.esm-bundler.js:363
  | Ia | @ | reactivity.esm-bundler.js:973
  | (anonymous) | @ | reactivity.esm-bundler.js:1123
  | qc | @ | reactivity.esm-bundler.js:373
  | Ni | @ | reactivity.esm-bundler.js:358
  | Ia | @ | reactivity.esm-bundler.js:973
  | (anonymous) | @ | reactivity.esm-bundler.js:1123
  | qc | @ | reactivity.esm-bundler.js:373
  | Ni | @ | reactivity.esm-bundler.js:358
  | Bt | @ | reactivity.esm-bundler.js:350
  | set | @ | reactivity.esm-bundler.js:487
  | e.<computed> | @ | reactivity.esm-bundler.js:408
  | d | @ | eventsource.ts:129
  | await in d (async) |   |  
  | l | @ | LogEventSource.vue:20
  | (anonymous) | @ | InfiniteLoader.vue:23


```

**Comment by amir20** [comment]
Ah excellent! That helps a lot. Would you be able to send the log that is causing that? Based on the logs, it looks like one of the logs you have is like a valid json but when I try to search through it, it is null. 

You can email it if you don't want to paste it here.

**Comment by amir20** [comment]
Looking at the code path again I think I found how one could end up here. Going to merge and release.

**Comment by amir20** [comment]
Released.
