### ISSUE TITLE
Incorrect `Content-Type` on log fetch endpoint

### ISSUE THREAD

**Issue by JustAnotherArchivist** [amir20/dozzle#2458]
**Describe the bug**
On the log pagination API endpoint, Dozzle currently returns data with [the HTTP header](https://github.com/amir20/dozzle/blob/7431c3455fdebbcb6b31307de3914b8c8b1d0a1f/internal/web/logs.go#L54)

    Content-Type: application/ld+json; charset=UTF-8

This MIME type is assigned for [JSON-LD](https://en.wikipedia.org/wiki/JSON-LD?useskin=vector), a completely different data format from what's actually being returned: newline-delimited JSON (or JSON Lines or JSONL or LDJSON or NDJSON). Note that there is not yet a standardised MIME type for the latter: https://github.com/wardi/jsonlines/issues/19

**To Reproduce**

1. Go to the logs of a container.
2. Scroll up.
3. Observe the responses to network requests being made when reaching the top.

**Expected behavior**
Correct HTTP headers

Because there isn't currently a registered MIME type for JSONL (see link above), the only reasonable approach is currently a custom/unregistered type, e.g. `application/x-jsonl`. Once there is a standardised MIME type registered with the IANA, it should be replaced by that.

**Comment by amir20** [comment]
That's right. It's completely wrong. 

Does this break anything though?

**Comment by JustAnotherArchivist** [comment]
> Does this break anything though?

It doesn't break anything as far as usability of the web interface goes. If anyone were to use the API directly (though it seems undocumented?), it could cause some minor headaches if their HTTP client were to attempt to decode the response automatically. It did make my browser's network tools slightly sad because Firefox tried to decode the response as JSON, which obviously fails on the second line.

> I have also seen application/jsonlines+json.

There are two reasons why this shouldn't be used. Firstly, any MIME type whose second part doesn't start with `x-` (or `X-` or `x.`) is supposed to be officially registered; this one obviously [is not](https://www.iana.org/assignments/media-types/media-types.xhtml). But secondly and more importantly, the `+json` suffix would mean that the data is valid JSON. That's why the JSON-LD type, `application/ld+json`, uses it: its data format is JSON and can be parsed by any JSON parser, but there's extra structure in it beyond that to make it specifically JSON-LD. Except in the special cases of exactly zero or one lines, JSONL is *not* valid JSON and requires special support in the parser.

**Comment by amir20** [comment]
> If anyone were to use the API directly

I hope no one ever does that. My APIs are tightly coupled to the UI. They are constantly changing with each release. Hopefully, they would use Docker API directly. 

> It did make my browser's network tools slightly

Agreed it should be fixed. I am OCD when it comes to tech debt. 

Sounds good for the rest. 

I'll patch with `application/x-jsonl` when I get a chance. Working on some authentication stuff right now.

**Comment by amir20** [comment]
Fixed now in master. Test with `amir20/dozzle:master` or wait a while until I release it. Thanks for taking the time to do the research for the real solution. It saved me some time. 

The event stream still remains `text/event-stream` because I think that's the right type. But if it isn't, let me know.

**Comment by JustAnotherArchivist** [comment]
Lovely, thank you!

`text/event-stream` is the correct type for SSE, yeah.
