### ISSUE TITLE
dozzle not starting with new release (custom docker user)

### ISSUE THREAD

**Issue by 5olu7ion** [amir20/dozzle#2462]
**Describe the bug**
The new 5.1.2 release is not starting, when running the image with a custom user (--user 1000:101). When using 5.1.1, everything runs smoothly. 

**To Reproduce**

Run dozzle wit this compose config (adjust user an group accordingly, and watch out for the remote host):
```
dozzle:
   container_name: dozzle
   restart: unless-stopped
   image: amir20/dozzle:v5.1.2
   user: 1000:101
   logging:
     driver: local
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - 8120:8080
   environment:
     - DOZZLE_NO_ANALYTICS=true
     - DOZZLE_REMOTE_HOST=tcp://192.168.1.111:2375\|otherhost
     - DOZZLE_HOSTNAME=docker
```

**Expected behavior**
Image should run with 5.1.2 like it run with 5.1.1

**If applicable include logs with `--level debug` and browser logs**
```
2023-10-31 19:06:08.395	
level=info msg="Accepting connections on :8080"
2023-10-31 19:06:08.394	
level=info msg="Connected to 2 Docker Engine(s)"
2023-10-31 19:06:08.356	
level=info msg="Creating client for otherhost with tcp://192.168.1.111:2375"
2023-10-31 19:06:08.321	
level=info msg="Dozzle version v5.1.1"
----------START WITH v5.1.1----------
2023-10-31 19:05:54.793	
time="2023-10-31T18:05:54Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 19:04:53.674	
time="2023-10-31T18:04:53Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 19:03:52.337	
time="2023-10-31T18:03:52Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 19:02:51.069	
time="2023-10-31T18:02:51Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 19:01:49.798	
...
2023-10-31 17:50:41.493	
time="2023-10-31T16:50:41Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 17:50:39.099	
time="2023-10-31T16:50:39Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 17:50:37.388	
time="2023-10-31T16:50:37Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 17:50:35.641	
time="2023-10-31T16:50:35Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
2023-10-31 17:50:34.013	
time="2023-10-31T16:50:34Z" level=fatal msg="Unable to create data directory: mkdir /data: permission denied"
----------START WITH v5.1.2----------
```

**Comment by amir20** [comment]
Hmm interesting. I've never tested with `--user`.  What does it achieve? 

I wonder if I can do `mkdir /data`. But if you do end up using an authentication method then it won't be able to write settings to disk.

**Comment by amir20** [comment]
As a temporary fix, I have created `data` dir in Dockerfile. You can test it with `amir20/dozzle:pr-2463`. But that means that if you try to use the new features with authentication, it won't sync your settings because it can't write to disk. 

I am not sure what would be a fix around this. 

I am not too familiar with `--user` flag so maybe you can tell me if there is a better way to do this.

**Comment by 5olu7ion** [comment]
Hello @amir20,
thanks a lot for answering so fast :-)
I tested the PR Version, and everything works as expected now:
```
10/31/2023
10:08:47 PM
level=info msg="Dozzle version pr-2463"
10/31/2023
10:08:47 PM
level=info msg="Creating client for otherhost with tcp://192.168.1.111:2375"
10/31/2023
10:08:47 PM
level=info msg="Connected to 2 Docker Engine(s)"
10/31/2023
10:08:47 PM
level=info msg="Accepting connections on :8080"
```
Yes, I use the user flag for almost all my containers, and it causes that the container process(es) run under the specific user. You can track it with `ps aux`. 
I'm not an absolute expert, but your fix seems to be a good idea, because it should still be possible to provide the yaml configuration via bind mount (-v /path/to/config.yaml:/data/config.yaml). 
I personally don't need a config file (and no persistence), and I'm absolutely fine with the various cli parameters (like --addr).

**Comment by amir20** [comment]
Great. I was trying to create a non-root user to see if I can do this without you trying it. But I think it highly depends on your environment. I did

```
RUN addgroup -S dozzlegroup && adduser -S dozzleuser -G dozzlegroup
```

But looks like on my linux box it doesn't work. It might be a permission issue. So I don't know what could be the problem.

**Comment by amir20** [comment]
For now, I will merge the PR and release patch.

**Comment by amir20** [comment]
Looks for me the error 

```
"Could not connect to local Docker Engine: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1\": dial unix /var/run/docker.sock: connect: permission denied"
```

So I think it's out of scope to figure out how to get the users right. Closing.
