### ISSUE TITLE
Option to display Dozzle update is available on dashboard.

### ISSUE THREAD

**Issue by JSouthGB** [amir20/dozzle#2475]
**Is your feature request related to a problem? Please describe.**
Display on the dashboard when a new version is available.

**Describe the solution you'd like**
I'd like to see without having to click into settings when a new version is available.

**Describe alternatives you've considered**
Manually checking for Settings page.

**Additional context**
Perhaps make it an option in the settings page to display on the dashboard when a new update is available. I imagine many folks don't frequent the settings and may miss out on updates for a while. I merely happened to check the settings and found that I'm on v4.10.3 (for which I don't even see a tag) compared to the current v5.2.3.

**Comment by amir20** [comment]
That's on my todo list 😎

**Comment by amir20** [comment]
@JSouthGB what do you think of this? I have been trying different ideas and I think this makes the most sense. 

<img width="568" alt="Screenshot 2023-11-07 at 3 17 27 PM" src="https://github.com/amir20/dozzle/assets/260667/39911bbf-b2be-4ef3-a583-d49994dfd910">

**Comment by JSouthGB** [comment]
That's even better than I figured. Not intrusive and still very noticeable. You even fit in additional information with the prior releases. 

I don't know if you were already working on this, either way that's some quick response time!

**Comment by amir20** [comment]
I had already the place to put it and the data, I just to make the drop down. It still took me a couple hours which I found annoying. haha. 

I only get a couple hours a week so I'll have to work on it again later. 

I'll let you know when there is something to test.

**Comment by JSouthGB** [comment]
I'm sorry it took up all your time. I certainly get it, I frequently spend more time than originally anticipated.

Curious, what else are you looking to do with it?  The screenshot looks good and functional.

**Comment by amir20** [comment]
Good question. There is actually a few of things I have been thinking about. They are subtle but I am trying to reduce annoying people. Here is what I was thinking remaining: 

- Should I show all versions in the drop down? Right now it is all versions with updates being highlighted. I think this might annoy people. But I am not sure. Other products seem to have all updates. Since I release often, I think I'll keep it this way. 
- Should the red dot go away after clicking? I wasn't thinking it should. But that could weird if it doesn't
- I want to also add message for breaking changes so people know what to expect before updating. 
- Finally, I don't know where it should take the user if they do click a release. Should it open Github? Or see the details in the Dozzle. 

Anyway, these are the things I am thinking about. Let me know your thoughts.

**Comment by JSouthGB** [comment]
> * Should I show all versions in the drop down? Right now it is all versions with updates being highlighted. I think this might annoy people. But I am not sure. Other products seem to have all updates. Since I release often, I think I'll keep it this way.

I would think released versions only. In my very inexperienced opinion, running the latest update would be equivalent to a "dev" version.

> * Should the red dot go away after clicking? I wasn't thinking it should. But that could weird if it doesn't

The read dot should go away. When clicked, the user has been notified, fulfilling the intention of the notification. A user isn't required to act upon a notification.

> * I want to also add message for breaking changes so people know what to expect before updating.

I like this. Particularly useful for those who don't read change logs or just skim them.

> * Finally, I don't know where it should take the user if they do click a release. Should it open Github? Or see the details in the Dozzle.

A link to the clicked version GitHub release would make sense. E.g. [v5.3.0](https://github.com/amir20/dozzle/releases/tag/v5.3.0)

**Comment by amir20** [comment]
> I would think released versions only. In my very inexperienced opinion, running the latest update would be equivalent to a "dev" version.

I did mean only released versions. But what I meant to say is if it should prior versions too. So for example, if user is on version `5.3.1`, should it also show release notes for version `5.3.0`?  

Additionally, what should it do if user has the latest? Should it just say "no updates"?

**Comment by JSouthGB** [comment]
Displaying the 5 most recent releases seems informative (with a relative or real timestamp) without being an info dump or overload. Though I know many apps don't show prior versions so maybe it's unnecessary.

Displaying release notes in the modal could be too much, I'd reserve that for the GitHub releases page (while adding a **breaking changes** note when appropriate). And it should display the same if clicked/hovered when no updates are available, just without the red dot.

The **breaking changes** note should probably be under the user's current version. If they're more than 5 versions out of date, they wouldn't see the note. So thinking it through a bit more, perhaps do just the current and most recent version (if current is outdated), then the user can dive into the other change logs if they like. In this case, the modal could merely display a "no updates available" note while still working in a link to the repo.

**Comment by amir20** [comment]
Yea, I think some of that makes sense. I am still thinking it over, but thanks for helping me brainstorm. It's interesting for such a simple change, there is a lot to consider.

**Comment by amir20** [comment]
OK I think I am done. It should look good. The only thing left is translations to other languages which I can come back to later. I am going to merge to master soon and hopefully you can provide feedback by testing `amir20/dozzle:master`.

**Comment by EDIflyer** [comment]
Ah just found this thread - I commented in https://github.com/amir20/dozzle/issues/2489#issuecomment-1806846514 as I wasn't quite sure what this was 😄 

I appreciate the work that has gone into it, I guess my initial thought would be of a more of a subtle notification under the version number just saying a new one was available +/- a link to release notes, I wasn't sure if it needed a permanent announcement icon? (sorry, just a thought and possibly a bit late!!)

**Comment by amir20** [comment]
@EDIflyer Yea, I guess for someone who always updates there is less value. Not against hiding it if there is no updates. 

> version number just saying a new one was available +/- a link to release notes

The reason I didn't do this was because some times folks are going from version `5.3.x` to `5.5.y`. There could have been multiple releases between and I copied this idea from other app likes Github or Bugsnag where each release is announced.

**Comment by amir20** [comment]
@JSouthGB the work on this issue is done so closing. We can revisit hiding if others feel strongly.

**Comment by EDIflyer** [comment]
@amir20 thanks - I think hiding it if no updates would be great. Also would be good to horizontally align the centre with the Gravatar icon for when it is displayed 😉  Appreciate the point re showing changes from previous versions if out of date by quite a few.

**Comment by JSouthGB** [comment]
> @JSouthGB the work on this issue is done so closing. We can revisit hiding if others feel strongly.

Apologies, I missed your message yesterday.

Just pulled the image and I think it looks great. Very non intrusive and to the point. 

To @EDIflyer - Dozzle works well for me without any pain points, so I don't frequently check for updates. Also, when I posted this request, I was on a version that didn't have the version displayed in the banner. Perhaps a minor tweak down the line would be to move the notification down to the version number.

@amir20 - I appreciate your speedy response to this enhancement request!

**Comment by amir20** [comment]
Interesting Portainer does something similar. :) 

<img width="745" alt="Screenshot 2023-11-12 at 1 16 53 PM" src="https://github.com/amir20/dozzle/assets/260667/98ddfea0-883f-4cfe-89c9-675f081f77a4">

**Comment by EDIflyer** [comment]
Haha yep - I remember they had a bug for ages where the red dot wouldn't disappear even when you'd viewed it and everyone was getting quite fed up! 😂 They use it for quite a lot of notifications around container actions working/not working 🙂

**Comment by EDIflyer** [comment]
A minor point @amir20 (how unlike me!😉), but the fact that notifications have been viewed isn't being synced with user settings just now - I click on the icon and the red dot disappears but then when I access Dozzle on the next browser it's back again!  Would it be possible to add this to the synced dataset? 🙂

**Comment by amir20** [comment]
It's on my to do. :) 

I think there is a few things that need to be sticky.

**Comment by amir20** [comment]
See #2509
