### ISSUE TITLE
Option to disable log colors

### ISSUE THREAD

**Issue by Veejnny** [amir20/dozzle#2484]
Hi @amir20 

We are already using coloring in our logger library, and I recently upgraded Dozzle to the newest version. However, it is not working well together. So, my question/idea is: Is it possible to disable log colors? If not, is there any chance to implement this option?

Example:

My already colored log:
![image](https://github.com/amir20/dozzle/assets/57194031/bebce0c8-f7a3-46ba-b539-9ec9bc8f2226)

Same log in dozzle:
![image](https://github.com/amir20/dozzle/assets/57194031/ba1edba3-aa37-449e-9efd-d5508d67f970)

**Comment by amir20** [comment]
What is not working exactly? Is it the green color?

Unfortunately I don't control this. I pass the logs directly to https://www.npmjs.com/package/ansi-to-html which does the coloring. If I was to skip this then you would see something like `"\u001b[31mHelloWorld"` which would be bad. 

The only thing that has changed with color in the last year is https://github.com/amir20/dozzle/issues/2175, which respect the foreground color. 

If you are technical, then look at the documentation at https://www.npmjs.com/package/ansi-to-html#options and see if there is some configuration that could fix this.

**Comment by Veejnny** [comment]
Hello, I just fixed my problem with adding "\x1b[0m" to reset color. I am not sure why in dozzle i saw collored all line but this fixes it on my side. Have a nice day :)
