### ISSUE TITLE
Be able to share search and pinned containers with others

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2486]
Something that I have been thinking about is for Dozzle to be able to share the state of all panes and search filters with other people. I think this would be very useful with https://github.com/amir20/dozzle/issues/2036 which a user can store their configuration but also send it out as a link like `http://dozzle.internal/share?data=QWRkaXRpb25hbGx5IGltcHJvdmVkIFBSIGJpdCBieSBleHRlbmRpbmcgdGhlIHNpZ24taW4gd2luZG93IGFuZCBsZXZlcmFnaW5nIEpJVCB3aGljaCBpbXByb3ZlZCBvdmVyYWxsIENVSiBwZXJtaXNzaW9uIHB1bnQgYnkgWlolLiA` which data would be some stored configuration.

**Comment by amir20** [comment]
@EDIflyer what do you think?

**Comment by EDIflyer** [comment]
Interesting idea - I guess as I'm the only admin for my containers I wouldn't have a direct use case for it (#2363 is higher up my personal wishlist lol) but I can certainly see how for teams working together on the same server it could be handy.

**Comment by amir20** [comment]
Doesn't look like a lot of interest. So closing.
