### ISSUE TITLE
Not sure if related but I just get this now when trying to view Dozzle...

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2489]
Not sure if related but I just get this now when trying to view Dozzle...

> Unauthorized user

Portainer logs show
```
level=error msg="Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name."
```

_Originally posted by @EDIflyer in https://github.com/amir20/dozzle/issues/2479#issuecomment-1806601580_

**Comment by amir20** [comment]
@EDIflyer can you try this?

**Comment by amir20** [comment]
With my testing, it works. So I am going to release a patch.

**Comment by EDIflyer** [comment]
Thanks - just pulled the patch and agree it fixes the issue!

My OCD was drawn to this though lol...
![image](https://github.com/amir20/dozzle/assets/13610277/9b0f0968-847e-4595-a5da-4ecd91f30947)
![image](https://github.com/amir20/dozzle/assets/13610277/3e6d080c-6d25-41a9-a06f-afc762c379ee)

The new announcement icon seems lower/smaller than the Gravatar icon - also I wasn't quite sure what this was meant to show (as I'm generally running the latest version and it just confirms I'm on the latest version) - would a small notification under the Dozzle version number saying an update is available be more subtle?

**Comment by amir20** [comment]
I plan to add test cases so that authentication shouldn't break. 

Not everybody runs latest version though. So the purpose of that drop down is to high light some of the releases people don't know about. 

This is especially important as I plan to remove the legacy authentication option. The drop down will warn users before updating to have expectations. 

You are right that if you always have the latest version then there isn't much to show. Maybe I'll hide it in the future. This was discussed in the other issue.
