### ISSUE TITLE
The name of the bottom container is obstructed

### ISSUE THREAD

**Issue by zqxvip** [amir20/dozzle#2500]
The name of the bottom container is obstructed

- OS: windows
- Docker version 19.03.12
- Browser & version edge latest 
- Version 5.4.1

![image](https://github.com/amir20/dozzle/assets/7312051/9f2b68c7-a117-428f-81ec-dce29fac9adf)

**Comment by amir20** [comment]
Thanks. I think that will be an easy fix.

**Comment by amir20** [comment]
This PR should fix it and move it to the left. This was the best option without having to move anything around. 

<img width="240" alt="Screenshot 2023-11-14 at 12 51 57 PM" src="https://github.com/amir20/dozzle/assets/260667/bb2760a3-f3df-4b88-b131-cbab8ba7590d">
