### ISSUE TITLE
Log questions

### ISSUE THREAD

**Issue by bobluck** [amir20/dozzle#2510]
**Describe the bug**
level=warning msg="unable to parse json logs - error was \"json: cannot unmarshal number into Go value of type map[string]interface {}\" while trying unmarshal \"401\""

**To Reproduce**
Launch Docker then check logs after some time

**Expected behavior**
Error free logs

**Screenshots**

**Desktop (please complete the following information):**

- DSM 7.x
- Docker version Latest
- Browser & version Safari
- Version 5.4.2

11/17/2023
11:37:05 AM
level=info msg="Dozzle version v5.4.2"
11/17/2023
11:37:05 AM
level=info msg="Connected to 1 Docker Engine(s)"
11/17/2023
11:37:05 AM
level=info msg="Accepting connections on :8080"
11/17/2023
11:37:13 AM
level=info msg="Token created for user admin"
11/17/2023
12:10:55 PM
level=info msg="Token created for user admin"
11/17/2023
01:01:33 PM
level=info msg="Token created for user admin"
11/17/2023
01:03:06 PM
level=warning msg="unable to parse json logs - error was \"json: cannot unmarshal number into Go value of type map[string]interface {}\" while trying unmarshal \"401\""
11/17/2023
01:03:06 PM
level=warning msg="unable to parse json logs - error was \"json: cannot unmarshal number into Go value of type map[string]interface {}\" while trying unmarshal \"401\""
11/17/2023
01:03:06 PM
level=warning msg="unable to parse json logs - error was \"json: cannot unmarshal number into Go value of type map[string]interface {}\" while trying unmarshal \"401\""
11/17/2023
01:03:06 PM
level=warning msg="unable to parse json logs - error was \"json: cannot unmarshal number into Go value of type map[string]interface {}\" while trying unmarshal \"401\""
11/17/2023
01:03:06 PM
level=warning msg="unable to parse json logs - error was \"json: cannot unmarshal number into Go value of type map[string]interface {}\" while trying unmarshal \"401\""

**Comment by amir20** [comment]
Interesting, I guess ``json.Valid` from Go thinks `401` is a valid json. Which I guess it is. I'll have to think of a better way to check this.

**Comment by bobluck** [comment]
ThanksSent from my iPhoneOn Nov 17, 2023, at 17:40, Amir Raminfar ***@***.***> wrote:﻿
Interesting, I guess ``json.Validfrom Go thinks401` is a valid json. Which I guess it is. I'll have to think of a better way to check this.

**Comment by amir20** [comment]
Try `amir20/dozzle:2512`. I hide the error if it's just a number error.

**Comment by bobluck** [comment]
Thanks, I”ll take a look later. Just learning this stuff, and takes me a while.

**Comment by bobluck** [comment]
Was unable to pull 2512
￼

**Comment by amir20** [comment]
I am not sure what command you are using. Its hard to guess. But the tag is `pr-2512`. And it is here https://hub.docker.com/layers/amir20/dozzle/pr-2512/images/sha256-7515dc2f046b0b3db7b80f6961dc20b06e960ce070301da10d957069848c9e47?context=explore

I am going to merge my fix because I did some more testing and it seems to work fine.

**Comment by amir20** [comment]
This is now in `master` with `amir20/dozzle:master`.

**Comment by bobluck** [comment]
Ahh, I missed the pr- and just used 2512, my mistake. I’ll just keep the :latest tag and await the update. Thanks for your attention. Like the docker.

**Comment by bobluck** [comment]
Amir, 5.4.3 up and running, the logs are looking great. Thanks
