### ISSUE TITLE
Missing Favorite Icon

### ISSUE THREAD

**Issue by uhlhosting** [amir20/dozzle#2522]
**Describe the bug**
In several instances where image name is longer, there are chances the buttons are hidden.
<img width="1172" alt="image" src="https://github.com/amir20/dozzle/assets/6324047/eeac8e2b-cecf-4161-928a-1bcb4459b158">

**To Reproduce**

1. Go to 'Homepage'
2. Click on 'Any longer names dozzle containers'
3. Scroll down to 'as seen above the favorite icon will be missing, I believe you should trim the container titles to a MAX value.'

**Expected behavior**

**Screenshots**
<img width="1172" alt="image" src="https://github.com/amir20/dozzle/assets/6324047/494fbe35-875c-4452-b3d3-7fbf9bf324cf">

**Desktop (please complete the following information):**

- OS: Mac OS
- Docker version: Latest
- Browser & version Safari , Latest 17.x
- Version latest 4.5.3

**If applicable include logs with `--level debug` and browser logs**

**Comment by uhlhosting** [comment]
This seems to occur under several circumstances, the readings there are either complete hosted repo image, or a sha256 key that is to download the container:

<img width="1157" alt="image" src="https://github.com/amir20/dozzle/assets/6324047/cfc7a1b0-d6a2-4b0d-9421-5903da3a9f70">
 
Hope this helps.

**Comment by uhlhosting** [comment]
I believe easier would be to move when is not visible the element for add to favorite, to the Menu maybe? Making sure people can always reach it.

**Comment by amir20** [comment]
I think I'll have to either move the icon or figure out to set max width. 

I also support mobile so need to think of that.

**Comment by uhlhosting** [comment]
Also one thing I can think of would be to allow the closing of the browsing tab, and shorten the name of the machine to the "." mark.

This is just a bit of css, is really not a hard bug/issue to fix

<img width="564" alt="image" src="https://github.com/amir20/dozzle/assets/6324047/dba9c734-2dd5-48f3-8d66-89d5107e7ccd">

**Comment by amir20** [comment]
I tried to fix it but it was hard with all the CSS. In #2535 I moved the star to left. It might interfere with health check icon. You can try it and see if it's better. I am still thinking about it. You should be able to test it with `amir20/dozzle:pr-2535`. 

Btw, +1 for Arc browser!

**Comment by amir20** [comment]
This is fixed now @uhlhosting. 

<img width="544" alt="Screenshot 2023-12-01 at 6 30 19 AM" src="https://github.com/amir20/dozzle/assets/260667/bec1ddbc-df72-4b51-9d3a-0097a8a247b0">

The part I didn't like was the healthcheck icon but I have moved that to the right now.
