### ISSUE TITLE
Adding a *Restart* option for containers

### ISSUE THREAD

**Issue by akash-ramaswamy** [amir20/dozzle#2532]
**Is your feature request related to a problem? Please describe.**
I felt many times that it would be so nice to have a **Restart** option for individual containers, since it would be handy for immediately restarting the containers during development.

**Describe the solution you'd like**
Adding a refresh button here and mapping this to restart using [docker engine api](https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerRestart)

![image](https://github.com/amir20/dozzle/assets/87078332/1b214da0-b358-41f2-b63f-1b10215fbf56)

I would be happy to get this assigned to me if @amir20 you feel that this is a good handy feature!

**Comment by akash-ramaswamy** [comment]
We can use the [golang SDK](https://pkg.go.dev/github.com/docker/docker/client?utm_source=godoc#section-documentation) for this feature!

**Comment by amir20** [comment]
Hi @akash-ramaswamy. The focus of Dozzle has been so far to collect data like logs and stats. I haven't focused on other uses cases which would mutate or change the state of containers. I think there are other tools like Portainer which do same thing. 

Additionally, taking space in the UI for a button which won't be used by a lot of people seems like a bad decision.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 !

I understand the focus on data collection, but a Restart option for individual containers in Dozzle could significantly boost developer productivity during active development phases. It aligns with common needs and could be used as "optional" setting or so, to address UI concerns. Your thoughts on this?

**Comment by amir20** [comment]
Hey @akash-ramaswamy, I hear you. But I am very careful to add new features, especially if it won't be useful for most users. 

> Restart option for individual containers in Dozzle could significantly boost developer productivity during active development phases

Thinking about this personally, I have never had the need to restart a container. I am usually jumping between my terminal or created some kind of process in Docker Desktop that automates this. 

> It aligns with common needs and could be used as "optional" setting or so, to address UI concerns

There aren't actually a lot of bells and whistles to Dozzle right now. But you also have to consider the maintenance. As Dozzle has gotten more sophisticated in the last year, I have to be extra careful about releasing and not breaking anything.  This is one the of the major reasons why I don't add a lot of hidden features because then I would have to test them all. Some times my integration tests doesn't catch anything. 

All that being said, I am willing to be proven wrong if others show interest in this feature.  There hasn't been any previous feature requests to start, restart or stop containers. It would be easier to justify changes to the UI and complexity if more people want it. I am not convinced it is that. 

Hope that sounds fair.

**Comment by akash-ramaswamy** [comment]
Hmm yes @amir20 , I understand your point.

**Comment by ab623** [comment]
From my perspective, Portainer is very heavy for some "simple" container management. 

Personally if Dozzle had a simple and minimal, start/stop/restart functionality, that would be super useful for me.

**Comment by amir20** [comment]
@akash-ramaswamy maybe you can prototype something to see how it works. If its something passive that doesn't interfere then we can try adding it. 

It would be a lot of work though :) You need to: 

- Create new APIs
- UI work with Vue
- And of course test it

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! Sure. I will try to share a prototype soon 😄

**Comment by akash-ramaswamy** [comment]
Im working on the test cases. Will update here once done with testing.

**Comment by amir20** [comment]
Also, maybe implement `stop` too? Right now the code seems to only assume on action but the `/api/actions/{name}` is pretty clean to support something like `containerAction(id, action)` where you could send different actions. 

And if you want to get _REALLY_ fancy, you could update the search box to support restart :)

**Comment by ab623** [comment]
I was actually working on the same implementation! @akash-ramaswamy yours looks like a great start!

I had put the actions in the dropdown menu as well, as it looks cleaner. Potentially a stop container option too? :)

Is it worth hiding the UI functionality behind a settings toggle. So the user doesn't have to have those options always available to them?

**Comment by amir20** [comment]
> Is it worth hiding the UI functionality behind a settings toggle. So the user doesn't have to have those options always available to them?

Yea, I was thinking that too. I know this would be useful for some folks because the want Dozzle to be read only. 

Wow, I went from having very few PRs to two people working on same feature. Can't believe it.

**Comment by akash-ramaswamy** [comment]
> Also, maybe implement `stop` too? Right now the code seems to only assume one action but the `/api/actions/{name}` is pretty clean to support something like `containerAction(id, action)` where you could send different actions.
> 
> And if you want to get _REALLY_ fancy, you could update the search box to support restart :)

I love this refactor :heart:

**Comment by akash-ramaswamy** [comment]
> Thanks, looked at the code a little bit. You'll need to use `withBase` for `fetch`. There is some examples.
> 
> For the UI, let's move it inside the dropdown on the right. Maybe at the end? I don't think we should put it in the header as previously mentioned. I can just imagine some one clicking it by accident. Seems like you use Dozzle in dev, but others use it in production.
> 
> Ideally, I would also implement it a "are you sure?" but that could be part of a different PR.
> 
> Thanks for doing it! Looks like it took less time than expected :)

Yes @amir20 i saw it. Thanks for guiding me!

**Comment by akash-ramaswamy** [comment]
> I was actually working on the same implementation! @akash-ramaswamy yours looks like a great start!
> 
> I had put the actions in the dropdown menu as well, as it looks cleaner. Potentially a stop container option too? :)
> 
> Is it worth hiding the UI functionality behind a settings toggle. So the user doesn't have to have those options always available to them?

@ab623 , we can certainly add this as an option in the settings. But wouldn't it be handy if it is readily available in the dropdown menu?

**Comment by ab623** [comment]
> > Is it worth hiding the UI functionality behind a settings toggle. So the user doesn't have to have those options always available to them?
> 
> Yea, I was thinking that too. I know this would be useful for some folks because the want Dozzle to be read only.

The use case was addressed my Amir earlier. :)

Additionally it unclutterers the "actions" from the viewing

**Comment by amir20** [comment]
To make it easier to merge, let's do it as a different PR. If there was an option to disable this in the setting, then I don't think a confirmation would be needed anymore since the user has explicitly asked for it. 

Some things I have been thinking about: 

1. Should this be enabled by default? I have no idea. 
2. Should this be a UI toggle or a command line ENV? 

It could be disabled by default any maybe only enabled via `--enable-control` or something like that? 

@akash-ramaswamy there is already support for toasts with `useToast()` so if you get an error just use that. I think it will make your life easier.

**Comment by akash-ramaswamy** [comment]
Answering your points:

1. @amir20 Initially can we roll out disabled by default? Mentioning it only in the release notes?
2. UI toggle would be more than enough? just my opinion

Yes @amir20 , i have implemented the toast for error handling. Just shared the initial commit for getting out some ideas / guide!

**Comment by amir20** [comment]
Remember UI toggle is specific for each user where env variables are global. When authentication is enabled, each user profile is stored. 

I am trying to think of other use cases, like deployed in a dev environment and used between 3 people. So many decisions to make which is what I have actually enjoyed about Dozzle the most! It has made me a better product manager.

**Comment by akash-ramaswamy** [comment]
@amir20  `--enable-actions` would be a nice fit? Also, will it be passed like below?

`docker run --name dozzle -e ENABLE_ACTIONS=true -d --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:8080 amir20/dozzle:latest`

**Comment by akash-ramaswamy** [comment]
This looks pretty i think so? Your thoughts @amir20  @ab623  ?

![image](https://github.com/amir20/dozzle/assets/87078332/5b380449-efe7-45c3-a419-8397e983ed55)

**Comment by akash-ramaswamy** [comment]
The stop / start would be based on actual container state

**Comment by akash-ramaswamy** [comment]
I feel that if i position it below the `show *` options set, it would make more sense?

**Comment by amir20** [comment]
>  I feel that if i position it below the show * options set, it would make more sense?

Yes, I agree. I think at the end would be best. 

I like it so far. 

> @amir20 --enable-actions would be a nice fit? Also, will it be passed like below?

It should be `DOZZLE_ENABLE_ACTIONS`. See something like https://github.com/amir20/dozzle/blob/050e499f8e718b959cf3e26808947203d5eed860/main.go#L43. It is probably a lot easier to add a flag than UI toggle. You would want the flag to be passed in to web and to `index.html` where I parse it in https://github.com/amir20/dozzle/blob/050e499f8e718b959cf3e26808947203d5eed860/assets/stores/config.ts#L11. Then you can use it anywhere in the UI to conditionally hide it.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! I have updated the code with all discussed changes and `DOZZLE_ENABLE_ACTIONS` flag!

[branch link](https://github.com/akash-ramaswamy/dozzle/tree/feature/restart-container)

**Comment by ab623** [comment]
Thanks for the hard (and quick) work on this @akash-ramaswamy ! 🙂

**Comment by amir20** [comment]
Alright, merged to master. I am going to test it a little. You all can try it with `amir20/dozzle:master`. If all good, I can release.

**Comment by amir20** [comment]
@akash-ramaswamy did you want to take a crack of also updating the docs? https://github.com/amir20/dozzle/tree/master/docs/guide

**Comment by akash-ramaswamy** [comment]
That would be great and I love to do it! 😄

Will update it now!

> @akash-ramaswamy did you want to take a crack of also updating the docs? https://github.com/amir20/dozzle/tree/master/docs/guide

**Comment by amir20** [comment]
You can test with `pnpm docs:dev`

**Comment by amir20** [comment]
I found a small bug where after a restart the logs have the same id. I think it's still OK though. 

I am going to release this now.

**Comment by EDIflyer** [comment]
Nice work @akash-ramaswamy :) Just tested this out (added `- DOZZLE_ENABLE_ACTIONS=true` to the `environment:` section of my docker-compose and works really nicely - stopped, started, restarted and all seemed to work well.  I've found the Dozzle file to streamed log occasionally gets stuck so nice to be able to just restart with this.  I also have Portainer setup to only be accessible when connected via SSH (via a port forward) so it's nice to have access to container control directly from Dozzle (already behind 2FA via Authelia for safety).

PS as an aside for those that haven't seen it - [Dockge](https://github.com/louislam/dockge) by Louis Lam (of Uptime Kuma fame) looks like quite a nice lightweight Portainer alternative.

**Comment by amir20** [comment]
Dockge creator actually has video where installs Dozzle. https://www.youtube.com/watch?v=E805XcbTzgY :)

**Comment by amir20** [comment]
Closing this feature since it's now complete. Thanks all for contributing!

**Comment by EDIflyer** [comment]
I'd be supportive. Restart works OK but I don't like the idea of being able up stop it as you then kill of your UI and you'd need to use a different route in - interestingly Portainer does something similar where it greys out the tick box for itself so you can't select it to stop itself.

**Comment by amir20** [comment]
Created #2553
