### ISSUE TITLE
Support for not restarting Dozzle

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2553]
> > Dockge creator actually has video where installs Dozzle. https://www.youtube.com/watch?v=E805XcbTzgY :)
> 
> 
> 
> Haha DBTech isn't the creator but yep that's the video where I saw it and Louis Lam has seen it and commented - defo a great choice of container to demo things with 😍👍
> 
> 
> 
> Any thoughts re an exclusion for stopping the Dozzle container? (not sure how technically feasible that is).

Hi @EDIflyer , i'm actually working on it and glad that you brought up here. You have any ideas? Any thoughts on this?

_Originally posted by @akash-ramaswamy in https://github.com/amir20/dozzle/issues/2532#issuecomment-1835622015_

**Comment by amir20** [comment]
@EDIflyer @akash-ramaswamy let's use this one to keep track of work

**Comment by akash-ramaswamy** [comment]
I don't know if this is a good idea or not, but what if, we disable/grey-out the actions when `currentContainer` has/contains image value of dozzle?

![image](https://github.com/amir20/dozzle/assets/87078332/4c56721b-ec7f-4c57-a45f-dec7745ab2c5)

**Comment by ab623** [comment]
I don't think that we should restrict that. The user makes a conscious decision to stop containers, and should understand stopping the dozzle service will stop their access. 

I dont think we should block them artificially from doing so.

**Comment by amir20** [comment]
I think there can be a few options:

Which containers to be disabled?

1. Simplest option would be disable `amir20/dozzle`
2. Use labels so that multiple containers can opt out of being disabled 

My personal philosophy has been to not over build until there is some validation that a more complex solution is needed. For this, I think option 1 is fine. 

On the UI, hide vs disable. Generally, disabling means that there is some action that can enable it. In this case, there is no action that can enable the button for Dozzle. So I think it would be better to just hide it. Otherwise, I think the user might be confused to see the button but disabled.

**Comment by amir20** [comment]
> I don't think that we should restrict that. The user makes a conscious decision to stop containers, and should understand stopping the dozzle service will stop their access.

That's a thought too. I haven't really spent a lot of time using this feature to be honest to know if should be enabled for Dozzle.

**Comment by ab623** [comment]
I personally would say not its not a required feature to implement at this point in time. Someone would have to knowingly enable the enable actions option, then select the Dozzle container, then go into the overflow menu, and only then hit Stop. If they managed to do all that, they certainly knew what they wanted to do, and probably wanted to do it.

However if you do want to implement, I would say disable the Stop only, Restart should still be allowed, so it doesn't change the end state of the container, just interrupts it while it restarts. 

I suggest holding off, unless we see it more wildly requested, and then reassessing from there. I assume most wont even enable the enable actions option, as they wont know its there unless they read the documentation :)

**Comment by ab623** [comment]
I see what you are saying. If we did add it I would suggest allowing it to stop, but for the Dozzle container only, enabling some confirmation popup stating "Stopping this service will stop Dozzle UI from working". 

The reason I think we shouldn't disable it entirely would be, it gives the user freedom to shut it down if they want to. An example, I have a service which stops containers after inactivity, and brings them back to life when it detects someone trying to access it, Dozzle included. So being able to stop Dozzle from my perspective is useful. 

One thing we need to consider is 

> ![image](https://private-user-images.githubusercontent.com/87078332/287285613-4c56721b-ec7f-4c57-a45f-dec7745ab2c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDYyMzgsIm5iZiI6MTcwMTQ0NTkzOCwicGF0aCI6Ii84NzA3ODMzMi8yODcyODU2MTMtNGM1NjcyMWItZWM3Zi00YzU3LWE0NWYtZGVjNzc0NWFiMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE1NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YTQzNWFkZTA2OTliOTVjYjNhNDQ1ZmJlMDFhMmZmMDY5YzNiNjAxMzg4ZGFjNTBiYWM0NDlmMWUyNTc1ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VW0KJbXVJJx3HJVg_Rz2tbEOUXoevOS65OMdmwJP5gQ)

What if the image is coming from a docker file. E.g. My dockerfile might build from dozzle as the base image. What does the "image" property contain then?

**Comment by EDIflyer** [comment]
Agree only needs to be on Dozzle container given it's an opt-in option.  I couldn't see the image included, it just showed as broken. I'm not sure if there's any way for the Dozzle UI to know which container it 'belongs' to? (genuinely have no idea!)

**Comment by akash-ramaswamy** [comment]
> What if the image is coming from a docker file. E.g. My dockerfile might build from dozzle as the base image. What does the "image" property contain then?
>

I think, this is a rare case 🤔

**Comment by ab623** [comment]
Very much rare, and maybe one that can just be ignored to be honest. If you're building from a base image, you **definitely** know what you are doing :)

**Comment by akash-ramaswamy** [comment]
We can actually achieve this by exploring this [API](https://github.com/moby/moby/blob/v24.0.7/api/types/image_summary.go#L8)

**Comment by EDIflyer** [comment]
Sounds fair enough :)

**Comment by akash-ramaswamy** [comment]
> Akash, perhaps you can think of other ways to improve Dozzle. There are a few open issues which I haven't had a chance to work on. But also, I think you can add some test cases for Go that doesn't exists for the feature you worked on. 
> 


Sure @amir20 ! I will start to work on it and update you as i progress. I was looking out other issues also, but as you said, i will be concentrating on test cases first.
