### ISSUE TITLE
Move notification bell

### ISSUE THREAD

**Issue by ab623** [amir20/dozzle#2563]
The notification bell, takes up an unnecessary amount of space in the main window. I propose it get moved to next to the settings icon in the side bar.

If there is an agreement I can look at getting a PR up for it.

![image](https://github.com/amir20/dozzle/assets/3438974/41aa1aff-a26a-4170-9fab-6882af6fc51e)

**Comment by amir20** [comment]
This won't work because the notification bar changes when authentication is enabled.  There is also links that can go there when users have enabled markdown. So it's not that simple. You'll have to try different settings yourself to see how they work.

**Comment by ab623** [comment]
Okay. I'll dig a bit deeper separately. Thanks for the background info.
