### ISSUE TITLE
Adding context menu for copying / actions on log messages

### ISSUE THREAD

**Issue by akash-ramaswamy** [amir20/dozzle#2571]
**Is your feature request related to a problem? Please describe.**
Hi @amir20 ! I find it often very difficult to select the whole log row and copy. For example, if i need to copy this row, I would need to select the whole row.
![image](https://github.com/amir20/dozzle/assets/87078332/e9677489-0ede-4363-a920-779b31e55bab)

**Describe the solution you'd like**
Instead, If we could add a context menu on right-click of the current log row, we can provide options such as **copy log**, to make life easier.

Any thoughts on this?

**Comment by amir20** [comment]
I had actually worked on this but scrapped it because the UI was ugly. If you can think of a minimal solution that doesn't interfere too much then I think it would be a good addition. 

For your example, you mean copy the JSON, right? So I guess it would just copy the original JSON without any filters?

**Comment by akash-ramaswamy** [comment]
Thanks for reminding to improvise the *search menu* part too @amir20 ! This is an important point to make sure this is a really usable feature.

**Comment by akash-ramaswamy** [comment]
@amir20 How about this hover action?


https://github.com/amir20/dozzle/assets/87078332/2af279ae-ee38-4a7d-bb99-d392e348143d

**Comment by amir20** [comment]
I like it a lot. But I wonder what it would look like with `json`? Because there is another link that shows up to expand json. So it might not look good.  Have you thought of that?

**Comment by amir20** [comment]
Also, not related, why is `DOZZLE_ENABLE_ACTIONS` showing a warning?

**Comment by akash-ramaswamy** [comment]
> Also, not related, why is `DOZZLE_ENABLE_ACTIONS` showing a warning? 

I actually run two different containers, just was playing with old and new versions. Old version doesn't contain that feature right?

**Comment by akash-ramaswamy** [comment]
> I like it a lot. But I wonder what it would look like with `json`? Because there is another link that shows up to expand json. So it might not look good.  Have you thought of that? 

Im planning to show this only on minimized view. Im thinking of something else for expanded view, or modify this accordingly.

Any thoughts?

**Comment by amir20** [comment]
> I actually run two different containers, just was playing with old and new versions. Old version doesn't contain that feature right?

That's right. 

> This is just an initial idea. Im planning to show this only on minimized view. Im thinking of something else for expanded view, or modify this accordingly.

I don't like the current solution. So open to trying something else. I guess before spending time, it's worth calling out that you need a solution which: 

- [ ] handles in search mode to jump in context
- [ ] allows opening and closing json
- [ ] allows copy pasting 
- [ ] And extensible to options in the future. eg. add another option to do something else

**Comment by akash-ramaswamy** [comment]
> I don't like the current solution. So open to trying something else. I guess before spending time, it's worth calling out that you need a solution which:
> 
> * [ ]  handles in search mode to jump in context
> * [ ]  allows opening and closing json
> * [ ]  allows copy pasting
> * [ ]  And extensible to options in the future. eg. add another option to do something else

Hi @amir20 , I thought so many ways! But i find that this one fills all the checks! I also think this is extensible and also handles in the search context too!


https://github.com/amir20/dozzle/assets/87078332/9e2604f1-b7d8-489d-af9f-e8bc29f09a0e

**Comment by amir20** [comment]
Hmm I do like that. Just a little jump on hover. Send PR so I can try it out.

**Comment by akash-ramaswamy** [comment]
I have raised a rough implementation of the feature, please try out and suggest any improvements @amir20 @ab623 !

**Comment by akash-ramaswamy** [comment]
> Hmm I do like that. Just a little jump on hover. Send PR so I can try it out.

@amir20 I think we can avoid it by slightly fixing the padding. But the padding should be visible, since it helps in popping out the menu on hover.
