### ISSUE TITLE
[Feature Request] Ability to search across all container logs

### ISSUE THREAD

**Issue by ericrafalovsky** [amir20/dozzle#2576]
**Is your feature request related to a problem? Please describe.**
Today, Dozzle supports searching for a string in exactly one container. This works well when you know exactly which container contains the logs you are looking for, but in some cases you either aren't completely confident which container/s you want to search in, and sometimes you want to find related logs across several containers (eg an error ID)

**Describe the solution you'd like**
A "global" search bar to search for a string across all containers.

**Comment by amir20** [comment]
Great feature request but technically very hard. Docker doesn't allow me to search across all containers so Dozzle would have to search each container manually. That would be slow and probably not work well. 

Dozzle is similar to the `docker logs` command. So if you think about it, you would have to `grep` each log and that would be super slow. 

The only other option would be to store everything in a database which I think is too much work.

**Comment by ericrafalovsky** [comment]
>So if you think about it, you would have to grep each log and that would be super slow.

I'm less familiar with the details of the problem space here, but perhaps there are opportunities for parallelization here? Perhaps there's also a way to relax the product requirements to make this more feasible. For example, not interleaving logs from containers, displaying search results for each container async (rather than all at once),  etc

**Comment by amir20** [comment]
The search is done on browser right now. So parallelization wouldn't be an option. One would have to move search to API and then do parallel requests to Docker.

**Comment by amir20** [comment]
Going to close this. I don't have plans to work on it as it is a lot of code to write.
