### ISSUE TITLE
Copy with JSON logs is overlapping 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2579]
Oops more bugs when testing JSON...

<img width="1389" alt="Screenshot 2023-12-09 at 6 28 44 AM" src="https://github.com/amir20/dozzle/assets/260667/2237f1bf-8555-48d6-ba0a-7d691427b33d">

_Originally posted by @amir20 in https://github.com/amir20/dozzle/issues/2572#issuecomment-1848425449_

**Comment by amir20** [comment]
@akash-ramaswamy created this bug to continue discussion. Let's bring all related bugs you find here.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 , regarding this JSON bug keeping the parent `div` (which wraps timestamp, stdout/stderr, JSON and copy button) if set to `w-full` it resolves this bug.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 , regarding this comment https://github.com/amir20/dozzle/pull/2572#issuecomment-1848424922 this is fine. I was initially thinking this too!

I thought we also could add `word-break` to the log message div, as it could break into new line automatically and width is maintained!

**Comment by amir20** [comment]
Send a pr and I'll test it. I have a complicated set up so can test edge cases.

**Comment by akash-ramaswamy** [comment]
@amir20 raised a PR

**Comment by amir20** [comment]
Merged the other PR. So looks like search is just remaining. 
<img width="1406" alt="Screenshot 2023-12-09 at 6 21 53 AM" src="https://github.com/amir20/dozzle/assets/260667/3379609f-f3f2-4d21-96c8-48d27ee27b3f">

**Comment by amir20** [comment]
Tested #2580. Looks good!

**Comment by akash-ramaswamy** [comment]
> Merged the other PR. So looks like search is just remaining.

I have a query though, after we did this change how would a user choose `Jump to Context` if the search entry is at the top?

![image](https://github.com/amir20/dozzle/assets/87078332/e67075b7-5a6d-4e7a-b83f-2a4c91f65a45)

**Comment by amir20** [comment]
I think it would be fine since the user can scroll. But I guess it will be one of those things I'll have to test out to really know.

**Comment by akash-ramaswamy** [comment]
> I think it would be fine since the user can scroll. But I guess it will be one of those things I'll have to test out to really know.

But the image I highlighted is the **First Log entry** 🥶

**Comment by amir20** [comment]
Maybe for now it will be ok since selecting only the first log won't be common. 

We can release a new version and see what others say. If it's a common bug then we can move it or do something else.

**Comment by amir20** [comment]
If you can get the PR today then I'll try to release.

**Comment by amir20** [comment]
Releasing now. The only weird bug I saw was that sometimes when clicking to show context, the yellow line would go away. But honestly, I think this is good enough.  Generally, after release, I get so many updates that if someone has a bug they will let you know. I am going to close this. Great job!

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! I will check that bug you mentioned and let you know!
