### ISSUE TITLE
[REQUEST] Ability to selectively ignore specific containers

### ISSUE THREAD

**Issue by jd-apprentice** [amir20/dozzle#2590]
**Is your feature request related to a problem? Please describe.**
No! This is not a problem at all.

**Describe the solution you'd like**
I would like to be able to choose which containers the user sees. This is because, for example, I have two servers, one for production and one for development, and I have multiple applications from different projects. I would like, for instance, Team 1 to see their containers, but Team 2 not to see them.

**Describe alternatives you've considered**
One solution for my problem could be just having apps from different teams on different servers but that is not possible atm.
Other solution could be to create a subnet inside the machine and separate hostnames maybe?

**Comment by jd-apprentice** [comment]
Hey! Thanks for the answer.

I'll like the idea of having different instances with the `--filter` flag. I'm going to give it a try these days once I have some time!

And about the complex solution seems totally usable, a lot of people likes to put proxys ahead of the product they are using, in my case I find your software really cool since I rather have this instead of for example something super complete logging solution like sentry, sentry is cool but expensive to self-host and requires a lot of configuration, but with this if I can separate which logs can be seen, developers could just watch the logs from containers directly and debug in deployed environments in case something wrong happens.

**Comment by amir20** [comment]
> I'll like the idea of having different instances with the --filter flag. I'm going to give it a try these days once I have some time!

Great! I'll close.

> for example something super complete logging solution like sentry, sentry is cool but expensive to self-host and requires a lot of configuration

That's exactly what happened to me. I started looking at other solutions and they were are all super complicated or cost money. It just didn't make sense for my projects that weren't making any money to be costing money. 

However, over the time, Dozzle has matured. So I do want to make sure to support more complicated user cases like multiple teams, enterprise uses case like profiles and different authentication. 

If you think of anything that would help your teams to be more effective let me know.

**Comment by DASPRiD** [comment]
@amir20 I think user/group based filters could be really practical for my team – setting up an individual instance for practically every user sounds a little bit bothersome :)

**Comment by amir20** [comment]
@DASPRiD What kind of authentication do you use? Could you create a new issue with details of your setup?
