### ISSUE TITLE
The QR code display is unfriendly and cannot be scanned.

### ISSUE THREAD

**Issue by kokojacket** [amir20/dozzle#2592]
![image](https://github.com/amir20/dozzle/assets/74887370/90652e93-2fc8-4db9-900e-530249cd84d8)

**Comment by amir20** [comment]
There isn't an easy fix for this because Dozzle is optimized for reading textual logs.

**Comment by amir20** [comment]
This has been implemented now since a few people asked for it. I am not sure if it's compact enough where QR code would work, but can be tested now with latest version and enabled in settings.
