### ISSUE TITLE
favicon for Safari

### ISSUE THREAD

**Issue by bobluck** [amir20/dozzle#2597]
**Is your feature request related to a problem? Please describe.**
favicon does not work in Safari, it does in Firefox.

**Describe the solution you'd like**
a Safari compatible favicon.

**Describe alternatives you've considered**
switch browsers, not realistic.

**Additional context**
<img width="171" alt="Screenshot 2023-12-15 at 15 42 35" src="https://github.com/amir20/dozzle/assets/128809007/512a337d-0e5f-4d7a-9b51-60cd8b65efe6">

**Comment by amir20** [comment]
Safari doesn't support SVG icons. :(  And usage is [below 5%](https://caniuse.com/link-icon-svg) so not much point of fixing it because it would require converting a lot of stuff.

**Comment by bobluck** [comment]
Ok thanksSent from my iPhoneOn Dec 15, 2023, at 16:44, Amir Raminfar ***@***.***> wrote:﻿
Safari doesn't support SVG icons. :(  And usage is below 5% so not much point of fixing it because it would require converting a lot of stuff.

**Comment by amir20** [comment]
I'll close this for now. If in the future I have time I'll fix it.

**Comment by bobluck** [comment]
Thank you Sent from my iPhoneOn Dec 15, 2023, at 17:04, Amir Raminfar ***@***.***> wrote:﻿
I'll close this for now. If in the future I have time I'll fix it.
