### ISSUE TITLE
Improve Log Line Copy Button

### ISSUE THREAD

**Issue by nrgbistro** [amir20/dozzle#2619]
When copying a log line using the copy button on the right, the result in my clipboard contains additional character codes that make searching for my issue harder than expected. For example, I have an error from one of my containers. Here is what's copied using the button:

`[31m[Nest] 7  - [39m12/22/2023, 9:56:31 PM [31m  ERROR[39m [38;5;3m[MediaService] [39m[31mAn error occurred while configuring transcoding options: Error: ENOENT: no such file or directory, scandir &apos;/dev/dri&apos;[39m`

Here is what I would have expected the copy button to produce:

`[Nest] 7  - 12/22/2023, 9:56:10 PM   ERROR [MediaService] An error occurred while configuring transcoding options: Error: ENOENT: no such file or directory, scandir '/dev/dri'`

**Comment by amir20** [comment]
It's because you have interactive mode with colors. Maybe something Dozzle can detect and remove? @akash-ramaswamy any ideas?

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! I have tested this fix, hope this resolves the issue :)

**Comment by amir20** [comment]
Merged the fix in master. Thanks @akash-ramaswamy !

**Comment by amir20** [comment]
v5.8 will address this.
