### ISSUE TITLE
Feedback: Remove the custom help pages 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2627]
[Custom documentation](https://dozzle.dev/guide/custom-documentation) was added in 5.1. However, I think less than 0.5% have used this feature. 

I plan to remove this, unless I see anybody objecting to it.

**Comment by amir20** [comment]
PR is at #2628

**Comment by EDIflyer** [comment]
Not something I use myself - we used MkDocs Material for all documentation.

**Comment by amir20** [comment]
This is now removed in mastewr.
