### ISSUE TITLE
🚨 Deprecation Warning: Legacy auth is going to be removed in v6.x

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2630]
### Summary
Legacy authentication is going to be removed in favor of multi-user authentication as described [here](https://dozzle.dev/guide/authentication#file-based-user-management).

### What is legacy authentication? 
Legacy authentication is configured using `--username` or `DOZZLE_USERNAME` and `--password` or `DOZZLE_PASSWORD`.  This is a single user mode which worked well for most people. 

### What is the new authentication model? 
The new authentication model was introduced in 5.x and supports [simple](https://dozzle.dev/guide/authentication#file-based-user-management) or [forward proxy](https://dozzle.dev/guide/authentication#forward-proxy).  The simplest option is to use simple mode by creating `/data/users.yml`: 

```
users:
  admin:
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
```

Documentation is can be found at https://dozzle.dev/guide/authentication#file-based-user-management

### Why is legacy being removed? 
There were two use cases that were impossible with the legacy system: 

1. Multi-user support was not possible. Proxy authentication is more secure as Dozzle will use whatever headers are passed to it. So Dozzle needed a way to support different users. 
2. Persisting user settings across different browsers. In legacy mode, everything is stored to `localstorage` because there was never more than one user. With the new authentication provider models, user data is now stored on server in `/data` directory. 

Both of these issues are addressed now. 

### What will happen in v6.x?
In version 6.x, if Dozzle is configured to use `--username`, it will throw an error and not start.

**Comment by ankitrgadiya** [comment]
Is it possible to make the Remote Headers configurable? I would like to use Cloudflare's Zero Trust service that sets a pre-defined Header (`cf-access-authenticated-user-email`).

**Comment by amir20** [comment]
@ankitrgadiya I think it's possible. I couldn't find any documentation on `cf-access-authenticated-user-email`. I won't have time to work on it for a few weeks. I haven't seen a lot of people ask for this feature though. If you can send a PR then happy to merge it.

**Comment by ankitrgadiya** [comment]
@amir20 Sure thing, raised the PR #2642.

**Comment by amir20** [comment]
Merged. Will release 6.x tomorrow.

**Comment by kokojacket** [comment]
DOZZLE_AUTH_PROVIDER: simple does not take effect
![image](https://github.com/amir20/dozzle/assets/74887370/82509fa8-009d-43c3-8fa6-b619043d0305)

**Comment by Tyree** [comment]
Trying to switch to simple auth provider, but the instructions for setting up the users.yml file is incomplete.  Says: "The content of the file looks like", but then doesn't show what it looks like.
Trying to make this change on an unRAID server (not using compose or cli). Any help is appreciated. Thanks!

**Comment by kokojacket** [comment]
@Tyree I've added users.yml but it still doesn't work
````
users:
  admin:
    name: koko
    password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11xxxxxxxxxx"
````

**Comment by Tyree** [comment]
> @Tyree I've added users.yml but it still doesn't work
> 
> ```
> users:
>   admin:
>     name: koko
>     password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11xxxxxxxxxx"
> ```

In your setup, your username is actually 'admin', not koko. See my example, the lowercase admin is what you use to login., The Admin is just the name of the user. Could be anything. Also, you may need to add quotes around the name for the file to parse correctly.

**Comment by kokojacket** [comment]
@Tyree Still not effective
![image](https://github.com/amir20/dozzle/assets/74887370/68e9c434-4547-47e9-a8b5-e71e27f86b2e)
![image](https://github.com/amir20/dozzle/assets/74887370/9b26247b-f1e6-42a3-8517-91b61d707e57)

**Comment by kokojacket** [comment]
@Tyree 
![image](https://github.com/amir20/dozzle/assets/74887370/0d489f32-86cc-48e6-ac01-2b086bc6d64d)

**Comment by Tyree** [comment]
You only need to give it access to /data, not a direct path to the yml file. If the yml file is in the /data directory, it'll pick it up.
I'm not sure if that's what is breaking things for you, but that part is definitely redundant and I'm not sure you can link directly to files that way with docker. (I'm a novice user)

**Comment by kokojacket** [comment]
@Tyree No, I confirmed that it did not take effect and I also granted file access permissions. I also tried mounting only the folder but not the file.

**Comment by kokojacket** [comment]
![image](https://github.com/amir20/dozzle/assets/74887370/bd98de8e-e2f1-4f75-bd55-223f40c7a565)

**Comment by Tyree** [comment]
Gotcha. Well, someone smarter than me is going to have to jump in on this one. From what I can see, it's pretty close to what works on mine.
One final thing, I'm ignorant of your system setup, but /share is a valid root folder?

**Comment by kokojacket** [comment]
yes it is a valid top-level directory

**Comment by amir20** [comment]
@Tyree good find. Documentation wasn't deployed correctly.  It is fixed now and an example of users.yml file should be there. It's here https://dozzle.dev/guide/authentication#file-based-user-management

@kokojacket can you create a new issue? I don't think you have mounted the files correctly. If you give me an example of docker compose and users.yml then I can try to reproduce it. 

Also the documentation is fixed now so maybe you can try again.

**Comment by kokojacket** [comment]
It's amazing, it's just been successful again

**Comment by amir20** [comment]
I will keep this open for a couple more days and then close it. Hopefully, by then, everybody has migrated over.

**Comment by amir20** [comment]
Closing as I hope most people are migrated.

**Comment by shedman214** [comment]
Has anyone done this in the unraid version? trying to this but does not work?

**Comment by Tyree** [comment]
> Has anyone done this in the unraid version? trying to this but does not work?

I did. Worked fine.
So, you added the environment variable, the volume path, and set up the users.yml file in the format posted above and in the docs?
Show us what you've set up so we can troubleshoot.

**Comment by NicoHerold** [comment]
> Has anyone done this in the unraid version? trying to this but does not work?
@shedman214 

delete the "Username" and "Password" in the Unraid Envoirements.
Then add the path like so:
![Screenshot_175](https://github.com/amir20/dozzle/assets/19534108/f9a75d65-1903-41b8-8854-4593e28cc77f)

Then create the file users.yml 
like here: https://dozzle.dev/guide/authentication#file-based-user-management
**Just sha-256 which can be computed with "echo -n password | shasum -a 256"**
So get the string for the password is `echo -n yourpassword | shasum -a 256`

and insert the users.yml file to the location from the envoirement u have. for me it was `/mnt/user/appdata/dozzle/`
    
![Screenshot_174](https://github.com/amir20/dozzle/assets/19534108/ab914fa6-c976-472c-8af8-ac8f7404fcd1)

Then u can start the container in Unraid and all done. (so work this for me)

**Comment by shedman214** [comment]
My apologies i was asking the steps to make it work in unraid. Didnt know
how to do it.

**Comment by amir20** [comment]
Thanks everybody who has responded. It's great to see others helping!

**Comment by Tyree** [comment]
> My apologies i was asking the steps to make it work in unraid. Didnt know how to do it.
@shedman214 
Did @NecoHerold get you straightened out with his instructions?

**Comment by mguilherme** [comment]
> > Has anyone done this in the unraid version? trying to this but does not work?
> > @shedman214
> 
> delete the "Username" and "Password" in the Unraid Envoirements. Then add the path like so: ![Screenshot_175](https://private-user-images.githubusercontent.com/19534108/294684136-f9a75d65-1903-41b8-8854-4593e28cc77f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODYwNzgsIm5iZiI6MTcwNDU4NTc3OCwicGF0aCI6Ii8xOTUzNDEwOC8yOTQ2ODQxMzYtZjlhNzVkNjUtMTkwMy00MWI4LTg4NTQtNDU5M2UyOGNjNzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDAwMDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYjljYTAyOTg3NmRlMmVhNDY4ODZhM2FlNzViM2Y2ZDQ4NWU3YzE5MTE5NjgzZWE5OTRkNmUxNWEzZDExZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3adpIJFwObkbrfyvUAAFAUv3IQotsMpKBPr2_ZmGLA)
> 
> After this, unraid show like so: ![Screenshot_172](https://private-user-images.githubusercontent.com/19534108/294684469-18953007-6e22-493a-9ada-68c067791567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODYwNzgsIm5iZiI6MTcwNDU4NTc3OCwicGF0aCI6Ii8xOTUzNDEwOC8yOTQ2ODQ0NjktMTg5NTMwMDctNmUyMi00OTNhLTlhZGEtNjhjMDY3NzkxNTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDAwMDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMGE1NmIyYjM5N2E1YWU5MzJiOGUyNTczZjIxYjU0ZTNiOWQyY2FjZmY1MmEyNTkzNjlhMWIzNmE4YWZhMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cpGnurPmBKW-OLFX5tq-VB81Fe8Wbmtkl86RkJapc3c)
> 
> Then create the file users.yml like here: https://dozzle.dev/guide/authentication#file-based-user-management **Just sha-256 which can be computed with "echo -n password | shasum -a 256"** So get the string for the password is `echo -n yourpassword | shasum -a 256`
> 
> and insert the users.yml file to the location from the envoirement u have. for me it was `/mnt/user/appdata/dozzle/`
> 
> ![Screenshot_174](https://private-user-images.githubusercontent.com/19534108/294684197-ab914fa6-c976-472c-8af8-ac8f7404fcd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODYwNzgsIm5iZiI6MTcwNDU4NTc3OCwicGF0aCI6Ii8xOTUzNDEwOC8yOTQ2ODQxOTctYWI5MTRmYTYtYzk3Ni00NzJjLThhZjgtYWM4Zjc0MDRmY2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDAwMDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZTA0ODQ4YjhiZjVlNmIzMWI2ZTYyNTNiNjZjZDVmYzJmN2IyMmJkNWUzY2ZhMDUxNDJhZWNkNzk0NzE5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AfDkgs8XDZm6doeLgyku-3XCfASOej-JXawbThWvZOc)
> 
> Then u can start the container in Unraid and all done. (so work this for me)

you are still missing the **DOZZLE_AUTH_PROVIDER = simple**, you also need to add that env variable, otherwise the users.yml won't do anything

**Comment by acidburnmonkey** [comment]
Am having the same isue as Koko ; dozzle is not reading my users.yml file and am sure the volume is mounted correctly

**Comment by natanaelsc** [comment]
the same issue here too

**Comment by amir20** [comment]
For anybody who is still having a problem, if Dozzle cannot read `users.yml`, it will throw a big error and not start. Please check the logs.  Make sure `DOZZLE_AUTH_PROVIDER` is set correctly and use the [example](https://dozzle.dev/guide/authentication#file-based-user-management) which is just admin/password. 

If you still can't get it to work, create a new issue with debug [enabled](https://dozzle.dev/guide/debugging).

**Comment by luoweihua7** [comment]
> Am having the same isue as Koko ; dozzle is not reading my users.yml file and am sure the volume is mounted correctly

try add `-v DOZZLE_AUTH_PROVIDER=simple` or use command `--auth-provider simple` ([File Based User Management](https://dozzle.dev/guide/authentication#file-based-user-management)), work for me both

**Comment by Enissay** [comment]
Deploying dozzle on many machines on swarm, is there anyway to easily use the stackfile to setup the admin login without the need to manually provide a yaml file on each machine ?

**Comment by amir20** [comment]
@Enissay One of the pros for using files is that you can use docker secret. Here is an example https://earthly.dev/blog/docker-secrets/

I haven't used it personally, but you should be able to create a secret entry from the content of user.yml and mount that to all your instances.

**Comment by Enissay** [comment]
Oh, true, it has been a while since I last used them.
Gosh, _dozzle_ added many new features since I last checked a few months ago. Very well done mate <3

**Comment by aph5nt** [comment]
please restore  legacy authentication in new version, you can 3 types of auth

**Comment by OA-Steve** [comment]
For Unraid users having issues. I tried everything in this thread multiple times. I finally deleted the container and re-added it from the from Community Apps. It worked perfectly after that with the same settings and users.yml. Good luck.

**Comment by bozzio83** [comment]
No matter what I try on unraid I get username and password are not valid.  Ive tried copy and pasting your users.yml without changing a thing. I've tried new username and hash.  Dozzle loads but i get not valid login.

**Comment by amir20** [comment]
@bozzio83 open a new issue with sample compose file and any configuration. There is also a new generate sub command you can use to generate users.yml file. 

I am going to lock this thread since the new auth method has been working for a while now.
