### ISSUE TITLE
How to run behind a reverse proxy with Caddy?

### ISSUE THREAD

**Issue by EricFROL** [amir20/dozzle#2636]
As title says. 
In the [FAQs](https://dozzle.dev/guide/faq) there's info about disabling the buffering in nginx, but nothing about caddy. 
Cant find anything googling though.

Any help? Thank you.

**Comment by amir20** [comment]
Do you find it to actually not work with Caddy? I have used Caddy personally and never had a problem. I even just tested with `caddy reverse-proxy --from :9191 --to :8080`. 

What's not working?

**Comment by EricFROL** [comment]
Nothing gets never loaded...

**Comment by EricFROL** [comment]
![image](https://github.com/amir20/dozzle/assets/42719382/26460485-ce5e-4a68-8332-4d71df343708)

**Comment by amir20** [comment]
I would need more details to help. 

1. Do you see browser errors in console? 
2. Look at the network tab, I am guessing one of the requests fails
3. Does Dozzle work without using Caddy? 


Try https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#streaming and set `flush_interval: -1`

**Comment by EricFROL** [comment]
1. 
![image](https://github.com/amir20/dozzle/assets/42719382/288da31e-f8de-4a97-9ad3-ef7dea2fa572)
This is the caddy log:
`ERR undefined | ts=1703960872.1715066 logger=http.handlers.reverse_proxy msg=aborting with incomplete response upstream=192.168.1.36:9999 duration=0.035572156 request=[object Object] error=reading: context canceled `

2.
![image](https://github.com/amir20/dozzle/assets/42719382/62714766-92cc-4c84-bde2-05fdf5695bd3)

3.
Yes.

**Comment by amir20** [comment]
I really don't know since for me it works.  I am not sure of your configuration but something else is causing it.  

Your first error doesn't seem related to Dozzle. 

As I suggested in the comment above, try `flush_interval` to `-1`. I don't have any other ideas. If you can get me to reproduce it then it might be easier. 

Sorry.

**Comment by EricFROL** [comment]
Done, still with the issue...

This is my docker compose:
```
version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#     - /path/to/certs:/certs
    ports:
      - xxxx:8080
    environment:
      DOZZLE_REMOTE_HOST: ****
```

So I docker compose up that and get it working, and my caddyfile looks like this:

```
(other stuff)
xxxxxxx {
  reverse_proxy xxx.xxx.xxx.xxx:xxxxx {
    flush_interval -1
    header_up -Accept-Encoding
    header_down -x-webkit-csp
    header_down -content-security-policy
    }
  filter {
    content_type text/html.*
    search_pattern </head>
    replacement "<link rel='stylesheet' type='text/css' href='https://theme-park.dev/css/base/dozzle/aquamarine.css'></head>"
    }
}
```

I'm using Theme.Park custom css, thats why caddyfile looks that complex.

**Comment by amir20** [comment]
Why are you removing encoding? 😳 that's probably your problem.

**Comment by EricFROL** [comment]
What do you mean with encoding?

**Comment by amir20** [comment]
I haven't tested this but `header_up -Accept-Encoding` removes `text/event-stream` which could break. 

I know Caddy works just fine with `caddy reverse-proxy --from :9191 --to :8080` so I think you should start removing all headers until it breaks to find the culprit.

**Comment by amir20** [comment]
I tested with 

```
:2080

reverse_proxy :8080
```

It seems to work. I am not too familiar with theme-park so I suggest you don't use that.
