### ISSUE TITLE
json: cannot unmarshal object into Go value of type []releases.githubRelease

### ISSUE THREAD

**Issue by Ian-Drunkenson** [amir20/dozzle#2640]
Docker newest release on an ARM64/Armbian machine, fresh installation.

All went well and it was running some time but over night this happend and it stopped:

>level=info msg="Dozzle version v5.8.1"
level=info msg="Connected to 1 Docker Engine(s)"
level=info msg="Accepting connections on :8080"
level=warning msg="error reading releases: json: cannot unmarshal object into Go value of type []releases.githubRelease"
level=info msg="shutting down gracefully, press Ctrl+C again to force"

**Comment by amir20** [comment]
That's just a warning. Nothing should be broken. Right? GitHub was probably down.

**Comment by Ian-Drunkenson** [comment]
Dozzle exited by itself and in Portainer it showed a red broken heart with exit code 0. I restarted the container a few hours ago and up to now its still running.

**Comment by amir20** [comment]
Hmm. There is no timestamps so hard to guess what caused the exit. 

I'll see if I can fake a broken GitHub api and reproduce this. The code doesn't exit but maybe I don't see it. 

Exit status 0 means a clean shutdown so it might not be related to Dozzle.
