### ISSUE TITLE
more compact line height

### ISSUE THREAD

**Issue by gbrandt1** [amir20/dozzle#2644]
**Is your feature request related to a problem? Please describe.**
the distance between lines is too high for my taste. 
too much space is empty and ascii art in log files appears "striped".

**Describe the solution you'd like**
perhaps add a switch for "compact" layout?

**Describe alternatives you've considered**
or where can i adjust the CSS to have a more compact display?
or maybe CSS can be fixed on the client side?

**Additional context**

example:

![image](https://github.com/amir20/dozzle/assets/17267871/2dc6f84e-1c25-4258-b7db-7e715a4c76d3)

**Comment by amir20** [comment]
Hello,

Thanks for the suggestions. I have not gotten a whole a lot of requests about this. I think someone had asked for QR codes  https://github.com/amir20/dozzle/issues/2592 not being right. So I don't think many people need this. For me Dozzle is for reading logs so the little padding helps. 

However, if you think a lot of people would find this helpful, then I am open to PRs about it. I think what would make sense is a toggle in settings called "compact mode" vs "normal", similar to how gmail has that settings. You just need to know a little tailwind. 

You are other option is to find a browser extension that allows you to overwrite the padding.  I don't know of any good ones to be honest. I know Arc browser has something native.

**Comment by amir20** [comment]
Haven't heard back. Closing.

**Comment by kokojacket** [comment]
I also hope to improve this QR code scanning problem For example, add a toggle setting with no line spacing

**Comment by amir20** [comment]
This has been implement now since a few people asked for it.
