### ISSUE TITLE
No logs showing up

### ISSUE THREAD

**Issue by Explosion-Scratch** [amir20/dozzle#2647]
**Describe the bug**
No logs are showing up but my containers are.

**To Reproduce**
Open dozzle

**Expected behavior**
Logs are shown

**Screenshots**
Dashboard:
<img width="1712" alt="image" src="https://github.com/amir20/dozzle/assets/61319150/0e820c28-6a7f-4b16-a078-e864f786f0e2">

**Desktop (please complete the following information):**

https://github.com/amir20/dozzle/assets/61319150/c41e200e-c501-4fbd-a4ae-113645281c7c

- OS: Linux Arm 64
- Docker version:
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:26 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:26 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Browser & version: Arc 120
- Version: 6.0.0

**If applicable include logs with `--level debug` and browser logs**

**Comment by Explosion-Scratch** [comment]
Update: Found out it was AdGuard filtering the streaming log endpoint. Turned off AdGuard and it's fixed. Sorry guys!

**Comment by amir20** [comment]
Is this adhuard browser extension? I use the dns blocker and haven't seen this.

**Comment by Explosion-Scratch** [comment]
> Is this adhuard browser extension? I use the dns blocker and haven't seen this.

Yep. For some reason I can't find it in the logs but I turned it off and it started working again. I use AdGuad Home on Mac (with self-hosted DNS server as well)
