### ISSUE TITLE
Search using labels

### ISSUE THREAD

**Issue by LvargaDS** [amir20/dozzle#2648]
**Is your feature request related to a problem? Please describe.**
No, just missing possibility for my usecase.

**Describe the solution you'd like**
I would like to be able to search in containers according labels. I have some labels (i.e. **hostname=app.example.com** or keys like traefik.http.routers.appname.rule) attached to most of my containers.

I would like to search in container labels using values, or "key=value" pair.

**Describe alternatives you've considered**
Another solution for my usecase is to spawn dozzle with filter parameter for each "usual" subset of machines, which I use and use different instances of dozzle on different url addresse to show different docker containers.

**Additional context**
There seems to be large portion of labels now (including small html pages, links to icons, description, homepages, ...) when I start even small container. See:
```
docker run --detach --label skuska=ano traefik/whoami:latest  
docker ps --format "{{.Image}}: {{.Labels}}" | grep whoami
```

Sample output (manually changed format slightly):
```traefik/whoami:latest:
org.opencontainers.image.revision=87f25fc35b3e9051117dddfd11bbae5fbc986581,
org.opencontainers.image.source=https://github.com/traefik/whoami,
org.opencontainers.image.version=1.10.1,
skuska=ano,
org.opencontainers.image.created=2023-07-12T14:02:18Z,
org.opencontainers.image.description=Tiny Go webserver that prints OS information and HTTP request to output,
org.opencontainers.image.documentation=https://github.com/traefik/whoami,
org.opencontainers.image.title=whoami,
org.opencontainers.image.url=https://github.com/traefik/whoami
```

So there can be problem sending all labels in first stream event. Consider sending them separately and attach them to containers in second event. Also intelligent fuzzy search can have problem handling so much more data.

**Comment by amir20** [comment]
@LvargaDS just so I understand, you mean searching for containers using the fuzzy search text box right? 

I think it would be actually pretty easy to add this.  I use fuse.js with [extended search](https://www.fusejs.io/examples.html#extended-search) option.  Sadly, I don't think it supports `key=value` though.  I would just have to pass the lables and then you do things like `traefik.http.routers`. 

Is this what you mean?

**Comment by amir20** [comment]
I prototyped this really quick. You can try `amir20/dozzle:pr-2649`. 

`key=value` will not work.  Fuzzy search might match a lot of other containers by name but you can do exact match by prepending '. So like like `'foo`, will do an exact match for foo.

**Comment by LvargaDS** [comment]
Thanks for reply and looking into it. It works nice, through I was expecting to be able to search also using label key. On the other side, more reasonable is to be able to search only using label value and for sure, it is enough for my case.

Thanks. From my point of view, this feature is implemented.

**Comment by amir20** [comment]
Great. I'll release later today. 

Fuse.js only indexes text. It doest not allow for key/value pair. So if I was to index the keys, it wouldn't really be helpful as searching for a key would just display the items that have the key. Ideally, it would be `key=value`, which is not possible.

**Comment by amir20** [comment]
This is now released.
