### ISSUE TITLE
Cosmetic: Show nozzle itself as healthy

### ISSUE THREAD

**Issue by ramsnerm** [amir20/dozzle#2654]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To get a green checkmark next to the Dozzle log file entry as for the other where a heal check implementation is possible.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by amir20** [comment]
I don't understand the request. Try again?

**Comment by ramsnerm** [comment]
On the left side of the Dozzle page is the list of all available log files. If a container is healthy a green checkmark is shown. Next to Dozzle log file is no green Checkmark. I thought it is nice to set a green checkmark as well bcause Dozzle is running.

**Comment by amir20** [comment]
That's not what that check mark means. The check mark is only shown when health check is enabled. By default health check is not enabled.

**Comment by ramsnerm** [comment]
Is it possible to make an healtcheck for Dozzle? I did it for all my other containers with "wget/curl".

**Comment by amir20** [comment]
https://dozzle.dev/guide/healthcheck
