### ISSUE TITLE
Configurable date format of timestamp

### ISSUE THREAD

**Issue by masterwendu** [amir20/dozzle#2665]
**Is your feature request related to a problem? Please describe.**
The date format of the timestamp of a log message seems to take the language from the browser. 
In my case is this en-US, but I am from Europe and a dateformat MM/DD/YYYY is hard to read for me.

**Describe the solution you'd like**
I would like to have a UI setting with a text input to define the date format like for example: "DD.MM.YYYY"
Like there is a setting for 12 or 24 hours format.

**Describe alternatives you've considered**
An alternative would be to define it via an environment variable.

**Additional context**
![image](https://github.com/amir20/dozzle/assets/12148533/60c6aabf-021e-45e7-9bd4-12d80e5ceda5)

**Comment by amir20** [comment]
> In my case is this en-US, but I am from Europe and a dateformat MM/DD/YYYY is hard to read for me.

:) I never thought of that. 

I am not sure if you are familiar with javascript, but I use Intl.[DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) which doesn't support a custom format. Only a specific locale. So I don't think it would be easy to do that. Maybe a drop down to override the locale but I think that would be confusing personally?

**Comment by masterwendu** [comment]
Yeah a dropdown with locale wouldn´t be good.
But we could add a dropdown with dateformats and then use the corresponding locales:

MM/DD/YYYY -> en-US
DD/MM/YYYY -> en-GB
DD.MM.YYYY -> de-DE
YYYY-MM-DD -> en-CA

I tested the 4 with Intl.DateTimeFormat

**Comment by Nicokalak** [comment]
consider using https://momentjs.com/

**Comment by masterwendu** [comment]
> consider using https://momentjs.com/

Thanks for the tip but:

This is on the moment main page:
_Considering using Moment in your project?
There may be better modern alternatives.
For more details and recommendations,
please see [Project Status](https://momentjs.com/docs/#/-project-status/) in the docs._

So yeah, it would be ok to consider to use dayjs, but moment is not recommended.

**Comment by amir20** [comment]
@masterwendu That's pretty awesome. I didn't realize different locales change slashes and dots. I actually do the same thing things with time. I use `en-gb` for 24-hour style and `en-us` for 12 hour. 

When I get some time, I'll try it out today for date and use the ones you suggested. 

@Nicokalak momentjs is very outdated. Most functionalities can be done with browser. 

Dozzle's tries to have good out of the box defaults so I want to make sure I use built-in date formatters.

**Comment by amir20** [comment]
Try `amir20/dozzle:pr-2671` @masterwendu

**Comment by amir20** [comment]
This is released now. I also implemented a preview feature.

**Comment by EDIflyer** [comment]
Ooh absolutely brilliant!! 🥳

For some reason even though my PC is on en-gb (and I have UK English set in Chrome) I always got US-style dates which I found really confusing when trying to quickly glance at a log, esp if it wasn't obvious (when day was >12 so clearly not a month!) - being able to pick is a good solution.

I'm loving the new preview feature too 👍

![image](https://github.com/amir20/dozzle/assets/13610277/9ab32e47-4317-419a-8bd5-af8dbf3d0226)

**Comment by amir20** [comment]
Added long message in #2672 

I use javascript's `navigator.language` and always confused how these things are set. Good to know this is a good feature!

**Comment by masterwendu** [comment]
@amir20 great. Thanks for this super quick fix of my issue :smile: 
I updated and tried it. Works perfect :ok_hand:
