### ISSUE TITLE
Log search input box blocks content

### ISSUE THREAD

**Issue by IvanLi-CN** [amir20/dozzle#2679]
**Describe the bug**

<img width="1502" alt="image" src="https://github.com/amir20/dozzle/assets/30215105/65e55505-bbac-4f1f-a65e-6222f5226262">

I can't find any way to hide this input box but keep the search conditions. Maybe the search input box could float or be fixed at the top?

**To Reproduce**

1. Just search

**Desktop (please complete the following information):**

- OS: Mac OS
- Docker version 24.0.7
- Browser & version Arc (Chromium Engine Version 120.0.6099.199)
- Version v6.0.6

**Comment by amir20** [comment]
I think this works as expected. If someone is searching, then an area needs to be covered to show the search field. 

If I move the search to top, it will block the stats. So I think this is the best place to put it.

**Comment by IvanLi-CN** [comment]
I don't think stats are necessary when searching, but search results should be.

**Comment by amir20** [comment]
Hmmm, I looked at other browsers, (Arc, Safari, Chrome...) and they do put it up higher. I wouldn't be opposed to moving it higher. And I think you are right, when searching logs are more important than stats.

**Comment by amir20** [comment]
Try `amir20/dozzle:pr-2684`.  I think that's the highest I can move it.
