### ISSUE TITLE
In the 24-hour mode, midnight is represented as '24' rather than '00'

### ISSUE THREAD

**Issue by CruxH** [amir20/dozzle#2680]
**Describe the bug**
In the 24-hour mode, midnight is represented as '24' rather than '00'

**To Reproduce**
Adjust the time format setting to '24', enable timestamps, and review logs containing entries from midnight.

**Expected behavior**
Log entries from midnight are timestamped with '00' 

**Screenshots**

Issue:
![image](https://github.com/amir20/dozzle/assets/7459949/15a4472a-8ce6-481d-9015-ae556f15f1d1)

Same entry with time format set to '12':
![image](https://github.com/amir20/dozzle/assets/7459949/b66c208c-adc4-4d79-8a32-abffdb4903de)

**Comment by amir20** [comment]
This appears to be a bug with Chrome. 

https://stackoverflow.com/questions/60886186/intl-datetimeformat-shows-time-being-2459

**Comment by amir20** [comment]
Seems like using `hourCycle` should fix it. See #2685
