### ISSUE TITLE
Preview for settings - time format and long line wrap

### ISSUE THREAD

**Issue by CruxH** [amir20/dozzle#2682]
1. The snippet for a "very long message" appears short. On a large-resolution monitor with a moderately sized browser font, the message doesn't necessitate wrapping, making the 'wrap lines' toggle seemingly ineffective when enabled.

Here's the appearance with my current settings:
![image](https://github.com/amir20/dozzle/assets/7459949/9bac217b-2a31-4eab-adb8-6f8fb5faaa4a)

With the browser window set to half its original size, the wrapping capability is effectively showcased for the "very long message."
![image](https://github.com/amir20/dozzle/assets/7459949/da03deba-d6f6-46ed-bd39-de6dc9bcebfc)

2. The timestamps in the preview reflect the current system time. Therefore, when in the AM and setting the time format to '24', only the 'AM' tag is removed, making it challenging to demonstrate the actual conversion to the 24-hour format. Using dummy timestamps could effectively illustrate this conversion.

**Comment by CruxH** [comment]
> re: very long messages -- what would be the fix? I am not sure what to do? I could try putting a max width maybe. But also, I don't think it is enough of a problem to worry about it?

This isn't a real problem. Maybe just make paragraph longer?

**Comment by amir20** [comment]
Yea, the misalignment really bothers me too. I tried aligning Options to Display section but it looked really weird. I think this more relevant to you because you have a bigger screen. 

I am not sure of a better solution though.
