### ISSUE TITLE
Logs from disk query/issue

### ISSUE THREAD

**Issue by EDIflyer** [amir20/dozzle#2691]
I've got a logfile on disk that I'm streaming to make it available on Dozzle using the instructions (that I helped tweak 😂) at https://dozzle.dev/guide/log-files-on-disk.

To complicate things, this is a log file that I also email myself weekly (it's a script monitoring diskspace) and I delete it after it is emailed.

I noticed that it had stopped updating in Dozzle at the end of each week, I'm guessing due to the file being deleted (albeit a new one is created I presume it'll have a new inode id).  I've therefore tweaked my logging script to restart the docker container that streams the logfile to Dozzle each week once the new log is created.

The only issue I'm now noticing is that I get all the old ones also appearing, even though the logfile itself doesn't include them.  When I view the mounted volume in the container it also doesn't show them so it's like they're being cached somehow?

Dozzle appearance:
![image](https://github.com/amir20/dozzle/assets/13610277/b7f3432d-ca06-408a-9afb-99112a945e4a)

Contents of `/var/log/stream.log`:
![image](https://github.com/amir20/dozzle/assets/13610277/e72c1408-142e-48f2-bb3d-2727e360f69c)

**Comment by amir20** [comment]
I think this is to be expected because Docker has it own internal log database. It allows you to go back in time. I believe you need to remove the container or purge if you don't want to see the logs again.

**Comment by EDIflyer** [comment]
Ah OK, interesting - didn't realise that!

I've changed the script to stop & remove the existing container and recreate it from a docker compose file - that seems to have solved the problem.

When doing so I was interested to see the following which I hadn't noticed before -  it didn't seem to happen totally consistently though so I'm not sure what the criteria are for it being displayed?

![image](https://github.com/amir20/dozzle/assets/13610277/ab815a52-95f3-470a-9091-4d72993500a1)
![image](https://github.com/amir20/dozzle/assets/13610277/e3e7301b-bf34-4e7c-82ae-41601e8483cc)

It's a very nice feature though!  The one thing I might do is change the wording slightly - there's only a short countdown to quickly take in the message and I was looking for somewhere to click to get it to switch, I only realised after that it was actually click to cancel the move as it with automatically switch unless you cancel!

Would it perhaps worth rewording to "Dozzle found a similar container [id] that is running on the same host.  Will automatically switch to this container in [5, 4, 3, 2, 1] unless you click 'Cancel'"?

**Comment by amir20** [comment]
Ha nice. If the name of the container is the same then Dozzle will show that message.   

I would hope that after the first time the user learns, they won't be looking for the button anymore?

**Comment by EDIflyer** [comment]
Yes it's just I've had plenty with the same container name where it didn't seem to show it.

Re the wording- I just wonder if worth tweaking the text as the user doesn't actually need to do anything to switch?  The way it's currently worded makes it sound like you need to do something.

**Comment by amir20** [comment]
@EDIflyer I am ok with changing the text. The countdown part would be a little hard so maybe 

> Dozzle found a similar container [id] that is running on the same host. Will automatically switch to this container in  unless you cancel?

**Comment by amir20** [comment]
Also code is pretty easy to change if you want to send a PR. 

https://github.com/amir20/dozzle/blob/82765f4b680656856009a60bd2a927780c6ed196/locales/en.yml#L52

**Comment by EDIflyer** [comment]
Cool, will take a look @amir20

**Comment by amir20** [comment]
Closing. Will merge PR if you send it.

**Comment by EDIflyer** [comment]
Apologies for the delay @amir20 - finally got around to rewording as promised!
