### ISSUE TITLE
dozzle doesn't run if IPv6 is disabled on host system

### ISSUE THREAD

**Issue by mbsportcoupe** [amir20/dozzle#2692]
ERROR: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol

can you add a variable to disable ipv6 support on startup?

ie.: IPV6_DISABLE=1

**Comment by amir20** [comment]
I don't know if this is related to Dozzle. When do you see this error? It looks like the error is related to registry which is a Docker configuration and not Dozzle.

**Comment by mbsportcoupe** [comment]
The error came from Dozzle log on startup but turned out to be a dns issue. I replicated the behavior in another server also with ipv6 disabled and it started right up. my bad.
