### ISSUE TITLE
Mem usage / total memory

### ISSUE THREAD

**Issue by marcinwolosz** [amir20/dozzle#2693]
It would be perfect if you could add a feature to see how much memory we have and how much of it we're using. It would look something like this:

![memory](https://github.com/amir20/dozzle/assets/26607977/07c45cc5-c84e-471f-a3af-209315fc59c0)

You can get that info by api using `/info` endpoint or using `docker info` command. 

You can also provide an option to see even more docker stats somewhere

**Comment by amir20** [comment]
Dozzle doesn't know how memory there is. Only how much has been allocated which is why I didn't implement this.

**Comment by marcinwolosz** [comment]
But is there a way to make dozzle know how much memory is there? I’m able to check it with API or command line, so maybe there is a chance

**Comment by amir20** [comment]
If you have the technical expertise, I think it would be fairly easy to test. PRs are welcomed. :)

**Comment by amir20** [comment]
I am closing this since I don't have a lot of time to work on it.
