### ISSUE TITLE
Support LogFmt log message highlighting

### ISSUE THREAD

**Issue by offbyone** [amir20/dozzle#2695]
**Is your feature request related to a problem? Please describe.**
In the spirit of #920, which adds support for JSON logs, please support highlighting LogFmt messages.

Messages of this format: 

```
Timestamp="2024-01-11T22:52:32.935644Z" InstrumentationScope="A::Controller" SeverityText="INFO" Body="start" TraceId="1a5effcaeddc7e9a09d94750ac3c5c0b" SpanId="868ad5b2c9e42977" TraceFlags="01" a.dot-scoped-key="development" span.kind="internal" service.name="my-service" service.version="development" deployment.environment="development"
```

I'd like the ability to format the message to enhance readability and searching

**Describe alternatives you've considered**
I could figure out how to rewrite our service log ingestion framework to handle Json logs :D 

**Additional context**

**Comment by amir20** [comment]
Can you explain what you mean with "support highlighting LogFmt messages"? Is there a javascript parser that can be used for this? 

I think it might be hard to do unless I do the logic myself.

**Comment by offbyone** [comment]
I apologize for underspecifying it. It's probably best to point at a [specification](https://brandur.org/logfmt) and an [implementation](https://github.com/go-logfmt/logfmt)

It's not json, it's an ingestion format supported for Splunk

**Comment by amir20** [comment]
Ah interesting there is a go library for unmarshalling. Perhaps, Dozzle can read it, convert it to an object and send it over as json which would be displayed like JSON?

**Comment by offbyone** [comment]
That sounds like a pretty good solution!

**Comment by amir20** [comment]
Seems to work pretty awesome

**Comment by offbyone** [comment]
It _does_!

LogFmt is so loose that the formatter definitely catches some lines that are not:

```
I, [2024-01-16T21:05:29.368867 #1]  INFO -- : Refreshing Gem list
I, [2024-01-16T21:05:36.158010 #1]  INFO -- : listening on addr=0.0.0.0:9393 fd=9
I, [2024-01-16T21:05:36.165830 #1]  INFO -- : master process ready
I, [2024-01-16T21:05:36.174222 #31]  INFO -- : worker=0 ready
I, [2024-01-16T21:05:36.175946 #32]  INFO -- : worker=1 ready
```

These logs are not, strictly speaking, logfmt, but the parser is picking them up:

![Image](https://github.com/amir20/dozzle/assets/181693/e97ddebe-955f-4961-b82d-8bce2fe9e57d)

That, however, is _not_ a dealbreaker; I'd happily handle some janky startup messages in exchange for the parser for the rest of the application's lifecycle.

**Comment by amir20** [comment]
Yea, oops. I broke something. Need to revert. I was trying to do a feature branch.

**Comment by amir20** [comment]
Go let's try again with `amir20/dozzle:pr-2705`

**Comment by offbyone** [comment]
That version lost the logfmt parsing on lines that _were_, although it's not misparsing the `I,` lines.

`Timestamp="2024-01-16T21:33:48.312840Z" InstrumentationScope="OpenTelemetry" SeverityText="INFO" Body="Instrumentation: OpenTelemetry::Instrumentation::Rails was successfully installed with the following options {}" service.version="development" deployment.environment="development"` is just coming up as an unparsed line.

**Comment by amir20** [comment]
Ahh hold on. I am having `git` issues.

**Comment by amir20** [comment]
Oh I think something is wrong with logfmt implementation. Plain text is also parsed as valid logs. Which is why it is breaking. Hmm I am not sure if there is a way around it if it treats all logs as logfmt.

**Comment by offbyone** [comment]
Like I said, I'd rather see a few plaintext logs get mangled. Especially if there's a way I can get at the raw line somehow.

**Comment by amir20** [comment]
Alright third time is the charm I hope. Try again `amir20/dozzle:pr-2705`. I check for all valid `key/value` pairs now. So I think this a good compromise.

**Comment by amir20** [comment]
Nice! Need to fix performance issues before releasing.

**Comment by offbyone** [comment]
I really appreciate this. Thanks!

**Comment by amir20** [comment]
It works out for me because all Go logs with logrus are in this format.

**Comment by amir20** [comment]
This was a pretty awesome idea. Half of my logs are now supporting this feature. 

I guess the only "bug" i have found is that the copy/paste feature will copy as json not logfmt.
