### ISSUE TITLE
Container exec support

### ISSUE THREAD

**Issue by mhkarimi1383** [amir20/dozzle#2696]
**Is your feature request related to a problem? Please describe.**
Just needed a simple exec option in UI using `ContainerExecCreate` and `ContainerExecStart` in docker client in go

**Describe the solution you'd like**
Shell Exec option in UI

**Describe alternatives you've considered**
Using another tool :(

**Additional context**

**Comment by amir20** [comment]
If you mean docker exec to run a command, then that's a very hard thing to build. I don't think Dozzle should have that since there are so many other tools that already do.

**Comment by amir20** [comment]
Not planning to support this so closing.
