### ISSUE TITLE
Thinner scrollbars & double scrollbar?

### ISSUE THREAD

**Issue by mnpenner** [amir20/dozzle#270]
There's not a ton of space if you put 2 or 3 logs up side-by-side. May I suggest a few improvements?

1. Have a [hamburger] button to hide the dozzle/sidebar menu
2. Make the [scrollbars thinner](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp)
3. There's a double scrollbar on the far right. I think the outer one is for the whole window/html but it doesn't need to be there at all.

![](https://mpen.xyz/share/2020/02/phpstorm64_2020-02-01_18-33-41.png)

Great project BTW. I was looking for a nice simple alternative to the other Docker UIs out there and this is perfect! So thank you.

**Comment by amir20** [comment]
Thanks for the feedback! I have honestly never looked at Dozze on Windows so it makes sense for some of these improvements. 

1. I have been working on the hamburger menu for a while. But been busy. I'll try to finish it up. 
2. I am trying to not override the default UI for the operating system as that can really piss people off. :) On mac, it's auto hidden. So I'll have to think of this one to see if there is any easy way to do this. 
3. This is a bug. I have spent so much time fixing it on mobile and mac. I haven't found a way to disable scroll bar on window :( I'll keep looking. I'll try get a virtual machine for windows and test it. 

What operating system are you using so I can test it? 

Thanks again. If you see any quick fixes then send me a PR. The code is pretty simple in Vuejs.

**Comment by mnpenner** [comment]
> What operating system are you using so I can test it?

Windows 10. Screenshot is from Chrome.

Scrollbars are a little prettier in Firefox but still too wide IMO.

![](https://mpen.xyz/share/2020/02/firefox_2020-02-01_20-04-41.png)

> I am trying to not override the default UI for the operating system as that can really piss people off.

Haha, yeah I get that. I normally don't like when websites mess with the scrollbars but in rare scenarios it can be nice. You could make it a configuration option; you've already got font size in there.

To fix the double scrollbar issue I think you just need to remove the `overflow-x` and `overflow-y` from `html`

![](https://mpen.xyz/share/2020/02/firefox_2020-02-01_20-09-40.png)

**Comment by amir20** [comment]
Thanks @mnpenner . That helps a lot. I was able to reproduce it using VirtualBox on Mac. Let's see what I can do. 

Interestingly, Dozzle doesn't work in Edge at all. 🤨Will have to fix that too.

**Comment by mnpenner** [comment]
I wouldn't worry *too* much about Edge; Edgium is out now and that works fine.

![](https://mpen.xyz/share/2020/02/firefox_2020-02-02_12-36-12.png)

**Comment by amir20** [comment]
Thanks. I realized that after I saw that it was the older version. 

So there is something I try to do which might affect this logic a little. When there is only one active container, I try to just put everything in `<body>`. Only when multiple containers are open, the double scroll shows up because then each container will need it's scrollbar. 

So I'll have to figure out how to apply your css above only when `activeContainers.length > 0`. I think I have a way of doing it though by watching how many containers are open.

**Comment by amir20** [comment]
@mnpenner here is what I changed and looks like to be working in Chrome for windows and mac. Haven't tested in FF. 

1. Added `overflow` fixes to `html`. It looks to have worked. 
2. Created a new setting option called "smaller scrollbar" defaulting to false. I noticed that on Mac it would overtake the default behavior and always add the bars. This was not the desired behavior for me. Even though Gmail seems to do it. For now, I disabled it for default. 
3. Added the code you provided for scrollbar only when the flag is enabled. 

`v1.20.19` should have this deployed. Give it a try and let me know. Next week I can try the hamburger again.

**Comment by amir20** [comment]
https://github.com/amir20/dozzle/releases/tag/v1.20.19 has been released.

**Comment by mnpenner** [comment]
Looks great! Thank you!!

![](https://mpen.xyz/share/2020/02/2020-02-03_20-46-21.png)

**Comment by amir20** [comment]
Great! I am still working on the collapse functionality.

**Comment by amir20** [comment]
@mnpenner #274 adds collapsable menu. It will be live on `v1.20.20`
