### ISSUE TITLE
Show all containers on 1 single page

### ISSUE THREAD

**Issue by discofris** [amir20/dozzle#2700]
**Is your feature request related to a problem? Please describe.**
When having lots of containers, I only see 15 per page. Would be great to have an option to show *all* my containers on 1 single page. 

**Describe the solution you'd like**
A simple button "All", next to the page numbers.
Would be a great feature when using the multiple hosts option.

Simple example:

![dva-4868](https://github.com/amir20/dozzle/assets/6281711/42b2bffa-29ae-4d9e-b24f-76c84b4503ae)

**Comment by amir20** [comment]
The reason this is not an option is performance. Each of those bar graphs consume a lot of CPU and people were saying their CPU was close to 100%. So I had to introduce pagination.

**Comment by discofris** [comment]
Pagination is fine, but just an extra button "Show All".
And a _Click at your own risk_ warning?

**Comment by amir20** [comment]
I am curious, can you try `amir20/dozzle:pr-2701`? I set pagiunation to 1000. What does your CPU look like?

**Comment by discofris** [comment]
Dozzle via my Chrome (only 1 single session/tab/exe):

![dva-4871](https://github.com/amir20/dozzle/assets/6281711/72758161-da4f-4f64-bb3c-71a42d3b33a0)

Similar behaviour in Edge:
![dva-4872](https://github.com/amir20/dozzle/assets/6281711/7457fa98-7981-46e0-b678-a5dc669e3c62)

Dozzle:
![dva-4869](https://github.com/amir20/dozzle/assets/6281711/b25a699e-87ab-484d-a684-f13414acbfcd)

I fully understand your point now ;-).

So pagination in combo with a 'Show All' (pagination 1000?) wouldn't be clever ... ?
Or maybe a Docker environment option which would set pagination to 1000? That way we have choice.

**Comment by amir20** [comment]
What's happening in those screenshots? I don't see a high CPU. Or are you pointing something else out

**Comment by discofris** [comment]
CPU percentage around 7-10%. Not really that high CPU usage. 
I guessed that's what you meant by high?

**Comment by amir20** [comment]
Oh that's not that bad. Some people were saying 60%. I guess it depends on how active these containers.

**Comment by discofris** [comment]
When my Chrome tab with Dozzle is not "visible" (not active in the foreground because I'm typing this reply on github.com on another tab), it consumes more: around 15-18% CPU.
When switching back to my Dozzle page, it goes down again:8-10%CPU.
The CPU/Mem markers on your Dozzle page are quite impressive and accurate! Explains the CPU usage ;-)

**Comment by amir20** [comment]
I think when I get a chance I'll just make the page size configurable with a drop down.

**Comment by amir20** [comment]
Merged for now. Going to releaser.

**Comment by discofris** [comment]
Many thanks @amir20 !
I'm on Lenovo Thinkpad Core i7 (Windows)
