### ISSUE TITLE
pinned container can not redirect automatically

### ISSUE THREAD

**Issue by zqxvip** [amir20/dozzle#2704]
**Describe the bug**
pinned container can not redirect automatically

**To Reproduce**

1. pinned some container
2. restart container

- OS: centos 8
- 24.0.7
- edge
- Version 6.0.8

**Comment by amir20** [comment]
That's weird. The logic has nothing to do with pinned. Is it happening consistently?

**Comment by amir20** [comment]
So I tested this. I don't think it has anything to do with pinned. Stopping containers and starting again won't redirect since it's the same container. Redirect looks for containers with different ids. I tested with pinned at it works.

**Comment by zqxvip** [comment]
If I don't refresh the webpage.It looks like this ↓
![image](https://github.com/amir20/dozzle/assets/7312051/3158c715-6a83-4e1f-8184-b5823f73d2d4)

**Comment by amir20** [comment]
Hmm that looks like a different bug. But I can't reproduce it. How are you seeing this? 

I am doing...

```
docker run -d --name test ...
docker stop test
docker start test
```

I see consistently one container with test.

**Comment by zqxvip** [comment]
I will first delete a container and then create a container with the same name.
The old version I used before was able to automatically redirect.
Maybe it's 6.0.2. I can't remember clearly.
