### ISSUE TITLE
Add the ability to set/force a default language

### ISSUE THREAD

**Issue by Impact123** [amir20/dozzle#2706]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I want to be able to set/force a default language. A global option should be available for people not using authentication.
For others an option before logging in and in the user setting might make sense.

**Describe alternatives you've considered**
-

**Additional context**
Dozzle seems to use the browser's main language (which isn't necessarily english) but for technical things english just makes more sense.

**Comment by amir20** [comment]
Yea I think this makes sense.

**Comment by amir20** [comment]
This was added in #2708 but got some bugs.

**Comment by amir20** [comment]
You can test with `amir20/dozzle:master`

**Comment by Impact123** [comment]
Thanks, this part seems to work fine so far. I couldn't see any bug(s) in my brief test.

**Comment by amir20** [comment]
The but was minor but the default was empty so I changed it to `Auto`.

**Comment by amir20** [comment]
Should be fixed now. Going to release today.
