### ISSUE TITLE
glances docker logs

### ISSUE THREAD

**Issue by adamaen87** [amir20/dozzle#2714]
Hello,
since version 6.0.8 i don't have any logs with the "glances" docker container, pretty sure it was working with 6.0.7.
Thanks.

**Comment by amir20** [comment]
Can you find exactly the version this broke? Because nothing major changed in that version.

**Comment by amir20** [comment]
I see now. Glances uses ansi colors. Related to #2639. I am not sure if I will add support for this yet.

**Comment by amir20** [comment]
So I went back all the way to version 5.7. It never worked for me.

**Comment by adamaen87** [comment]
i 'm testing and let you know.

**Comment by adamaen87** [comment]
Ok sorry i tought it was working before... i also try revert back glances version.
Thanks.
