### ISSUE TITLE
Ability to send notifications to discord webhook

### ISSUE THREAD

**Issue by toto99303** [amir20/dozzle#2715]
Hello, I love how simple and effective Dozzle is.
However it would be really beneficial if we had an option to tie a discord webhook and be able to receive notifications upon WARNING or ERROR messages in the docker logs. It could be done as a simple ON/OFF switch for each docker and level of notification.

I've searched the web and there is no single solution for that.
Thanks for your time!

**Comment by amir20** [comment]
See #2614. The hook isn't a problem, it's processing the logs which someone else is working on. 

Closing this as duplicate.
