### ISSUE TITLE
Username and password is not working

### ISSUE THREAD

**Issue by jay-ox** [amir20/dozzle#2716]
Hello,

When we're running docker with username and password, the container is going in restart mode, without username and password, it is working fine, below is the command and snapshot for the same.

cmd : docker run -dit --name monitoring -dit --volume=/var/run/docker.sock:/var/run/docker.sock -p 1000:8080 amir20/dozzle:latest --username "admin" --password "0156ZmF4yVAumuYabdhg"

Result: FATAL[0000] Using --username and --password is removed on v6.x. See https://github.com/amir20/dozzle/issues/2630 for details. 
![dozzle error](https://github.com/amir20/dozzle/assets/108863714/d0ec02f6-e58e-4324-a93b-1214dae29a0c)

**Comment by amir20** [comment]
Did you read the error? It tells you why it's failing. See the issue to use the new auth mode.
