### ISSUE TITLE
Dozzle container Login with ID and password got disabled.

### ISSUE THREAD

**Issue by nrupad** [amir20/dozzle#2726]
**Describe the bug**
Dozzle container Login with ID and password got disabled, when we run the container it gets into exit state all of sudden.
-- To run the dozzle container we need run without applying ID Password, which is no more secure without that. Till now it was working on ubuntu 22 but since last week it's failing to start a dozzle container.

**Screenshots**
Attaching the screenshot for your reference.

![image](https://github.com/amir20/dozzle/assets/98634165/15c73e41-7dc6-48b8-a313-b24a8c50cbf6)

**Comment by amir20** [comment]
Did you read issue #2630? You need to follow instructions there to use the new auth model.

**Comment by nrupad** [comment]
New auth method doesn't support ID Password support
