### ISSUE TITLE
File Based User Management: documentation clarification

### ISSUE THREAD

**Issue by reiner2** [amir20/dozzle#2738]
The File Based User Management documentation, here:
https://dozzle.dev/guide/authentication

Suggests to run:
`echo -n password | shasum -a 256`
or respectively 
`echo -n 'secret-password' | sha256sum`

On:
`uname -a`
`Darwin <> 23.3.0 Darwin Kernel Version 23.3.0: <> RELEASE_X86_64 x86_64`, OS 14.x

On:

`uname -a`
`Linux <> 6.5.11-linuxkit  x86_64 x86_64 x86_64 GNU/Linux`, Ubuntu 20.04 LTS

the above generates:
`5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  -`

Note the excess `  -`  

Appending `| cut -d' ' -f 1` like:
`echo -n password | shasum -a 256 | cut -d' ' -f 1`

`echo -n 'secret-password' | sha256sum | cut -d' ' -f 1`

`5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8`

Note the absence of excess Note the excess `  -`

Helps with the copy&paste

**Comment by amir20** [comment]
What's the question? You could also do `echo -n password | shasum -a 256 | head -c 64`. Feel free to send PR for docs if it is unclear.

**Comment by reiner2** [comment]
Wasn't really a question -- just a mere suggestion 
Agreed  `| head -c 64` kind of like does almost the the same

`5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8<machine name>:~ <user`$`

 Touché
 As requested will do a FR for the docks

**Comment by amir20** [comment]
Closing.
