### ISSUE TITLE
[Feature Request] Fuzzy search in mobile UI

### ISSUE THREAD

**Issue by pzerone** [amir20/dozzle#2744]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to search the logs for specific keywords other than to use the built in find of the browser. 
**Describe the solution you'd like**
I propose a fuzzy search feature that can filter the logs in real-time and show the ones that gets matched in the log view.
Is this something that can be achieved or will it be out of scope for the project?

**Comment by amir20** [comment]
This is already implemented. See the video.

**Comment by pzerone** [comment]
Heya, thank you for the fast reply. I think the logs page could use a search bar just like the container search. I mostly use dozzle from my phone on the go and that red and blue menu is not available in mobile UI and pressing Ctrl+F is not an option there.
![IMG_20240202_091630](https://github.com/amir20/dozzle/assets/46400271/c5a5e4e3-3500-4231-84f6-f78eb607a30a)

What do you think?, And thank you for building this amazing program!.

**Comment by amir20** [comment]
So I guess the real feature request is to add search to mobile view? Because it does work just fine on desktop, right?

**Comment by pzerone** [comment]
One could say that. But instead of implementing the same feature twice for 2 UIs, how about just adding an always visible search bar on the middle, near the memory usage part of the UI with the ^F hint. That will make it easy for mobile UI to tap on the bar to start searching, all while desktop UI can still trigger it using ^F or by clicking on the bar

**Comment by amir20** [comment]
It would be the same feature. It's just hidden right now on mobile. 

So this has been discussed a few times in the past. I have carefully selected which features are shown on mobile. The space in mobile is very small. I have intentionally hidden the drop down to reduce the complexity. 

I think to do what you suggested will require more work. See this https://github.com/amir20/dozzle/issues/2561#issuecomment-1843952628 which I try to compare which features should be available on mobile. 

Realistically, not all features should be available on mobile as it would really complicated the UI and I am trying to keep it simple.

**Comment by pzerone** [comment]
Very much understandable. I just found out that switching the phone into landscape mode shows the menu and is usable. it's just the matter of inconvenience, typing in landscape mode. If you don't mind, keep this feature request as a low priority one. If not, happy to close this issue.

**Comment by amir20** [comment]
There is a few times I would personally find search useful. I'll keep it open for now. I don't think it makes sense to enable the drop down but maybe a better solution in the future that is more compact.

**Comment by amir20** [comment]
Going to close this. Not much interest from other folks.
