### ISSUE TITLE
Eek - possibly spoke to soon - have found a bug the other way round now I'm afraid!!

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2749]
Eek - possibly spoke to soon - have found a bug the other way round now I'm afraid!!

Screen recording below (and I promise this is definitely on `master`!):
1. Select running container
2. 2-dot menu and select Stop
3. Container stops, name goes grey and goes to bottom of list
4. 2-dot menu correctly switches Stop to Start
5. Refresh page
6. Container now jumps back up to main running list and name switches back to white, despite container still being stopped. 2-dot menu now shows Stop rather than Start (I'm guessing tied in to the container name being in white rather than grey?). In the video I then restarted the container from the menu just to show it did come back up.

![Animation](https://github.com/amir20/dozzle/assets/13610277/088d1172-2591-4069-99bc-ea9476e036a9)

_Originally posted by @EDIflyer in https://github.com/amir20/dozzle/issues/2740#issuecomment-1924883418_

**Comment by amir20** [comment]
Looks like I fixed this before then broke it again. Should be fixed now.

**Comment by EDIflyer** [comment]
Happy to confirm all looks good on latest version on `master` - top container it drops down, goes grey and action button changes to start 👍 

Whilst we're on the topic - any thoughts re the one I have that isn't running but exists purely for Watchtower checks?  It's not in an 'exited' state but a 'created' one

![image](https://github.com/amir20/dozzle/assets/13610277/c7f773ac-d7a5-4d65-a539-f44fd2a476d7)
![image](https://github.com/amir20/dozzle/assets/13610277/b2c5ed27-6cdb-436a-94d6-dba3e684cace)
![image](https://github.com/amir20/dozzle/assets/13610277/07341180-5d83-460c-84a7-d691c492463d)
![image](https://github.com/amir20/dozzle/assets/13610277/80432262-38e2-4a87-900c-bdff37c7a4bb)
![image](https://github.com/amir20/dozzle/assets/13610277/18046202-848e-4fdb-8b82-78d04b8cf5e9)

It's not a biggie, but for one that shows 'Container stopped' and has 'Start' in the menu and is listed at the bottom I thought it would be greyed out too as not actively running?

**Comment by amir20** [comment]
@EDIflyer can you do `docker ps --format "{{.ID}} {{.Image}} {{.State }}"` and tell me what state that container is in?

**Comment by EDIflyer** [comment]
@amir20 had to add a cheeky wee `-a` to that but looks like it is 'created' as per the screenshots & Portainer...

> 0c77fc39ac6b squidfunk/mkdocs-material:latest created

**Comment by amir20** [comment]
I am a little stumped because `created` is not even an event listed in https://docs.docker.com/engine/reference/commandline/system_events/

So how are you doing this again? How does a container get into the `created` state?

**Comment by EDIflyer** [comment]
Oh wow, interesting! This is the docker-compose I'm using...
``` yaml
version: '3'
services:
  mkdocs-checkforupdates:
    container_name: mkdocs-checkforupdates    
    image: squidfunk/mkdocs-material
    restart: "no"
    network_mode: none
```

I'm just adding that as a stack and running it.  When you first run it then it just exits but then after future docker restarts it seems to just sit as created.

I've found a bit more mention of it:
https://stackoverflow.com/questions/43734412/what-does-created-container-mean-in-docker
https://docs.docker.com/engine/reference/commandline/container_create/
https://www.baeldung.com/ops/docker-container-states#1-created

**Comment by amir20** [comment]
Thanks those links help. So what do you think Dozzle should do? If it is not running, there is no log and I would expect it to not even show up, right?

**Comment by EDIflyer** [comment]
It currently shows as grouped with the other stopped containers (and is removed if you toggle off showing stopped containers) so I'd just make the text grey like the other stopped containers.  It does show up in the `docker ps -a` so personally I'd still expect it to be showing in Dozzle - esp as the start command from the two-dot menu _does_ work on it so it's pretty handy to have it listed 😃

**Comment by amir20** [comment]
That's true. I'll have to play with `docker create` to see if I can get something in this state. Have you found how to go from running -> created state? Is that even possible? Or can it only go one direction like created -> starting -> running?

**Comment by EDIflyer** [comment]
I'm not sure TBH!  I've got a couple of servers with a similar setup and both have that mkdocs container above just sitting as created - I think it might be after Watchtower has pulled a new image for them?  As if I make them fresh they just show as exited, same if I restart the docker daemon, so maybe it's Watchtower replacing the image in the background on a stopped container that does it??
