### ISSUE TITLE
Docker image not compatible with arm32v6

### ISSUE THREAD

**Issue by BubiDevs** [amir20/dozzle#275]
Hi all,
the project seems very good! I want to use it on my Raspberry server, but I cannot do it because the docker image is not `arm32v6` compatible.

I tried to fork the repo, modify the Dockerfile to use a `arm32v6/alpine:latest`as base image but it doesn't work.

## Problem 1: build image failed from within the nozzle folder

The first problem that I got is that I was unable to build the image from within the repo folder. The steps that I followed are the following:
 
1. Create a new Dockerfile and use `arm32v6/alpine:latest` as base image
2. Build the image locally:

```
cd dozzle
docker build -t bubidevs/dozzle:latest -f Dockerfile-arm32v7 .
```

Here I got an error on the last build step:

```
Step 7/8 : COPY dozzle /
COPY failed: stat /var/lib/docker/tmp/docker-builder446079037/dozzle: no such file or directory
```

## Problem 2: image built but not working

To solve the issue, I went back outside the `dozzle` folder and built the image in this way:

```
cd ..
docker build -t bubidevs/dozzle:latest -f dozzle/Dockerfile-arm32v7 .
```

In this way I was able to build the image, but when I try to create a container, it fails with this error:

```
ERROR: for dozzle  Cannot start service dozzle: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/dozzle\": stat /dozzle: no such file or directory": unknown
```

Could you please help me?

Many thanks in advice!

**Comment by amir20** [comment]
Hi @BubiDevs,

Building for arm is not as simple as using `arm32v6/alpine:latest`. You also have to compile for arm. Which explains why you are getting the error. `dozzle` binary is built with goreleaser and goreleaser currently don't support any multi-arch building for Dozzle. 

Good news is that all binary for different architectures are already built and pushed to Github.  You can go to [releases section](https://github.com/amir20/dozzle/releases/tag/v1.20.19) and download `ARM` binary. Extract the `*.tar.gz` file and just run with `./dozzle`. 

I also have a RPi+ which works fine this way. 

I won't be supporting mult-arch docker images until it's out of experimental. It also seems it doubles the size of docker image so that might be annoying for some folks.

**Comment by BubiDevs** [comment]
Hi @amir20, many thanks, I got the point!

I created a new `Dockerfile` that downloads the binary for the `arm32v6` architecture, and it works properly! :)

I post it here if someone will need it.

```
FROM arm32v6/alpine:3.7 as certs
RUN apk --update add ca-certificates wget tar bash

# Download dozzle binary built for arm32v6
RUN wget --output-document=dozzle.tar.gz -q https://github.com/amir20/dozzle/releases/download/v1.20.19/dozzle_1.20.19_Linux_ARM_32-bitv6.tar.gz 
RUN tar -xvf dozzle.tar.gz
RUN chmod +x dozzle

FROM scratch
ENV PATH=/bin
ENV DOCKER_API_VERSION 1.38
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=certs dozzle /

ENTRYPOINT ["/dozzle"]
```

You can also find the image on Docker Hub as [bubidevs/dozzle](https://hub.docker.com/repository/docker/bubidevs/dozzle).

Thanks a lot for the clarification and for the great project! 🚀

**Comment by amir20** [comment]
Sounds good. This project is regular updated so your docker images will be stale very soon. The right approach is for me to also push multi-arch images. I will wait until docker provides that natively.

**Comment by YouveGotMeowxy** [comment]
@BubiDevs TY for making this dockerfile. Is there a way to get it to use the latest dozzle version w/out hand editing the dockerfile each time? (sorry, I'm new to all of this).

**Comment by BubiDevs** [comment]
> @BubiDevs TY for making this dockerfile. Is there a way to get it to use the latest dozzle version w/out hand editing the dockerfile each time? (sorry, I'm new to all of this).

Hi @YouveGotMeowxy! Currently is not possible to get always the latest release, because the bin files are always versioned (like `dozzle_1.20.21_Linux_ARM_32-bitv6.tar.gz`).

Maybe we can ask to @amir20 to also update a sort of "latest version" file and we can get that file instead of the fixed version inside the Dockerfile. Could be possible @amir20?

**Comment by amir20** [comment]
Hello. I checked with goreleaser to see what options it gives me. The default settings is to add version to everything and I like that option to make it clear. 

Good news, I have been working on a publish method using `docker xbuild` and I think I should have a multi-arch docker images published this week. Stay tuned.

**Comment by STaRDoGG** [comment]
As always, excellent work on this @amir20 , much appreciated. =)

**Comment by amir20** [comment]
Hi folks, 

I am hoping you guys can try out my latest test at [Docker hub.](https://hub.docker.com/r/amir20/test/tags). It is published as `amir20/test` which has a multi-arch format. 

<img width="1237" alt="Screen Shot 2020-03-17 at 4 22 59 PM" src="https://user-images.githubusercontent.com/260667/76910563-96dbd480-686b-11ea-90ee-1b13dd99ff0b.png">


```
docker run --volume=/var/run/docker.sock:/var/run/docker.sock -it -p 8080:8080 amir20/test
```

Can you try this on different architectures? My initial testing shows that it works on ARM and AMD64? 

Do you think I need any other architectures besides arm64, arm32 and amd64?

**Comment by STaRDoGG** [comment]
@amir20 Looks good! I just tested the `/test` version on my Docker Desktop (Windows), and on my Raspberry Pi 3 B+, and it's working great on both. Not a hitch.

Those architectures seem to cover everything I would use; I'm not sure about anyone else, lol.

**Comment by BubiDevs** [comment]
Hi @amir20, I tested the image on my Raspberry Pi 3 and it works properly!

Many thanks for this great update! 🚀

**Comment by amir20** [comment]
That's great. Thanks both for testing. I have updated the code and starting to test the new github actions. Bad news is that it takes 20 minutes to do a multi-arch push. 💩But it works!

**Comment by amir20** [comment]
Going forward with `v1.21.1` all build are multi-arch. One downside is that I no longer need goreleaser so I removed it. But that means I won't have official releases.

Not sure anybody would ever need releases because most people used docker anyway. However, the changelog is lost now. I have to figure out how to get that back.

**Comment by modparts** [comment]
Hi @amir20 ;

Just letting you know that the amir20/test is running perfect on my pi 4 8GB with Raspbian OS 64 beta

**Comment by amir20** [comment]
This issue is old now. You don’t need to use amir20/test anymore. All builds are multi arch.
