### ISSUE TITLE
DOZZLE_TAILSIZE and DOZZLE_KEY removed?

### ISSUE THREAD

**Issue by 825i** [amir20/dozzle#2756]
**Describe the bug**
I set this up on Unraid like many other people but with version 6.32x I am now getting this error in the log:

```
time="2024-02-06T13:12:53Z" level=warning msg="Unexpected environment variable DOZZLE_TAILSIZE"
time="2024-02-06T13:12:53Z" level=warning msg="Unexpected environment variable DOZZLE_KEY"
time="2024-02-06T13:12:53Z" level=info msg="Dozzle version v6.2.1"
```

So these two flags are no longer supported? Should I remove them from the Unraid config?

- OS: Unraid
- Docker version: 20.10.24, build 297e128
- Browser: Chrome Based

**Comment by amir20** [comment]
Yup. Those are no longer used.

**Comment by aalencia** [comment]
Ah good to know.  Who updates unraid's version?  just curious :). I just installed which led me here.

time="2024-02-16T08:08:38Z" level=warning msg="Unexpected environment variable DOZZLE_KEY"
time="2024-02-16T08:08:38Z" level=warning msg="Unexpected environment variable DOZZLE_TAILSIZE"
time="2024-02-16T08:08:38Z" level=info msg="Dozzle version v6.2.4"
time="2024-02-16T08:08:38Z" level=info msg="Connected to 1 Docker Engine(s)"
time="2024-02-16T08:08:38Z" level=fatal msg="Could not find users.yml file at /data/users.yml"

**Comment by aalencia** [comment]
I feel naked without dazzle ;)
