### ISSUE TITLE
Higher idle CPU consumption since 6.2.x

### ISSUE THREAD

**Issue by spasche** [amir20/dozzle#2765]
**Describe the bug**

Since I updated to version 6.2.x I noticed that dozzle is now in the top CPU consumers of all the containers on my system.
The screenshot below shows the cadvisor CPU consumption of the dozzle container, measured while dozzle is not accessed on its web interface.
Before the 6.2.0 release, the CPU consumption was almost 0 when dozzle is not in use.

I guess this might be related to #2740, which collects stats in the background?

**To Reproduce**

Update from 6.1.1 to 6.2.2. and measure CPU consumption without accessing the web interface.

**Expected behavior**

I'd expect dozzle CPU consumption to be near 0 when not in use, like it was on 6.1.x

**Screenshots**

![image](https://github.com/amir20/dozzle/assets/105751/047d1f79-0b25-412d-8217-f109930e262f)

**Comment by amir20** [comment]
How many containers do you have?

**Comment by spasche** [comment]
```
docker ps | wc -l
109
```

**Comment by amir20** [comment]
Ah I have tested with 50. Yea, with 100s of containers it would increase CPU. But this comes at user value to processes CPU and memory usage. Which is something I personally use to understand why containers exited and what was their memory usage without having Dozzle open. 

Let me think if there is a better way to do it to reduce CPU. I wish Docker would just give me all container stats with one connection instead N connections.

**Comment by spasche** [comment]
Right, I see how collecting stats in the background can be quite useful by not having to keep Dozzle open.

My main use case for Dozzle is to check the logs, for the CPU and memory I use cadvisor (which requires [a bit of tuning](https://github.com/google/cadvisor/issues/2523) if you don't want it to eat all your CPU).

Maybe having an option to disable background stats could be a trade-off for users with many containers who could live with the old behavior. But I understand it may add quite a bit of complexity to support both behaviors.

**Comment by amir20** [comment]
It's not a horrible idea to disable it. But it would make it complicated. I think it would have to disable it all together. 

The other problem is that I hope to add some features like alerting for high CPU. 

Looking at the Docker CLI, there is no way to listen to all stats in one connection. I'll have to CPU profile and see if I can reduce anything on my side. 

Let's keep this open, and see if other people have this problem.

**Comment by amir20** [comment]
@spasche so I wasn't exactly able to reproduce this. I spun up 100 containers. At idle time, my CPU was roughly around 2%. With browser open to Dozzle, it jumped to 5% but that's about it. 

I did a profile and found that decoding the JSON payload from Docker is where the majority of the CPU is being consumed. 

So I tried a faster json library like `goccy/go-json` with #2766. You can test with `amir20/dozzle:pr-2766`. This brought down the CPU to roughly 1.2% with 100 containers. I used `top` to see this. 

Seems like the CPU load is small that it doesn't warrant any huge improvements. I am on an old Intel Macbook 2018 while testing. 

Can you give the new PR a try? If it helps a lot, I'll merge it, but otherwise it doesn't feel significant enough to spend a lot of time on it.

**Comment by amir20** [comment]
Did you get a chance to test pr-2766?

**Comment by spasche** [comment]
Many thanks for the analysis and improvement. The graph below shows CPU consumption with version 6.2.2 and then with the container from the pr:
![image](https://github.com/amir20/dozzle/assets/105751/d5656efd-fa1b-4f91-b2c4-8ef0be169afb)
The improvement is about 30% less CPU consumption, which is quite good I think!

**Comment by amir20** [comment]
That is pretty good. So let me merge that.

**Comment by amir20** [comment]
Releasing `6.2.3`.  You should see a little more improvement when using Dozzle too.

**Comment by spasche** [comment]
Perfect, thank you so much for addressing this so quickly 👏 (and for Dozzle in general, which is such a useful tool).
As you mentioned, now the CPU consumption is quite reasonable, so I think it can be closed.
