### ISSUE TITLE
users.yaml is not accepted as a valid user configuration

### ISSUE THREAD

**Issue by flamestro** [amir20/dozzle#2767]
**Describe the bug**
I tried to setup the simple auth flow and create a users.yaml (with a). This resulted in errors and I could not figure out why.
Turns out that the code only supports yml as an ending. 

**To Reproduce**

1. create a simple auth config with users.yaml as a config filename
2. container does not spin up

**Expected behavior**
yaml and yml should both work as they are synonyms for each other. Both should be handled.

- Docker version: latest

**If applicable include logs with `--level debug` and browser logs**

```
time="2024-02-08T22:57:54Z" level=info msg="Dozzle version v6.2.2"
time="2024-02-08T22:57:54Z" level=info msg="Connected to 1 Docker Engine(s)"
time="2024-02-08T22:57:54Z" level=fatal msg="Could not find users.yml file at /data/users.yml"
```

**Comment by amir20** [comment]
Hmmm you maybe right according to https://yaml.org/faq.html

Seems fair enough. Maybe tomorrow I can take a quick look.

**Comment by flamestro** [comment]
For me this is solved but it took around 40 mins to debug as I thought I misconfigured the volume instead of the filename.

So maybe we can save others some time :D

**Comment by amir20** [comment]
If you know Go then PRs are appreciated!

**Comment by flamestro** [comment]
sadly I don't :/ 
But I am sure I can figure it out somehow. If this can wait a few days I might find some time to solve it. If I am not able to do so in a reasonable amount of time I can ping you again

**Comment by amir20** [comment]
Sounds good. It should be super easy. `main.go` checks for the valid file.  https://github.com/amir20/dozzle/blob/a99672a5dabbc2f11806eb5839c562fd8293e3f4/main.go#L169-L175

So just check if `users.yaml` exists and then `users.yml`.

**Comment by amir20** [comment]
Gonna close this. Let me know if you can send a PR.
