### ISSUE TITLE
Timeout after update to 2.6.4

### ISSUE THREAD

**Issue by steakhutzeee** [amir20/dozzle#2773]
**Describe the bug**
After updating my Dozzle container to latest version 6.2.4 it looks very slow or unresponsive, with Homarr complaining that the API was too slow. I tried restarting the container many time, from Portainer the logs for Dozzle say it is accepting connections but when I reach for it it does not open ad goes timeout. 

**To Reproduce**

Update to 6.2.4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Docker version: docker --version
Docker version 25.0.2, build 29cf629
- Browser & version: Chrome
- Version: 2.6.4

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
V2.6.4 doesn't exist.

I haven't seen this and about 10k installations per day. So might be something in your environment.

**Comment by steakhutzeee** [comment]
My bad it is 6.2.4

**Comment by amir20** [comment]
It's probably something on your side. Unless you see an error that could help me debug.

**Comment by steakhutzeee** [comment]
Looks like I had a pending Docker engine update. After that it returned to work fine.
