### ISSUE TITLE
Dozzle keeps exiting after 6.2.0+ versions for REMOTE_HOSTS 

### ISSUE THREAD

**Issue by peterbuga** [amir20/dozzle#2779]
**Describe the bug**
Dozzle keeps exiting after 6.2.0+ version with the message 
`level=fatal msg="error while listening to docker events: unexpected EOF. Exiting..."` 

**To Reproduce**
The setup includes connections to (previous working) remote `tecnativa/docker-socket-proxy` via haproxy, so basically inside dozzle I mount certs files to `/certs/<host>/{ca,cert,key}.pem` 

**Expected behavior**
Avoid hard exiting when docker events not available.

**Screenshots**

**Desktop (please complete the following information):**
Docker version install

**If applicable include logs with `--level debug` and browser logs**
A recent change has been added to version 6.2.0+ versions https://github.com/amir20/dozzle/compare/v6.1.1...v6.2.0#diff-2d19c8194afb71cf59b850c9e062ba33252ed30205cb370ab223a216c9352c8dR310 that seems to trigger this behavior.

**Comment by amir20** [comment]
> Avoid hard exiting when docker events not available

Are you disabling events API? Even in the older version it was required to load the containers. I think you'll need to enable it because it breaks a lot of functionalities.

**Comment by amir20** [comment]
Haven't heard back. Also looked at the code. It would be pretty hard to support Dozzle without events API.

**Comment by peterbuga** [comment]
@amir20 

apologies for belated reply!
turns out you were right to some degree, at least you pointed me in a debugging direction 👍

I didn't had events API disabled for `tecnativa/docker-socket-proxy` but due to latest code hardening it exposed a certain misconfiguration in my haproxy loadbalancer that sits on top of "docker-socket-proxy" 

my setup is basically 
```Dozzle -> haproxy load balancer (w/ backends servers via multiple vpns) + ssl enabled -> docker-socket-proxy (for each server) -> docker.sock```

analyzing a bit `tecnativa/docker-socket-proxy` turns out there's a specific route for events API https://github.com/Tecnativa/docker-socket-proxy/blob/master/haproxy.cfg#L78 + https://github.com/Tecnativa/docker-socket-proxy/blob/master/haproxy.cfg#L44 and these configs were the key to make it work, replicating this logic on my haproxy made everything stable - leaving this here in case anyone else comes across a similar problem.

thanks for such a helpful piece of software and sorry for throwing a non-dozzle specific problem (at least I learned something new today 🙆‍♂️)

**Comment by amir20** [comment]
@peterbuga that's great! Thanks for the update. In Dozzle documentation, I did have events as a required API. 

Good to know there were other upstream issues. 

You are welcome! Glad you like it. I use Dozzle almost everyday for my own projects.
