### ISSUE TITLE
Impossible to get more logs of my container

### ISSUE THREAD

**Issue by GMercat** [amir20/dozzle#2783]
**Describe the bug**
When i try to get more logs of my container, the web interface doesn't show them.

**To Reproduce**
Steps to reproduce:

1. Need a container with lot of logs
2. Scroll up to ask previous logs.
3. I see this request: `http://<IP>/logs/api/logs/localhost/d360c9192114?from=2024-02-19T13%3A42%3A44.616Z&to=2024-02-19T13%3A42%3A44.873Z&stdout=1&stderr=1`
4. But when i look in dozzle logs i see: ` level=debug msg="fetching logs from Docker with option: {ShowStdout:true ShowStderr:true Since:2024-02-19T13:42:44Z Until:2024-02-19T13:42:44Z Timestamps:true Follow:false Tail: Details:false}"`
We lose the precision of the request.

**Expected behavior**
In this case I expect the call on the docker api to keep the millisecond precision.

**Desktop (please complete the following information):**

- OS: CentOS Linux release 7.9.2009
- Docker version 
```
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:55:21 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:54:24 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```
- Browser & version : `Brave`, Version 1.62.165 Chromium: 121.0.6167.184 (Build officiel) (arm64)
- Version: `v6.1.0`

Thanks

**Comment by amir20** [comment]
I think this would only happen if you have thousands of logs per second. Is that what you have?

**Comment by GMercat** [comment]
Thank you for your quick reply.

Yes I have around 2000 per sec.

I have a question after quickly reading the code. Why not use `RFC3339Nano` instead of `RFC3339` all the time where parameters `from/since` and `to/until` are manipulated between the website and the docker api call ?

**Comment by amir20** [comment]
> I have a question after quickly reading the code. Why not use RFC3339Nano instead of RFC3339 all the time where parameters from/since and to/until are manipulated between the website and the docker api call ?

Yea, I think that's exactly what it should do.  I was looking at Docker code to make sure that is supported. https://github.com/moby/moby/blob/9d1541526c5beab51d2344b47624a160f199bbe6/api/types/time/timestamp.go#L37 It seems like it is. 

So perhaps that would be an easy fix. 

> Yes I have around 2000 per sec.

That's impressive. Most people are pushing Dozzle to its limits with the number of containers, but you use cases is also a good edge case.

**Comment by amir20** [comment]
@GMercat Can you try `amir20/dozzle:pr-2785`? I haven't tested it personally but maybe you can quickly test it.

**Comment by amir20** [comment]
In the latest, I see 

```
{"level":"debug","msg":"fetching logs from Docker with option: {ShowStdout:true ShowStderr:true Since:2024-02-19T22:51:18.071Z Until:2024-02-19T22:55:23.476Z Timestamps:true Follow:false Tail: Details:false}","time":"2024-02-19T23:05:10Z"}
```
So maybe it worked. But I guess I'll have to wait for you to confirm.

**Comment by GMercat** [comment]
Yes it's better ! Thanks

But i have another question: How the interval of search is calculated ?

Because i see another issue...

If i have a lot of logs from my container, the internal of search is small, in my case it's `from: 2024-02-20T10:59:57.249Z` and `to=2024-02-20T10:59:57.295Z` but i have not log in this interval, the last log before is at `2024-02-20 10:59:57.187815`...

It's why a ask my question: How the interval of search is calculated ?

Thank you in advance for your answer

**Comment by amir20** [comment]
That's a more complicated answer. But I'll try anyway. 

1. On first request Dozzle fetches about 300 lines of logs. This is the sweet spot before browser uses a lot of memory. 
2. When scrolling up, I calculate the difference first line and last line in time. So if the difference is 10s, I ask for previous 10s of data. 

The reason I have to do this is because on the first run I call `docker logs --tail 300`, but for subsequent calls I cannot do `docker logs --tail 300 --until XYZ`. It seems like Docker API doesn't support `--tail` and time based queries.  If I don't do this then I might end up loading 10000 lines of logs. Which would be the case for you and Dozzle would run out of memory. 

I hope that makes sense? 

Given your situation, it is not always perfect. Especially if you one second you get 10000 logs / sec and another second you get 2. Unfortunately, I can't think of a better solution given the limitations of the API.

**Comment by amir20** [comment]
Released a new build with that fix.

**Comment by GMercat** [comment]
> That's a more complicated answer. But I'll try anyway.
> 
> 1. On first request Dozzle fetches about 300 lines of logs. This is the sweet spot before browser uses a lot of memory.
> 2. When scrolling up, I calculate the difference first line and last line in time. So if the difference is 10s, I ask for previous 10s of data.
> 
> The reason I have to do this is because on the first run I call `docker logs --tail 300`, but for subsequent calls I cannot do `docker logs --tail 300 --until XYZ`. It seems like Docker API doesn't support `--tail` and time based queries. If I don't do this then I might end up loading 10000 lines of logs. Which would be the case for you and Dozzle would run out of memory.
> 
> I hope that makes sense?
> 
> Given your situation, it is not always perfect. Especially if you one second you get 10000 logs / sec and another second you get 2. Unfortunately, I can't think of a better solution given the limitations of the API.

Thanks for your response, it makes sense.
