### ISSUE TITLE
Changing items per page (15, 30, 50, 100) should reset current page

### ISSUE THREAD

**Issue by ldrahnik** [amir20/dozzle#2784]
**Dozzle version(s) affected:** 6.2.4

**How to reproduce**

Have more then 15 docker instances (and < 100) and on second page change items on page to 100. Now will be page empty because everything is fit to page number 1 but current page is not reset so app is still on page 2 with no docker instances.

**Possible Solution**

Reset current page when is changed items per page settings.

**Comment by amir20** [comment]
Hmm yea, this is a bug. Probably an easy fix when I get around it.
