### ISSUE TITLE
Support alternative Gravatar-compatible hosts

### ISSUE THREAD

**Issue by nogweii** [amir20/dozzle#2787]
**Is your feature request related to a problem? Please describe.**
I like [Libravatar](https://www.libravatar.org/) and want to promote it's usage. It's an alternative to Gravatar that can be self-hosted.

**Describe the solution you'd like**
A new CLI flag (or maybe keeping it to environment variable only, as it's a more niche request) to configure the hostname `user.AvatarURL()` uses:

https://github.com/amir20/dozzle/blob/07d0c7fac503705573c568f038ef7e263341580f/internal/auth/users.go#L25-L31

**Describe alternatives you've considered**
There isn't a possible alternative, but it's also not the end of the world. Unless I make a browser extension, maybe?

**Comment by amir20** [comment]
Haven't heard back. Closing.
