### ISSUE TITLE
Possibility to get Plex Console into Dozzle

### ISSUE THREAD

**Issue by IIIdefconIII** [amir20/dozzle#2799]
**Is your feature request related to a problem? Please describe.**
Nope just a nice feature to have

**Describe the solution you'd like**
Having a output of the plex internal console to a dozzle item

**Describe alternatives you've considered**
Creating a direct hyperlink to the Console in homeassistant

**Additional context**
Would love it to have the random console stuff beeing visable in dozzle as i use dozzle for like the global syslog thingy to watch for issues first;

![image](https://github.com/amir20/dozzle/assets/9917659/02709293-b939-4ce9-8151-8fc2163a0104)

**Comment by IIIdefconIII** [comment]
might be this but im not sure: didnt check to be honest

![image](https://github.com/amir20/dozzle/assets/9917659/517f194c-c90d-4edf-8860-d39d35f091a1)

**Comment by amir20** [comment]
@IIIdefconIII to be honest, I have no idea. I am not too familiar with Plex. I suspect Plex write to a file instead of `stdout`. If you can mount the log file maybe you can use https://dozzle.dev/guide/log-files-on-disk

**Comment by IIIdefconIII** [comment]
> @IIIdefconIII to be honest, I have no idea. I am not too familiar with Plex. I suspect Plex writes to a file instead of `stdout`. If you can mount the log file maybe you can use https://dozzle.dev/guide/log-files-on-disk

thanks for this info and i will look into it later probably next week. would be awesome!
