### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by bobluck** [amir20/dozzle#2806]
**Is your feature request related to a problem? Please describe.**
Have to re login every time app is visited, meaning book marked container is not revisited and the main window is displayed instead.

**Describe the solution you'd like**
- Option to stay logged in for a period of time, or forever if on local network
- Optionally set default log upon login. (I prefer watchtower)

**Comment by amir20** [comment]
> Have to re login every time app is visited, meaning book marked container is not revisited and the main window is displayed instead.

That seems like a bug that I can fix. 

> Option to stay logged in for a period of time, or forever if on local network

Dozzle doesn't know you are on a local network. I just cookies so if you close your browser then it is a reset.

**Comment by bobluck** [comment]
Thanks, keeps getting better. Sent from my iPhoneOn Mar 5, 2024, at 13:23, Amir Raminfar ***@***.***> wrote:﻿

Have to re login every time app is visited, meaning book marked container is not revisited and the main window is displayed instead.

That seems like a bug that I can fix.

Option to stay logged in for a period of time, or forever if on local network

Dozzle doesn't know you are on a local network. I just cookies so if you close your browser then it is a reset.

**Comment by bobluck** [comment]
Sweet, one less annoyance in my digital life. Keep up the good work.
