### ISSUE TITLE
Please provide insight on CPU statistics

### ISSUE THREAD

**Issue by FoxxMD** [amir20/dozzle#2811]
![2024-03-07_09-27](https://github.com/amir20/dozzle/assets/4663766/a6e6270b-d79e-42ba-a977-cd9a7b0310b0)

When I have containers that have high CPU usage I get these kind of numbers, well over 100%, that don't really mean anything to me. I expect CPU percentage to be what percentage of all CPU cores that container is using.

The docs do not hint at what this percentage is measuring or how it is measured. Can you please provide clarification on what **Total CPU Usage** and **AVG. CPU %** actually mean.

For context, this is on a 10c/20t single socket xeon CPU.

Thanks

**Comment by amir20** [comment]
It's the same behavior as `docker stats` so hopefully no documentation needed. 

If you are using more 100% then it means you are using more than one CPU, eg. 250% means you are using 2.5 cores. For you it looks like you have at least 17. 

Also, you should update Dozzle.
