### ISSUE TITLE
Unexpected environment variable(s) DOZZLE_TAILSIZE and DOZZLE_KEY

### ISSUE THREAD

**Issue by daithi-coyle** [amir20/dozzle#2814]
Installed the Dozzle container ages ago on Unraid, using the Selfhosters.net template.
I finally got around to fixing the authentication changes made for 6.x.
Upon restarting the container I got warnings in the log for these two variables.

I obviously haven't kept up, but I couldn't find info on either of these vars on google.
Have they been replaced by something else, or should I just delete them?

**Comment by amir20** [comment]
Yep. Just delete them. No longer used.

**Comment by daithi-coyle** [comment]
thank you
