### ISSUE TITLE
[Feature Request] Replicated Container in one Log

### ISSUE THREAD

**Issue by rodistic** [amir20/dozzle#2817]
**Is your feature request related to a problem? Please describe.**
We have an active Backend which has been replicated serveral times for Performance, when we do have some failure we always need to have every replicated dozzle log open and check where the error comes from, thats quite frustrating because we a have a lot of traffic.

**Describe the solution you'd like**
It would be nice if Dozzle had a setting (bundle Replicated logs or so) where its searches an container name for examble "backend",
and puts every "backend.{task_id}" in that one head container log.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by amir20** [comment]
I think this would be a good feature too but right now all search is done on the browser.  Which means if there were 10 containers that need to be searched they would all need to be processed on the browser. 

Eventually, I plan to move all search to backend but until then I don't think I'll put on this feature.

**Comment by amir20** [comment]
Going to close this as there is a lot of other things that need to happen to be able to support this. One of the issues of bringing search to backend is that it will be slower and lose context in the browser. So I think I am going to hold off. 

Open to PRs or anybody else who wants to help on this issue.
