### ISSUE TITLE
Only the first match of a searched query is highlighted

### ISSUE THREAD

**Issue by meteoncu** [amir20/dozzle#2822]
**Describe the bug**
Only the first match of a searched query is highlighted when it appears multiple times in the logs

**To Reproduce**
1. Go to the logs of one of the containers.
2. Open the search bar and type a query that has multiple matches within the log entries.
3. Observe the highlighted results.
4. You see "only one" match is highlighted

**Expected behavior**
All instances of the searched query should be highlighted in the logs

**Desktop (please complete the following information):**

- OS: macOS
- Docker version: 20.10.10
- Browser & version: Google Chrome - Version 122.0.6261.112 (Official Build) (arm64)
- Version: 6.2.5

**Comment by amir20** [comment]
I think I'll need more details because "it works for me"™️ 

See screenshot 

![Capture-2024-03-12-082849](https://github.com/amir20/dozzle/assets/260667/250b2efa-410f-4b6c-8732-e3cff6cc13c4)

**Comment by meteoncu** [comment]
As you can see, there are multiple "found" strings in each log entry. However only one of them is highlighted in a row.

<img width="1116" alt="Screen Shot 2024-03-13 at 13 17 07" src="https://github.com/amir20/dozzle/assets/8741505/7dcba9de-714d-4a70-b826-b3657fbb2180">

**Comment by amir20** [comment]
Oh I see. I thought you meant the second word isn't matching. Let me check the code.

**Comment by amir20** [comment]
Was an easy fix. Thanks for the find.
