### ISSUE TITLE
Container logs open Slow.

### ISSUE THREAD

**Issue by ericvlog** [amir20/dozzle#2833]
**Describe the bug**
When click on the container for view logs, it seems be very slow loading, and need to wait.

**To Reproduce**
on dozzle main pages click on container

**Expected behavior**
It should be instant loading when click on container.

**Desktop (please complete the following information):**
docker-compose dozzle

I also have test on docklogkeeper vs dozzle, their function is lack and interface is not so gorgeous but when click on container it seems instant open the logs.

**Comment by amir20** [comment]
It loads almost instantly for me. Can you record a video? No one else is having this issue so something might be unique to your set up.

**Comment by ericvlog** [comment]
> It loads almost instantly for me. Can you record a video? No one else is having this issue so something might be unique to your set up. 

Wow, I know where the problem is, 1 of my userscript of finding terms in any website causes it to freeze.

Thanks for your hint!!

Wonderful thens docklogkeeper more!!👍

**Comment by amir20** [comment]
Great. I wonder if there is anything Dozzle could do to avoid that. But if it's a custom script then I think it's outside of my control.
