### ISSUE TITLE
Malformed output when log contains an equals sign

### ISSUE THREAD

**Issue by tigerchase96** [amir20/dozzle#2834]
**Describe the bug**
Whenever a container's console output contains `a = b`, Dozzle seems to misinterpret the line as a series of variables and ends up malforming the entire line.

**To Reproduce**

1. Run some variation of the following code, in any container. This example is in Python but the language doesn't matter. The only important part is the second print statement.
```py
import time

print("hello world")
print("Failed to run somecommand with somevariable = 1")

while True:
    time.sleep(1)
```

2. Open the Dozzle logs for the container
3. Observe that the output looks like the screenshot below

**Expected behavior**
I expected the message to be printed as-is: `Failed to run somecommand with somevariable = 1`

**Screenshots**

![image](https://github.com/amir20/dozzle/assets/12799103/51c326de-b575-4bd6-9bd5-ffd17a7eade5)

**Desktop (please complete the following information):**

- OS: Windows 10
- Docker version: 25.0.3
- Browser & version: Chrome 122.0.6261.129
- Version: v6.3.1

**Comment by amir20** [comment]
Hmm that does seem like a tricky bug.  Dozzle supports https://grafana.com/docs/loki/latest/send-data/promtail/stages/logfmt/ but the parser seems pretty relaxed. 

I am not sure how to fix it.

**Comment by amir20** [comment]
Looks like I do `strings.Contains(message, "=")`. Maybe I should change it to some regex without spaces around `=`.

**Comment by ncrothers** [comment]
Would it be reasonable to check if the message matches regex something like `^[^ ]+=[^ ].*`? This would expect the message to start with a key that contains no spaces (which I think is reasonable restriction), which I would imagine is a typical use case for key-value logs. That way it would match:

```
time=2012-11-01T22:08:41+00:00
```

But none of these:

```
This is a log message: "key=value"
Testing a variable = 2
```

**Comment by tigerchase96** [comment]
Thanks for the quick reply! If you can't find a good way to improve the regex, another option could be adding a new environment variable that disables all parsing and prints all messages as-is. Just tossing out an idea. 🙂

**Comment by amir20** [comment]
> adding a new environment variable that disables all parsing and prints all messages as-is. Just tossing out an idea

Not worth it. Makes testing and configuration harder. 

Let me play around with regex.

**Comment by amir20** [comment]
This should be fixed with https://github.com/amir20/dozzle/pull/2835. Can you try it with `amir20/dozzle:pr-2835`?

**Comment by tigerchase96** [comment]
That appears to have fixed my problem. Just to be sure, I tested out some different variants to see what the output looks like:

```py
print("Failed to run somecommand with somevariable = 1")
print("Failed to run somecommand with somevariable=1")
print("somevariable=1")
print("somevariable = 1")
print("somevariable=1 another=2")
print("somevariable = 1 another = 2")
```

![image](https://github.com/amir20/dozzle/assets/12799103/859f5049-1acd-4105-a23f-14bf36b7fb0d)

My original test case is now correct, and `somevariable=1 another=2` is still being parsed as expected.
I'm wondering if `somevariable=1` should have been picked up by your updated regex, however.

**Comment by amir20** [comment]
`somevariable=1` does not work because I check for at least two valid key value pairs. So I think it's ok. The reason is that a single log with key sounds like a bug. Will merge now.
