### ISSUE TITLE
It does not seem to stop collecting stats after 6 hours

### ISSUE THREAD

**Issue by zvirja** [amir20/dozzle#2838]
**Describe the bug**
Recently you introduced stopping collecting stats after X hours. I see in container logs that it stopped:

```
time="2024-03-20T21:06:40Z" level=info msg="Dozzle version v6.4.0"
time="2024-03-20T21:06:40Z" level=info msg="Connected to 1 Docker Engine(s)"
time="2024-03-20T21:06:40Z" level=info msg="Accepting connections on :8080"
time="2024-03-21T03:38:47Z" level=info msg="stopped collecting container stats"
```

But reality is that it didn't. As I still see high CPU usage by `dockerd` and `containerd` and `~0.6%` CPU usage by dozzle.

Also when I open later Dozzle and look at history, it looks like it was partially stopped..

![image](https://github.com/amir20/dozzle/assets/1074182/e853dedc-7654-486a-9536-eea279aa5932)
 
I suggest to also add logging when starting collecting the stats, so we can troubleshoot it better. As now it only prints an entry upon stop.

**Comment by amir20** [comment]
If you enable [debug](https://dozzle.dev/guide/debugging) then you will get a lot more logs. 

> 0.6% CPU usage by dozzle

This is not much. I am not sure if it would ever get to 0. Golang has other threads running which I cannot control. 

I did some testing before releasing and it seemed to have worked. But I guess there is no way to prove it that Docker actually disconnected. I'll add another debug statement when the container stat stream stops from my side. Maybe that will help.

**Comment by zvirja** [comment]
If you create a PR with more logging (+ INFO logging on start/resume) and tell me how to enable DEBUG logging, I'll gladly test it.

> This is not much. I am not sure if it would ever get to 0. Golang has other threads running which I cannot control.
It was mostly 30% CPU for docker which was an issue. Those `0.6` was a sign to me that something does not go well..

**Comment by amir20** [comment]
> It was mostly 30% CPU

Wow. OK let me check it. 

> how to enable DEBUG logging 

I already linked that https://dozzle.dev/guide/debugging

**Comment by zvirja** [comment]
> Wow. OK let me check it.

Yeah, 30% CPU is my regular consumption by Docker when I use dozzle :)

I've turned on the logging, let me see

**Comment by amir20** [comment]
Ok I definitely found a bug. So much threading and async code going on, I'll have to pay more attention to it.

**Comment by amir20** [comment]
Since the bug was pretty serious, I am releasing `6.4.1`. Can you try that with `debug` enabled? 

You should see messages likes 

```
INFO[0033] stopped collecting container stats
DEBUG[0033] stopping to stream stats for: 268d41bad592
....
```

Which means it should have worked.

**Comment by zvirja** [comment]
Oh, I am glad you did! Awesome. Let me do another round of testing 😊

**Comment by amir20** [comment]
It seems to work for me in a couple environments I tested last night. How about yours?

**Comment by zvirja** [comment]
Yes, I've just finally tested and and it seems to work now!! Awesome 😍

Thanks you a lot!

**Comment by amir20** [comment]
Nice. This was a hard feature so there might be more bugs.

**Comment by zvirja** [comment]
@amir20 I don't know if you coded it on purpose or not, but the fact that it does not collect logs upon restart until the first request from UI is JUST AWESOME!!! Please keep that forever :blush:

**Comment by amir20** [comment]
Yea did that on purpose. Took me a lot of testing 😅

**Comment by zvirja** [comment]
I truly appreciate your effort :star_struck:
