### ISSUE TITLE
Filter main list and summary section by host

### ISSUE THREAD

**Issue by Snuffy2** [amir20/dozzle#2842]
**Is your feature request related to a problem? Please describe.**
I'm currently able to see the docker stack for my 3 different servers on a single Dozzle instance which is great. When I select a Host, the left menu only shows the containers running on that host. It would be awesome if the main screen could also filter to just those containers running on the host. That way I can see the full picture of just one host such as the total number of running and total containers, memory and CPU usage, etc.

**Comment by amir20** [comment]
I think this makes sense. Just not the highest priority for me right now. So I'll keep it open.

**Comment by amir20** [comment]
See #2932. A pretty big change to dashboard is coming that should fix this.
