### ISSUE TITLE
Concatenated logs

### ISSUE THREAD

**Issue by realitix** [amir20/dozzle#2851]
**Is your feature request related to a problem? Please describe.**
My app consists of several containers that interact with each other. When a task is launched, I would like to see all the logs related to that task. Currently, I have to go into each container individually, which is tedious.

**Describe the solution you'd like**
I would like a panel that displays the logs from all the containers in one place (like when we do a docker compose up).

Thanks

**Comment by amir20** [comment]
You can already see multiple logs using the panel feature. Do you mean something else?

**Comment by amir20** [comment]
I see.  I did some quick investigation. There doesn't seem to exist a command to get all logs, eg `docker stack logs ...`. Which means Dozzle would have to fetch all the services for a specific stack and then tail each container. This is a bit much right now to implement. 

Let's keep this open. If there is more interest I'll come back to it.

**Comment by amir20** [comment]
The more I think about this, I think the right way would be Dozzle to just support services and stacks, which is a pretty big effort. I wonder how many people would be interested in that. I haven't gotten a lot of issues for that.

**Comment by ThreeTheOG** [comment]
The command `docker compose logs` gets the logs from a stack in the current directory, or you can use `docker compose --project-directory /opt/stacks/my_stack/compose.yaml logs`.

**Comment by amir20** [comment]
@ThreeTheOG Dozzle has no knowledge of `compose` files. When compose projects are launched on to a server, they get mapped to services and stacks.  The only way to get these logs is through `docker service`.  `docker compose` is only used locally for development.

**Comment by amir20** [comment]
Closing this in favor of #2862. `docker stack` and `services` would be all part of swarm if I ever get to it.

**Comment by amir20** [comment]
I am starting to think of this a little more. See https://github.com/amir20/dozzle/issues/2960 and provide feedback. I think it might be doing to see how it works out.
