### ISSUE TITLE
It's displaying logs from another container

### ISSUE THREAD

**Issue by twist3dimages** [amir20/dozzle#2861]
**Describe the bug**
Occasionally I will click on a container and it will display logs from another one, sometimes it will have logs from another container and itself (So I will see logs from Radarr in Sonarr) and sometimes when I click Sonarr, I see Radarr logs, as an example)

**To Reproduce**

1. Open Dozzle
2. Click on several containers
3. Look at logs
4. See logs from another container

**Expected behavior**
I would like it to only display the logs on the container I clicked

**Screenshots**
![image](https://github.com/amir20/dozzle/assets/33134502/00d8aaf1-e7af-40af-9905-54a0eaa543b0)
In this example, I am not even looking at Authelia logs and that's the only thing I see
**Desktop (please complete the following information):**

- OS: Unraid
- Docker version  24.0.9
- Browser & version Chrome 
- Version [123.0.6312.87

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
This has never happened to me. Maybe record a video next time.

**Comment by twist3dimages** [comment]
I have a lot of containers 🤣

**Comment by amir20** [comment]
I have tested with 150 containers. 

You can try enabling debug logs and see if the right container is being streamed. If the logs are correct then something is going on in the browser. 

I am on the phone but to enable debug is on Dozzle.dev

**Comment by amir20** [comment]
Closing until I hear more. Follow instructions at https://dozzle.dev/guide/debugging to enable debug with a video would be helpful.
