### ISSUE TITLE
Is the color of the log text incorrect?

### ISSUE THREAD

**Issue by devioa** [amir20/dozzle#2867]
**Describe the bug**
There is a color deviation in the log text. The text color I see in the Portainer and `docker logs -f <container name>` is correct. But in Dozzle, there are color deviations.

**Expected behavior**
The color of the log text is correct.

**Screenshots**
![1](https://github.com/amir20/dozzle/assets/38558065/41ac14c7-b244-4c6f-b071-f6f9b2e0c1c6)
![2](https://github.com/amir20/dozzle/assets/38558065/d08dfb69-4d8b-4ef0-8b90-76b9e82e4386)
![3](https://github.com/amir20/dozzle/assets/38558065/787daf32-ac49-4244-aea5-fdaa14bad54a)
![4](https://github.com/amir20/dozzle/assets/38558065/aba1ccb3-adc1-41c6-a56c-ab5b74b648af)

**Desktop (please complete the following information):**
- OS: Windows 11
- Docker version 25.0.3
- Browser & version Chrome 118
- Version dev(built from latest source code)

**Comment by amir20** [comment]
I use https://www.npmjs.com/package/ansi-to-html to convert ansi color to CSS html. So I don't think they would be an exact match. 

The configuration is done at https://github.com/amir20/dozzle/blob/c448636641510b76f4c934bcdf7b554dab86ced5/assets/components/LogViewer/SimpleLogItem.vue#L20-L30

Send a PR if you think it can be improved.
