### ISSUE TITLE
Password only provider for authentication

### ISSUE THREAD

**Issue by vanodevium** [amir20/dozzle#2870]
Please return password only authentication.

> It is possible even without a login, only a password. Which can be specified via an environment variable or option.

This is for those cases where only people who have the password have access to the logs. But as group of people change, there is no way to constantly change the file with user logins and passwords.

**Comment by amir20** [comment]
This won't happen. It has been discussed before as Dozzle moved to a multi-user auth system by storing each user's profile on disk. There will be new things in the future to store like saved searches, recent containers, etc.... With a single user system that breaks and introduce more confusion, which makes it impossible to optimize for both. 

You have 3 options: 

1. Just use a single username in `users.yml` file. Everybody will have one profile stored but that is working as designed given you have only one user. 
2. Use the proxy forward https://dozzle.dev/guide/authentication#forward-proxy solution and proxy Dozzle. This is **preferred** as I don't think Dozzle should be the primary authentication method. I strongly recommend you do this if you are technical for your org. Some solutions also support SSO which means you don't have to worry about who joins and leaves.
3. Use a simple nginx proxy and just enable password to protected Dozzle. Probably not great if you have sensitive logs.
