### ISSUE TITLE
Default background color for ANSI logs is black instead of default

### ISSUE THREAD

**Issue by sasmith** [amir20/dozzle#2873]
**Describe the bug**
The default background color for ANSI logs is black, regardless of whether a user is in light or dark mode. This means that if a user uses ANSI code 49 (to indicate a default background color), they'll get black. This isn't great for light mode.

**To Reproduce**
Run a docker container that logs the string `\x1b[49mHello World`. View this log in Dozzle, in light mode. This line will show up with a black background.

**Expected behavior**
ANSI color code 49 should be some sort of default background.

**Screenshots**
![Screenshot 2024-04-04 at 13 48 01](https://github.com/amir20/dozzle/assets/2469501/cc673846-daf5-4a22-a0fb-bfe9e9edee85)

**Desktop (please complete the following information):**

- OS: Mac OS
- Docker version: 26.0.0
- Browser & version: Chrome 
- Version: 6.4.2

**Proposed fix**
This is an issue that Dozzle inherits from ansi-to-html, which has a default background color of black. Changing the initialization of `AnsiConvertor` in `assets/components/LogViewer/SimpleLogItem.vue` to something like `new AnsiConvertor({ escapeXML: false, fg: "var(--base-content-color)", bg: "initial" });` seems to address the problem.

Here both `bg: "initial"` and `bg: "transparent"` work for my purposes. It's possible that setting `fg: "initial"` would also simplify matters, but fg colors currently seem fine to me.

**Comment by amir20** [comment]
Nice catch. Can you send PR? Otherwise I'll look tomorrow.

**Comment by amir20** [comment]
Maybe `var(--base-color)` would be better.

**Comment by amir20** [comment]
Try `amir20/dozzle:pr-2874`.

**Comment by sasmith** [comment]
This looks fixed to me -- thank you!
