### ISSUE TITLE
Dozzle (internal) time / TZ environment option

### ISSUE THREAD

**Issue by ZTiKnl** [amir20/dozzle#2877]
**Describe the bug** /feature request
Dozzle has its own log, which displays UTC times on my Synology, even though the Synology is set to GMT+1, causing Dozzle to report its internal time incorrectly in the Dozzle logs

**To Reproduce**
Start Dozzle docker container, and read the log files, it says:
`06/04/2024 **00:43:28** level=info msg=Accepting connections on :8080 time=2024-04-05T**22:43:28**Z`

**Expected behavior**
Dozzle should accept the TZ environment variable to allow internal time/date to match system

**Screenshots**
Dozzle log in Dozzle:
![image](https://github.com/amir20/dozzle/assets/53024556/13670740-41d1-492b-ba4b-0c9f21856998)

Synology time settings:
![image](https://github.com/amir20/dozzle/assets/53024556/b3c326a4-248c-4add-a386-0523220148af)

Dozzle Docker ENV vars:
![image](https://github.com/amir20/dozzle/assets/53024556/b011a506-4056-4bdb-bedb-bb34af073386)

**Desktop (please complete the following information):**
Not applicable

**If applicable include logs with `--level debug` and browser logs**
This seems overkill, but willing to provide if required :)

There is no rush for me to get this done, everything works perfectly for me, I am a happy Dozzle user, thank you!

**Comment by amir20** [comment]
Hey there,

I am still having a hard time understanding. So two things: 

1. According to [documentation](https://pkg.go.dev/time#example-Location) `TZ` should work. So I am not sure why it is not. 
2. time is the date printed in UTC. But in javascript, I convert it to local timezone of the browser. Isn't that good enough? 

In computers, two things are hard, naming things and timezones. :P 

I am not doing anything to stop `TZ` so I am not sure what needs to be done.

**Comment by ZTiKnl** [comment]
I think I may have created confusion here, apologies if so, I'll try to explain as clear as I can :)

Dozzle reports dates/times perfectly in browsers, that part does work as expected.
The incorrect time is found in Dozzle's own log entries.
Stop and (re)start the dozzle service, and Dozzle will report at which time it has shutdown/initiated in _its own_ log files.

Example dozzle log section:
![image](https://github.com/amir20/dozzle/assets/53024556/4dd80185-312d-4706-bb1f-60644b75c0d1)

This log entry happened at **00:43:28** _local time and system time._
But according to the log entry itself, this event happened a day earlier at **22:43:28**

This tells me that Dozzle thinks that the local time is 2 hours earlier than it actually is set on system.
This happens with a lot of Docker packages, and is usually corrected by setting a TZ environment variable.

The desired output of the Dozzle docker log should be:
`06/04/2024 00:43:28` `level=info msg=Accepting connections on :8080 time=2024-04-06T00:43:28Z`

The time shown in blue on the left, is the correct time
The time shown inside the log entry (white text, black background) is not the correct time


Another example from a seperate docker image (audiobookshelf).
This is a log line where the TZ is not set for this docker container (note the two different times):
![image](https://github.com/amir20/dozzle/assets/53024556/2492e2f0-def9-43f7-bcaa-c8b5795de015)

This is a logline where the TZ is set to Europe/Amsterdam for this docker container:
![image](https://github.com/amir20/dozzle/assets/53024556/ca96ee54-c981-4ba1-aa05-d95ffc40006a)

Setting the TZ env var for that container sets the correct local time for audiobookshelf.
This works for nearly all Docker containers, and I was hoping to do the same with Dozzle

**Comment by amir20** [comment]
I see. I think I know what the problem might be. I don't have a solution though. TZ is probably working but my logging utility is not using it. I am using logrus and according to https://stackoverflow.com/questions/40502309/how-can-i-set-the-logrus-time-to-utc it doesn't pick up TZ unless I implement my own formatter. Seems a little too complex. 

I don't think I'll prioritize this now but PRs are welcomed if you are up to it. 

However, that being said, I looked at [best practices](https://stackoverflow.com/questions/11537106/is-it-always-a-good-idea-to-store-time-in-utc-or-is-this-the-case-where-storing#:~:text=Generally%2C%20it%20is%20the%20best,off%20for%20that%20time%20zone.).  It seems like using UTC for logs is the most common thing to do. I don't know of any logging utility that allows you to change the timezone when logging. Instead, when reading, it should be presented in whatever timezone the UI needs it.

**Comment by ZTiKnl** [comment]
Ah that makes sense, thank you very much for digging into this and explaining!

The last thing I wanted to do here is cause extra work on something that is nothing more than a 'minor inconvencience' at worst, so do feel free to ignore/close this ticket ;)

**Comment by Vaskyy** [comment]
So to understand it right:
"      - TZ=Europe/Berlin" does nothing?
Since the times of my logging are off by 2 hours, even with that setting.

**Comment by yokonrad** [comment]
> So to understand it right: " - TZ=Europe/Berlin" does nothing? Since the times of my logging are off by 2 hours, even with that setting.

A little bit late... but yes - it does nothing. But you can set a time of your host by passing by a volume with reference to /etc/localtime.

Example for docker compose:
```
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
