### ISSUE TITLE
I don't want to track all docker container logs. 

### ISSUE THREAD

**Issue by satishsverma** [amir20/dozzle#2879]
I don't want to track some docker container logs. 

for example :-
nginx - show logs in dozzle ui
redis - don't show
postgresql - don't show
app - show logs in dozzle ui

could be possible?
- Thanks

**Comment by amir20** [comment]
You can use `--filter` with your own labels. Similar question asked https://github.com/amir20/dozzle/issues/2590

**Comment by satishsverma** [comment]
Thanks @amir20 

It's works.

**Comment by amir20** [comment]
Added https://dozzle.dev/guide/filters
