### ISSUE TITLE
Dozzle Config screen and Container Summary missing from Safari but present in Chrome

### ISSUE THREAD

**Issue by taw123** [amir20/dozzle#2885]
Thanks for the quick followup on the container management issue. I pulled your current container and v6.4.4 does indeed resolve the issue.

Since you closed thee issue I figured you wanted me to open a new one for the browser issue. I copied the content and created as new issue merging the relevant data.

For some bizarre reason **Safari** is showing a BLANK Container "Summery/Stats Page" without the settings settings header. Chrome on the same machine has not issue.

**Chrome working:**
<img width="1725" alt="Chrome- with data" src="https://github.com/amir20/dozzle/assets/10588252/6199883a-322e-4e45-ab87-43123f380211">

**Safari Failing:**
<img width="1603" alt="Safari- Session Data" src="https://github.com/amir20/dozzle/assets/10588252/9fe64743-cc81-424d-bfc1-ee098d90f82c">
<img width="1603" alt="Safari- Local Storage" src="https://github.com/amir20/dozzle/assets/10588252/58d48083-138a-416c-82ff-ed9ffd6cbf4e">

I might hazard a guess that it **could** potentially related to the following error...  BTW let me state up from the host is a QNAP NAS that peer QNAP default it has a generated self signed cert that is tied to it's IP (Link local) and not a cert for my actual domain IF that it potentially relevant). one day I will get around to setting up proper domain based certs via Lets encrypt but again bigger fish to fry at the moment and both the NAS and host are inside a firewall on LL addresses.

<img width="1746" alt="Safari- potentially related to the following error" src="https://github.com/amir20/dozzle/assets/10588252/953487d2-5274-4d46-9da7-bd66e7da3c0f">

**Desktop config:**
```
OS: MacOS 10.15.7 (19H2026)
Docker version: 20.10.27-qnap1
Browser & version: Safari 15.6.1 (15613.3.9.1.16, 15613) & Chrome: 15.6.1 (15613.3.9.1.16, 15613)
Version: 6.4.3 & 6.4.4

```

Again thanks for any insights you might have bit of a headscratcher.....

**Comment by amir20** [comment]
Hmm I use Safari often and am on `Version 17.4.1`.  I haven't seen this. Your version seems to be very old. It looks like a security exception based on the screenshot. Do you have an extension installed? Could you try a different Mac with newer Safari?

**Comment by amir20** [comment]
I think I see the problem. I use the latest javascript features and in the error I see that Safari is complaining about `toSorted()`. Based on https://caniuse.com/?search=tosorted this is not supported in Safari 15. Safari 15 is from 2021 so I think I would try to update if you can. Otherwise stick to Chrome.

**Comment by taw123** [comment]
Yeah it's an old system (Catalina based) so Safari 15 is as far as it goes.  I don't live on Chrome and only use on occasion to test a thing here or there. Guess I'll just live with it but thought I would mention in case anyone else mentions....   WOULD never have known there was a summary screen unless per chance I happened to open it also on chrome.  lol

Regardless, thanks for looking into it!
T

**Comment by amir20** [comment]
I have looked at this before to support older browsers, but it would compilation really complicated. If it's just `toSorted()` then I think I can replace it. But I wish there was a way to just tell me which features I am using that are not supported. Because there is no guarantee that in the future another page might use something new.

**Comment by amir20** [comment]
I looked in to this a bit. There is no easy tool that tell me all the new features I am using. So I don't think I will try to support legacy browsers.

**Comment by amir20** [comment]
I removed `toSorted()` and used a similar function that should work. Unfortunately, I did not find any way to tell me which features are not available for Safari 15.  See #2895.

**Comment by taw123** [comment]
Hot Dog!

TY.

It works like a champ.
<img width="1788" alt="Screen Shot 2024-04-20 at 1 55 58 PM" src="https://github.com/amir20/dozzle/assets/10588252/be57f711-ce87-4a53-9c86-38462291bbdb">

**Comment by amir20** [comment]
Nice. There is no way for me to test it. So thanks for screenshot! I wasn't able to find out what else might be missing but I think this is good enough for now.
