### ISSUE TITLE
Traefik 2.11 breaks Dozzle (fixed)

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#2887]
From one of the latest version seems the log visualization is broken
i have dozzle behind traefik2, it was fully working few days ago (i have configured for autoupdate to lates so i will tryto figure out the corretly broken version)

while trying to give more context here a little gif showing the issue:
![Apr-11-2024 12-37-07](https://github.com/amir20/dozzle/assets/4574593/5375c1dc-13db-420c-a6be-1bed1cc653f6)

**Comment by amir20** [comment]
@FrancYescO I used Traefik myself in production. I haven't seen this. If you can figure which version broke it then I can do a diff. Did anything change on your side?

**Comment by amir20** [comment]
From the gif it looks like the event stream is failing. Does Dozzle show any errors in logs?

**Comment by blaze6x6** [comment]
This is Traefik related. Had the same issue. Downgraded Traefik from latest (2.11.1) to 2.10.7 and it works like a charm. It didn't affect just Dozzle but my other containers too.

**Comment by amir20** [comment]
Ah yes, I have been running 2.10. Looks like I will hold to updating 🤣

**Comment by blaze6x6** [comment]
2.11.2 is available now. Didn't try it yet :)

**Comment by FrancYescO** [comment]
jesus..   @blaze6x6 thanks moving traefik back to tag v2.10 solved

seems it totally breaks up HTTPs stream randomly dropping the TCP stream (dozzle is just one of the service that it was breaking)

**Comment by FrancYescO** [comment]
> 2.11.2 is available now. Didn't try it yet :)

seems not.. :latest :v2.11 :3.0 tags of traefik have this issue and random `499 Client Closed Request` errors

**Comment by amir20** [comment]
Looking at the [changelog](https://github.com/traefik/traefik/releases), looks like a lot was changed regarding timeout for live connections. 

A lot of clients are going to be broken if their connection keeps getting closed.

**Comment by FrancYescO** [comment]
btw, just to better manage this cases on dozzle side.. i think you can avoid "resetting" the full ui and just keep the last received content like cached

**Comment by amir20** [comment]
There is some historical reasons. Caching of the container list is complicated because containers can also be deleted and the UI wouldn't know. I could do a diff but for now kept it simple. 

The logs is more complicated. I found in some edge cases the browser disconnecting would cause a memory leak and the only solution was to just delete the buffer.

**Comment by SGudbrandsson** [comment]
I just had this issue with Traefik 2.11.2

I downgraded to 2.10.1 and everything works properly for me now.

**Comment by blaze6x6** [comment]
Are you sure you were on 2.11.2? I am on latest version for about 20 hours now with no issues on any of my container.

**Comment by SGudbrandsson** [comment]
Hmm .. maybe the one before that, but I just downgraded to 2.10 and that fixed everything for me.

**Comment by amir20** [comment]
Closing since it looks like it is fixed.
