### ISSUE TITLE
Can't scroll up in side-by-side view

### ISSUE THREAD

**Issue by didmar** [amir20/dozzle#2894]
**Describe the bug**
When using Firefox and viewing two containers side-by-side, scrolling up with the mouse wheel does not work.
I did not have the issue with a different web browser (Chrome).

**To Reproduce**

1. Open a private window in Firefox 
2. Navigate to dozzle (e.g., http://localhost:8080)
3. Select any container and click on "Pin as column" button to create a side-by-side view
4. Click inside the logs to make sure it is focused
5. Scroll up with the mouse wheel, but nothing happens

**Expected behavior**
It should scroll up.

**Desktop (please complete the following information):**

- OS: Ubuntu Linux 22.04.4
- Docker version: 26.0.0
- Browser & version: Firefox 124.0.1
- Version: 6.4.6

**Comment by amir20** [comment]
This is a known issue https://github.com/amir20/dozzle/issues/547. I have no solution because I don't use a scroll wheel.

**Comment by amir20** [comment]
Closing this since I won't have time to fix it. If anybody is an expert in Firefox then it would be great if they can fix it.
