### ISSUE TITLE
Problem identifying "Fail"

### ISSUE THREAD

**Issue by 0xNakah** [amir20/dozzle#2904]
Hi Amir,

I hope this message finds you well. I've been using Dozzle and finding it extremely helpful for monitoring my Docker containers. Iam not if this is a bug or not but iam using the Dozzle to grab logs from a dotnet api application and it doesnt detect Fail/Exceptions as an error.

![Screenshot from 2024-04-18 10-32-23](https://github.com/amir20/dozzle/assets/69905009/1f7e8fb3-315a-4bee-9301-9f578ed7bf82)

**Comment by 0xNakah** [comment]
In dotnet, we can have "Crit" and "Fail" as an error message both return an 500 error!

**Comment by amir20** [comment]
Hmm I don't see `fail`. https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#log-level `fail` might be something your application is doing and not common in C#. 

TBH, I don't do a lot C#. So if you think you can send a PR then that would be great.  I won't have a lot of this month to add new levels.

**Comment by amir20** [comment]
So I tried running a C# container on Mac and was not able to. It doesn't seem like `fail` is a common level in C#. I am going to close. 

If you want to send a PR then that would be great.
