### ISSUE TITLE
feat: support copy permanent link URL to clipboard

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2907]
That's an interesting idea. The issue with that is I would personally expect it to go to current container eg. `/container/[id]` and not the share url which would be `/show?name=foo.bar`.

I think you are making it more complicated than it needs to be honestly. I have a view of which features people request the most. Being able to share is not one of them. So there is no reason to put something with one click.  

A better solution would be to put in the drop down and create a custom keyboard shortcut like `command + shift + C` or something like that and have that copy the URL too. 

Let's move this conversation to a new issue.

_Originally posted by @amir20 in https://github.com/amir20/dozzle/issues/2523#issuecomment-2067712900_

**Comment by amir20** [comment]
@adtc here is the issue.

**Comment by amir20** [comment]
<img width="225" alt="Screenshot 2024-04-20 at 8 49 54 AM" src="https://github.com/amir20/dozzle/assets/260667/ab34b677-1b0a-43b6-b2b2-16adea2a1478">

You can put it after `search` and may be call it `Share URL`? I think the name needs to be important because it is sharing the container by name and not ID.  Maybe call it `Copy permanent link`. 

You can see how I do the menu https://github.com/amir20/dozzle/blob/master/assets/components/LogViewer/LogActionsToolbar.vue 

and keyboard shortcut at https://github.com/amir20/dozzle/blob/b5b8650ce681fc02f4e77db125a3f04b1f2401c2/assets/components/LogViewer/LogContainer.vue#L47-L51

**Comment by amir20** [comment]
And https://github.com/amir20/dozzle/blob/master/assets/components/LogViewer/LogMessageActions.vue to properly look for copy and paste capabilities.

**Comment by ADTC** [comment]
Thanks. I'll check this out soon.

**Comment by amir20** [comment]
Any update on this? Do you still plan to do this?

**Comment by ADTC** [comment]
Yes, just swamped right now, and travelling. Please keep it open.

**Comment by amir20** [comment]
Gonna close this.
