### ISSUE TITLE
Podman Socket Connection Issue

### ISSUE THREAD

**Issue by seaborn-sandia** [amir20/dozzle#2913]
**Describe the bug**
Dozzle is deployed on a rootless podman host where the socket is enabled and running without issue. The `DOCKER_HOST` variable is specified and points to the running podman socket. When the container starts, however, it reports '*Could not connect to any Docker Engines*' and fails. I suspect I am forgetting something but I cannot seem to figure out what I am forgetting, any help is greatly appreciated.

**To Reproduce**
- Install podman rootlessly on an EL8 machine
- Enable the podman socket for your current user
- Write the compose script shown below
- Deploy the container with `podman compose`

**Expected behavior**
Dozzle should start up, find the podman sock through the mountpoint or through the `DOCKER_HOST` variable and should be able to submit API requests from there

**Desktop (please complete the following information):**
```bash
$ cat /etc/*release
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
$ docker version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.6
Built:        Mon Oct  9 10:15:55 2023
OS/Arch:      linux/amd64
```

```bash
$ systemctl --user status podman.socket 
● podman.socket - Podman API Socket
   Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; vendor preset: enabled)
   Active: active (listening) since Mon 2024-04-22 09:29:27 MDT; 55min ago
     Docs: man:podman-system-service(1)
   Listen: /run/user/1001/podman/podman.sock (Stream)
   CGroup: /user.slice/user-1001.slice/user@1001.service/podman.socket

Apr 22 09:29:27 workstation systemd[5802]: Listening on Podman API Socket.
$ cat podman-compose.yaml 
version: "3"

services:
  dozzle:
    container_name: dozzle
    image: localhost/dozzle:latest
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      - DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock

$ podman-compose up
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=dozzle', '-a',
'--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'dozzle_default']
podman create --name=dozzle \
  --label io.podman.compose.config-hash=fffa4ca5ae57116fc417eae6c453c7a5e70f78c4b7cbb929c8336521d23b9a54 \
  --label io.podman.compose.project=dozzle --label io.podman.compose.version=1.0.6 \
  --label PODMAN_SYSTEMD_UNIT=podman-compose@dozzle.service --label com.docker.compose.project=dozzle \
  --label com.docker.compose.project.working_dir=/home/ahdial/Documents/development/containers/dozzle \
  --label com.docker.compose.project.config_files=podman-compose.yaml \
  --label com.docker.compose.container-number=1 --label com.docker.compose.service=dozzle \
  -e DOCKER_HOST=unix:///run/user/1001/podman/podman.sock \
  -v /run/user/1001/podman/podman.sock:/var/run/docker.sock --net dozzle_default --network-alias dozzle \
  -p 9999:8080 localhost/dozzle:latest
16a693f6a919b7a5c12df50f7d689cba65c5c52d6b07e97f4f16f90e7780402a
exit code: 0
podman start -a dozzle
time="2024-04-22T16:19:18Z" level=info msg="Dozzle version v6.5.1"
time="2024-04-22T16:19:18Z" level=fatal msg="Could not connect to any Docker Engines"
exit code: 1
```

**Comment by amir20** [comment]
Thanks for the details. I don't know podman well and wouldn't be the best person to set it up and test it. However, looking at your compose file I think I spot a mistake. You shouldn't need to use `DOCKER_HOST` and mount `/var/run/docker.sock`. You only need to mount it if you plan to use the sock file OR `DOCKER_HOST` for a remote connection. 

In this case, I think removing `DOCKER_HOST` should work.

**Comment by amir20** [comment]
Also, what is `localhost/dozzle:latest`? Are you building yourself?

**Comment by seaborn-sandia** [comment]
Thank you for the quick response, I appreciate it. I have yet to use the socket service rootlessly so I am no expert either. Oh okay, the `DOCKER_HOST` is for external host monitoring, that makes sense. I went ahead and removed the environment variable but ran into the same issue.
```bash
$ cat podman-compose.yaml
version: "3"

services:
  dozzle:
    container_name: dozzle
    image: localhost/dozzle:latest
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock
    ports:
      - 9999:8080

$ podman-compose up
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=dozzle', '-a',
'--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'dozzle_default']
podman create --name=dozzle \
  --label io.podman.compose.config-hash=690bb931e8b7283a32523343f1b0a6c6aba1151959ea73490370417bac5c0951 \
  --label io.podman.compose.project=dozzle --label io.podman.compose.version=1.0.6 \
  --label PODMAN_SYSTEMD_UNIT=podman-compose@dozzle.service --label com.docker.compose.project=dozzle \
  --label com.docker.compose.project.working_dir=/home/ahdial/Documents/development/containers/dozzle \
  --label com.docker.compose.project.config_files=podman-compose.yaml \
  --label com.docker.compose.container-number=1 --label com.docker.compose.service=dozzle \
  -v /run/user/1001/podman/podman.sock:/var/run/docker.sock --net dozzle_default --network-alias dozzle \
  -p 9999:8080 localhost/dozzle:latest
e0b7dc25cdf12ff1c7bbf72a108932adda860aee036253b97c562c2fa7ae7864
exit code: 0
podman start -a dozzle
time="2024-04-22T17:18:40Z" level=info msg="Dozzle version v6.5.1"
time="2024-04-22T17:18:40Z" level=fatal msg="Could not connect to any Docker Engines"
exit code: 1
```
Oh good question about the image. I am pulling the Dozzle 6.5.1 and then relabeling it as a localhost image for reasons. It's the same image as the 6.5.1 image available on Dockerhub, I just smacked on another label and called it through there.
Just as a sanity check, I ensured that the sock was owner by my user and thus available for my services to reach.
```bash
$ ll /run/user/1001/podman/podman.sock
srw-rw----. 1 1001 1001 0 Apr 22 09:29 /run/user/1001/podman/podman.sock
```
I have tried a few different formulations of the sock path including specifying it directly as `/run/user/1001/podman/podman.sock` instead of using the `$XDG_RUNTIME_DIR` environment variable but no use so far.

Thank you again for helping me to debug this.

**Comment by amir20** [comment]
Try enabling debug `--level debug` and let me know what that prints. It sounds like something is not connecting locally.

**Comment by amir20** [comment]
Ah interesting. I wouldn't know too much about it as it seems to be specific to podman. 

I'll have to do some digging when I get a chance. Unfortunately, I am only on a Mac so it wouldn't be easy to replicate though. 

I wonder if you can use `curl --unix-socket /var/run/docker.sock http://localhost/v1.44/containers/json`

If you can get that to work first then theoretically it should work with Dozzle.

**Comment by seaborn-sandia** [comment]
Oop, it was a podman issue. As [someone described](https://github.com/containers/podman/discussions/14238#discussioncomment-2746415) in a podman-related issue: operations on the podman sock require that the container be run with the `--privileged` flag. I went ahead and added that flag to my compose file like so:
```yaml
version: "3"

services:
  dozzle:
    container_name: dozzle
    image: localhost/dozzle:latest
    privileged: true
    volumes:
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    environment:
      - DOZZLE_LEVEL=debug
```
Bring that container online rootlessly but with the privileged flag resulted in a successful start.
```bash
podman start -a dozzle
time="2024-04-22T19:06:17Z" level=info msg="Dozzle version v6.5.1"
time="2024-04-22T19:06:17Z" level=debug msg="filterArgs = {map[]}"
time="2024-04-22T19:06:17Z" level=debug msg="Connected to local Docker Engine"
time="2024-04-22T19:06:17Z" level=info msg="Connected to 1 Docker Engine(s)"
time="2024-04-22T19:06:17Z" level=info msg="Accepting connections on :8080"
time="2024-04-22T19:06:17Z" level=debug msg="subscribing to docker events from container store localhost"
time="2024-04-22T19:06:17Z" level=debug msg="Post \"https://b.dozzle.dev/event\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```
Thank you for helping me to debug this!

**Comment by amir20** [comment]
That's awesome! Woohoo.

**Comment by JonBendtsen** [comment]
--privileged was the answer for me too, and I am indeed running podman desktop on a mac
