### ISSUE TITLE
Why the log shows that the service is shutting down automatically

### ISSUE THREAD

**Issue by dnslin** [amir20/dozzle#2921]
**Describe the bug**
```
2024/04/30
15:54:11
level=
info
msg=
shutting down gracefully, press Ctrl+C again to force
time=
2024-04-30T07:54:11Z
2024/04/30
15:54:11
level=
debug
msg=
shutdown complete
time=
2024-04-30T07:54:11Z
2024/04/30
15:57:04
level=
info
msg=
Dozzle version v6.5.1
time=
2024-04-30T07:57:04Z
```

**Desktop (please complete the following information):**

- OS: debian12 
- Docker version Docker-compose latest
- Browser & version chrome
- Version latest

**Comment by amir20** [comment]
Your question is vague. It's not automatic. It's just a regular shutdown. Maybe out of memory or something else.
