### ISSUE TITLE
Feature request : Be able to download only STDOUT or only STDERR logs

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#2922]
Currently when downloading the logs we get both STDOUT and STDERR is the same file.
It would be great if we could choose to only download STDOUT or only STDERR.

An idea would be to have these entries in the menu : 
"Download ALL"
"Download STDOUT only"
"Download STDERR only"

This can be useful for a nginx container where one would like to only download the content of access.log (STDOUT) or only the content of error.log (STDERR)

**Comment by amir20** [comment]
Not a bad suggestion. 

I think it would make more sense to download what the browser is showing. Adding more labels is never a good idea as it makes the UX cluttered. Luckily there is already an option to show only stdout or err so I can reuse that for the download.
