### ISSUE TITLE
Feature Request : AVG.CPU (%) and AVG.MEM(%) : allow live updating of sorting

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#2925]
Currently when sorting containers on AVG.CPU(%) or AVG.MEM(%), the sorting is not updated automatically. The containers are only sorted at the time the column header is clicked.

Here is an example : 
![image](https://github.com/amir20/dozzle/assets/11772429/1943a43b-7529-40ed-8bcc-46a1690e60b5)

The sort order was correct when i clicked on the column to sort the containers by AVC.CPU (%): Only the first container was consuming 25% of the CPU and the other containers 0%.
But some seconds later you can see that some containers started to use the CPU (you can see the last one at 3% CPU for example) and that their order was not refreshed.

I don't know if it is a bug or working as intented.

**Comment by amir20** [comment]
Works as intended. I used to have it sort but for 100 containers would spike CPU to more than 40%. I think a better compromise is to sort every 10s. But wouldn't say that's highest on my priority.

**Comment by amir20** [comment]
Updated to every 10s.
