### ISSUE TITLE
Merge logs from the same container on different servers.

### ISSUE THREAD

**Issue by luisgs7** [amir20/dozzle#2927]
Hello everyone, I have an application that has two load balancer servers, but I need to merge the logs from the same application that are running on different servers, to facilitate the debugging process, I would like to know if dozzle has any resources for this, or is there any recommendation.

Thanks in advance.

**Comment by amir20** [comment]
No plans for this right now. I was thinking of supporting Swarm services in the future but it doesn't sound like you are using Swarm. 

It's actually pretty complicated to do this because Dozzle groups similar logs together. So having more than one container would break that.

**Comment by amir20** [comment]
Haven't heard back.

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/issues/2960. I am thinking about this a little more.
