### ISSUE TITLE
Multiple filters?

### ISSUE THREAD

**Issue by dmd** [amir20/dozzle#293]
Is it possible to have multiple dozzle_filters? What would be the syntax?

**Comment by amir20** [comment]
You should be able to use `,` to separate filters. I convert `,` to `&` and [parse as URL params](https://github.com/amir20/dozzle/blob/master/main.go#L65).

**Comment by dmd** [comment]
Thanks!

**Comment by 123dev** [comment]
How do you do this with docker-compose environment?
`,` does not work, and defining multiple `DOZZLE_FILTER` environments makes only the last one work.

**Comment by amir20** [comment]
@123dev `,` should work. Can you show me your command? 

I did `docker run -e DOZZLE_FILTER=name=foo,status=running --volume=/var/run/docker.sock:/var/run/docker.sock amir20/dozzle --level debug` which basically what compose would do. 

It prints `level=debug msg="filterArgs = {map[name:map[foo:true] status:map[running:true]]}"` which means it worked.

**Comment by 123dev** [comment]
Hi,

Thanks for the follow up, can you please try with multiple name values?
`DOZZLE_FILTER=name=a-test,name=b-test`

I need to restrict it to predefined set of container names.
I don't think I can use a wildcard, hence trying to specify multiple of them.

Thanks

**Comment by amir20** [comment]
I see what you are trying to do. I don't think that is possible right now. I looked at the code and I am using maps. I'd have to figure out a way to parse map of lists. 

I don't think it's worth doing this. Do you really need it or can you use labels?

**Comment by 123dev** [comment]
Thanks for trying, I'll try labels, its just that there are containers already running that don't have labels.
I'm sure I can get it to work.

Thanks again.

**Comment by amir20** [comment]
Cool. I'll probably eventually get around to matching how Docker works. But I am using an external library for parsing flags which currently doesn't support lists like this.

**Comment by 123dev** [comment]
Thanks a bunch @amir20 no urgency, for all future containers, I'm setting labels, which should be fine, I'll try to phase out existing containers as it is impossible to add a label after the creation.

Thanks for all your efforts and sharing.
Have a good day

**Comment by amir20** [comment]
@123dev go-arg's author gave me a quick turn around to fix the bug for `--filter`. https://github.com/amir20/dozzle/pull/1200 adds support for multiple `--filter`. And it was minimal work from me. Thanks @alexflint!
