### ISSUE TITLE
Resources dashboard for remote host

### ISSUE THREAD

**Issue by garanda21** [amir20/dozzle#2931]
**Is your feature request related to a problem? Please describe.**
When navigate to the main Dashboard, with the list of containers and Memory/CPU resources, seems that it's always stick to localhost, in case you wanna see those resources for any `DOZZLE_REMOTE_HOST` there's no option.

**Describe the solution you'd like**
Would be nice to have a dropdown on the dashboard to choose between different hosts and see host resources too

**Additional context**
My localhost is "Synology", but also want to see "Raspi" Dashboard

<img width="664" alt="Captura de pantalla 2024-05-04 a las 18 35 23" src="https://github.com/amir20/dozzle/assets/9530250/843cbc8a-d94f-449f-9b02-4eeebeb4dc43">

**Comment by amir20** [comment]
Duplicate https://github.com/amir20/dozzle/issues/2842 :)
