### ISSUE TITLE
Feature request : Provide an endpoint that returns in json format the stats displayed on the main page

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#2938]
Do you think it would be possible to have an endpoint (ex: http://localhost:8888/stats) that returns what is displayed on the main page but in a json format ? 

![image](https://github.com/amir20/dozzle/assets/11772429/dcfdd9fd-c33d-4be5-81ee-bd37df083f6d)

Idea of json output : 

```
{
    executing: 41
    total: 41
    cpu: 0.05
    mem: 7160
    version: "6.5.2"
    containers: [
        {
            container_name: "my-container-1"
            host: "localhost"
            status: "running"
            created: 2024-05-08"
            cpu_avg: 0.10
            mem_avg: 0.50
        },
        {
            container_name: "my-container-2"
            host: "localhost"
            status: "running"
            created: 2024-05-01
            cpu_avg: 0.35
            mem_avg: 0.15
        }
    ]
}
```

It would allow to monitor the containers from a monitoring app that is outside the host using the Dozzle endpoint :)

I've searched on the internet if there was already some existing docker image that allows to expose docker stats through an http server endpoint, but can't find any.

**Comment by amir20** [comment]
I think this is outside of scope of Dozzle. But even more importantly a lot of logic happens on the front end which means it would not be available to API. 

Additionally, API would be very complicated to support correctly with authentication.
