### ISSUE TITLE
Dozzle mobile version

### ISSUE THREAD

**Issue by VinceVinceVinceVinceVinceVince** [amir20/dozzle#2941]
I would like to be able to start containers via dozzle from my phone. As i try to enable the desktop mode in the settings i cannot find the desktop site option.
Does anyone know how to solve the issue descriped above?
Best regards
Vincent

**Comment by VinceVinceVinceVinceVinceVince** [comment]
no does not work.

**Comment by VinceVinceVinceVinceVinceVince** [comment]
what else could work?anybody knows?

**Comment by amir20** [comment]
It's hard to help you when there isn't any details. Take a screenshot with your phone rotated. 
The menu is there for me. 


<img width="936" alt="Screenshot 2024-05-15 at 8 18 01 AM" src="https://github.com/amir20/dozzle/assets/260667/17bec1ee-70a2-492c-89aa-7e3870ba0fbe">
