### ISSUE TITLE
Error with every page refresh

### ISSUE THREAD

**Issue by marcinwolosz** [amir20/dozzle#2953]
Hi, everytime i refresh page, for a very short time, i see an error. 
I use remote host
take a look at the video

https://github.com/amir20/dozzle/assets/26607977/9d467850-fb1d-4bf9-b455-137e4c0203ec

![Zrzut ekranu 2024-05-13 125101](https://github.com/amir20/dozzle/assets/26607977/4b54ae0e-4300-45de-9862-921afa741b13)

It looks like it doesn't appear on chrome or opera.
For firefox. it might be related with **/api/events/stream** endpoint. 

- OS: Windows
- Browser: Firefox 125.0.3
- Dozzle version: 6.6

With debug logs i see:

```
time="2024-05-13T10:56:56Z" level=debug msg="context done, closing event stream"
time="2024-05-13T10:56:57Z" level=debug msg="resetting timer for container stats collector tcp:address.com:2376"
time="2024-05-13T10:56:57Z" level=debug msg="Cache miss for []releases.Release"
time="2024-05-13T10:57:06Z" level=debug msg="context done, closing event stream"
time="2024-05-13T10:57:06Z" level=debug msg="Cache hit for []releases.Release"
time="2024-05-13T10:57:06Z" level=debug msg="resetting timer for container stats collector tcp:address.com:2376"
```
Thanks

**Comment by amir20** [comment]
Yea, it happens to me too on Firefox. But I am not sure how to fix it. It's because event source disconnects and Dozzle thinks it's broken. 

Do you know of a fix?

**Comment by marcinwolosz** [comment]
hmmm, maybe we can just wait a few seconds before showing toast? :)
```go
es.addEventListener("error", (e) => {
      if (es?.readyState === EventSource.CLOSED) {
        setTimeout(() => {
          showToast(
            {
              id: "events-stream",
              message: t("error.events-stream.message"),
              title: t("error.events-stream.title"),
              type: "error",
            },
            { once: true },
          );
        }, 5000); // 5sec delay
      }
    });

```

**Comment by marcinwolosz** [comment]
Maybe we can just wait for a few seconds before showing toast? :)

```go
    es.addEventListener("error", (e) => {
      if (es?.readyState === EventSource.CLOSED) {
        setTimeout(() => {
          showToast(
            {
              id: "events-stream",
              message: t("error.events-stream.message"),
              title: t("error.events-stream.title"),
              type: "error",
            },
            { once: true },
          );
        }, 5000); // 5sec delay
      }
    });

```

**Comment by amir20** [comment]
That's what I was thinking too. But I went a different direction after debugging. `readyState` is `CONNECTING` for a bad state and `CLOSING` with a good close. I did that change https://github.com/amir20/dozzle/pull/2958

Can you try `amir20/dozzle:pr-2958`?

**Comment by marcinwolosz** [comment]
Yep, it works!

**Comment by amir20** [comment]
Merged. Will release when there is more fixes.
