### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by zodac** [amir20/dozzle#2962]
**Is your feature request related to a problem? Please describe.**
I use [Authentik](https://github.com/goauthentik/authentik) as an identity provider in front of Dozzle, so authentication is handled there and then the request is forwarded on to Dozzle. I also use [Uptime-Kuma](https://github.com/louislam/uptime-kuma) to monitor my services. If a healthcheck endpoint existed for Dozzle, that could be excluded from an auth flow and used for monitoring the status of the service. It would also be useful for setting up a `healthcheck` section in docker-compose setups.

**Describe the solution you'd like**
A new URL (dozzle.domain/status) which returns a HTTP 200/204 when the service is online.

**Describe alternatives you've considered**
There are some workarounds for Uptime-Kuma (discussed [here](https://github.com/louislam/uptime-kuma/issues/4220#issuecomment-1853816474)), though it does make the monitoring more complex than it needs to be. A simple healthcheck makes monitoring in general easier, for other monitors or even docker/k8s.

**Comment by amir20** [comment]
So this https://dozzle.dev/guide/healthcheck? 

`/healthcheck` already exists too which isn't auth protected.

**Comment by zodac** [comment]
Well, I feel foolish. I don't know how I missed it. Apologies, and thanks for the link!
