### ISSUE TITLE
Feature Request: Network stats on dashboard

### ISSUE THREAD

**Issue by jordanlambrecht** [amir20/dozzle#2964]
<img width="725" alt="Screenshot 2024-05-20 at 09 08 39" src="https://github.com/amir20/dozzle/assets/54866853/95aba84d-f7b1-47f1-aa1a-c7b927a78ee9">

On the main dashboard, it would be great to see network usage in addition to ram and cpu. Not sure if that's a heavy lift or not though.

**Comment by amir20** [comment]
Too much work 😂

**Comment by jordanlambrecht** [comment]
@amir20 hahaha feel that hard.

**Comment by amir20** [comment]
Working on Swarm support right now which seems to be a A LOT of work. So maybe I'll look at this in future.
