### ISSUE TITLE
"Swam" mode? 🏊

### ISSUE THREAD

**Issue by darkvertex** [amir20/dozzle#2991]
**Describe the bug**

"Swam Mode" should read "Swarm Mode":
https://github.com/amir20/dozzle/blob/aed903d57d45bbf0cf86fe3ff897f5f0e709cfaf/locales/en.yml#L26

**Screenshots**
<img width="137" alt="image" src="https://github.com/amir20/dozzle/assets/941331/97d87737-4375-45f3-8897-3f0710aa14ee">

**Comment by amir20** [comment]
😁

**Comment by amir20** [comment]
Not sure to be disappointed that no one said anything until now or happy that I finally know.

**Comment by darkvertex** [comment]
Haha.. well, thanks for the quick fix! lol 😁
