### ISSUE TITLE
Remove need for docker.socket on dozzle container when using swarm and DOZZLE_REMOTE_HOST enviroment variables

### ISSUE THREAD

**Issue by githubbiswb** [amir20/dozzle#3003]
I love the changes so docker swarm is supported! Well done sir! At the end of this is a working docker swarm setup for my 5 node cluster anyone can use, feel free to adapt it and adopt it in any documentation you want to update. 

With that said, as you can see in my 5 node cluster, each proxy already has access to the docker socket for reading. Dozzle is smart enough it seems to not duplicate the logs on the docker node where dozzle and its proxy container both happen to be running. 

Still it would be really cool if dozzle when seeing it had remote hosts specified ignored its need for a docker socket mount at all, since it goes to query the proxy that is already running on the node it happens to be living on. 

Lastly, in my implementation there is not even a need to expose ports on the proxy sockets since they all live in a network together on stack creation. With a reverse proxy (which I plan to do) you wouldn't even need to expose the dozzle port either. This really locks down even read-only access to the docker socket.

[doz.txt](https://github.com/user-attachments/files/15522556/doz.txt)

**Comment by amir20** [comment]
Thanks! 

> Still it would be really cool if dozzle when seeing it had remote hosts specified ignored its need for a docker socket mount at all, since it goes to query the proxy that is already running on the node it happens to be living on.

This is already possible! 

In fact, I have been playing with 5+ nodes with Swarm locally and I am able to do 

```
docker run  -p 8080:8080 amir20/dozzle --remote-host "tcp://198.19.249.84:2375|node1" --remote-host "tcp://198.19.249.68:2375|node2" --remote-host "tcp://198.19.249.16:2375|node3"
```

Local socket is not required. 

> Lastly, in my implementation there is not even a need to expose ports on the proxy sockets since they all live in a network together on stack creation. With a reverse proxy (which I plan to do) you wouldn't even need to expose the dozzle port either. This really locks down even read-only access to the docker socket.

That's great. Yes if everything is in a compose file then it should just work like that. If I get a chance, I will update the docs. 

Btw, have you tried `--mode global` in Swarm. I feel like it should be able to deploy each. I just don't know how the port forwarding would work. I wonder if `host:2375` would still work.

**Comment by githubbiswb** [comment]
Ah! Yep that does work without the local socket. I must have had another config change that was keeping dozzle from coming up and fixed it along the way! Awesome!

I will look into global, I do want to use it. The trick is finding a way to have a static name given to each global container.... and this might be the ticket?

https://stackoverflow.com/questions/40467716/set-hostname-of-service-container-to-hosts-hostname

**Comment by githubbiswb** [comment]
Got it! See attached
[doz.txt](https://github.com/user-attachments/files/15525817/doz.txt)

**Comment by amir20** [comment]
That's awesome! Looks like the pet forwarding just works. 🎉

**Comment by amir20** [comment]
Hey @githubbiswb can you take a look at https://github.com/amir20/dozzle/issues/3052 and provide some feedback? I have been thinking about agent mode and as a swarm power user I think your feedback would be great.
