### ISSUE TITLE
Log incorrectly displaying as JSON

### ISSUE THREAD

**Issue by danielnhoward** [amir20/dozzle#3006]
**Describe the bug**

When NextJS fails to fetch an image, it logs the following line:

```
upstream image response failed for https://www.gravatar.com/avatar/37296937a4c3c7fd1472c792da3c3704?d=mp&d=404&s=150 404
```

When this line is viewed in Dozzle, it seems to think that it is json encoded, and displays the following:

```
failed= for= image= response= upstream=
```

**Screenshots**
In Docker Logs:
![image](https://github.com/amir20/dozzle/assets/67344225/97174c4c-8dfb-4c33-b4d8-2c97ea266902)

In Dozzle:
![image](https://github.com/amir20/dozzle/assets/67344225/122e75d8-caf1-4aa4-a51b-47ee2195d874)

**Desktop**

- OS: Windows 11
- Docker version: 24.0.5
- Browser & version: Brave 1.66.118
- Version: v7.0.3

**Comment by amir20** [comment]
Hey! This is actually because Dozzle support logfmt with `key=value` format. Seems like the `=` is breaking it though. I am using some library, but the parsing is too broad. I think I'll have to rewrite this section of the code since so many people have complained about it. 

I'll have something to test in few days.

**Comment by danielnhoward** [comment]
Thanks for taking a look!

**Comment by amir20** [comment]
@danielnhoward Try `amir20/dozzle:pr-3007`. I didn't do a whole a lot of testing so if you can test a lot to make sure I didn't break anything else would be appreciated!

**Comment by amir20** [comment]
Did more testing. Found 1 bug. Going to release later today unless someone finds a new bug.

**Comment by danielnhoward** [comment]
Thanks for fixing this! (Apologies, I was away from my computer so unable to do any testing)
