### ISSUE TITLE
Dozzle container crashes when null is logged

### ISSUE THREAD

**Issue by BigEnoter** [amir20/dozzle#3011]
**Describe the bug**
Apparently Dozzle seems to crash when anything logs `null` & container's page that logged it is opened

**To Reproduce**

1. Start Dozzle container (1)
2. Start another container (2) which may log `null` in console (in my case that was simple Express application)
3. Open logs page for container (2)
4. Log `null` in console

**Expected behavior**
Dozzle will not crash and log `null` correctly

**Screenshots**
When the logs page for container (2) is opened & null is logged that's what happens
![image](https://github.com/amir20/dozzle/assets/32816798/f6e93d51-d820-44ea-a971-9e1fb02dee79)

**Desktop (please complete the following information):**

- OS: Windows, Ubuntu 20.04
- Docker version: 26.0.0, 26.1.1
- Version: 7.0.4

**Comment by amir20** [comment]
Do you mean literal "null"? Or actual null like `log.info(null)`. 

The stack trace helps so I think I can figure out what might be the issue.

**Comment by BigEnoter** [comment]
The actual null, yeah

**Comment by amir20** [comment]
It's hard for me to reproduce since I have to figure out how to actually log null. But based on the error I think I fixed it in https://github.com/amir20/dozzle/pull/3012

Can you try `amir20/dozzle:pr-3012`? 

I wonder if something else might be broken.

**Comment by BigEnoter** [comment]
Yep, with #3012 it doesn't crash anymore, looks like this now
![image](https://github.com/amir20/dozzle/assets/32816798/bfb20ad2-b4ed-4f4d-a774-dd02e6d042e0)
The blank spaces are the ones where `null` is logged (doing so by `console.log(null)`)

**Comment by amir20** [comment]
Oh that's still ugly. Ok I think I'll need actually create a real test and possibly replace null with "".

**Comment by amir20** [comment]
OK this was more complicated than I thought 🤯 Turns out `"null"` is valid json so it got parsed correctly but then turned back to `nil` which broke everything. 

I think my latest push fixes it by replacing `null` with "".

**Comment by BigEnoter** [comment]
Yup, now it seems to be just an empty string
![image](https://github.com/amir20/dozzle/assets/32816798/dd6040e8-6d0a-4905-ad47-2aeb3bd03896)

**Comment by amir20** [comment]
Cool. Merging. Will release later today after my work day.
