### ISSUE TITLE
Scrollbar for search menu

### ISSUE THREAD

**Issue by Shmatthew** [amir20/dozzle#3017]
Hello!

Is it possible to expand or add a scrollbar for the search menu?
When you entering search menu and type some words, it shows you only 5 matches. It's not very comfortable when u want to search or just see some services in your huge docker stack, for example. Or to see all containers with the same name match at once. (if there is more then 5 copies deployed)
This would be a very useful feature i think. At least in our company everyone would like this))

Thanks!

**Comment by amir20** [comment]
Hello! @Shmatthew could you help me understand your use case? I only show top 5 because I'd hope that if someone searches for something specific then the sorting algorithm is good enough to be in the top 5. What are you searching and how many containers do you have? Screenshots would help.

**Comment by Shmatthew** [comment]
I'm sorry but I can't show screenshots for some reasons)
We have docker swarm cluster with 5 nodes with multiple docker stacks. Some of these stacks contain about 40 containers for example. And some of swarm nodes have more than 250 containers. Some services have more than 6 words in their names and and may differ only in the last word for example. And its a little bit hard to search them by your eyes in the left menu list, and also swapping between other nodes to see wich of them deployed required container.

For ex.
We have containers:
my-stack-name_abc-cba-111
my-stack-name_abc-cba-222
my-stack-name_abc-cba-333
...
my-stack-name_abc-cba-777

In search menu i remember that containers that i need have that part of their name: "my-stack-name_abc-cba", and i dont remember what is in their last word. The search menu will only show me 5 matches, not all these 7 containers. And if these names not a containers' but services' names wich have multiple replication, in that case we have much more than 7 containers with slightly similar names in different masters, that can't be searched in the search menu. Only if i type their full container or service name wich is not easy to remember sometime)

**Comment by amir20** [comment]
I see. That actually makes sense. I think it does make sense to expand more than 5 given your use case and I agree that when names are similar it is confusing. 

I am hoping to not add a scrollbar but let me play with it today to see what it looks like on mobile.

**Comment by amir20** [comment]
Seems to be ok with 10. So I am going to merge. Try `amir20/dozzle-master`

**Comment by Shmatthew** [comment]
Thank you very much! I've tried it already. Top 10 is better of course. But it still not enough for our environment in some searches. And when I saw this list of 10 our services, I started scrolling for other matches intuitively)) Btw top10 is ok in many cases i think.
So, if it's hard to do to show all the matches in this "top10" window with a scrolbar and it will degrade performance or not be usable on moblies, then we can close this task, no problem. Top5 is 100% not comfortable, top10 is much better.

**Comment by amir20** [comment]
Hmmm ok I think I see what you are saying now. Your idea is to actually not limit any results and just show them. Is that right? I use https://www.npmjs.com/package/fuse.js and am not sure if it would break. Ideally, fuse.js would be smart enough to have a threshold and only show matches that are within the threshold. 

What's a good test for myself? I am guessing I should create 50+ containers with similar name like `test-foo-bar-XXX` and randomize the XXX.  Is that similar to your use case? 

I like this approach personally. Assuming fuse.js works then it might be a better experience.

**Comment by amir20** [comment]
Ok a lot more CSS than I thought and admittedly I am not an expert.  But I think I have something working. 

You can see the video at #3029 and test it with `amir20/dozzle:pr-3029`. I'll hold off merging since this is requires testing in a few browsers and mobile.

**Comment by amir20** [comment]
I have been testing #3029 and been pretty happy actually with the experience. Thanks for the suggestion. Let me know how your testing goes. I have tested in mobile, multiple browsers of different screen sizes.

**Comment by Shmatthew** [comment]
It's sooo amazing right now!
Great thanks to you from our team!
