### ISSUE TITLE
Allow dozzle to monitor logs across different servers

### ISSUE THREAD

**Issue by sefininio** [amir20/dozzle#3021]
**Is your feature request related to a problem? Please describe.**
I have multiple servers installed in my house (4 RPis, a NAS, a media server, etc). This means each should run its' own dozzle container to be able to monitor logs.

**Describe the solution you'd like**
Like Portainer has the option to run agents on remote machines and a single main container on the main server - Something similar would be great - so that each will run a dozzle agent reporting to the main dozzle container.

**Comment by amir20** [comment]
There is no agent but you can do https://dozzle.dev/guide/remote-hosts#connecting-with-a-socket-proxy

I debated this a lot in my head. Having an agent would be very complex. And very few would use it.

**Comment by sefininio** [comment]
OK.
Is it possible to load multiple remote hosts with the `--remote-host ` flag?

**Comment by amir20** [comment]
Yes.
