### ISSUE TITLE
health status

### ISSUE THREAD

**Issue by Cronist** [amir20/dozzle#3026]
**Is there a way to see the health status of the containers on the dashboard as a column that has health checks?**
It would be perfect to see the health status of the containers on the dashboard as a column that has health checks.

**there is a column named "status" on the dashboard and it is sayıing "running"**
on the docker ps output, it says healthy or running or restarting etc.

thank you in advance.

**Comment by amir20** [comment]
This is actually pretty complicated because in Dozzle everything is event based. Docker API doesn't have a "status changed" event so the UI would never update. 

Also it wouldn't make much sense to do this because on the homepage, only the "running" containers are shown.
