### ISSUE TITLE
inspect

### ISSUE THREAD

**Issue by Cronist** [amir20/dozzle#3027]
"inspect" would be perfect if Dozzle had this feature.

**Comment by amir20** [comment]
I have no idea what you mean by inspect.  

Share the use case and what you mean exactly. Some things make sense to be part of Dozzle if it helps to debug and monitor.

**Comment by Cronist** [comment]
I mean for debugging purposes there is a command like "docker inspect d7e744bc5d41"
the last part of the command is the ID of the running container.
it shows all the info about the container networking, image, status, ports, IP addresses, config, health status, health checks, ENVs etc. 
it is so useful for debugging. but I dunno if the API has that interface or not.

just a part of that command output.

```
        "Config": {
            "Hostname": "d7e744bc5d41",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOZZLE_AUTH_PROVIDER=simple",
                "DOZZLE_HOSTNAME=Securify Identity",
                "DOZZLE_NO_ANALYTICS=true",
                "PATH=/bin"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "/dozzle",
                    "healthcheck"
                ],
                "Interval": 3000000000,
                "Timeout": 30000000000,
                "StartPeriod": 30000000000,
                "Retries": 5
            },
            "Image": "amir20/dozzle:latest",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/dozzle"
            ],
            "OnBuild": null,
            "Labels": {

```

**Comment by amir20** [comment]
Hmm the goal of Dozzle is to solve a user need. There is a lot of data Docker has available I can display but it would just make the UI confusing. I rather be international. `docker inspect` use case is broad so it would be hard to nail on a specific use. As an example,  inspect lets you see health status. But that's already possible. You can also see image name and that's displayed at top. Inversely,. you can also see `hostname` and `volumes`. But what would be the value of that. Those are very niche and specific things that might be better just use `docker inspect`.

**Comment by amir20** [comment]
Closing as I don't see any value for users.

**Comment by Lockszmith-GH** [comment]
Came here to look for this request - this is probably the command I use most on the cli, it allows me to check how the container was started.
Dozzle has changed my workflow to the better, been using it for the past few month on my home-server.

If dozzle had an inspect button and allow viewing the json output, it feels like a great fit.
I hope, amir, you might change your mind.
