### ISSUE TITLE
[Question] How does work the File Based User Management? 

### ISSUE THREAD

**Issue by Zer0xxxx** [amir20/dozzle#3035]
From the doc: https://dozzle.dev/guide/authentication#file-based-user-management

But this is very obscure for me.
I've just added Dozzle to my docker-compose.yml as explained earlier in the doc, and now I have to figure out what are `--auth-provider`, `--auth-provider simple`, etc.

I don't understand. Where those flags should go?
Shoud I just create a file `/data/users.yml` in my Docker container? How?

---

EDIT: Oh, sorry, I'm tired and didn't see the `docker-compose.yml` tab below the tip.
Maybe the docs could gain some clarity by going more quickly straight to the point, idk. :/

**Comment by Zer0xxxx** [comment]
Oh, sorry, I'm tired and didn't see the `docker-compose.yml` tab below the tip.
Maybe the docs could gain some clarity by going more quickly straight to the point, idk. :/

**Comment by amir20** [comment]
I think they are pretty clear.

**Comment by Zer0xxxx** [comment]
> I think they are pretty clear.

Still didn't understand though.

**Comment by Zer0xxxx** [comment]
Finally found out how to do it as I wanted, using a docker-compose.

This was a very confusing point in my experience.
Having clear step-by-step documentation with a file tree presentation would have been a much better experience in my opinion.
