### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [amir20/dozzle#305]
Hi

I'm trying to run Dozzle on my Raspberry PI but after creating the container and trying to run it I just get:

> standard_init_linux.go:211: exec user process caused "exec format error"

I think it's because of my architecture since there's no ARM build?

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/issues/275. ARM version is released just not as docker images.

**Comment by amir20** [comment]
Arm releases are part docker releases now.
