### ISSUE TITLE
Visual formatting of array of objects

### ISSUE THREAD

**Issue by ldrahnik** [amir20/dozzle#3057]
**Describe the bug**

Visual bug while displaying an array of objects. The last item of the array can be hidden with the text `expand json`.

**To Reproduce**

Try to display an array of objects.

**Expected behavior**

Have better formatting. I prefer the possibility of hiding the entire array + hiding each item + displaying a count of array items.

**Screenshots**

![Screenshot from 2024-06-25 16 37 28](https://github.com/amir20/dozzle/assets/3233644/85b05dcc-8088-43ba-a6e9-a74ba8f68632)

![Screenshot from 2024-06-25 16 37 28](https://github.com/amir20/dozzle/assets/3233644/58a59f6e-e371-4db0-b935-3e77a03bc9d4)

**Desktop:**

- Browser & version [`chrome`,  `126.0.6478.114`]
- Version [`6.2.4`]

**Comment by amir20** [comment]
Hey @ldrahnik 

> Visual bug while displaying an array of objects. The last item of the array can be hidden with the text expand json

You have a very old version. Update Dozzle as a lot has changed. 

> Have better formatting. I prefer the possibility of hiding the entire array + hiding each item + displaying a count of array items.

I am not sure what that means. 

Could you provide an example of a log so I can reproduce? Is the problem the trailing bracket or something else. I am not sure.

**Comment by ldrahnik** [comment]
Hey @amir20 Yeah, sorry, I will update to the latest version first and then post it here reproducible log lines. I have not checked the code, is used any external library for json visualization? Or you do that by own?

**Comment by ldrahnik** [comment]
@amir20 I have updated to the latest version `7.0.7` and although it looks like it has a lot of changes and improvements I do not know how to print an array of objects (standard .json format) as friendly as possible.

**Comment by ldrahnik** [comment]
@amir20 Sorry, I was in a hurry and I forgot to mention that I tried the suggested approach by you:

```
logger.info(JSON.stringify({data: data_raw})
```

example with specific data:

```
const json = [{"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}, {"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}, {"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}, {"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}, {"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}, {"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}, {"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}]

logger.info(JSON.stringify({data: json}));
```

with result:

![Screenshot from 2024-06-28 13 56 38](https://github.com/amir20/dozzle/assets/3233644/06e7a1dd-8131-4774-ad9e-089efaeca9ec)

and then I decided to use a multiline approach because I had a problem finding out when the line with concrete patient starts. Do I miss something? I want to use your approach but with each array item on a new line with the possibility collapse/show as multiline object. 

In case I use:

```
logger.info(JSON.stringify({data: data_raw})
```

for each array item like this:
```
  console.log(JSON.stringify({"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}))
  console.log(JSON.stringify({"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}))
  console.log(JSON.stringify({"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}))
  console.log(JSON.stringify({"CISPAC": "11111111111", "JMENO": "Foo Bar", "ORDER_DATE": "28.6.2024", "ID": "2024-06-26-00002433", "MAIL": "ldrahnik@gmail.com", "PHONE": "999999999"}))
```

it works flawesly with my goal:

![Screenshot from 2024-06-28 14 07 47](https://github.com/amir20/dozzle/assets/3233644/5c7a4e8a-d4b1-41ab-acf0-23b6e5738c7c)

![Screenshot from 2024-06-28 14 08 01](https://github.com/amir20/dozzle/assets/3233644/d91d86d8-a296-4ec7-8688-a2ebe0475002)


So I guess I do something wrong or visualizating json with nested objects in array friendly is not supported?

```
crons_backend   | 2024-06-28T12:07:01.239064381Z {"data":[{"CISPAC":"11111111111","JMENO":"FooBar","ORDER_DATE":"28.6.2024","ID":"2024-06-26-00002433","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"},{"CISPAC":"11111111111","JMENO":"Foo Bar","ORDER_DATE":"28.6.2024","ID":"2024-06-26-00002433","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"},{"CISPAC":"11111111111","JMENO":"Foo Bar","ORDER_DATE":"28.6.2024","ID":"2024-06-2600002433","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"},{"CISPAC":"11111111111","JMENO":"Foo Bar","ORDER_DATE":"28.6.2024","ID":"2024-06-26-00002433","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"},{"CISPAC":"11111111111","JMENO":"Foo Bar","ORDER_DATE":"28.6.2024","ID":"2024-06-26-00002233","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"},{"CISPAC":"11111111111","JMENO":"FooBar","ORDER_DATE":"28.6.2024","ID":"2024-06-26-00002433","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"},{"CISPAC":"11111111111","JMENO":"Foo Bar","ORDER_DATE":"28.6.2024","ID":"2024-06-26-00002433","MAIL":"ldrahnik@gmail.com","PHONE":"999999999"}]}
```
