### ISSUE TITLE
The URL in the log can be set to highlight and hyperlink

### ISSUE THREAD

**Issue by thsrite** [amir20/dozzle#3063]
<img width="886" alt="image" src="https://github.com/amir20/dozzle/assets/54088512/598b138b-0ece-4b63-a7ec-a2a88ced30a8">

The URL in the log is not very clear now. Can we set it to be similar to VS where the URL address is highlighted and a hyperlink is displayed for clicking.

![image](https://github.com/amir20/dozzle/assets/54088512/d922b4e6-6c49-44d4-97a3-1679c256f8ef)

**Comment by amir20** [comment]
If you mean auth link then yes, I think that would be a good idea. I am still busy with #3058 so I won't get this for a while. If you send a PR, I can merge it.

**Comment by thsrite** [comment]
3ks！
