### ISSUE TITLE
Envvar not available anymore

### ISSUE THREAD

**Issue by toast-ts** [amir20/dozzle#3074]
**Describe the bug**
I wouldn't call this a bug, but I got no choice so... This envvar used to exist in older Dozzle versions but now I have noticed in the logs that newer versions no longer references it anymore.
The variable is `DOZZLE_WAIT_FOR_DOCKER_SECONDS`, however your documentation is the only place in the repository that references it.

**To Reproduce**

_I can edit this comment to add steps if needed? I feel like it shouldn't be._

**Expected behavior**

**Screenshots**
![image](https://github.com/amir20/dozzle/assets/96593068/2bafd011-a4f6-4678-aff4-03783afa3ead)
![image](https://github.com/amir20/dozzle/assets/96593068/6c184731-193d-4f7e-8949-b031ba03cce0)

**Desktop (please complete the following information):**

- OS: Ubuntu 24.04 LTS
- Docker version: 25.0.2
- Browser & version: Firefox 127.0.2
- Version: 8.0.1

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
`DOZZLE_WAIT_FOR_DOCKER_SECONDS` has been removed in v8.  In the future, I will automatically retry agents but localhost `docker.sock` needs to be there.

**Comment by amir20** [comment]
Oh yea I should update the documents 😅

**Comment by toast-ts** [comment]
Oh I see, haha.

**Comment by amir20** [comment]
Fixed in #3083
