### ISSUE TITLE
orphaned container when using Show stopped containers

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#3077]
**Describe the bug**
removed container will remain in the sidebar list and is impossible to show logs

**To Reproduce**
- enable the option Show stopped containers (IMOH this should be enabled by default :D)
- stop **and remove** a container from a stack - "Container stopped" row correctly shown
- restart the container (so the container will have a fully different ID) - you will be redirected to the new one (thanks to the other option that redirect based on name)
- on the sidebar the deleted containers **will stay forever until a page refresh**, clicking an a container that was removed you will get an infinite load

**Expected behavior**
when a cointainer is removed, delete from the sidebar list

**Comment by amir20** [comment]
Yea that might be a bug. Will come back to it.

**Comment by amir20** [comment]
@FrancYescO How was Dozzle deployed? Was it with agents or just locally?

**Comment by FrancYescO** [comment]
locally

**Comment by amir20** [comment]
Wait I misunderstood this. I don't think this ever worked. Removed containers were never removed from the list. So I guess it is not something I broke recently.

**Comment by FrancYescO** [comment]
i cannot be very sure but yes, maybe this bug was something very old

**Comment by FrancYescO** [comment]
seems this fix breaks the "Automatically redirect to new containers with the same name" function, maybe a delay is needed before fully removing the container while you are visualising it and redirecting you to the page "no container found"

**Comment by amir20** [comment]
Yea, I see this now. Hmm.
