### ISSUE TITLE
Question: How to see logs of older containers after they were restarted or recreated?

### ISSUE THREAD

**Issue by skulltech** [amir20/dozzle#3078]
My use-case requires me to look at historical container logs so that I can find out what happened with a specific request from weeks ago. Is that possible with Dozzle, maybe with some settings at the docker compose and log driver level? My stack is a simple docker compose stack with 5-10 services.

**Comment by FrancYescO** [comment]
if recreated, the logs are lost so i don't thing dozzle can do anything.

if restarted you should able to see the logs, maybe you just need to enable in settings `Show stopped containers` to see from a container that is stopped while looking at dozzle.... if you need for a specific time range maybe you need to wait for https://github.com/amir20/dozzle/issues/2363

**Comment by amir20** [comment]
@skulltech Dozzle is not backed by any database. If the container still exists, you can "show stopped containers" as @FrancYescO suggested. 

I think this is a very a niche feature request. It would require an embedded database which would incur 100MBs of memory that most people probably wouldn't want. And it would be too maintenances heavy to have optionally enabled.  For that reason, I won't be implementing it.  Even when I implemented a small stats collect in memory people complained that it took more memory than they had originally intended for.  It also requires additional indexing to go to a specific time which further complicates the resources.
