### ISSUE TITLE
Scrolling up sometimes just stops even if there are more logs

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#3086]
**Describe the bug**
Sometimes when I scroll up, I reach '0%' and I cannot scroll up anymore in the logs even if there are more logs available.
If I scroll down again a bit and scroll up again it correctly displays the infinite symbol instead of '0%' and I can see the older logs as expected.
Sometimes even scrolling down and up again does not resolve the problem. 
To resolve the problem I need to refresh my browser.

**To Reproduce**
It is quite random and hard to reproduce (I'm trying to reproduce it right now to take screenshots and get logs, but I cannot reproduce it) but it happens at least a few time a day.
There is no error displayed in Dozzle logs

**Expected behavior**
Scrolling up should allow me to see older log entries.

**Screenshots**
Will try to add screenshot when I can reproduce the problem again

**Desktop (please complete the following information):**

- OS: Windows
- Docker version : Docker version 24.0.6, build ed223bc
- Browser & version : Firefox 127.0.2 (64 bits)
- Dozzle version v7.0.7

**If applicable include logs with `--level debug` and browser logs**
Will try to add logs when I can reproduce the problem again.

**Comment by amir20** [comment]
I have seen this rarely too. Unfortunately, I haven't been able to see it enough. I also don't have Windows so it might be something with the way it works on Windows.  It would have to be easily reproducible for me able to try to fix it. 

I won't be able to spend too much time on this. If you know javascript or can help out then let me know what could be causing it. I suspect it has to do with the way intersection pixels are done.
