### ISSUE TITLE
Dozzle not self reporting version correctly

### ISSUE THREAD

**Issue by dj3520-git** [amir20/dozzle#3087]
Describe the bug:
The self reported version since v8.0.2 just says 'head'. This doesn't seem to have any adverse effects other than whilst being on the latest version the update announcement button says I've got a lot of catching up to do :-).

Run any version since v8.0.2 and check Dozzle's logs at just the info level, the message for the self reported version is just:
`msg=Dozzle version head`

Expected behavior:
The version is reported correctly, like v8.0.2.
`msg=Dozzle version v8.0.2`

Screenshots:
![image](https://github.com/amir20/dozzle/assets/65852870/c380e59b-f07a-4106-adfc-72da7a04e274)

- OS: Debian 12
- Docker version: 27.0.3
- Browser & version: Chrome 126.0.6478.127
- Version: v8.0.3 (latest)

**Comment by amir20** [comment]
I noticed this last night too. Something is broken in GitHub pipeline. Not sure what yet.

**Comment by amir20** [comment]
Found a fix. Can't believe it took me an hour to figure out the right import path for `-X` in `go build`.
