### ISSUE TITLE
Sorting services in swarm mode

### ISSUE THREAD

**Issue by wildyaboku** [amir20/dozzle#3093]
**Is your feature request related to a problem? Please describe.**
I have a large number of services on my server, with updates deployed throughout the day. It seems like the services in the "swarm mode" sidebar are arranged randomly, and rearrange both after deployment and after reloading the Dozzle UI, which makes it a bit difficult to quickly find a particular service.

**Describe the solution you'd like**
Sort the services by their name (maybe natural sort would be best). If it's possible to sort by other means, like age or freshness, a persistent option could also be added in the settings to choose between the sorting modes.

Thank you for all your incredible work on this project so far! ❤️

**Comment by amir20** [comment]
Do you mean services or stack names? Screenshot would help. 

Agreed that it should be consistent.

**Comment by wildyaboku** [comment]
I mean services specifically, when using Docker Swarm with the recently-added "swarm mode" toggle enabled. I don't think I can screenshot it, but it's the stuff that gets listed under `docker service ls`.

I have some stacks (made with docker compose) on another server, and the containers within them seem to be sorted correctly at a glance.

**Comment by amir20** [comment]
Here is a screenshot: 

<img width="331" alt="Screenshot 2024-07-11 at 10 07 36 AM" src="https://github.com/amir20/dozzle/assets/260667/63eca824-643a-4804-a8e7-c94847826feb">

I assume you mean the services inside the stack right? In my screenshot, clashleader and dozzle are stack names. Under each, there are multiple services.

**Comment by wildyaboku** [comment]
Oh, I see. Apologies, that's not quite what I mean. I don't have any stacks like that in this case, just straight up services on a single-node swarms cluster, here's a very limited screenshot from a server that uses CapRover which is nearly the same setup:

![image](https://github.com/amir20/dozzle/assets/499470/8d2376ae-afdf-4b98-937a-1d0794893412)

**Comment by amir20** [comment]
Ah I see. Ok that helps. I didn't actually think about that.

**Comment by amir20** [comment]
@wildyaboku I think the fix was easy. I added a few `sort()`s in the UI. Try `amir20/dozzle:pr-3096` and see how that works?

**Comment by wildyaboku** [comment]
That seems to have worked wonderfully. It's a lot more readable now:

![image](https://github.com/amir20/dozzle/assets/499470/1e20cb84-4fce-4c55-9ce7-a3f0cecdd53d)

**Comment by wildyaboku** [comment]
Thank you @amir20!
