### ISSUE TITLE
Question why so many requests to b.dozzle.dev

### ISSUE THREAD

**Issue by Reupireup** [amir20/dozzle#3101]
Hello,
Since the last update I see a lot of requests to b.dozzle.dev, what is the point of these requests?
Thx

**Comment by amir20** [comment]
That's the analytics beacon. I had a bug where it wasn't checking `NO_ANALYTICS`. It should be fixed now in `v8.0.5`. Can you confirm?

**Comment by Reupireup** [comment]
Yes, it fixed now, thx
