### ISSUE TITLE
Filter combined Output of hosts

### ISSUE THREAD

**Issue by Its4Nik** [amir20/dozzle#3127]
### Describe the feature you would like to see

We can filter fot STDOUT and STDERR on a per container basis but i would love to be able to filter on the per stack level.

### Describe how you would like to see this feature implemented

Kinda of exactly the same, with the little blue and red button in the "Stat-Bar", it fits the style and is easy and comprehensive for everyone.

**Comment by amir20** [comment]
It's actually implemented in the API just need to do the drop down in UI.
