### ISSUE TITLE
Dozzle-Agent version

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3133]
Hi

The version of each Dozzle agent should be displayed somewhere in Dozzle. At the moment I don't know which ones I still need to update or what version they are at.

**Comment by amir20** [comment]
That's a good idea 🤔

**Comment by Mephisto090** [comment]
![image](https://github.com/user-attachments/assets/e99b3973-1cf2-4a7b-a00f-30c25e21731a)

Maybe under the container display

**Comment by amir20** [comment]
Yea, I agree.  I'll probably come back to this in the future. Working on #3094.

**Comment by amir20** [comment]
<img width="1316" alt="Screenshot 2024-07-23 at 8 10 50 PM" src="https://github.com/user-attachments/assets/1600a1d9-c342-445d-88aa-cef1b3494d07">

It will probably look like that. Where it says `pr-3145` will be the version number. I have also added icons. It will also change colors when versions are old. 

Additionally, I have added docker version. 

What do you think?

**Comment by Mephisto090** [comment]
![image](https://github.com/user-attachments/assets/63d3ae04-2eed-4ba4-8f76-8842cea0b2d0)

Unfortunately, it somehow doesn't show me that

**Comment by amir20** [comment]
What? It hasn't been released yet. How did you run it?

**Comment by Mephisto090** [comment]
with `pr-3145` :D

**Comment by amir20** [comment]
<img width="1460" alt="Screenshot 2024-07-26 at 1 58 25 PM" src="https://github.com/user-attachments/assets/81e699de-84a3-4b06-9baa-abfdb24ce5bb">

**Comment by Mephisto090** [comment]
![image](https://github.com/user-attachments/assets/84b51acb-31a6-470b-a2ec-61c6728338a7)

For the sake of completeness, don't you want to display the version on the server? My little inner Adrian Monk is screaming loudly inside me :D

**Comment by amir20** [comment]
There is already a notification bar that shows updates and other stuff. But I am not a UI genius.

**Comment by Mephisto090** [comment]
I just meant that it is uniform. That way, the little version bubble behind the server is missing. That way, everything is at a glance
