### ISSUE TITLE
Add enviroment variables to override Display and Option default values

### ISSUE THREAD

**Issue by meta3ark** [amir20/dozzle#3146]
### Describe the feature you would like to see

Most of the container logs I inspect already include timestamps to 1ms accuracy. I would like to change the default "Show Timestamps" flag to be off via an ENV argument like DOZZLE_DISPLAY_SHOW_TIMESTAMPS.

Changing "Show stopped containers" default value would also be useful.

**Comment by amir20** [comment]
This is something that was discussed in the past. It's actually pretty difficult to pass env variables. 

If you use authentication then all your settings will be sticky across browsers. That is ultimately be a better solution. 

I am not a fan of adding ENV variables for everything. It's hard to manage.
