### ISSUE TITLE
Is there only a version of the AMR architecture available？Mine is based on the AMD64 architecture

### ISSUE THREAD

**Issue by liutianping0326** [amir20/dozzle#3149]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

amir20/dozzle:agent 

### ✅ Command used to run Dozzle

docker run --name dozzle -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock -p 7007:7007 amir20/dozzle:agent agent --hostname 10.0.31.55

### 🐛 Describe the bug / provide steps to reproduce it

Is there only a version of the AMR architecture available？Mine is based on the AMD64 architectur

### 💻 Environment

None

### 📸 If applicable, add screenshots to help explain your bug

![image](https://github.com/user-attachments/assets/83151cb5-084a-4680-8ea7-d14225bd8429)

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

None

**Comment by amir20** [comment]
You are not using a valid version. amir20/dozzle:agent was just for testing. Use amir20/dozzle:latest.

**Comment by amir20** [comment]
Did I mess up the documentation somewhere? Hopefully not.

**Comment by amir20** [comment]
Looks like I have a typo here https://dozzle.dev/guide/agent#changing-agent-s-name. Going to fix that.
