### ISSUE TITLE
[8.1.0] Label.Container

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3154]
![image](https://github.com/user-attachments/assets/b4d8ac61-b671-49a8-9857-f67033bfd611)

somehow something is displayed wrong in the container

**Comment by Mephisto090** [comment]
And this one 
![image](https://github.com/user-attachments/assets/dd5df21e-12a4-4799-85df-83c5888bb37b)

**Comment by Mephisto090** [comment]
next one `button.canel`

![image](https://github.com/user-attachments/assets/534df5db-580c-4c2c-91a2-f5fa6b2202f0)

**Comment by amir20** [comment]
I think I know the issue. I load the locales asynchronously. Seems like fallback is broken.

**Comment by amir20** [comment]
Try https://github.com/amir20/dozzle/pull/3156

**Comment by Mephisto090** [comment]
its work
