### ISSUE TITLE
Storage Space

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3155]
### Describe the feature you would like to see

Hello,

a great piece of information would be how much storage space docker uses and how much is still free.

`docker system df`

**Comment by amir20** [comment]
What specifically about `docker system df` is useful? 

I see 

```
❯ docker system df                                                                                                                                                                                                               7:27:00
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          17        3         257.3MB   219.3MB (85%)
Containers      504       253       0B        0B
Local Volumes   16        0         664.1MB   664.1MB (100%)
Build Cache     127       0         3.196GB   3.196GB
```

**Comment by FrancYescO** [comment]
maybe you are interested in visualising some data from
`docker system df -v` a/o `docker ps --size` (these command should be cached as for big hosts/container can be slow)

but the free disk space is still an OS info

**Comment by Mephisto090** [comment]
This would be information from the Linux system
`df -h` Show free space of the entire file system

**Comment by amir20** [comment]
> Does it have to come from Docker or can normal Linux commands be used?

Since Dozzle is running inside a container, it only has access to container stats. Disk usage is only visible if the host allows it. 

I don't think `docker system df -v` will be useful in your use case because it only shows how much your containers are using the disk. It won't show an accurate avail %. 

I am not sure of a better way.

**Comment by Mephisto090** [comment]
> I don't think `docker system df -v` will be useful in your use case because it only shows how much your containers are using the disk. It won't show an accurate avail %.

It would be possible to calculate what is still free.

It would be enough to know if Docker is "full"

**Comment by amir20** [comment]
> It would be possible to calculate what is still free.

No, because I wouldn't know how much total disk space is available.

**Comment by Mephisto090** [comment]
But the table has 3 columns (Size, used, Avail)

**Comment by amir20** [comment]
Again, I don't have access to `df`. Just `docker system df`.

**Comment by amir20** [comment]
One idea is to use github.com/shirou/gopsutil. It could work. Based on https://github.com/shirou/gopsutil/issues/1613 it will be limited to what is exposed to Docker. Not sure how many people limit this 💁

**Comment by amir20** [comment]
One thing that is interesting, Dozzle currently reports on Docker usage. CPU usage outside of Docker is not reported. So I think the bigger idea would be to support node utilization. This would only work in agent mode.

**Comment by Mephisto090** [comment]
This tool reads Docker's strorage nicely. Maybe you can get some inspiration from it

https://github.com/amerkurev/doku

**Comment by amir20** [comment]
That seems to show how much Docker is using it eg `docker system df -v`. Not how much the host is free. eg. `du -sh`. Am I missing something?

**Comment by Mephisto090** [comment]
Example from my Ubuntu machine

![image](https://github.com/user-attachments/assets/d8345523-ba1f-4da9-af76-4c0218c59172)

Above you can see how much is free

**Comment by amir20** [comment]
> Also, you need to mount the top-level directory (/) on the host machine in ro mode. Otherwise, Doku will not be able to calculate the size of the logs and bind mounts.

Ah. Looks like `/` is mounted. Interesting.

**Comment by Mephisto090** [comment]
I'm glad I could give you a little inspiration. Maybe an idea to expand dozzle

**Comment by Mephisto090** [comment]
Btw. I like to use only one tool for everything and not many to have everything

**Comment by amir20** [comment]
So it looks like it's possible to use `statfs` API from C to get volume data. However, `/` does need to be mounted. I think this would be a good add for agents, however, I don't think a lot of people would want it. It would also require an extra step to mount which most people don't do.

I wish there was a way to validate interest for this feature. It might be a lot of work with not many people using it. 

Is there a way to do polls or votes in Github?
