### ISSUE TITLE
Unreliable search

### ISSUE THREAD

**Issue by ciotorcristian** [amir20/dozzle#3178]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Remote Hosts

### 📦 Dozzle version

8.1.3

### ✅ Command used to run Dozzle

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    networks:
      - docker_socket_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8080
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5m
      start_interval: 30s
      start_period: 5m
    environment:
      - PUID=1000
      - PGID=1000
      - DOZZLE_REMOTE_HOST=tcp://docker_socket_proxy:2375

### 🐛 Describe the bug / provide steps to reproduce it

Hello,

I am facing a problem with the search in Node Red logs. I have a tag [debug:AC] in front of all the logs that are related to the AC automation flow. If I search for "debug:AC" it does not return all the entries where it found that tag. Examples are attached below:

Before the search:
![1](https://github.com/user-attachments/assets/d07b9db4-8bbd-4442-a4d9-bc3838d94afb)

After the search:
![2](https://github.com/user-attachments/assets/ca95d48c-2c2c-44fc-9de5-07c14f6794ae)

As you can see, it only shows two entries for each hour instead of the initial 4.

### 💻 Environment

![3](https://github.com/user-attachments/assets/cdae745a-15bf-4063-b59f-3fcf2ea751b7)

**Comment by amir20** [comment]
I haven't been able to reproduce this. Are you able to see this behavior every time?  If so, can you attack the logs and I can try locally.

**Comment by amir20** [comment]
Also, search is done in the browser. So bring up browser debugging logs when this happens to see if there are any errors.

**Comment by amir20** [comment]
Hmmm I did find another bug that might be related. I am seeing some logs missing when searching for a common term. I'll investigate a little.

**Comment by amir20** [comment]
I think I found the problem. Apparently, global flag in javascript is [quirky](https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results). Try `amir20/dozzle:pr-3180`.

**Comment by amir20** [comment]
Did it work?

**Comment by ciotorcristian** [comment]
It worked! Thanks so much
