### ISSUE TITLE
getting the following error : Something is not right Dozzle UI timed out while connecting to API. Please check network connection and try again.

### ISSUE THREAD

**Issue by christodwise** [amir20/dozzle#3183]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

latest

### ✅ Command used to run Dozzle

version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

### 🐛 Describe the bug / provide steps to reproduce it

Something is not right Dozzle UI timed out while connecting to API. Please check network connection and try again.

### 💻 Environment

docker

### 📸 If applicable, add screenshots to help explain your bug

<img width="624" alt="Screenshot 2024-08-06 at 3 46 59 PM" src="https://github.com/user-attachments/assets/50cbb0d4-fae5-4d44-8dfd-5f4d254404c6">

**Comment by amir20** [comment]
Not enough details for me to help. What's the issue?

**Comment by christodwise** [comment]
When I try to deploy dozzle in docker I'm getting the following error and unable to view the logs: 

`Something is not right Dozzle UI timed out while connecting to API. Please check network connection and try again`
<img width="1425" alt="Screenshot 2024-08-06 at 6 48 43 PM" src="https://github.com/user-attachments/assets/5c9c887a-1743-4364-9a3e-efc9a6c9ac01">

**Comment by amir20** [comment]
This error happens when a network error happens. It can be a proxy error or something else.  If you have a proxy then try going to Dozzle directly. Also look for errors in Dozzle logs. 

You need to investigate a little more before filing an issue because I don't know what could be the problem.

**Comment by christodwise** [comment]
I haven't set up any proxy. 

```
Attaching to dozzle
dozzle    | time="2024-08-06T08:17:05Z" level=info msg="Dozzle version v8.1.4"
dozzle    | time="2024-08-06T08:17:05Z" level=info msg="Connected to 1 Docker Engine(s)"
dozzle    | time="2024-08-06T08:17:05Z" level=info msg="Accepting connections on :8080"
dozzle    | time="2024-08-06T08:34:33Z" level=error msg="error encoding containers to stream: write tcp 172.26.0.2:8080->192.168.10.241:59137: write: connection timed out"
```

**Comment by amir20** [comment]
Seems like a network timeout. Can't help since I can't reproduce it.

**Comment by adam6806** [comment]
@amir20 I'm having the same issue. Here's some debug logs.

`{"level":"info","time":"2024-12-31T03:13:38Z","message":"Dozzle version v8.9.1"}
{"level":"debug","filter":{},"host":"smithflix","time":"2024-12-31T03:13:38Z","message":"Listing containers"}
{"level":"debug","time":"2024-12-31T03:13:38Z","message":"Adding local Docker Engine"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:38Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","filter":{},"time":"2024-12-31T03:13:38Z","message":"initializing container store"}
{"level":"debug","filter":{},"host":"smithflix","time":"2024-12-31T03:13:38Z","message":"Listing containers"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:38Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:38Z","message":"docker store subscribing docker events"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:38Z","message":"Fetching host"}
{"level":"info","clients":1,"time":"2024-12-31T03:13:38Z","message":"Connected to Docker"}
{"level":"info","time":"2024-12-31T03:13:38Z","message":"Accepting connections on :8080"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:38Z","message":"Fetching host"}
{"level":"debug","id":"94676105f83a","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"99a681205187","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"8a9d89e829c3","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"b2727804d985","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"6c32deb51549","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"344670a54621","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"3cf4383bf4f7","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"e7e93c56c15e","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"a536a8886f70","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"2b3c790e356f","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"8a0fd907abf3","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"8807b1c270ff","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"834b491ffacb","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"5c6a6ea3e31e","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"9b6706df4007","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"c5b10c01ee6a","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"236a366c2c5d","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"90315c4c5818","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"c38886510f0b","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"2b27c98ac584","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"6c08874bc78c","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"56626ce3122a","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"a82fb91ccd21","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"87346e6662f8","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"d34410def993","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"e53d4d83061d","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"283c1567e06e","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"12010d74d9df","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","id":"03a26cc8f214","time":"2024-12-31T03:13:38Z","message":"Finding container"}
{"level":"debug","containers":29,"time":"2024-12-31T03:13:38Z","message":"finished initializing container store"}
{"level":"debug","filter":{},"host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Listing containers"}
{"level":"debug","filter":{},"host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Listing containers"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"5c6a6ea3e31e","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"2b27c98ac584","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"6c08874bc78c","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"c5b10c01ee6a","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"a536a8886f70","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"834b491ffacb","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"9b6706df4007","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"94676105f83a","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"12010d74d9df","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"283c1567e06e","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"236a366c2c5d","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"2b3c790e356f","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"3cf4383bf4f7","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"c38886510f0b","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"e53d4d83061d","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to listen to docker events"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"8807b1c270ff","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"b2727804d985","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"a82fb91ccd21","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"87346e6662f8","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"99a681205187","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"03a26cc8f214","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"e7e93c56c15e","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"6c32deb51549","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"d34410def993","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"8a9d89e829c3","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","container":"56626ce3122a","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"90315c4c5818","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"8a0fd907abf3","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"Fetching host"}
{"level":"debug","container":"344670a54621","host":"smithflix","time":"2024-12-31T03:13:41Z","message":"starting to stream stats"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:45Z","message":"Fetching host"}
{"level":"debug","filter":{},"host":"smithflix","time":"2024-12-31T03:13:45Z","message":"Listing containers"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:45Z","message":"Fetching host"}
{"level":"debug","hit":false,"data":"[]releases.Release","time":"2024-12-31T03:13:46Z","message":"Cache hit"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:48Z","message":"Fetching host"}
{"level":"debug","filter":{},"host":"smithflix","time":"2024-12-31T03:13:48Z","message":"Listing containers"}
{"level":"debug","host":"smithflix","time":"2024-12-31T03:13:48Z","message":"Fetching host"}
{"level":"debug","hit":true,"data":"[]releases.Release","time":"2024-12-31T03:13:48Z","message":"Cache hit"}`

**Comment by adam6806** [comment]
I hit this URL and I do appear to be getting data back. http://192.168.0.113:8100/api/events/stream (I changed ports to 8100 to make sure there wasn't a conflict)

event: container-stat
data: {"id":"344670a54621","cpu":0.019470198675496687,"memory":0.15741568990460347,"memoryUsage":105930752}


event: container-stat
data: {"id":"03a26cc8f214","cpu":6.506445733222867,"memory":0.26193746807496354,"memoryUsage":176267264}


event: container-stat
data: {"id":"d34410def993","cpu":101.3949504950495,"memory":35.613251647441444,"memoryUsage":23965454336}


event: container-stat
data: {"id":"5c6a6ea3e31e","cpu":0.0012860676009892828,"memory":0.10757124304709835,"memoryUsage":72388608}


event: container-stat
data: {"id":"283c1567e06e","cpu":0,"memory":0.01824809521050194,"memoryUsage":12279808}

**Comment by adam6806** [comment]
I'm also seeing data in the javascript 
![image](https://github.com/user-attachments/assets/642655f2-4eab-49b4-8b2b-3979a1b62d9c)

**Comment by adam6806** [comment]
Tried running some js in the browser.

const eventSource = new EventSource('http://192.168.0.113:8100/api/events/stream');

eventSource.onopen = function() {
    console.log('Connected to stream');
};

eventSource.onmessage = function(event) {
    console.log('Message:', event.data);
};

eventSource.onerror = function(error) {
    console.error('Error:', error);
    setTimeout(() => {
        console.log('Reconnecting...');
        eventSource = new EventSource('http://192.168.0.113:8100/api/events/stream');
    }, 5000); // Retry after 5 seconds
};


I did get an error but after the retry, I successfully connected to the stream. I'm wondering if my network is just being slow because I have a backup going right now?

**Comment by amir20** [comment]
@adam6806 hard to tell what is going on. I wait [8 seconds](https://github.com/amir20/dozzle/blob/08e5deba7ee44b0f4b5003fe029a4e485156ff85/assets/stores/container.ts#L103-L117) before showing that error. 

You can try: 

1. `curl http://192.168.0.113:8100/api/events/stream` and see what that looks like 
2. Try a different computer or locally to see if there is something going on 
3. Do a full restart and use `htop` to see what else is going on the host
4. If you are using a proxy, then hit Dozzle directly 

Seems like something is different about your env and I can't debug it.

**Comment by adam6806** [comment]
> @adam6806 hard to tell what is going on. I wait [8 seconds](https://github.com/amir20/dozzle/blob/08e5deba7ee44b0f4b5003fe029a4e485156ff85/assets/stores/container.ts#L103-L117) before showing that error.
> 
> You can try:
> 
> 1. `curl http://192.168.0.113:8100/api/events/stream` and see what that looks like
> 2. Try a different computer or locally to see if there is something going on
> 3. Do a full restart and use `htop` to see what else is going on the host
> 4. If you are using a proxy, then hit Dozzle directly
> 
> Seems like something is different about your env and I can't debug it.

I've curled it and I did post that data above. Getting all the event data it would seem. I'm not proxied on this yet so I am just hitting the IP:Port directly. I'll try a restart.
