### ISSUE TITLE
Ability to customize a container's name through a Docker label

### ISSUE THREAD

**Issue by Jeto143** [amir20/dozzle#3189]
### Describe the feature you would like to see

In some cases, setting the name of the container through Docker (via `--name` or `container_name`) is not possible. For instance, using [Coolify](https://coolify.io/), you can customize container names but if you do so, you lose the rolling update feature, so container names usually are randomized slugs.

### Describe how you would like to see this feature implemented

Since we already have [`dev.dozzle.group`](https://dozzle.dev/guide/container-groups#custom-groups) as a possible label to define the name of a group, why not introduce a `dev.dozzle.name` label as well, that if defined for a given container, would supersede its actual name within Dozzle?

**Comment by amir20** [comment]
Not a bad idea. Seems like a simple a change if you want to send a PR.  Changes would be at: 

https://github.com/amir20/dozzle/blob/ffc4559047f52a8e0ac3f31cf30ecdc24be1c293/internal/docker/client.go#L358

https://github.com/amir20/dozzle/blob/ffc4559047f52a8e0ac3f31cf30ecdc24be1c293/internal/docker/client.go#L382

**Comment by Jeto143** [comment]
Thanns! I'll give it a shot ASAP.

**Comment by amir20** [comment]
Any update? I won't have much time either so I might close if neither of us can do it. 🙈

**Comment by Jeto143** [comment]
> Any update? I won't have much time either so I might close if neither of us can do it. 🙈

Still planning on it, I'll give it a go either this week or next week.

**Comment by Jeto143** [comment]
@amir20 There you go, lmk what you think!

**Comment by amir20** [comment]
Nice! Merged. I am hoping you tested it :)  It is now in master so if you give it a try with `amir20/dozzle:master` and test it. I can release later today.

**Comment by Jeto143** [comment]
> I am hoping you tested it :)

I did a basic test, yeah: I had a bunch of containers already running, then ran a quick `docker run` command after the change with the new label and saw the new container appear on the list with the desired name.
