### ISSUE TITLE
Support any name in swarm mode

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#3192]
I tried in a couple containers using `docker inspect "$(echo $HOSTNAME)" | jq '.[0].Config.Labels["com.docker.swarm.service.name"]'` and it indeed returned the correct service name.

_Originally posted by @Enissay in https://github.com/amir20/dozzle/issues/3058#issuecomment-2259366202_

**Comment by amir20** [comment]
@Enissay Seems like this would be a good solution. If I try something can you test it?

**Comment by Enissay** [comment]
> @Enissay Seems like this would be a good solution. If I try something can you test it?

I would gladly!

**Comment by amir20** [comment]
It should work now based on my testing. Can you try `amir20/dozzle:pr-3193`? If it doesn't work, then enable debugging. I'll still have to update the docs before merging.

**Comment by amir20** [comment]
Did you try it? Trying to merge this.

**Comment by Enissay** [comment]
Just finished work and heading home. Will try and reply ASAP

**Comment by amir20** [comment]
Documentation is updated in #3193. Will merge when you give me ✅

**Comment by Enissay** [comment]
✅
It is working fine on my 5 machines swarm!

**Comment by amir20** [comment]
Merged. Going to release a patch now.
