### ISSUE TITLE
Remoteupdate

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3200]
### Describe the feature you would like to see

Another little idea from me :)

I already run 7 servers that I monitor via Dozzle. Each time I have to log in via Putty and restart or update the agents and the server. Is there any way to solve this via the Dozzle interface?

**Comment by amir20** [comment]
Docker containers are immutable. It would be confusing for users if it upgraded. You can use https://github.com/containrrr/watchtower which does the same thing. No reason to be part of Dozzle.
