### ISSUE TITLE
Seeing logs for stopped containers

### ISSUE THREAD

**Issue by konradstrachan** [amir20/dozzle#3221]
### Describe the feature you would like to see

Being able to sww stopped containers and access their logs in exactly the same way as running containers

### Describe how you would like to see this feature implemented

Within the list of containers show both running and stopped, potentially differentiated by the running containers using the usual text colour and the stopped containers using a lighter colour to distinguish between the two types of containers

### Describe any alternatives you've considered

I've read the FAQs and searched around but can't find any reference to how to make stopped containers show their logs using Dozzle. Portainer enables this, but it provides a lot of additional functionality I don't want to expose for this use case.

**Comment by amir20** [comment]
@konradstrachan I am not sure what you are asking. Have you enabled showing stopped containers in settings? 

<img width="1063" alt="Screenshot 2024-08-21 at 9 13 15 AM" src="https://github.com/user-attachments/assets/ed106f86-9eb4-4d91-8496-8b888d971360">

**Comment by konradstrachan** [comment]
Doh! I read through everything but somehow missed this option. As a suggestion it's worthwhile having this in the FAQ in case someone else misses it like me. Thanks for the reply

**Comment by undaunt** [comment]
I agreed with @konradstrachan as I searched the docs website for this and couldn't locate it.

**Comment by amir20** [comment]
PRs welcomed to update documentation. 🙋🏼
