### ISSUE TITLE
sometime is not possible to load old logs 

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#3222]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.2.1

### ✅ Command used to run Dozzle

NR

### 🐛 Describe the bug / provide steps to reproduce it

if the loadmore request put a `from` and `to` timeframe with no logs you will be unable to load older logs.... you can keep try to scroll up but the request will be fired asking for logs in the same timeframe giving the same empty result

i'm sure there are some older log but i have no way to increase the timeframe to load as it will be guessed automatically

<img width="656" alt="image" src="https://github.com/user-attachments/assets/c60a7b7d-d782-4516-b2d2-881f36131955">

### 💻 Environment

NR

**Comment by amir20** [comment]
This is almost like the opposite of burst. In burst, I am trimming. But perhaps, if there is no logs, I should try to find more logs?

**Comment by FrancYescO** [comment]
a little workaround is to redo another request starting from the "previous to", but the best solution maybe is to keep searching for at least a line in the past before giving an empty result

**Comment by amir20** [comment]
This should be fixed with https://github.com/amir20/dozzle/pull/3230 but it's a little hard to test it. So I might just merge it unless you can figure out a way to easily test it @FrancYescO.

**Comment by FrancYescO** [comment]
i'm not able to easy retest it as without optimization of https://github.com/amir20/dozzle/pull/3230 pretty often i get a full freeze of the UI, i'll keep an eye on it

btw it should be easy replicable when the log flow is not regular:
- no log for 10min
- 1min with 3000 entries
- again no log for 10min

**Comment by amir20** [comment]
🤔 `fill` was changed to `minimum`. 

With the latest release, I did change the logic a little bit for pagination. I wonder if [this broke](https://github.com/amir20/dozzle/pull/3377) it? 

There was a bug where if the there were a lot of lines emitted at the same time, Dozzle was skipping over them and thus breaking pagination experience. 

This issue is the opposite where you want less items to be loaded.

What is happening again? Is it slow or something else?

**Comment by FrancYescO** [comment]
not slowing down, after a bit of scrolling i'm not able to "load more" (but i know there are a lot of other logs, infact also the percentage is at 1%)

**Comment by amir20** [comment]
Hmm I think I see what you mean. Might be something else then.... let me check.

**Comment by FrancYescO** [comment]
just noticed another cointainer fully refuses to load logs... is like an infinite load spinner (same as if the container has no logs)
<img width="708" alt="image" src="https://github.com/user-attachments/assets/ee238262-2722-4fb8-be54-dfc0420464f4">

but using the download button it downloads 2,9MB of logs... here i'm a little lost, idk what can cause this

to specify again: here i'm not talking when loading more logs, just on the first load

**Comment by amir20** [comment]
I am guessing in that instance, there was a javascript bug that broke the page.

**Comment by FrancYescO** [comment]
> I am guessing in that instance, there was a javascript bug that broke the page.

nope... js console is clean, dozzle logs are clean, but the /stream endpoint keep returning no logs on this container.. is something like content in these logs that breaks the be output and returns empty output...

**Comment by FrancYescO** [comment]
> I wonder if [this broke](https://github.com/amir20/dozzle/pull/3377) it?

btw, yes with 8.7.2 i'm able to reach the start of logs (also if a strangely see "1%" during all the scroll)

**Comment by FrancYescO** [comment]
> just noticed another cointainer fully refuses to load logs... is like an infinite load spinner (same as if the container has no logs/the filter on level have no results) <img alt="image" width="708" src="https://private-user-images.githubusercontent.com/4574593/385461660-ee238262-2722-4fb8-be54-dfc0420464f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NDkwMzUsIm5iZiI6MTczMTQ0ODczNSwicGF0aCI6Ii80NTc0NTkzLzM4NTQ2MTY2MC1lZTIzODI2Mi0yNzIyLTRmYjgtYmU1NC1kZmMwNDIwNDY0ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMjE1ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA4ZGNkNjM0ZDI2ODM5MDRjZGI2OGY1MjdhZDdiNWVkYWRlMDE3MjQ5OGZjZWYwMmQ2NDM4ZmY2OWJiZjljNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tOMN-WAOnhcpHkJzCBif7zAEaxDgDesfMooE-BJpaig">
> 
> but using the download button it downloads 2,9MB of logs... here i'm a little lost, idk what can cause this
> 
> to specify again: in this case i'm not talking when loading more logs, just on the first load

while this was broken in >=v7.0.5 (v7.0.4 correctly loads the logs of this container)

**Comment by amir20** [comment]
I believe I noticed it happen during my testing. Something broke. I'll try to figure out what is going on. The "side" in "side project" is challenging. 😅

**Comment by amir20** [comment]
Created https://github.com/amir20/dozzle/issues/3383 as new issue for the regression. 

For [this comment](https://github.com/amir20/dozzle/issues/3222#issuecomment-2471564111)

> just noticed another cointainer fully refuses to load logs... is like an infinite load spinner (same as if the container has no logs/the filter on level have no results)

I don't think that's related to this.
