### ISSUE TITLE
UI: Show version info on host too, not only for agents

### ISSUE THREAD

**Issue by l33tlamer** [amir20/dozzle#3228]
### Describe the feature you would like to see

I wish we could see the current version number label on the current Dozzle host too, in the main view.

Currently it shows it only on the remote agents, but not the host machine itself. This makes the whole overview look a bit odd. In addition, it would help to ensure that all Dozzle deployments are running the same version at one quick glance. Currently i can see the version that all my agents are running, but then i need to go into the settings menu on the host and compare that to the version number there.

[Here is a screenshot of the current view with multiple agents.](https://imgur.com/Nn8nTvz)

**Comment by amir20** [comment]
This was asked a few times. I am not against it. Except it might be confusing for the following reason. 

Dozzle supports agents, remote connections and local. None of them are required. For agent, it's simple as showing the agent version. 

However, Dozzle can be started just in UI mode and only connected to only agents. Where would the version be then?  In my opinion, the version should be shown on the UI and not specific to a server. 

Does that make sense? Which is why I have it on the settings page. Maybe the version number should be shown on the homepage near the top instead.

**Comment by amir20** [comment]
ping @l33tlamer

**Comment by l33tlamer** [comment]
Hey thanks for taking the time to reply!

> This was asked a few times. I am not against it. Except it might be confusing for the following reason.

Sorry i should have search existing issues before posting.

> Dozzle supports agents, remote connections and local. None of them are required. For agent, it's simple as showing the agent version.
> 
> However, Dozzle can be started just in UI mode and only connected to only agents. Where would the version be then? In my opinion, the version should be shown on the UI and not specific to a server.
> 
> Does that make sense? Which is why I have it on the settings page. Maybe the version number should be shown on the homepage near the top instead.

Yes i think i understand what you mean.

But why not simply have the version number of the host in the settings menu always. That way in "UI only" mode or without any agents, its still there are makes sense.

But if its run with agents only, display the version in the main view (as it is right now).

And if its run with host plus agents, display the version in the main view too, for the host and each agent.

Maybe using a slightly different color for the host to make it stand out a little compared to agents if thats a worry. Like a brighter shade of green vs a darker shade of green, if the version is up to date. And a brighter red/darker red if its out of date. Or something like that.

**Comment by amir20** [comment]
I am having hard time understanding. 

> But why not simply have the version number of the host in the settings menu always. That way in "UI only" mode or without any agents, its still there are makes sense.

Can you provide a screenshot?
