### ISSUE TITLE
broken log level badge

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#3234]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.2.1

### ✅ Command used to run Dozzle

-

### 🐛 Describe the bug / provide steps to reproduce it

This is an excerpt from official docker registry container log... seems the parser does not really like the format:
![image](https://github.com/user-attachments/assets/9de44c27-5994-4998-a8a0-6d47f911879f)

### 💻 Environment

-

**Comment by amir20** [comment]
Can you give me the `docker run` you used to run this. I don't run this container.

**Comment by FrancYescO** [comment]
`docker run -d -p 5000:5000 --restart always --name registry registry:2`

a few request to `/v2/_catalog?n=1000` should be enough to have a similar log

**Comment by amir20** [comment]
I tried running `registry:2` and got access denied. Haven't had much time to look at the README file. So I'll come back to it when I have time.

**Comment by FrancYescO** [comment]
hmm i just retried and i can confirm that a simple GET request to http://127.0.0.1:5000/v2/_catalog?n=1000 also issued from browser is working flawless (and gives `{"repositories":[]}` as response) .... maybe you have port 5000 user from something else?

**Comment by amir20** [comment]
Good guess. Port 5000 was something else. I would have never guessed that. 

I see the problem.  Not sure what is causing it. It's not as bad as I thought though.

**Comment by amir20** [comment]
Coming back this I think I know what is going on. I won't be able to fix it. The logic for grouping logs together with same level is if they are very close to each timer with timestamp. It does create false positives and this is one of those cases. I don't think I can do anything about it as I am just _guessing_ the levels.
