### ISSUE TITLE
Dozzle agent isn't able to run

### ISSUE THREAD

**Issue by ThreeTheOG** [amir20/dozzle#3273]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

8.4.3

### ✅ Command used to run Dozzle

```services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    restart: unless-stopped
networks: {}
```

### 🐛 Describe the bug / provide steps to reproduce it

Dozzle agent is erroring out on my raspberry pi 4b

I run the same docker compose to run the agent on one of my servers, and it works just fine. 

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 4
  Paused: 0
  Stopped: 7
 Images: 17
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-1020-raspi
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.702GiB
 Name: grimhex
 ID: 45dfe8b2-a19a-46b1-af89-5472844c93ea
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

dozzle-pi-dozzle-agent-1  | v6.2.5
dozzle-pi-dozzle-agent-1  | Usage: dozzle [--addr ADDR] [--base BASE] [--hostname HOSTNAME] [--level LEVEL] [--username USERNAME] [--password PASSWORD] [--auth-provider AUTH-PROVIDER] [--auth-header-user AUTH-HEADER-USER] [--auth-header-email AUTH-HEADER-EMAIL] [--auth-header-name AUTH-HEADER-NAME] [--wait-for-docker-seconds WAIT-FOR-DOCKER-SECONDS] [--enable-actions] [--filter FILTER] [--remote-host REMOTE-HOST] [--no-analytics] <command> [<args>]
dozzle-pi-dozzle-agent-1  | error: invalid subcommand: agent

**Comment by ThreeTheOG** [comment]
Using `image: amir20/dozzle:pr-3272` fixed the issue.

**Comment by amir20** [comment]
> dozzle-pi-dozzle-agent-1 | v6.2.5

You are running version 6 and not the latest.

**Comment by amir20** [comment]
You can test with `docker run amir20/dozzle --version`. 

Closing for now. Also don't use `pr-3272`. That has bugs.
