### ISSUE TITLE
List of exposed ports

### ISSUE THREAD

**Issue by pmarki** [amir20/dozzle#3285]
### Describe the feature you would like to see

Hi, great work! I use it all the time, now when there is an option to start/stop containers I'd love to see ports mapped so this application could replace docker management and simply dashboards (I actually keep a dashboard only top keep list of ports being used in my docker setup). Have you thought about this maybe?

### Describe how you would like to see this feature implemented

List of containers on starting page shows also ports that are exposed

### Describe any alternatives you've considered

Plenty of dashboards provides this feature, often they are over complicated or labels have to be kept in sync with docker compose configuration.

**Comment by amir20** [comment]
Hello,

Thank you! I have a couple of questions for you:

1. One principle I want to maintain for Dozzle is monitoring frequently changing data, such as stats, logs, and health checks. I can't imagine ports changing often. What is your use case? Do you need to check this frequently?
2. If it's easy to add, I’m not concerned about the principle. Where do you think it should be displayed? I believe the homepage dashboard is the most suitable location. The container log has a lot of UI elements, but it may not be used by many people.

Let me know! Thanks!

**Comment by pmarki** [comment]
Hi,
Let me explain a bit more. 

At the moment we have a list of containers on starting page, there is a name, host, status, created and average metrics, there could be also a column for mapped ports. To avoid increasing width of the container status could be changed to an icon maybe (or even icon with drop down to stop/start the service?)

Another idea would be turn this table more into cards, similar to how hosts are now presented, sorting could be done as a dropdown next to "Rows per page", that could allow to have all information visible on mobile view and fixed 'kind of' an issue where cell text is truncated in narrow window.

My use case is: 
One place to manage containers: I can stop/start them, I can checks logs, I can see how I can access the service without looking into docker-compose.yaml to find out which port has been assigned to this container, I can quickly find available port when spinning up new container. Based on this I can say your project is close to perfection :)  I could try to play with the code and propose something myself but I thought worth asking first.

**Comment by amir20** [comment]
Just for reference, I collect data and seems like on average the maximum number of containers are around 10k. 
<img width="941" alt="Screenshot 2024-09-26 at 8 11 34 AM" src="https://github.com/user-attachments/assets/69b3295e-2e5c-42fc-b8b2-80cc85a2794d">

I would consider this data when implementing UI changes.

**Comment by pmarki** [comment]
Hi @amir20, 
Once again words of appreciation to you (and all the people sharing their awesome work for free).
I will try to implement this. To be honest I already managed to have something.

**Comment by amir20** [comment]
@pmarki :) Gentle ping.

**Comment by pmarki** [comment]
Hi @amir20 pull request should be ready next week.

**Comment by amir20** [comment]
Great. I am preparing to release a new build today. I'll just release another one when you are ready.

**Comment by amir20** [comment]
Haven't heard back for a while. Going to close this @pmarki. I appreciate all the work you did but just judging from interest I don't see this is as highly wanted feature.

**Comment by pmarki** [comment]
Hi @amir20 it's still on my todo list, I just didn't have time to continue, better to close as I'm not sure when PR will be ready.

**Comment by sglbl** [comment]
> Plenty of dashboards provides this feature, often they are over complicated or labels have to be kept in sync with docker compose configuration.

I also came to create an issue for this and saw yours. Which other tools do you use to check the exposed ports? I have tens of images and even inside docker I use 8000 port, to expose I have so many apps so I mix them all the time. I would like to know the easiest ui to check for those.
