### ISSUE TITLE
lightweight alerting

### ISSUE THREAD

**Issue by tcurdt** [amir20/dozzle#3288]
### Describe the feature you would like to see

I would like to be able to monitor the logs for keywords and expose that information as a prometheus metric.

### Describe how you would like to see this feature implemented

Usually one looks at live logs after something happened. For some things this means some keyword are found in the logs. I get that this isn't the focus of doozle, but maybe it would be possible to define some monitoring rules and just expose them as prometheus metrics. That skips a lot of the notification complexities and still allows to integrate some alerting.

### Describe any alternatives you've considered

Loki

**Comment by tcurdt** [comment]
> What does that mean?

Can you be more specific what is unclear?


> Monitoring is not a lightweight task. It requires processing all logs in the background, which significantly increases CPU usage. I'm not particularly concerned about the notification aspect since it can operate in plugin mode. The real technical challenge lies in processing all the logs in the background.

We can also call it KISS alerting instead of "lightweight".

I haven't had the chance to fully dig into the code, but the idea would be to hook [into the server where all the messages are received](https://github.com/amir20/dozzle/blob/master/internal/agent/server.go#L358) or into the client where they are sent. We just need to tap into the stream.

But maybe I am missed something how the client/server communication works in detail.

Of course will searching every line for a substring will increase the CPU usage. But I am positive enough that a `strings.Contains(message, 'Error')` and a prometheus `counter.Inc()`, even for every log line, will not be what brings our servers down. When done on the clients it would make this even distributed. It would just mean more prometheus endpoints to scrape.

If needed, this work could even be spread across CPU s(using workers) of course, but it would probably be good to profile before adding that complexity.

If `fail2ban` can do it, I am positive there are options.

> I had an idea to implement an option that allows users to select specific containers for log processing while the browser is open. This concept was discussed in detail in https://github.com/amir20/dozzle/issues/2614. It involved service workers, notifications, and a considerable amount of JavaScript. However, it appeared unreliable because browsers often terminate background tabs.

That proposal mentions HTML5 notifications and web workers - which leaves me puzzled for the use case.
In my book this feature should not require a single line of javascript.
At most the browser could be used to control the needles we are searching for.

There are of course ways for a richer and better in-browser experience when going beyond (prometheus) counters.
But this would still be just a list of pointers into the stream, gathered and exposed by the server.

**Comment by amir20** [comment]
> Can you be more specific what is unclear?

I don't know prometheus metrics at all. Is this something that Dozzle would push metrics to or something else? How does integration with prometheus work? 

> I haven't had the chance to fully dig into the code, but the idea would be to hook [into the server where all the messages are received](https://github.com/amir20/dozzle/blob/master/internal/agent/server.go#L358) or into the client where they are sent. We just need to tap into the stream.

That's not how Dozzle works with the Docker API. There is no "hook" for that. Docker exposes an API where each container log requires a separate stream. For 100 containers, this means 100 connections are needed to listen to the logs.

Dozzle doesn't create any connections until a user requests them. If three users ask for a log, there will be three live API streams. When they close their browsers, the connections to the API close as well. Unfortunately, Docker doesn't provide a "pipeline" for all container logs, which complicates this request. However, Docker does have a stats API that I use to stream all stats in the background. This implementation added 10% CPU usage, which many users found excessive. I modified the implementation to stop streaming after a period of inactivity.

On average, I have seen 200 containers. Having 200 open connections to Docker would require intense processing.

> Of course will searching every line for a substring will increase the CPU usage. But I am positive enough that a strings.Contains(message, 'Error') and a prometheus counter.Inc(), even for every log line, will not be what brings our servers down. When done on the clients it would make this even distributed. It would just mean more prometheus endpoints to scrape.

This wouldn't be the bottleneck. As described above, it would be getting all the logs. 

> If fail2ban can do it, I am positive there are options.

Sorry I don't know fail2ban. 

> That proposal mentions HTML5 notifications and web workers - which leaves me puzzled for the use case.
In my book this feature should not require a single line of javascript.
At most the browser could be used to control the needles we are searching for.

HTML5 is not relevant to the implementation here; it merely served as a means of pushing notifications. Since Dozzle lacks a way to process all the logs, I thought it would be better to add a toggle in the search feature to trigger alerts. This is a neat idea, as it would only listen to the necessary containers. However, I believe you can grasp the complexity involved.

Does this clarify the complexity and performance issues?

I would love to support this use case, but I don't think it is as straightforward as many believe. I also oppose making this an opt-in implementation because I have found that adding toggles and configurations introduces significant complexity.

If you want to look a the code more and propose ideas then I can support you. But I won't work on this personally.

**Comment by tcurdt** [comment]
> I don't know prometheus metrics at all. Is this something that Dozzle would push metrics to or something else? How does integration with prometheus work?

You basically have counters (and others primitives). You could think of it a score board. 
And prometheus connects to the endpoint and scrapes the data and puts it into database.
Then Grafana would connect to that database to visualize the metrics.

Alerting can be setup on both Prometheus or Grafana.

It's really easy to add and a very common way to expose metrics.

https://prometheus.io/docs/guides/go-application/

> That's not how Dozzle works with the Docker API. There is no "hook" for that. Docker exposes an API where each container log requires a separate stream. For 100 containers, this means 100 connections are needed to listen to the logs.

That still allows for tapping into the stream(s).
 
> Dozzle doesn't create any connections until a user requests them. If three users ask for a log, there will be three live API streams. When they close their browsers, the connections to the API close as well. 

But it is that design that is the downfall of the idea.
The log reader would need to be independent of the browser.

> Unfortunately, Docker doesn't provide a "pipeline" for all container logs, which complicates this request.

Not really. This would still work without a single pipeline.
It's a task that is easy to distribute.

> However, Docker does have a stats API that I use to stream all stats in the background. This implementation added 10% CPU usage, which many users found excessive. I modified the implementation to stop streaming after a period of inactivity.

I saw that feature - and I also found it a bit strange given the focus for dozzle is log tailing.
And 10% is indeed surprisingly much for that.

We have metrics usually come from other tools already.

> On average, I have seen 200 containers. Having 200 open connections to Docker would require intense processing.

Sounds more like a kubernetes cluster than a docker host 🙃
We would only be interested in a fraction of all container logs anyway.


> > Of course will searching every line for a substring will increase the CPU usage. But I am positive enough that a strings.Contains(message, 'Error') and a prometheus counter.Inc(), even for every log line, will not be what brings our servers down. When done on the clients it would make this even distributed. It would just mean more prometheus endpoints to scrape.
> 
> This wouldn't be the bottleneck. As described above, it would be getting all the logs.

Unless you are streaming from the containers straight to the browser you get access to all the logs already.
Even if it's not in a central place.


> > If fail2ban can do it, I am positive there are options.
> 
> Sorry I don't know fail2ban.

A very standard tool that listens that matches on log files and triggers temporary firewall bans.

https://github.com/fail2ban/fail2ban


> HTML5 is not relevant to the implementation here; it merely served as a means of pushing notifications

Even that sounds like a strange idea to me.

> Since Dozzle lacks a way to process all the logs, I thought it would be better to add a toggle in the search feature to trigger alerts. This is a neat idea, as it would only listen to the necessary containers. However, I believe you can grasp the complexity involved.

That's still too browser oriented for my taste.

I don't think it's that complex the way I have it in my mind. But it seems like you are looking at it from a very different (more frontend) angle. Which is fair, but then I probably have to come up with something else then.
Find something else, fork or build something myself.

We've been using Loki in the past and I am not particular thrilled about it.
The first glimpse of dozzle looked nice and simple. Which got me interested.


> I would love to support this use case, but I don't think it is as straightforward as many believe. I also oppose making this an opt-in implementation because I have found that adding toggles and configurations introduces significant complexity.

I am pretty confident it's not that complex - but it might not be the best match for dozzle.

> If you want to look a the code more and propose ideas then I can support you. But I won't work on this personally.

Thanks for the offer.

**Comment by amir20** [comment]
Hey @tcurdt, I don't feel like we are collaborating well. There might be a language barrier, as the tone of your messages seems condescending. It feels like I'm arguing with a product manager about the complexity of a feature, only to be told it's easy.

You seem to have completely missed my point and focused on areas that don't matter.

Here’s a quick response, but it sounds like you don’t plan to work on this, so I will close the discussion.

1. I'm not sure why you are focused on the browser. My response had nothing to do with it. Browser notifications are just one way of receiving notifications; the processing still needs to happen. Messages can be sent to a browser, Prometheus, iOS push, or any other method. That’s what I meant by a plugin that probably doesn’t matter. Your response seems to focus on your specific use case.
2. You completely missed my point about the limitations of Docker. The architecture of Dozzle has nothing to do with this feature; it’s a limitation of the Docker API. The Docker API doesn’t provide a single pipeline for all logs, forcing clients to create separate threads for each container. Each thread adds about 2%. If you don’t believe me, you can prototype it. Therefore, I don’t think there is a scalable approach.
3. `fail2ban` doesn’t use the Docker API. I thought you would have looked at the code. It listens for file changes, which is much cheaper. This could even be done with Docker if you know where the files are stored. If I ever charge for Dozzle as an enterprise solution, I might implement that. But for now, Dozzle only leverages the API.

That said, it doesn’t seem like you plan to work on this. It sounds like you expected me to take the lead. I build Dozzle for myself and focus on my own use cases, and this isn’t one of them.

Closing for now.

**Comment by tcurdt** [comment]
> as the tone of your messages seems condescending. It feels like I'm arguing with a product manager about the complexity of a feature, only to be told it's easy.

Sorry, that certainly wasn't my intention.


> You seem to have completely missed my point and focused on areas that don't matter.

But I have the same feeling and hence decided to walk away.


> You completely missed my point about the limitations of Docker.

You are focused on a limitation that (honestly) barely matters in this context.
If you are fine with dozzle as is - I am not here to convince you it's not.


> fail2ban doesn’t use the Docker API. I thought you would have looked at the code. It listens for file changes, which is much cheaper. This could even be done with Docker if you know where the files are stored. 

Not just fail2ban...

https://github.com/grafana/loki/tree/3c36ba949d65e803cc6702b8664f87aca07ed052/clients/pkg/promtail

...and it's not that hard to find the log files on disk FWIW.

But that didn't even matter for the discussion I tried to have.


> It sounds like you expected me to take the lead. 

Not really. I was only testing the waters if you are interested in contributions. But I get that you are not.

**Comment by amir20** [comment]
> You are focused on a limitation that (honestly) barely matters in this context.
If you are fine with dozzle as is - I am not here to convince you it's not.

This is 100% not true. These matter a lot. I am not sure if you understand Docker enough to be able to provide alternative solutions.  I am saying one thread per log is not acceptable and I haven't heard what you propose.  This actually matters a lot and some people are running on older devices & raspberry pies with limited resources. 

>  Not really. I was only testing the waters if you are interested in contributions. But I get that you are not.

I am interested in contributing.  But you seem to argue more than propose alternative architectures. A better approach is to see a PR, prototype, design ideas. I'd like to think I am not the one writing all the code.

**Comment by tcurdt** [comment]
> I am not sure if you understand Docker enough to be able to provide alternative solutions

And that is not a condescending assumption?

But back to the technicals:

You can obtain the the file location via inspect call and will be given a `LogPath`

```
"LogPath": "/var/lib/docker/containers/a9a49af965a22a942460165efc12aa6ee6da8fd7b9235a75fbda3311e0d34731/a9a49af965a22a942460165efc12aa6ee6da8fd7b9235a75fbda3311e0d34731-json.log"
```

From that on it's watching files. And as you said - that's much cheaper.
It would be a bigger change though.

But my point was that Dozzle is delivering log files ... right ... now. 
Why would the number of threads need to change for just tapping into that data (on the server)?

CPU usage would increase with the number of needles and containers of course.
But not every container might need the searching.


> A better approach is to see a PR, prototype, design ideas

It's usually wise to discuss contribution with the owner before spending the time on a PR.

But I understand now that this project was create with a different usage in mind.
So - no hard feelings. Let's just move on.

**Comment by amir20** [comment]
> But my point was that Dozzle is delivering log files ... right ... now.
Why would the number of threads need to change for just tapping into that data (on the server)?

Because the number of threads directly depend on the number of containers. For 100 containers, it would require 100 background threads.  Dozzle doesn't read LogPath. It uses `docker logs ...` API _per_ container. 

> But not every container might need the searching.

I think that's where we differ.  In my mind, I want to create a solution where if someone says "I want to look for [foobar] in all my containers"  It wouldn't use 100% CPU. 

Hopefully that makes sense now. 

And agreed, let's move on.
