### ISSUE TITLE
Option to remember user (stay logged in)

### ISSUE THREAD

**Issue by FibreTTP** [amir20/dozzle#3309]
### Describe the feature you would like to see

Related to #2806, which was closed after fixing an issue with redirect URLs, which was only one part of the feature request.

An option to persist user login state through browser sessions should be added. Length of validity could also be configurable with an environment variable.

### Describe how you would like to see this feature implemented

Set an exp claim in the JWT and set the same value in the cookie expires field? I assume that would work, but I don't know anything about Go or even JWTs in general so I can't really help here, sorry.

I think these are the relevant places in the code:
https://github.com/amir20/dozzle/blob/9fa4911aec72ae7b14eeade2b272f62e1b9a4969/internal/auth/simple.go#L39-L42
https://github.com/amir20/dozzle/blob/077eeb79170d3286cae8e817306a927f35b46ddf/internal/web/auth.go#L14-L21

And upstream:
https://github.com/go-chi/jwtauth/blob/c856efe2bae161976c2f8d9899f0ee1d1b77056e/jwtauth.go#L122-L135

**Comment by FibreTTP** [comment]
I check logs to make sure things aren't broken (e.g., Gluetun) often enough that even having to open Bitwarden and simply clicking auto-fill is getting annoying. I don't always have a web browser open, and obviously session cookies are cleared when closed.

It would be nice if the duration is configurable, but I feel like one day is a good default.

**Comment by amir20** [comment]
I see. This was easy enough solution that I implemented it in https://github.com/amir20/dozzle/pull/3313. 

I haven't added documentation yet, but you should be able to do `DOZZLE_AUTH_TTL=24h`. Only minutes and hours is supported right now. 

Give it a try and I can merge if it works. You should be able to test with `amir20/dozzle:pr-3313`.

**Comment by amir20** [comment]
@FibreTTP good call out. Turns out I was not using expiration correctly with jwts. I fixed it now. I tried testing it by making the cookie expire longer and indeed it expires as expected. 

Can you give another try?

**Comment by amir20** [comment]
BTW, there is a lot of changes in this release so you might notice some other changes.

**Comment by amir20** [comment]
Merged now. Will need to do testing before releasing.

**Comment by amir20** [comment]
Everything should be released now.
