### ISSUE TITLE
Empty lines are showing as hidden fields

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#3323]
I was about to open an issue for exactly this but as this (and another one) already exist, I decided to give my feedback here.

To reproduce this, you can `exec` into any container and run `echo "" | tee /proc/1/fd/1`. this writes a blank line to the stdout (`fd/1`) of the container process (`proc/1` assuming the main pid is `1`) and thus into the logs.

I stumbled across this issue after (finally) installing dozzle on my raspberry where I have some containers running periodic task and seperating the outputs by some blank lines. I was extremely confused when seeing `all values are hidden`. While I understand your argument that it is [better UX to provide an indication instead of a real blank line](https://github.com/amir20/dozzle/issues/3109#issuecomment-2226937363), maybe it would be even better UX to have a similar output with `blank line` instead?

I tried to dig myself into the code to provide a PR, but unfortunately it seems, that building on windows is not supported and I currently have no linux based dev environment available.

_Originally posted by @dodgex in https://github.com/amir20/dozzle/issues/3297#issuecomment-2408591071_

**Comment by amir20** [comment]
@dodgex that is a different bug. This issue ["all values are hidden" replacing non empty lines] was suggesting that I replace non-empty lines. Which I don't think it is true.

This reason this bug is happening is because Dozzle thinks an empty line is actually a JSON log with all fields empty. It's a pretty easy fix, just not on my priority.

> I tried to dig myself into the code to provide a PR, but unfortunately it seems, that building on windows is not supported and I currently have no linux based dev environment available.

Is this true? The build mostly happen in Docker so it should theoretically work.

**Comment by amir20** [comment]
I am going to see if I can easily fix this.

**Comment by amir20** [comment]
Easy fix. See https://github.com/amir20/dozzle/pull/3324. Try `amir20/dozzle:pr-3324`.

**Comment by dodgex** [comment]
Looks good!
![image](https://github.com/user-attachments/assets/816c6654-ed45-4a03-b4fd-06ff39ce1e0a)

**Comment by dodgex** [comment]
> Is this true? The build mostly happen in Docker so it should theoretically work.

From the readme:
```
To build and test locally:

Install [NodeJs](https://nodejs.org/en/download/) and [pnpm](https://pnpm.io/installation).
Install [Go](https://go.dev/doc/install).
Install tools with make tools.
Install node modules pnpm install.
Run make dev to start a development server with hot reload.
```

On windows I dont have `make`, but i bypassed this by running the commands from the makefile for [`make tools`](https://github.com/amir20/dozzle/blob/master/Makefile#L61-L64) and [`make dev`](https://github.com/amir20/dozzle/blob/master/Makefile#L38-L39) (just created the dist/index.html and ran `pnpm dev`). The `pnpm dev` command faild because it was unable to use the ["env vars before command" syntax](https://github.com/amir20/dozzle/blob/master/package.json#L20) and after removing the env vars there, it faild due to missing `reflex ` command.

**Comment by dodgex** [comment]
> I am going to see if I can easily fix this.

Thanks for the amazingly fast reaction! :)

**Comment by amir20** [comment]
I see. So dev is broken. But if you just build Dockerfile it should work since everything is contained. 

For dev to work I'd have to update env and some other stuff. 

Good to see this works. Merging and releasing Monday.
