### ISSUE TITLE
Defining Display Options as Environment Variables

### ISSUE THREAD

**Issue by arnabghosal** [amir20/dozzle#3325]
### Describe the feature you would like to see

Currently, after setting up dozzle, i have to manually setup the Display options based on my preferences
Is there a way to setup these settings via Environment variables which can be defined in the Docker Compose File

### Describe how you would like to see this feature implemented

Introduce following Env Vars (sample)

- DISPLAY_OPTS_COMPACT_MODE: true / false
- DISPLAY_OPTS_SMALL_SCROLLBAR: true / false
- DISPLAY_OPTS_TIMESTAMP: true / false
- DISPLAY_OPTS_LANG: en / es / fr / etc
- DISPLAY_OPTS_DATE_FORMAT: YYYY-MM-DD / DD.MM.YYYY / etc
- DISPLAY_OPTS_TIME_FORMAT: 12 / 24

In case the user has not defined the ENV Vars, the default value could be set

**Comment by amir20** [comment]
This question has come up several times. Implementing it would require too much work on my part. All user preferences are stored in local storage. Therefore, Dozzle would need to read the CLI for each setting, merge it with the defaults, and resolve conflicts with local storage whenever changes occur. It's not worth my time.

On the positive side, if you have enabled authentication, this process is already handled for you, as user settings are stored on disk across devices. This is the better solution. Without authentication, Dozzle cannot identify who is logged in, which would lead to confusion.

Of course, pull requests are welcome if you have the time to work on this.

**Comment by arnabghosal** [comment]
Hello

Thanks for your feedback.
Closing this request

Thanks
