### ISSUE TITLE
Allow dozzle to seamlessly integrate within an API Gateway

### ISSUE THREAD

**Issue by nlko** [amir20/dozzle#3326]
### Describe the feature you would like to see

Hello, 

I would like to access dozzle through an API Gateway (kong for instance). 

It seems to me that dozzle is rewiting urls because when I access the route to dozzle through kong (let say https://whatever:443/logs) the initial pages load and try to load data at https://whatever:443/assets/main-pNNO1wUV.css

On this route, kong hasn't been configured to strip the path (remove /logs in the path) yet, the path was removed, so I believe it has been done by dozzle.

Would it be possible to keep the base url as it is, this way https://whatever:443/**whatever/route/i-use-for-dozzle**/assets/main-pNNO1wUV.css would work with the gateway ?

**Comment by amir20** [comment]
I am not sure what you are asking. Have you read https://dozzle.dev/guide/changing-base? It should already work.

**Comment by nlko** [comment]
Thanks, it works!
