### ISSUE TITLE
Row View

### ISSUE THREAD

**Issue by Cyberwayn3** [amir20/dozzle#3329]
### Describe the feature you would like to see

It is nice to have the view in rows, but I would like to have column view too

**Comment by amir20** [comment]
I have no idea what you are talking about.

**Comment by Cyberwayn3** [comment]
You have the Pin as Column, would be good to pin as row's

**Comment by amir20** [comment]
That's a lot of work and you are the second person to ask for it in the last 4 years. So not really.
