### ISSUE TITLE
UI style Suggestions

### ISSUE THREAD

**Issue by iamxiaojianzheng** [amir20/dozzle#3331]
### Describe the feature you would like to see

Hopefully, when compact mode is enabled, the rounded corner style of the timestamp can be removed, which might look better.
![image](https://github.com/user-attachments/assets/b2ec8294-dbcb-4aee-bac6-8e757b5b5fcc)

Of course, this is just an innocuous suggestion. 😀

### Describe how you would like to see this feature implemented

current style
![image](https://github.com/user-attachments/assets/b1175e5c-673a-4c18-a391-667b2639f7ab)

That might be better
![image](https://github.com/user-attachments/assets/af17b799-e2bf-42cb-84b3-e1d991b0c395)

**Comment by amir20** [comment]
I like that idea. Send PR if you can.

**Comment by iamxiaojianzheng** [comment]
> I built according to the readme description, but got an error.
> 
> ```
> main.go:33: running "protoc": exec: "protoc": executable file not found in $PATH
> make: *** [Makefile:54: internal/agent/pb/rpc.pb.go] Error 1
> ```

resolved

**Comment by iamxiaojianzheng** [comment]
Sorry, after trying, I couldn't finish this pr.

I tried to change the css, but it didn't work. But it works in the browser. Maybe I'm not familiar with postcss.

assets/components/LogViewer/LogList.vue@98
```postcss
  &.compact {
    > li {
      @apply py-0;
      > div div[class~=selet-none] {
        @apply rounded-none;
      }
    }
  }
```

Additionally, I suggest removing the hard-coded `:size="small"`  in `Tag` component and instead having this controlled by a configuration item. 

The current timestamp cannot change as the font size configuration option is changed.

assets/components/common/Tag.vue
```vue
<template>
  <div class="inline-flex items-center justify-center rounded bg-base-lighter px-2 py-[0.2em]" :size="size">
    <slot></slot>
  </div>
</template>

<script lang="ts" setup>
const { size = undefined } = defineProps<{ size?: "small" | undefined }>();
</script>

<style scoped lang="postcss">
[size="small"] {
  @apply text-xs;
}
</style>
```

**Comment by amir20** [comment]
I'll take a look between my meetings and see what I can do.

**Comment by iamxiaojianzheng** [comment]
> https://github.com/amir20/dozzle/pull/3332/files Seems to work. You can test with `amir20/dozzle:pr-3332`.
> 
> > Additionally, I suggest removing the hard-coded :size="small" in Tag component and instead having this controlled by a configuration item.
> 
> I didn't understand this. It's not hard coded. It's default to `undefined`. But if you look at `LogDate.vue` it does have `small`. It would be very big if I remove it even in non-compact mode.

Okay, I get that.
