### ISSUE TITLE
Are you a designer? Looking for a new logo for Dozzle

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#3334]
### Help wanted

I am looking to create a new logo for Dozzle. If you are a designer or are interested then please let me know.

**Comment by urielmon** [comment]
I am not a designer, but love Dozzle and think it would be nice to see it refreshed :)
Found an online AI based logo generator called Looka (have absolutely no relation to it) that gives some clean and nice logos. 
See here for example a Dozzle modern logo I created in 30sec:
https://looka.com/s/200806274

![image](https://github.com/user-attachments/assets/fe4578c0-7428-48f2-9405-e40b4df1cf65)

**Comment by amir20** [comment]
@urielmon I looked at looka a while ago. I found most of their logos to be a 'cartoonish'. I ended up using ChatGPT and got some better ideas but the problem was that it doesn't create Figma files. So it was still hard to generate different variations of it. Maybe I'll use Looka with a combination of some other tool to generate Figma files.

**Comment by amir20** [comment]
Some ideas I have been playing with 

![Untitled from Figma (1)](https://github.com/user-attachments/assets/20452c48-0924-4477-8980-630adb274ebb)

![Untitled from Figma](https://github.com/user-attachments/assets/5c3b34e8-4e50-4d6f-9b3f-c38068fdfe86)

Of course, the colors are just for testing.
