### ISSUE TITLE
Missing vertical scroll bar on SQL Analytics overlay

### ISSUE THREAD

**Issue by yubiuser** [amir20/dozzle#3347]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.6.2

### ✅ Command used to run Dozzle

Not applicable

### 🐛 Describe the bug / provide steps to reproduce it

Open the SQL Analytics. If the results produce a table longer than the screen height one is able to scroll down, but no scroll bar is shown 

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 15
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-23-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.39GiB
 Name: s740
 ID: 8f5b43d7-eb98-4adb-9d15-15e52c62e678
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by amir20** [comment]
https://github.com/user-attachments/assets/16ed9deb-ac30-49aa-8fa7-20b4d4b74b58

There is a scrollbar for me. Tested on Chrome.

**Comment by yubiuser** [comment]
On chrome as well (Version 130.0.6723.69 (Official Build) (64-bit))

![Peek 2024-10-25 22-12](https://github.com/user-attachments/assets/193eb3e7-e3da-497c-b2f2-1e11f2253d22)

**Comment by yubiuser** [comment]
No issue using Firefox here.

**Comment by amir20** [comment]
What OS?

**Comment by yubiuser** [comment]
```
System:
  Host: T14Gen5 Kernel: 6.11.0-061100-generic arch: x86_64 bits: 64
  Desktop: MATE v: 1.26.2 Distro: Linux Mint 22 Wilma
```

**Comment by amir20** [comment]
Hmm seems to be a Linux bug. I don't have one handy. I'll keep this open, hoping someone who knows CSS really well can help out.
