### ISSUE TITLE
Settings: option for auto merging group into one view

### ISSUE THREAD

**Issue by vanodevium** [amir20/dozzle#3365]
### Describe the feature you would like to see

Imagine we have group of containers:

![image](https://github.com/user-attachments/assets/a1aa5732-4120-4f0f-9cf5-de41e5abfecd)

For now, if I click on **group name** it will be opened as accordion:

![image](https://github.com/user-attachments/assets/d82836a1-ec31-4a1b-8e25-f5e6acd4b44c)

If I want to see merged logs, I have to click exactly on **green button**.

It seems to me that it would be very convenient to be able to specify in the settings that clicking on the **group name** is like clicking on the green button

**Comment by amir20** [comment]
I wouldn't find this feature helpful. Just clicking the merge button is easy enough. Why make it complicated.
