### ISSUE TITLE
Agent fails to start

### ISSUE THREAD

**Issue by laneyweb** [amir20/dozzle#3367]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

8.7.1

### ✅ Command used to run Dozzle

services:
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
networks: {}

### 🐛 Describe the bug / provide steps to reproduce it

When trying to run the agent on another docker host, I get an error and the container fails to load.
I am running the standard compose.yml and get the following when running:
dozzle_agent-dozzle-agent-1  | v3.8.0
dozzle_agent-dozzle-agent-1  | Usage: dozzle [--addr ADDR] [--base BASE] [--level LEVEL] [--tailsize TAILSIZE] [--key KEY] [--username USERNAME] [--password PASSWORD] [--no-analytics] [--filter FILTER]
dozzle_agent-dozzle-agent-1  | error: too many positional arguments at 'agent'
dozzle_agent-dozzle-agent-1 exited with code 255

### 💻 Environment

Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 11
  Running: 7
  Paused: 0
  Stopped: 4
 Images: 59
 Server Version: 20.10.23
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b23a389d8c181697302d163356e97dec04eb8d88
 runc version: 5af893d
 init version: ed96d00
 Security Options:
  apparmor
 Kernel Version: 4.4.302+
 Operating System: DiskStation

 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.619GiB
 Name: bertha2
 ID: BIHU:IMAI:GGYJ:45JB:SERX:X3QI:SE64:M7HG:HSEI:TBOL:EMHT:DRQ4
 Docker Root Dir: /volume2/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by amir20** [comment]
You are not running `8.7.1`. You are running `v3.8.0` which as displayed in the logs.

**Comment by laneyweb** [comment]
Thank you for the reply. I tested Dozzle way back and it seems the old version was picked up somehow. I now have the latest. Appreciate the prompt reply.
