### ISSUE TITLE
Healthcheck in docker run?

### ISSUE THREAD

**Issue by janreinhardt** [amir20/dozzle#3370]
### Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### Dozzle version

8.7.2

### ✅ Command used to run Dozzle

```
docker run -d --name=dozzle --restart unless-stopped \
--health-cmd='/dozzle/healthcheck' \
--health-start-period=30s \
--health-interval=3s \
--health-retries=5 \
--health-timeout=30s \
-p 8888:8080 \
-e DOZZLE_ENABLE_ACTIONS=true \
-e DOZZLE_NO_ANALYTICS=true \
-v /var/run/docker.sock:/var/run/docker.sock \
amir20/dozzle:latest
```

### Describe the performance issue you are seeing

Please, this is not the right place for me asking for help, but Ive read everything and looked everywhere, and there is no other forum or help section, so all I can do is ask:
I am not running Dozzle via docker-compose, but just by the run command. **How do I get the healthcheck working?**

My below syntax
**--health-cmd='/dozzle/healthcheck'**
is wrong and Ive tried a lot, but Im still a newbie :-(

Thank you!

### How many containers, hosts, agents, etc. are you using?

17 containers

**Comment by amir20** [comment]
The correct command is `--health-cmd='/dozzle healthcheck'`. However, it doesn't seem to work. I have tested it and healtheck fails. I am not sure why.  Compose example from https://dozzle.dev/guide/healthcheck#adding-healthcheck seems to work . 

I am not sure why it is not working.

**Comment by amir20** [comment]
Yep. It is a bug from docker. https://github.com/docker/cli/issues/3719

`--health-cmd` is not correctly used. There is no fix. Using compose file should fix it.

**Comment by janreinhardt** [comment]
Thank you!
I would have always assumed this was my mistake and not a Docker bug

**Comment by zodac** [comment]
> Yep. It is a bug from docker. [docker/cli#3719](https://github.com/docker/cli/issues/3719)
> 
> `--health-cmd` is not correctly used. There is no fix. Using compose file should fix it.

Hi @amir20 , would you have any objection if I raised a PR to add the HEALTHCHECK command into the Dockerfile? I've tested it locally by extending your published image and it seems fine, and would avoid the need to define it elsewhere.

**Comment by zodac** [comment]
Thanks for the reply. That's fair enough, I'll leave it then. :)
