### ISSUE TITLE
Minimum logs is broken 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#3383]
seems we have a regression.. this bug came back in some of the latest version (the `fill` parameter seems is not anymore here)

_Originally posted by @FrancYescO in https://github.com/amir20/dozzle/issues/3222#issuecomment-2471528210_

**Comment by amir20** [comment]
@ FrancYescO 

I think my for loop was broken and breaking too soon. Try `amir20/dozzle:pr-3384`.

**Comment by FrancYescO** [comment]
i can confirm the pr fixes the issue, also if for all the scroll, and only for few containers, the percentage does not change i have "1%" in top right (also when i'm at the bottom of the logs)
