### ISSUE TITLE
Color Options

### ISSUE THREAD

**Issue by Droidem** [amir20/dozzle#3392]
### Describe the feature you would like to see

The ability to change the text colors

### Describe how you would like to see this feature implemented

An option in the settings to define the LogDetails.vue file.

https://github.com/amir20/dozzle/blob/9296b1f7cf591895b610ecbfc37b45b53f99f07e/assets/components/LogViewer/LogDetails.vue#L180-L197

### Describe any alternatives you've considered

I have to highlight the text to be able to read it.

**Comment by amir20** [comment]
What does it look like to you?

The solution isn’t simply to add settings. Instead, it’s better to select colors that harmonize well across various environments.

Customization can be a time-consuming process.

**Comment by Droidem** [comment]
The blue & purple is really hard to read when using the dark color scheme.

**Comment by amir20** [comment]
Glad I asked. That is not the code that is making those colors happen. 

Those colors are coming from your application. They are ANSI colors. They can't be customized. 

You should disable ANSI colors or switch to light mode.

**Comment by amir20** [comment]
The colors are coming from your application. I am not sure how you are logging. This isn't something I can help.
