### ISSUE TITLE
Add "Show hostnames" feature and column to Swarm logs

### ISSUE THREAD

**Issue by mitchplze** [amir20/dozzle#3395]
### Describe the feature you would like to see

> I might put in another feature req for this, but it would probably help if there was a `Show hostnames` radio button (and feature) on the below screen. The colour coding is a great start for Swarm mode, but having the actual node name available in log view would be very helpful.

<img width="557" alt="image" src="https://github.com/user-attachments/assets/ae7a2445-844c-4f89-8752-ce18f50306d6">

<img width="323" alt="image" src="https://github.com/user-attachments/assets/13c4bbad-3793-44c7-b701-6e725dd1aee3">

_Originally posted by @mitchplze in https://github.com/amir20/dozzle/issues/3378#issuecomment-2479963524_
            

### Describe how you would like to see this feature implemented

Toggle switch in display settings
Column in log view

### Describe any alternatives you've considered

Maybe showing a colour-coded legend of the hosts in Swarm mode, that shows which colour is which node.

**Comment by amir20** [comment]
To me this makes more sense to be part of drop down in service mode. 


<img width="215" alt="Screenshot 2024-11-16 at 4 36 16 PM" src="https://github.com/user-attachments/assets/feec08b6-f150-43cc-8949-508f8f58ff65">


I'll think about it.

**Comment by amir20** [comment]
This was fixed in https://github.com/amir20/dozzle/pull/3406
