### ISSUE TITLE
Nodejs express winston logs does not appear anymore

### ISSUE THREAD

**Issue by iwebbg** [amir20/dozzle#3397]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.7.4

### ✅ Command used to run Dozzle

Docker compose

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    networks:
      - ${NETWORK}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8080
    environment:
      DOZZLE_LEVEL: trace
      DOZZLE_BASE: "/dozzle"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

### 🐛 Describe the bug / provide steps to reproduce it

Before release of latest version, the logs from nodejs express winston appears to the container, now displays only console logs.
I also try to set DOZZLE_LEVEL: debug, but same issue. Before release it shows winston logs on trace

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-48-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.59GiB
 Name: stefan-zdev
 ID: 72e29a10-174c-4c28-814a-d5c2f28a074e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### 📸 If applicable, add screenshots to help explain your bug

![image](https://github.com/user-attachments/assets/4aeb5d4f-7fa3-457a-9c53-6d0383415443)
![image](https://github.com/user-attachments/assets/a841df84-cbe8-4638-80d5-a79ae26db65a)

**Comment by amir20** [comment]
I am not sure what you mean. Can you attach your logs in a zip file and I can give it a try locally. Latest release didn't change any logic in how the logs are read. 

I think something else is happening.

**Comment by iwebbg** [comment]
Maybe is not in a latest release but we have running 10 different backend servers, on both of them logs are appeared, but on same which we make docker prune and downloaded latest version, everything is shown like now, now will check on which version logs is shown.

**Comment by iwebbg** [comment]
now i downgrade to https://hub.docker.com/layers/amir20/dozzle/v8.5.4/images/sha256-1d3c0c2d34f8c9cbdad181061ad51315cefffbfd7cabad88dd48020f1a3418d7?context=explore

And nodejs logs appears, its with old logo of dozzle.

![image](https://github.com/user-attachments/assets/1b227aae-04c3-4c11-a480-0fa2e036b0fe)

**Comment by amir20** [comment]
There were some filters added to be able to hide different levels. I wonder if it broke something. 

But I would still need the logs for me to reproduce locally. So please attach the logs.

**Comment by iwebbg** [comment]
Here is the logs
[Uploading api-service.log…]()

**Comment by amir20** [comment]
That didn't attach anything. Try zipping it and attaching it.

**Comment by amir20** [comment]
Found the issue! Those logs helped. You logs have a weird ansi color for logs eg `"level":"\u001b[32minfo\u001b[39m"`. 

I'll see if I can fix it on my side.
