### ISSUE TITLE
[Podman] Logs not showing before/after redeployment with Ansible

### ISSUE THREAD

**Issue by rheaalleen** [amir20/dozzle#3405]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### 📦 Dozzle version

8.80

### ✅ Command used to run Dozzle

![image](https://github.com/user-attachments/assets/42f28ded-336b-410b-8a97-322c42125fc4)

### 🐛 Describe the bug / provide steps to reproduce it

The Dozzle server and agents are communicating directly with IP:Port over a management VLAN, so the SSE buffering issue shouldnt apply here to my understanding.

When provisioning the VMs with the configuration I´ve a random chance which agent and container logs are loading. Redploying from blank VMs spins the roulette again. I´m not using snapshots or some other kind of backup. During testing I destroyed the VMs with OpenTofu and created them again.

The only error that appears is "level=errorerror=host ada202f1-c272-4bfe-8b73-4ce3bb98db2d not found time=2024-11-19T00:35:04 message=error while finding container"

If I leave the deployment of Dozzle as it is and then update the containers the remaining agents also stop delivering logs.
The logs from the main Dozzle server then only displays the error log above for everything
![image](https://github.com/user-attachments/assets/7d707cdf-7728-4c49-8419-ccb724a4cb1b)

The current Ansible configuration downloads new images if applicable and recreates the systemd file, enabling and restarting the container. This means that IDs are changing during the lifecycle.

### 💻 Environment

host:
  arch: amd64
  buildahVersion: 1.28.2
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.6+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: unknown'
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.05
    userPercent: 0.07
  cpus: 2
  distribution:
    codename: bookworm
    distribution: debian
    version: "12"
  eventLogger: journald
  hostname: kanidm
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1051
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1051
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 6.1.0-27-cloud-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 120623104
  memTotal: 4118568960
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_1.8.1-1+deb12u1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1051/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1051/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 94h 6m 28.00s (Approximately 3.92 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/podman-deploy/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/podman-deploy/.local/share/containers/storage
  graphRootAllocated: 16733839360
  graphRootUsed: 6531084288
  graphStatus: {}
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1051/containers
  volumePath: /home/podman-deploy/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.19.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1

**Comment by amir20** [comment]
I don't use Podman, so I can't help much with reproducing this issue. However, after reading the log, I believe I understand the problem. When you provision a host and install Docker, it generates an `engine-id`. This [FAQ covers](https://dozzle.dev/guide/faq#i-am-seeing-duplicate-hosts-error-in-the-logs-how-do-i-fix-it) some details. I think this is why you're encountering the `host ada202f1-c272-4bfe-8b73-4ce3bb98db2d not found` error.

The solution is to write the same ID to `/var/lib/docker/engine-id` each time.

I'm sorry I can't provide more as I don't have your setup.

**Comment by rheaalleen** [comment]
Hey @amir20, thanks for the feedback.

Creating a fake engine-id works. With Ansible there is a module for creating namesapce UUIDs that fit the engine-id. After recreating the dozzle container every log/agent works flawlessly.

![image](https://github.com/user-attachments/assets/8194f796-de67-4a06-a550-588529ffc235)

Maybe it's worth a mention in the FAQ that running on Podman you have to create a fake engine-id file. Otherwise I haven't encountered any issues running it.

**Comment by rheaalleen** [comment]
Added some documentation with #3407
