### ISSUE TITLE
incorrect CPU display in the dashboard?

### ISSUE THREAD

**Issue by Boebbele** [amir20/dozzle#3414]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

latest

### ✅ Command used to run Dozzle

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8082:8080
    restart: unless-stopped
networks: {}

### 🐛 Describe the bug / provide steps to reproduce it

the app is great! Thank you!

But I noticed one thing: 
the display for the CPU performance gives me a value that is too high. Which lib do you use to read the value? psutil?

The green ring should also show a 1/4 circle at 25%, 1/2 circle at 50%,...CPU performance. Or? In my case, at 25% only an 1/8 circle is green....

### 💻 Environment

root@homeassistant:~# docker system info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins

**Comment by Boebbele** [comment]
Okay. sorry for my bad English...
I understand the CPU power is not that of the host but of docker. But can the CPU power of the host be lower than that of docker? Sorry for the stupid question. I'm a beginner with docker.

With the green ring... I mean the graphical display around the CPU performance number..
I assume that the circle is completely closed at 100% CPU and half full at 50%? I don't know how else to describe it.
![Imagepipe_0](https://github.com/user-attachments/assets/8c65851d-aad7-46c6-976a-63616f3956d1)

**Comment by amir20** [comment]
> With the green ring... I mean the graphical display around the CPU performance number..
> I assume that the circle is completely closed at 100% CPU and half full at 50%? I don't know how else to describe it.

No that is not correct. It is 100% for ONE cpu. You have four CPUs so max would be 400%. This is how operating systems report CPU usage for multiple CPUs.
