### ISSUE TITLE
Log4j stacktrace appends time to every line

### ISSUE THREAD

**Issue by raduiacobescu** [amir20/dozzle#342]
Log4j stacktrace appends time to every line, it should append it just to the first line and for the rest leave a tab.

Any idea on how to quickly fix this or I guess I will look over the code and try to contribute.

Thanks
Radu

**Comment by amir20** [comment]
@raduiacobescu, I assume Log4j is writing multiple lines and docker thinks they are each different log events. I don't know of any way to fix that because that's how docker stdout works. 

One idea is to make a settings option that disables timestamp.

**Comment by amir20** [comment]
PRs are welcomed. Otherwise this isn't a bug so closing.

**Comment by raduiacobescu** [comment]
I've added a pull-request: https://github.com/amir20/dozzle/pull/387/files

Kindly asking you for a bit of help on how to add into the LogViewer.vue the value `hiddenTimestamps` from settings
