### ISSUE TITLE
Implement healthcheck for swarm mode

### ISSUE THREAD

**Issue by wuast94** [amir20/dozzle#3420]
### Describe the feature you would like to see

would be nice to have an web endpoint for healthchecks with external services like uptimekuma.

### Describe how you would like to see this feature implemented

some simple json response so we can see that the app is startet

there could also be a check if the access to the docker sock is successfull

### Describe any alternatives you've considered

im running in a swarm env and i could use docker healthcheck and connect uptimekuma to the socket but that is something i would like to avoid becouse of security reasons and i then must run uptimekuma on the managers which i also dont like.

**Comment by amir20** [comment]
That's already implemented. https://dozzle.dev/guide/healthcheck#enabling-healthcheck internally it hits /healthcheck. You can do the same thing. It just won't work with agents.

**Comment by wuast94** [comment]
found this too but i just get a white screen or the error https://github.com/amir20/dozzle/blob/3f3346d00354fd14383a0368a588b4bf869e9f23/internal/web/healthcheck.go#L20

but everything elso works so its a false positive for me?

**Comment by amir20** [comment]
Can you test with curl? I'll try it out some time today.

**Comment by wuast94** [comment]
500 with `Error listing containers`
```
* [HTTP/2] [1] OPENED stream for https://sub.domain.tld/healthcheck
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: sub.domain.tld]
* [HTTP/2] [1] [:path: /healthcheck]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET /healthcheck HTTP/2
> Host: sub.domain.tld
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/2 500 
< access-control-allow-origin: *
< alt-svc: h3=":443"; ma=2592000
< content-type: text/plain; charset=utf-8
< date: Sun, 24 Nov 2024 15:50:46 GMT
< permissions-policy: camera=*, microphone=(), geolocation=(), payment=(), usb=()
< referrer-policy: same-origin
< strict-transport-security: max-age=63072000; includeSubDomains; preload
< vary: Origin
< x-content-type-options: nosniff
< x-forwarded-proto: https
< x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex,noindex,nofollow,nositelinkssearchbox
< x-xss-protection: 1; mode=block
< content-length: 25
< 
Error listing containers
* Connection #0 to host sub.domain.tld left intact
```
or 200 with zero content
```
* [HTTP/2] [1] OPENED stream for https://sub.domain.tld/healthcheck
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: sub.domain.tld]
* [HTTP/2] [1] [:path: /healthcheck]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET /healthcheck HTTP/2
> Host: sub.domain.tld
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/2 200 
< access-control-allow-origin: *
< alt-svc: h3=":443"; ma=2592000
< date: Sun, 24 Nov 2024 15:50:47 GMT
< permissions-policy: camera=*, microphone=(), geolocation=(), payment=(), usb=()
< referrer-policy: same-origin
< strict-transport-security: max-age=63072000; includeSubDomains; preload
< vary: Origin
< x-content-type-options: nosniff
< x-forwarded-proto: https
< x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex,noindex,nofollow,nositelinkssearchbox
< x-xss-protection: 1; mode=block
< content-length: 0
< 
* Connection #0 to host sub.domain.tld left intact
```

maybee its becouse of my swarm? i deployed it global so the reverse proxy is load balancing i think, showing logs of services etc all working fine. also i see all my swarm members and the stats on the main screen.

**Comment by amir20** [comment]
You might be right. I don't think I have paid a lot of attention to swarm mode with healthcheck. I'll have to test it.  Right now, in Swarm mode, it tries to ping each host. But maybe that's not right.

**Comment by amir20** [comment]
Hmmm, I actually think it's working for me.

```
❯ http http://localhost:8080/healthcheck                                                                                                                                                                      
HTTP/1.1 200 OK
Content-Length: 0
Content-Security-Policy: default-src 'self' 'wasm-unsafe-eval' blob: https://cdn.jsdelivr.net https://*.duckdb.org; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
Date: Sun, 24 Nov 2024 16:56:50 GMT
```

I checked this about ten times, and each time I received a status of `200`.

Looking at the logs, everything seems to be functioning properly.

<img width="1649" alt="Screenshot 2024-11-24 at 8 57 47 AM" src="https://github.com/user-attachments/assets/b9619c46-2754-46a6-b21e-7e19e9f20eb0">

I am no longer encountering the `Error listing containers` message. It occurred briefly while the cluster was starting up, but now it's fine.

I do see room for improvement. I noticed that in swarm mode, the health check monitors all nodes, but it should only check its own connection.

**Comment by wuast94** [comment]
intresting, i also refreshed a lot of times and no i dont get it anymore. 

could it be that the first time after a start raises the error and then it works as expected?

**Comment by amir20** [comment]
I implemented the swarm feature a while ago. I believe the issue is that the nodes aren't discovered until the browser is refreshed. When this happens, they start loading, which explains why an error occurs in the first few seconds. 

I think that if I make the improvement I suggested above, it will resolve this issue.

**Comment by amir20** [comment]
Implemented a better health check for swarm. Now each node should test only it's own connection. Of course, if you are behind a proxy, it will randomly choose one to report the health status. You probably want to [setup](https://dozzle.dev/guide/healthcheck#enabling-healthcheck) health checks instead.

**Comment by wuast94** [comment]
thoose healthcheck i already have implemented so swarm can have controll over the containers. 

uptimekuma and the healthcheck is used as my central dashboard to see if everything is up and running as expected :)

thanks for the awesome work 💯
