### ISSUE TITLE
Limit of 25 agents supported

### ISSUE THREAD

**Issue by dhop90** [amir20/dozzle#3421]
### Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Agents

### Dozzle version

v8.8.1

### ✅ Command used to run Dozzle

kubernetes deployment

### Describe the performance issue you are seeing

Only 25 agents are supported.  I have 26 agents deployed and only the first 25 agents are monitored.  The 26th agent shows as offline

### How many containers, hosts, agents, etc. are you using?

26 agents

**Comment by amir20** [comment]
There is no limit. You are most likely running to [this issue](https://dozzle.dev/guide/faq#i-am-seeing-duplicate-hosts-error-in-the-logs-how-do-i-fix-it).  You should check for errors on your main UI instance. 

By the way, how you running in k8s? Are you using cri-dockerd?

**Comment by dhop90** [comment]
I've run into https://dozzle.dev/guide/faq#i-am-seeing-duplicate-hosts-error-in-the-logs-how-do-i-fix-it this issue before, this is not it.

Yes I'm using cri-dockerd

I've commented about my k8s setup before in this issue https://github.com/amir20/dozzle/issues/3108.

With 25 agents connected and 1 agent offline, if I take down one of the 25 agents online, the 1 previous offline agent becomes active.

**Comment by amir20** [comment]
Oh that's right I remember. 


Hmmm my dashboard shows people using up to 50 agents. So I don't think there is any hard limits. 

Are there no errors in the log?

**Comment by dhop90** [comment]
I made no changes and now it's working.  Only thing I did was shutdown a none cluster host for a couple hours then turned it back on.  All 26 agents are now connected.

**Comment by amir20** [comment]
Ok I am going to close. I don't think Dozzle is the culprit here. If there is no error then there is nothing to fix.
