### ISSUE TITLE
Can't display replaced containers' logs

### ISSUE THREAD

**Issue by zfben** [amir20/dozzle#3428]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.8.2

### ✅ Command used to run Dozzle

`podman run --name dozzle -v=/home/ubuntu/dozzle/data:/data -v=/run/user/1000/podman/podman.sock:/var/run/docker.sock -d -p 8080:8080 --replace docker.io/amir20/dozzle:latest --auth-provider=simple`

### 🐛 Describe the bug / provide steps to reproduce it

1. podman run with --replace
2.`Error response from daemon: no container with name or ID "73219636be31" found: no such container`

PS. I have added engine-id from https://github.com/amir20/dozzle/blob/master/docs/guide/podman.md, but I don't use Ansible, so I don't sure if engine-id is enought?

### 💻 Environment

host:
  arch: amd64
  buildahVersion: 1.33.7
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.10+ds1-1build2_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: unknown'
  cpuUtilization:
    idlePercent: 98.77
    systemPercent: 0.77
    userPercent: 0.46
  cpus: 2
  databaseBackend: sqlite
  distribution:
    codename: noble
    distribution: ubuntu
    version: "24.04"
  eventLogger: journald
  freeLocks: 2043
  hostname: VM-0-3-ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.8.0-49-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 272433152
  memTotal: 3770724352
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.4.0-5_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.4.0
    package: netavark_1.4.0-4_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.4.0
  ociRuntime:
    name: crun
    package: crun_1.14.1-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.1
      commit: de537a7965bfbe9992e2cfae0baeb56a08128171
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20240220.1e6f92b-1_amd64
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.1-1build2_amd64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 2084028416
  swapTotal: 2084564992
  uptime: 140h 42m 25.00s (Approximately 5.83 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/ubuntu/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ubuntu/.local/share/containers/storage
  graphRootAllocated: 52721041408
  graphRootUsed: 11654713344
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 10
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/ubuntu/.local/share/containers/storage/volumes
version:
  APIVersion: 4.9.3
  Built: 0
  BuiltTime: Thu Jan  1 08:00:00 1970
  GitCommit: ""
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3

### 📸 If applicable, add screenshots to help explain your bug

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/1fb8619b-0443-4211-a195-a3cd8f59eb5b">

**Comment by amir20** [comment]
I am having a hard time understanding this issue, but I'll take a guess. I have looked into the `--replace` flag, which seems to be unique to Podman, as Docker does not have such a flag. Currently, I don't believe Podman is fully supported in Dozzle.

However, it should be an easy fix. I don't use Podman personally, but I suspect that `--replace` triggers specific events that Dozzle is not tracking.

If more people were interested in this feature, it would make sense for me to investigate further. That doesn't seem to be the case right now.

**Comment by amir20** [comment]
I did a little bit of testing with podman on debian. I wasn't able to run podman on Mac. I tested `--replace` with 

    podman run --name test -d --replace docker.io/amir20/echo -r

Every time it seemed to work. The new id was also used and the name was replaced correctly.
