### ISSUE TITLE
"unsupported platform on 1 node"  with specified image,

### ISSUE THREAD

**Issue by falkheiland** [amir20/dozzle#3432]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Swarm Mode

### 📦 Dozzle version

latest

### ✅ Command used to run Dozzle

should be amir20/dozzle:latest , i suppose

### 🐛 Describe the bug / provide steps to reproduce it

n.a.

### 💻 Environment

n.a.

**Comment by falkheiland** [comment]
somehow did not picku up the line on creation

https://github.com/amir20/dozzle/blob/daee5b7dc413024a848dac08363301c9c04e3176/examples/docker.swarm.yml#L3

**Comment by amir20** [comment]
I have no idea what you are saying in this bug. Local-test is only for testing.

**Comment by falkheiland** [comment]
it is regarding the examples/docker.swarm.yml - 
it is under examples and titled docker.swarm.yml - so i assumed it is a docker swarm example - it did not seemed to be a test / for testing tbh.

**Comment by amir20** [comment]
https://dozzle.dev/guide/swarm-mode

I change examples all the time to do internal testing. The documentation is the right place to copy and paste commands.
