### ISSUE TITLE
Protecting sensitive data

### ISSUE THREAD

**Issue by temamagic** [amir20/dozzle#3444]
### Describe the feature you would like to see

First of all, thanks for this project!

It would be cool if it were possible to specify some sensitive data that should be masked in the logs. For example: I gave developers access to the logs, and I want to protect the logs from possible disclosure of tokens via echo or print.
It seems like this should be useful to many people in general.

### Describe how you would like to see this feature implemented

I haven't had time to dive into the code yet, but as I understand it, there is a method that sends messages from logs to a stream, it seems that you can control sensitive data there and mask it

### Describe any alternatives you've considered

I don't know any alternatives :(
Anyway, I don't know if this is the case with more complex stacks like ELK, but I don't need a complex stack.

**Comment by amir20** [comment]
Hello @temamagic,

Thank you for the suggestion. I haven't received many requests for this functionality, so I don't believe it's a current priority for most users.

Hiding sensitive data isn't Dozzle's responsibility; it should be managed at the application layer. Based on my research, the ELK stack and similar solutions only index the data provided to them. If you don't want something to be visible, it shouldn't be included in the logs. This is how most applications operate.

Closing.

**Comment by temamagic** [comment]
If I do this in my own fork, does it make sense for me to send you a pull request? In fact, it doesn't seem like a big task and I'm surprised that you rejected it. This is controlled not only at the application level, after all. The situation is simple: there is a group of developers who write code and send code to the server via CI/CD, but you personally do not control what they output in the logs there, and you want to protect your secrets

**Comment by amir20** [comment]
> If I do this in my own fork, does it make sense for me to send you a pull request?

Yes of course. I wouldn't reject a PR if it works well. 

> In fact, it doesn't seem like a big task and I'm surprised that you rejected it.

That's where I think we may differ. Ideas often start small but can turn into a complex amount of work. Historically, I have seen many people give up. If you know Go well, it could be easier. However, I want to ensure that you don't just build this feature for yourself. My concern is that PR authors often create features without considering all other use cases. Dozzle has users with very few containers but thousands of logs per second, as well as users with various containers. I have seen up to 10,000 containers, so I have made sure to accommodate most of these scenarios.

Here are a couple of things to consider if you plan to work on this:

1. Let's first agree on the overall logic to ensure you don't build something that doesn't make sense.
2. Configuration is very important. I don't think it should be in the UI. I suggest using a flag like `--mask`, which could accept a regex or something similar.
3. When thinking about solutions, you need to support plain text, JSON, and logfmt, which is similar to JSON. You need to traverse every item in the JSON to mask specific values. While you could process the JSON, be cautious of creating invalid JSON.
4. You might want to conduct some performance testing. I doubt regex will incur any significant cost, but you never know.
5. Do think about adding to the documentation 

I think the way Dozzle is designed right now is that these configurations are for all users.
