### ISSUE TITLE
Feature Request: Add Support for non-agent Filtering in Dozzle

### ISSUE THREAD

**Issue by BillySchwartz16** [amir20/dozzle#3447]
### Describe the feature you would like to see

We are using Dozzle in a Nomad cluster where there is one Dozzle agent per node. The current filter functionality is agent-based, but we would like to have the ability to set filters directly in the UI config, in addition to the agent-based filtering.

### Describe how you would like to see this feature implemented

Our deployment setup includes a UI deployed alongside our application group, with a reverse proxy performing path-based routing. We want the UI to automatically filter logs for the specific app it serves. Adding support for UI-based filtering would simplify our workflow and allow for more flexible, app-specific log viewing directly from the UI.

We'd like an option to define or override filters in the UI, either as a complement to or as an alternative to agent-level filtering. This would make Dozzle more adaptable to environments where filtering requirements vary per UI instance.

### Describe any alternatives you've considered

We could deploy an agent as a sidecar task to all our application nodes, but that would force us to spin up 10x the amount of agents. It's not ideal.

**Comment by amir20** [comment]
> The current filter functionality is agent-based, but we would like to have the ability to set filters directly in the UI config, in addition to the agent-based filtering.

Having a hard time understanding this. So if agent A, B, and C exist. Currently the nodes show up as A, B and C. What does it mean to set filter directly? Do you mean only show some agents or something else? 

> We want the UI to automatically filter logs for the specific app it serves. Adding support for UI-based filtering would simplify our workflow and allow for more flexible, app-specific log viewing directly from the UI.
It sounds like you want to filter the nodes based on a different rule, if I understand correctly. In the feature request at https://github.com/amir20/dozzle/issues/3439, there is a suggestion to filter containers by users. Perhaps allowing filtering nodes by user would also be a solution. If you are using authentication, this could be a similar approach. It could even be proxy-based, where I could parse the header values and filter nodes and containers using a regex. However, this still requires authentication to be enabled.

If you are not using authentication, this presents a problem, as there isn't a logical hook to change filters per route. Did you have something else in mind?

**Comment by BillySchwartz16** [comment]
We filter by container name. Right now, the "filter" environment variable is only accepted if the dozzle node is running in agent mode. We need it to filter on **non-agent** dozzle nodes. Hopefully below helps illustrate; 

Reverse proxy (authentication) -> app1.com | app1.com/logs (non-agent mode) <-> agentA, agentB, agentC

Reverse proxy (authentication) -> app2.com | app2.com/logs(non-agent mode) <-> agentA, agentB, agentC

We have no way to show each app their own logs in dozzle if the filter is set on the agent. We do have authentication setup at the proxy. We could probably pass a role into a custom header which could be used to filter with regex - if thats the easiest solution for you. That is not the simplest solution to implement for us.

It would be easiest for us if the **non-agent** dozzle accepted the filter environment variable.

**Comment by amir20** [comment]
I completely misunderstood your original request. 

If I understand correctly now, you want the filters to be configured in the UI instead of the agent. 

Currently, this is not possible because the filters are passed directly to the Docker client, where `docker.sock` resides. 

However, if I work on https://github.com/amir20/dozzle/issues/3439, I will need to abstract this so that filters can be changed per user. This would involve moving the filters to the UI, which I believe would meet your needs. This task requires significant refactoring. 

I have two questions for you: 

1. You probably don't care about authentication, but if done correctly, you should be able to pass those filters using your proxy headers. Then, you would only need to set up the agents and one instance of the UI. The UI would adjust filters based on the "logged in" user. Is that correct? 
2. How should Dozzle handle situations where filters are set at both layers? For example, if agentA has the filter `name=foo`, but the UI also has a filter `name=bar`, there is no merging because these filters are passed directly to Docker and represented as a map. In this case, there are two filters with the same "name." I think the filters on the agent should take priority since someone might want to filter what the agent displays. However, the filters from the UI would essentially be ignored. 

I'm not sure about a better solution, which is why the implementation is complicated.

**Comment by BillySchwartz16** [comment]
Yes, we can use proxy headers. We would use a role (or group) from the JWT and pass it into a header.  The role/header would be the **apps container name** we want to filter on.

 For us, the DOZZLE_FILTER env var would be set on the agent **OR** the UI container.  Never both.  Agreed; Agent filter > UI filter for priority.

**Comment by BillySchwartz16** [comment]
This did not work the filter is not being picked up. I cannot even see the log that the filters were read in the non-agent logs.

{"level":"info","time":"2024-12-13T20:26:46Z","message":"Dozzle version pr-3455"}
{"level":"info","clients":4,"time":"2024-12-13T20:26:46Z","message":"Connected to Docker"}
{"level":"info","time":"2024-12-13T20:26:46Z","message":"Accepting connections on :8080"}

**Comment by BillySchwartz16** [comment]
Here is the non-agent logs from LATEST:

{"level":"info","time":"2024-12-13T20:34:19Z","message":"Dozzle version v8.8.3"}
{"level":"debug","filterArgs":{REMOVED FOR SECURITY},"time":"2024-12-13T20:34:19Z","message":"Creating local client"}
{"level":"info","clients":4,"time":"2024-12-13T20:34:19Z","message":"Connected to Docker"}
{"level":"info","time":"2024-12-13T20:34:19Z","message":"Accepting connections on :8080"}

It seems to pickup the filter but then its creating a LocalClient instead of RemoteClient. I could be wrong about that-i'm not well versed in go.

**Comment by BillySchwartz16** [comment]
No, we still see all our containers even with the DOZZLE_FILTER env var set. Will you give me an example of your DOZZLE_FILTER that worked?

**Comment by amir20** [comment]
I did `DOZZLE_FILTER=name=foo`. I am passing it directly to Docker API so it should work similar to `docker ps -f ...`. 

Yes I tested filter on both sides. I wonder if the build is broken. Let me add logging and try again.

**Comment by amir20** [comment]
@BillySchwartz16 actually it seems like you are not pulling the right version.  `{"level":"info","time":"2024-12-13T20:34:19Z","message":"Dozzle version v8.8.3"}` is the wrong version.  It should be `pr-3455` as the version.  "Creating local client" log was removed.

Make sure you are using the right versions.

**Comment by BillySchwartz16** [comment]
@amir20 I left two comments in a row. The first comment was the correct version.  I was just showing the difference in the Latest and pr-3455

**Comment by amir20** [comment]
Wait I think I know what is happening. I missed a use case. Let me add some logging and come back.

**Comment by amir20** [comment]
Alright I think I figured out why it wasn't working. I wasn't passing the right filter. In the new version, when you start the UI, if they are only connected to agents, then you won't see anything. However, when you load the page you should see something like `Listing containers from agent filter={"name":["bold"]}`.  Then on the agent something like `Listing containers filter={"name":["bold"]} `. 

There are essentially two filters now. One filter set at the local level where the container store only fetches the items that satisfy the filter.  And, the second filter, where at run time a filter is used that comes from the UI. In the future, this filter could also a be user auth filter. 

Try it now.

**Comment by amir20** [comment]
Additionally, https://github.com/amir20/dozzle/pull/3456 now supports user level filter. You can set it up with [forward proxy](https://dozzle.dev/guide/authentication#forward-proxy). And then also use `Remote-Filter` header to change the filter based on who is logged in. This is will be nice because now you should be able to run only single instance of everything and depending on the headers, Dozzle should automatically update the filter set. 

I haven't tested this too much but it looks to be working with some local tests. 

Once you have validated, I can update the docs. And release.

**Comment by BillySchwartz16** [comment]
This is working locally for me, thanks! I still need to deploy and test in a cluster where our agents are actually remote and not on localhost.

**Comment by BillySchwartz16** [comment]
This works perfectly! Fully tested in our environment. TYVM!!

**Comment by amir20** [comment]
Great. 🚀 I'm going to merge. I assume you didn't check the forward proxy, correct?

**Comment by BillySchwartz16** [comment]
I did not set the proxy header yet. I will test that. "Remote-Filter: foo" will filter on name=foo? or is it Remote-Filter: name=foo?

**Comment by amir20** [comment]
It should be `Remote-Filter: name=foo`. I haven't tested it. Just remember it is the other PR. `pr-3456`.

**Comment by amir20** [comment]
OK documentation updated. I am going to merge everything in `master`. I am sure there might be bugs I have missed. But I think I'll release. Please do me a favor and test `master` to see if proxy forward works. You should be able to bring your Dozzle instance to only one UI instance.

**Comment by BillySchwartz16** [comment]
### Tested `pr-3456` Locally Using Nginx as Forward Proxy

Great Success!


### `nginx.conf`

```nginx
events {}

http {
    server {
        listen 80;

        location /logs {
            proxy_pass http://dozzle-ui:8080;
            proxy_set_header Remote-Filter "name=dozzle-ui";
            proxy_set_header Remote-User "admin";
            proxy_set_header Remote-Email "admin@test.com";
            proxy_set_header Remote-Name: "admin";
        }
    }
}
```

### docker-compose.yml

```docker-compose
version: "3.9"

services:
  dozzle-agent:
    image: amir20/dozzle:pr-3456
    container_name: dozzle-agent
    command: ["agent"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dozzle-ui:
    image: amir20/dozzle:pr-3456
    container_name: dozzle-ui
    ports:
      - "8080:8080"
    environment:
      DOZZLE_REMOTE_AGENT: "dozzle-agent:7007"
      DOZZLE_BASE: "/logs"
      DOZZLE_AUTH_PROVIDER: "forward-proxy"
    depends_on:
      - dozzle-agent

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dozzle-ui

networks:
  default:
    driver: bridge
```

**Comment by amir20** [comment]
That is great! 🚀 I released everything yesterday and updated the documentation. Your use case was a good one. Thanks for suggesting it.
