### ISSUE TITLE
Text Filter on container logs

### ISSUE THREAD

**Issue by lethalox** [amir20/dozzle#3448]
### Describe the feature you would like to see

Thank you for dozzle.   It is much better than looking at docker or docker compose logs.    But as much as like the solution, I feel one of the key items that is missing is the ability to filter the logs as they are coming in.  

### Describe how you would like to see this feature implemented

Implement the same filter on a given container that portainer has. 
![Portainter Logs](https://github.com/user-attachments/assets/847fa059-8cc6-4d20-bd1c-787da85d366a)

**Comment by amir20** [comment]
I don't understand this because search is implemented. Are you not finding it? 

<img width="1503" alt="Screenshot 2024-12-11 at 1 49 00 PM" src="https://github.com/user-attachments/assets/bf04ec3a-51c8-42ec-b9dc-333145edbdcb" />

You can also do `ctrl+f`.

**Comment by lethalox** [comment]
I guess, I did not realize it was there.  But it probably my own fault.
