### ISSUE TITLE
[Request] Search Highlight without Filtering

### ISSUE THREAD

**Issue by sw-carlos-cristobal** [amir20/dozzle#3449]
### Describe the feature you would like to see

I would love it if there was an option to not filter the logs but only to highlight the regex used. There are times when I want to search for a specific text but I don't want to lose the context surrounding that log entry,

### Describe how you would like to see this feature implemented

Instead of
![image](https://github.com/user-attachments/assets/87c47a04-eabb-4cbf-a66b-e300c8bedff2)

it would display like
![image](https://github.com/user-attachments/assets/664a17af-4cf7-4a71-be79-b1830796bf6c)

Exactly how Chrome can do highlighting on page searches.

**Comment by amir20** [comment]
If you press `ctrl+f`, it opens the Dozzle search. Pressing `ctrl+f` again switches to the browser's search functionality, allowing you to search everything on the page. The only downside is that regex cannot be used. However, there are many browser extensions available that support regex.


<img width="996" alt="Screenshot 2024-12-11 at 1 53 12 PM" src="https://github.com/user-attachments/assets/f6c8c7fb-375c-4802-b6dc-1d35ad914c9d" />


This approach is already implemented.
