### ISSUE TITLE
When too many splits occur, the close window icon (x) is not visible any longer and it becomes difficult or impossible to close panels.

### ISSUE THREAD

**Issue by skyscooby** [amir20/dozzle#3451]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.8.3

### ✅ Command used to run Dozzle

NA

### 🐛 Describe the bug / provide steps to reproduce it

Simply open 5-6 split panes... only solution at that point is to open a new window and start over..
Suggestions that might work.. 

- when a user clicks the PIN icon on the left panel.. change that icon to UN-PIN X.. so they can then use the same interface location to close the panel again.
- Limit the number of panels that can be opened based on the current browser width to a reasonable number
- change the panel UI so the X is in a location where it can not become hidden.

### 💻 Environment

NA

### 📸 If applicable, add screenshots to help explain your bug

![Screenshot From 2024-12-12 12-19-27](https://github.com/user-attachments/assets/6f6809e1-f316-465f-b054-538899cd21d8)

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

NA

**Comment by amir20** [comment]
Limiting wouldn't work because screen sizes are different. 

I think I am going to see if I can hide the stats when it becomes smaller then a specific size.

**Comment by skyscooby** [comment]
Screen sizes are indeed different, but that information is accessible to JS within the browser.. that's how responsive design works.

You also know the width of your assets you are placing at the top of each pane though.. so perhaps even enforcing a min width of the panel that allows for those to always fit.. and letting a horizontal scrollbar appear if too many panes are created for the window..

Anyway there is a dozen ways to address it.. it's your baby :)

**Comment by skyscooby** [comment]
Oh wow! a fix already! Good stuff :+1:

**Comment by amir20** [comment]
css containers are pretty awesome.
