### ISSUE TITLE
Supports connecting to the agent at runtime

### ISSUE THREAD

**Issue by Zeroc0077** [amir20/dozzle#3459]
### Describe the feature you would like to see

When I want to connect to a new agent, it seems that I need to modify the env and restart the container. It would be nice if I could dynamically connect to the new agent at runtime.

**Comment by amir20** [comment]
I believe you mean the ability to add agents using only the UI. That's a good idea, but I won't have time to work on it. Using `ENV` covers all use cases, including swarm. Configuring through the UI would require persistent databases or disk space to store the configuration, and it wouldn't be suitable for all scenarios. It's not worth the added complexity.

If you send PRs, that would be great.
