### ISSUE TITLE
Hide Sidebar Still Shows Empty Space on Right

### ISSUE THREAD

**Issue by beeing** [amir20/dozzle#347]
Hi, thanks for such a useful tool. Just found a small UI issue as below:

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/28744192/78530227-dc117780-7815-11ea-98df-2403ddd18fda.png">

The columns does not expand and fill up the empty space on the right after sidebar is hidden.

**Comment by amir20** [comment]
Yep, I was able to reproduce this. Hmmm not sure how to fix it. I rely on another library to do the pane resizing. Maybe someone else can take a look?

**Comment by beeing** [comment]
I've roughly check the splitpanes demo and found this - https://antoniandre.github.io/splitpanes/#toggle-a-pane-with-v-if

Looks like its using `v-if` where you're using `v-show` instead.

**Comment by amir20** [comment]
Nice. I'll try it this week. I recall not using `v-show` for a reason. I think there was another bug where the left panel wouldn't restore to the correct size. I'll see what happens.

**Comment by amir20** [comment]
Try `v1.21.8`. Should be up in 5 minutes.

**Comment by amir20** [comment]
Build is failing... I am investigating.

**Comment by amir20** [comment]
OK live now with `v1.21.9'

**Comment by amir20** [comment]
Does it work @beeing?

**Comment by beeing** [comment]
Yes, its working perfectly. Thanks @amir20
