### ISSUE TITLE
Container stopped message does not label which container was stopped.

### ISSUE THREAD

**Issue by skyscooby** [amir20/dozzle#3473]
### Describe the feature you would like to see

When watching any page streaming multiple containers if a container stops it will emit a Container stopped message. This line however is not prefixed with the container name like the log messages themselves. When watching many containers identifying which container was stopped is not easy.. you kind of have to deduce which one has stopped emitting messages.

### Describe how you would like to see this feature implemented

Either prefix the event with the container name or change the message on the event to 'Container stopped (container-name)' or '(container-name) stopped' or some variant that identifies which container was stopped. This would also be good to include in the Container started messages as well.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ContainerEventLogItem component to include the container name in the 'container-stopped' and 'container-started' event messages. This change improves the visibility of which container has stopped or started when watching multiple containers.

You can review changes in this commit: https://github.com/wwqwq2313/amir20-dozzle-3473/commit/988f7dae5cdf0e605f98de22c8edd65ce44c6241.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by amir20** [comment]
That's right. @skyscooby I noticed this too. If you have a screenshot handy then attach it too so I can remember. 

@wwqwq2313 who are you? You should be sending PRs to this repo.

**Comment by skyscooby** [comment]
![Screenshot From 2024-12-22 10-19-41](https://github.com/user-attachments/assets/6e01bec4-2760-4278-8d05-99dc0de9d2d5)

> who are you? You should be sending PRs to this repo.

Looks like some kind of new AI tool https://latta.ai/ourmission

**Comment by amir20** [comment]
> public issues Latta already tried to solve.

Keyword "tried".  😂
