### ISSUE TITLE
Adding new fitcher (docker-compoe loading)

### ISSUE THREAD

**Issue by klownkukold** [amir20/dozzle#3477]
### Describe the feature you would like to see

Hello. While using your usefull programm, we (command of programmers and testers) want to see new oportunity. Could you add opportunity to download all logs of docker-compose in the left trey near the buttom "merge all containers into one view". 

### Describe how you would like to see this feature implemented

It would be usefull to collect all logs into one to have opportunity analyze them without switching among isolated one docker-compose logs

### Describe any alternatives you've considered

No alternatives, you are the best. make one effort and you will be the best of the best

**Comment by amir20** [comment]
I have been thinking about this. When I get a chance it will be implemented, but not exactly as you suggested. 

1. The logs for multiple containers will need to be zipped. There is no way to combine them in a single file that doesn't use too much memory. 

2. I don't think I'll ever do all logs. Instead it will be logs that were logically grouped together. Like services and stacks or compose.
