### ISSUE TITLE
Traefik log levels in traefik v3.x are no longer automatically recognized or filterable

### ISSUE THREAD

**Issue by arudnitsky** [amir20/dozzle#3478]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.9.0

### ✅ Command used to run Dozzle

docker run -d --restart=unless-stopped --name dozzle --volume=/var/run/docker.sock:/var/run/docker.sock -p 0.0.0.0:7070:7070 --env DOZZLE_ADDR=:7070 amir20/dozzle:latest

### 🐛 Describe the bug / provide steps to reproduce it

I upgraded traefik from v2.x to v3.1 and Dozzle can no longer filter by log levels. In traefik v3, log levels are now three characters: DBG, INF, WRN, etc... whereas in v2, they were given by DEBUG, INFO, WARNING.

Everthing messages now found under Unknown. If the word "error" is detected in a message, a red dot is placed in the UI before the message.

Example traefik v3 logs:
```
2024-12-23T16:51:00Z INF github.com/traefik/traefik/v3/cmd/traefik/traefik.go:611 > Stats collection is enabled.

2024-12-23T16:51:00Z DBG github.com/traefik/traefik/v3/pkg/server/server_entrypoint_tcp.go:231 > Starting TCP Server entryPointName=http

2024-12-23T17:01:30Z WRN github.com/traefik/traefik/v3/pkg/version/version.go:76 > Error checking new version error="Get \"https://update.traefik.io/repos/traefik/traefik/releases\": dial tcp 13.39.208.199:443: i/o timeout"
```

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.4.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-127-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.97GiB
 Name: [redacted]
 ID: e3a2c2ef-2951-4d2c-a74e-612f1126d8a8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

### 📸 If applicable, add screenshots to help explain your bug

![dozzle-1](https://github.com/user-attachments/assets/f684fc73-4ad4-4183-a770-70180de1a9fb)

**Comment by amir20** [comment]
There are two things going on:

I look for error= to find errors. But seems like that's not a good assumption because some logs are debug and still have error. 

Dozzle doesn't support short levels like DBG. Easy enough to do if you can send a PR.
