### ISSUE TITLE
Push docker image also to Github registry

### ISSUE THREAD

**Issue by tobiasdiez** [amir20/dozzle#3483]
### Describe the feature you would like to see

In addition to pushing the docker image to dockerhub, it would be awesome to have it also in the Github registry. (E.g. docker is semi-blocked in China.)

### Describe how you would like to see this feature implemented

https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages

**Comment by amir20** [comment]
Easy enough to do if you can send a pr

**Comment by amir20** [comment]
I did a quick pr. Should be testable with `docker pull ghcr.io/amir20/dozzle:pr-3487`.  I'll merge later this week while I get other stuff done too.

**Comment by tobiasdiez** [comment]
Thanks for the quick fix!
