### ISSUE TITLE
Option to turn off time

### ISSUE THREAD

**Issue by beeing** [amir20/dozzle#360]
Currently Dozzle includes `today at 9:29 AM` in each line.

Since the log itself have timestamp, its possible for us to hide this?

Thanks in advance.

**Comment by amir20** [comment]
Someone else asked this question. I think it would be easy enough to add. Requires a change in `Settings.vue` and then updating the code to not show it. 

I am working on some icon changes right now but possibly in a week I can get to this. 

If you want to work on it, then I can point you to which files need to be changed.

**Comment by amir20** [comment]
This was a quick fix so I added it. 

<img width="1645" alt="Screen Shot 2020-04-11 at 7 20 50 PM" src="https://user-images.githubusercontent.com/260667/79059049-3baebf00-7c2a-11ea-8ee9-fb8cd41d3e9f.png">
