### ISSUE TITLE
Autoscroll stops when adding new column logs

### ISSUE THREAD

**Issue by beeing** [amir20/dozzle#361]
Everytime I add a new column, the existing columns will show the down arrow and need to click each of it.

**Comment by amir20** [comment]
Hi, thanks for filing this @beeing. It's a known issue. When the width of the columns change then scroll is readjusted. 

The fix is too complicated and not worth the effort right now. 

If you know of any easy fixes then let me know. I'll leave this open until I think of a solution.

**Comment by beeing** [comment]
Just got an insight for this. The scroll adjusted due to wrapping of the text.

A simple way to fix this is to disable text-wrapping so when column adjusted, it will not expand the height and causes the scroll to stop.

Another thing I noticed is the scrolling is just stopped but the list is continuously appending to the DOM. For better performance, I suggest to use virtual scrolling. This limits the number of entries in DOM.

I found this component in https://github.com/Akryum/vue-virtual-scroller

**Comment by amir20** [comment]
I think I have found a nice solution with minimal effort. I recently discovered [scroll-snap-type](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type), and with `scroll-snap-type: y proximity` I can make the scroll behave sticky to a specific element. I'll have to play around with it more, but so far it looks like it works well when resizing or adding new columns. 

Regarding a virtual dom, it's an interesting idea. Have you already faced performance issues? Would this be premature optimization? I have added thousands of logs with no degradation. But I guess if one was to leave Dozzle open over night and come back in the morning it could cause the memory to run out of memory. But I am not sure if it is worth the effort.

**Comment by amir20** [comment]
I tried using `DynamicScroller` a little and it was actually very choppy while scrolling. Probably not worth using it now unless enough people report memory issues.

**Comment by beeing** [comment]
The `scroll-snap-type` looks usable, however that some logs can be really long and with `text-overflow: wrap` it may not work properly too.

Hope I'm not asking too much - if there's a setting to disable `text-overflow` will be a good start.

I've looked into your codes, looks simple but need to see how the flow goes before attempting to change anything.

Thanks!

**Comment by amir20** [comment]
Hi @beeing. I don't think is an unfair ask at all. I am just trying to understand the real problem. If there is a way to fix the scroll issue without touching `text-overflow` then that's better IMO. Disabling `text-overflow` feels like a hack as I am sure others would want the scroll to be fixed without disabling anything. 

Also, something to think about... I am not sure sure how horizontal scroll would work. The panes right now all assume vertical scroll. But this should be easy to test. 

If you look at #370, then you can see how I added a new setting for timestamp. It would be basically the same thing for `text-overflow`. You can also look at `sticky-scroll` branch to see what I've done so far.

**Comment by beeing** [comment]
Thanks, I'll check it out.

**Comment by amir20** [comment]
Hi @beeing. I think I will just merged https://github.com/amir20/dozzle/pull/377 to master. It "kinda" works. Going from 1 column to 2, 3, 4... works just fine. Going from n columns to 2 works too. Going from 2 columns to 1, does not work. I am not sure why exactly. Seems like `scroll-snap-type` on `html` isn't being respected. I tried to figure it out but ran out of time.

**Comment by beeing** [comment]
Thanks @amir20, still busy with some tasks where I haven't looked into this yet.

But based on your issue, how about having a state in each column to auto scroll? I believe this is a practical approach.

**Comment by amir20** [comment]
I tired that first. It didn’t work great. There is a slight animation when the columns get created, so the code would have to wait until after the transition to calculate scroll. 

I also don’t have much time to spend on it. So this will have to do for now. CSS is cleaner approach IMO.
