### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Albinzr** [amir20/dozzle#440]
Isues

1. Takes long time to load initial log data
2. Getting new logs after a long delay
3. Sometimes updates wont come at all

**Comment by amir20** [comment]
Are you using a reverse proxy?

**Comment by Albinzr** [comment]
yes Im, Will that cause any issue? If so how can we solve it?

**Comment by amir20** [comment]
Read troubleshooting section in readme. You need to configure web sockets correctly.

**Comment by Albinzr** [comment]
Cool Thanks.
