### ISSUE TITLE
Feature Request: Optional sorting by capitalization

### ISSUE THREAD

**Issue by gottsman** [amir20/dozzle#452]
By default, Dozzle sorts with letters in caps first and then lower case. Can we provide a setting toggle for ignoring capitalization?

**Comment by amir20** [comment]
Thanks for the idea @gottsman. I didn't realize people use UpPerCase names :) 

I am less inclined to create another setting and making the settings page crowded. Instead, I want to provide good defaults until some one complains. 

Sounds like I should always sort with ignoring caps? Does that make sense to you? Sounds pretty easy to do in client.go.

**Comment by gottsman** [comment]
Agree with your solution. I am currently using UnRAID and the templates have inconsistent capitalization.

**Comment by amir20** [comment]
`v1.25.5` is being built. Should be up in about 15 mins.

**Comment by amir20** [comment]
https://github.com/amir20/dozzle/actions/runs/104875580
