### ISSUE TITLE
Request: Add to Heimdall

### ISSUE THREAD

**Issue by cptechie** [amir20/dozzle#462]
This container is awesome!

Can you submit your app to be listed on [Heimdall](https://apps.heimdall.site/)? Or if you are okay with it, I can submit for you on your behalf.

**Comment by amir20** [comment]
Hi @cptechie, I wasn't able to find much about HEIMDALL. What is it? Is there an about page?

**Comment by cptechie** [comment]
Heimdall is an application dashboard. You can read more about it below.
There is a gif on their readme showcasing the dashboard.

https://github.com/linuxserver/Heimdall/blob/master/readme.md

**Comment by amir20** [comment]
Nice. Seems like an application was already submitted. It won't let me submit it again. So closing. Thanks for thinking of Dozzle!

**Comment by cptechie** [comment]
Oh, that was me who submitted it haha. But then we have to go through the
steps below to add it to the list of apps within the service.

https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app

As this requires a fork and pull request of their repository I thought that
it would be fitting if the app developer actually did that. I did not want
to publish your app to the service without your consent.
