### ISSUE TITLE
Duplicate data recived 

### ISSUE THREAD

**Issue by Albinzr** [amir20/dozzle#473]
Same data have been send again and again
Attached screenshot 
![image](https://user-images.githubusercontent.com/7425577/82683281-6438c880-9c6e-11ea-9809-65f6182eb4ea.png)

**Comment by amir20** [comment]
You must be getting some exceptions which is causing Dozzle to restart the logging stream. I don't have a way to reproduce that. 

- What version are you running? 
- See if browsers console shows errors
- Run Dozzle with `--level debug` and see if other exceptions are thrown.

**Comment by amir20** [comment]
And obviously update to latest version because I fixed some stuff in #448 to stop the logging if container has stopped.

**Comment by Albinzr** [comment]
Will check right now and let you know

**Comment by Albinzr** [comment]
Just tested 
- Still got same logs again
- Dozzle didn't restart 
Dozzle 
![image](https://user-images.githubusercontent.com/7425577/82693015-59862f80-9c7e-11ea-9b4c-3a8b54da7ab7.png)

**Comment by amir20** [comment]
There is a lot of things that you didn't respond to. Based on your logs, you are over over two versions behind. Update to latest version. 

Also need to see Chrome's console.

**Comment by Albinzr** [comment]
Im using latest available version
![](https://user-images.githubusercontent.com/7425577/82693015-59862f80-9c7e-11ea-9b4c-3a8b54da7ab7.png)

**Comment by Albinzr** [comment]
I will get the chrome console details

**Comment by amir20** [comment]
@Albinzr you are not using the latest version. You need to do `docker pull amir20/dozzle` again. See https://hub.docker.com/r/amir20/dozzle/tags?page=1&ordering=last_updated. The latest is `v1.25.6`

**Comment by Albinzr** [comment]
Cool now its working fine, I was doing [amir20/dozzle:latest,](url) Which should have gave me the latest but I was getting 1.23.2 not sure why. When i did an manual `docker pull amir20/dozzle `as you mentioned it started to work thanks...

**Comment by amir20** [comment]
When you do `docker run amir20/dozzle:latest` it doesn't actually pull the latest. It just uses whatever has been tagged as latest on your machine. That's why you have to do `pull` first and then restart the container or as you did always use version numbers. 

You can read more about this behavior https://github.com/moby/moby/issues/13331
