### ISSUE TITLE
empty log view

### ISSUE THREAD

**Issue by StephanKrauss** [amir20/dozzle#548]
**Describe the bug**
Do not show logger messages

**To Reproduce**
I have installed the dozzle container with the command
docker run --name dozzle -d --volume=/var/run/docker.sock:/var/run/docker.sock -p 8888:8080 amir20/dozzle:latest

I control with docker ps.
The dozzle container works on port 8888

When i call in the browser the url: <myServer>:8888 i see the dozzle web interface

I see in the listing my service.
When i click on my service, i can't see the log messages.
When i check my docker service with 'docker logs <myServiceId>' i see the log messages.

On the docker host, the log files are under /var/lib/docker/containers/<token>/<logfile>

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Docker version

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

 - Browser & version Windows , Firefox 70.0b
 - Dozzle Version: v2.0.2. 

Can you give me an information ?

Your sincerly

Stephan
![dozzle](https://user-images.githubusercontent.com/17799669/86114547-f8e2e180-baca-11ea-96e5-3818c6b372e0.jpg)

**Comment by amir20** [comment]
Hi Stephan. Some questions and suggestions: 

1. Your docker version is over three years old. I don't do any testing with that version. Can you upgrade? Or are you locked in that version.
2. Are there any browser exceptions? 
3. Are there any exceptions or logs from Dozzle? 
4. Do all other containers work? 
5. Did this just start happening? How do you start this particular container? Share the compose file if you can.

**Comment by StephanKrauss** [comment]
Hello,

Big magic. When i stopp the container with 'docker container kill <docker id> 
in this moment i see the log messages in dozzle web interface.

Greetings 

Stephan
