### ISSUE TITLE
Some nginx documentation for reverse proxying dozzle

### ISSUE THREAD

**Issue by JohannesBe** [amir20/dozzle#561]
Hi Amir, 

Sorry to keep you waiting (#471); it's been busy as hell lately :)

Since dozzle requires server-sent events, some settings need to be finetuned in order for dozzle to work (and in order for it to work with enough users).

As you pointed out already, buffering might hold some SSE data, so that should be disabled:
```
    proxy_cache             off;
    proxy_buffering         off;
```

There are however some other problems that will also need to be configured to get dozzle to work reliably; namely settings related to connection timeouts. It is so that by default nginx will not keep proxied requests open for a long time, because this is quite expensive.

In order to configure this we need two things:
  1) An `upstream` block, such that we can configure timeouts from nginx <-> dozzle

```
# https://nginx.org/en/docs/http/ngx_http_upstream_module.html
upstream logs {
    server dozzle-logs:8080;

    keepalive 10;              # Number of connections to keep alive and recycle
    keepalive_requests 100;    # Number of requests to serve through one connection
    keepalive_timeout 1d;      # Time to keep idle connection open
}
```

  2) Configuration in the `server` block, such that we can configure timeouts from user <-> nginx

```
server {
  # ...

  # Or whatever location block
  location ^~ /logs {
    # We don't want any delays for realtime logging
    # Skip some TCP ACK/SYN buffering for achieving full package sizes
    # on transport level
    tcp_nodelay             on;

    # Caching and buffering
    proxy_cache             off;
    proxy_redirect          off;
    proxy_buffering         off;
    proxy_request_buffering off;

    # mitigate HTTPoxy Vulnerability
    # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
    proxy_set_header        Proxy "";

    # Set timeouts higher for websockets / SSE
    send_timeout            1d;
    proxy_read_timeout      1d;
    proxy_send_timeout      1d;
    proxy_connect_timeout   5;
    keepalive_requests      100;
    keepalive_timeout       1d;

    # Should refer to name of upstream block
    proxy_pass              http://logs;
  }
}
```

I know this is a lot of information, and the parameters are just example values, but I believe this might be a starting point.
Of course our server contains lots and lots of more config, but I tried to extract the most essential part.

Kind regards,

Johannes

**Comment by JohannesBe** [comment]
Probably best to refer to this information as a wiki post instead (after reformatting/discussion/cleanup/extra comments)?

**Comment by amir20** [comment]
Hey @JohannesBe thanks! I have an FAQ so I might to put it there. I had't thought of the timeout so that's good to document. 

Regarding the buffer, I send `X-Accel-Buffering: no` which [should](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) disable and buffering. Did you find that it did not?

**Comment by 123dev** [comment]
Hi folks,
I wonder if any of you have encountered this or have any ideas how to identify the problems we're encountering.

Accessing the dozzle service directly is working fine, even the name redirect #471 loads up immediately
Accessing through a reverse proxy on another host, with the following nginx config (code excerpts from this thread adapted to our nginx settings, thanks)

And the following setting in Dozzle
` DOZZLE_BASE=/dev19`

```
upstream dev19 {
    server                      10.10.1.19:9080;

    keepalive                   10;     # Number of connections to keep alive and recycle
    keepalive_requests          100;    # Number of requests to serve through one connection
    keepalive_timeout           1d;     # Time to keep idle connection open
}

server {
    listen                      8443 ssl http2;

    ssl_certificate             /etc/nginx/server.crt;
    ssl_certificate_key         /etc/nginx/server.key;

    ssl_session_cache           builtin:1000  shared:SSL:10m;
    ssl_protocols               TLSv1.2 TLSv1.3;
    ssl_ciphers                 ECDHE-RSA-AES256-GCM-SHA512:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
    ssl_prefer_server_ciphers   on;

    # add Strict-Transport-Security HSTS to prevent man in the middle attacks
    add_header                  Strict-Transport-Security "max-age=31536000";

...

    location /dev19/ {
        # Should refer to name of upstream block
        proxy_pass              http://dev19/dev19/;
        # We don't want any delays for realtime logging
        # Skip some TCP ACK/SYN buffering for achieving full package sizes
        # on transport level
        tcp_nodelay             on;

        # Caching and buffering
        proxy_cache             off;
        proxy_redirect          off;
        proxy_buffering         off;
        proxy_request_buffering off;
        proxy_set_header        X-Accel-Buffering no;

        # mitigate HTTPoxy Vulnerability
        # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
        proxy_set_header        Proxy "";

        # Set timeouts higher for websockets / SSE
        send_timeout            1d;
        proxy_read_timeout      1d;
        proxy_send_timeout      1d;
        proxy_connect_timeout   5;
        keepalive_requests      100;
        keepalive_timeout       1d;

        # Set headers and few more
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection 'upgrade';
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_http_version      1.1;
        proxy_cache_bypass      $http_upgrade;
    }

    client_max_body_size        10M;
}
```
Is working fine as well.

However this niginx is behind Azure Gateway (v2)
and accessing it through the gateway the dozzle portal loads immediately and comes up empty, after a long while, really long while, the containers are visible,
However the `show?name=conatiner-name` approach never works and the redirect never happens.

Checking the browser console logs, I see the following
![image](https://user-images.githubusercontent.com/13109154/117288944-0cbd4980-ae3a-11eb-9427-92ea7a779dda.png)

Would love to eliminate the long , really long (several minutes) delay of containers showing up, which is probably the same issue behind the name search not working.

Thanks.

**Comment by amir20** [comment]
Hi @123dev. 

Long story short: Seems like Azure does not support server side events. This is surprising since SSE have been around for a long time. 


Dozzle uses server side events to send updates real-time to browser. Some proxy servers buffer this which means that client will never see an update. This breaks Dozzle of course.  Dozzle sends `X-Accel-Buffering: no` which says don't buffer. 

I did some [searching](https://www.google.com/search?q=server+side+events+azure+gateway) `azure gateway server side events` and it seems like it is [not supported](https://docs.microsoft.com/en-us/answers/questions/224064/azure-api-management-supports-server-sent-events.html).   That question is from 2021. 

Which explains why it works via nginx but not Azure's gateway.

**Comment by 123dev** [comment]
Damn,

Thank you @amir20 for a quick and precise answer.
