### ISSUE TITLE
Notice: Deprecating --addr

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#567]
Dozzle allows binding to another hostname or port via the `--addr` option. But this isn't helpful when using with Docker as ports can be remapped. 

I plan to remove `--addr` unless there is a convincing reason.

**Comment by whalehub** [comment]
@amir20 I'd be bummed out if this option were to be removed. I'm running Dozzle as a systemd service outside of Docker and port 8080 is already occupied on my host because many applications choose that as their default port and some of them don't give you the option to change it. If you are planning to hardcode the port, I'd ask that it please at least be a unique/uncommon one.

**Comment by amir20** [comment]
Thanks @whalehub. Can I ask how you are running it outside of Docker? I don’t release binaries. I never thought people would run it without Docker. But that’s good to know.

**Comment by whalehub** [comment]
@amir20 Ha, well, I grab the binary from the container like this:

```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock:ro --name dozzle amir20/dozzle
docker cp dozzle:dozzle /usr/local/bin
```

I just realized that I actually don't use the `--addr` option, I use the environment variable `DOZZLE_ADDR`:

```
[Unit]
Description=Dozzle
Documentation=https://dozzle.dev/
After=network.target

StartLimitIntervalSec=14400
StartLimitBurst=10

[Service]
Restart=on-abnormal

Type=simple

User=dozzle
Group=dozzle

Environment="DOZZLE_ADDR=127.0.0.1:7368"

ExecStart=/usr/local/bin/dozzle

KillMode=control-group
KillSignal=SIGINT
TimeoutStopSec=60s

LimitNOFILE=1048576
LimitNPROC=512

ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
PrivateUsers=true

NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

**Comment by amir20** [comment]
Nice. I thought that's what you are doing. I used to release with GoReleaser but it didn't support multi-arch containers. 

Sounds like for now, I should put the removal of `--addr` or `DOZZLE_ADDR` on hold.

**Comment by amir20** [comment]
By the way, the whole reason for this deprecation was the request to add `EXPOSE port` to Docker images. But since the ports can change I didn't see it as a good option.

**Comment by disklosr** [comment]
@amir20 I explained in the original issue #23 why `--addr` switch isn't incompatible with `EXPOSE`. Both can coexist without issues.

@whalehub Out of curiosity, may I ask why aren't you running dozzle as a container?

**Comment by whalehub** [comment]
@disklosr I prefer using systemd for long-running applications whenever possible.

**Comment by amir20** [comment]
@whalehub I have been running my applications with Docker Swarm in single node mode and it has been great so far.

**Comment by amir20** [comment]
Given the feedback in this issue, I will not deprecate `--addr`.
