### ISSUE TITLE
DOZZLE_BASE not used everywhere to access dozzle API 

### ISSUE THREAD

**Issue by bartmeuris** [amir20/dozzle#581]
**Describe the bug**

When using a `DOZZLE_BASE` url set to something like `/logs`, when scrolling up it still calls the `/api/logs?id=...` endpoint, and not the `/logs/api/logs?id=...` endpoint.

I currently run this with a reverse proxy in front of it, and only the /logs is forwarded to Dozzle, which results in a 404.

**To Reproduce**
1. start a dozzle instance on a machine with docker containers with a lot of logs like this:
```
docker run -ti --rm -e DOZZLE_BASE=/logs -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock amir20/dozzle:latest
```
2. Open the dozzle UI in the browser, and open the browser developer tools
3. Select a container and scroll up until it needs to load previous lines
4. You'll see the following error on the very first line in the logs:
```
01/01/0404 page not found
```
You'll also see in the browser dev tools that it tries to access the `/api/logs?id=` endpoint

**Expected behavior**

The `DOZZLE_BASE` should be prepended when calling the API when fetching log history

**Comment by bartmeuris** [comment]
It seems the error might be down to this line:

```
https://github.com/amir20/dozzle/blob/19ce70ba1ce2a66a4df77207ddad5fe5266c2b82/assets/components/LogEventSource.vue#L65
```

But I'm not too familiar with javascript or vue.js...

**Comment by amir20** [comment]
Hello, thank you for the excellent write up. I recently refactored some code and looks like I missed this. This is definitely a bug. 

I can have a patch out today.

**Comment by bartmeuris** [comment]
Thanks for the quick response :) I can confirm that just adding the `${config.base}` to the line above fixes the issue, I forked the repo and fixed it there. Do I open a PR for this? It's maybe a bit overkill :)

**Comment by amir20** [comment]
If you have it working then send a PR! That way I can merge and release.

**Comment by amir20** [comment]
Will release in an hour.

**Comment by amir20** [comment]
`v2.1.2
docker pull amir20/dozzle:v2.1.2
`

Should be good now. Thanks!

**Comment by amir20** [comment]
Hi @bartmeuris, I was looking at git log and it turns out this feature was never working with `base`. So thanks for filing and fixing it!
