### ISSUE TITLE
Tabs \t are rendered inconsistently from local console

### ISSUE THREAD

**Issue by IAMtheIAM** [amir20/dozzle#584]
**Describe the bug**
Tabs are rendered inconsistently. On my local console, in the screenshot below, they appear lined up. But on dozzle, they are not aligned.

Also, depending on the date, whether "today" or "yesterday" that dozzle prefixes the lines with, it changes the tab output so that some align and some don't

**To Reproduce**
1. ```console.log(`
One: \t\t\t ${value}
OneTwo: \t\t ${value}
OneTwoThree: \t ${value}
OneMore: \t\t ${value}
`)```

**Expected behavior**
Console logs using string literal templates should render the same as when run locally (not in a docker container through dozzle).

**Screenshots**
![image](https://user-images.githubusercontent.com/13709948/87823548-76775300-c828-11ea-9912-daa785dc4d4d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows or Mac Os] Linux
 - Docker version [e.g. `docker version`'s output]
 - Browser & version [e.g. chrome, safari]
 - Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`] 1.20.18 (using docker image `amir20/dozzle:latest`

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
<img width="1404" alt="Screen Shot 2020-07-19 at 10 41 42 AM" src="https://user-images.githubusercontent.com/260667/87881189-73a56b00-c9ac-11ea-90d6-1ae37b8ce2ad.png">

I ran 

	console.log(` One: \t\t\t VALUE OneTwo: \t\t VALUE OneTwoThree: \t VALUE OneMore: \t\t VALUE `)

and I seems to work fine for me. So I am going to close and mark as need more info.

**Comment by IAMtheIAM** [comment]
Hey, I will give you more detailed info once I have a little more time to make it reproducable for you.
