### ISSUE TITLE
Support HTTPS/WSS

### ISSUE THREAD

**Issue by kmlucy** [amir20/dozzle#6]
I have Dozzle reverse proxied with SSL. The main page loads, but the websocket connections do not:
```
Mixed Content: The page at 'https://URL/dozzle/container/ID' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://URL/dozzle/api/logs?id=ID'. This request has been blocked; this endpoint must be available over WSS.
```

I have websocket proxying setup in NGINX, but it seems like Dozzle is still looking for a ws:// connection. NGINX doesn't show any logs, so it is being blocked in the browser and not even making it to my proxy.

If I temporarily allow unsafe connections, Dozzle exits with this error:
```
2018/11/19 21:48:00 websocket: request origin not allowed by Upgrader.CheckOrigin
```

**Comment by amir20** [comment]
I suspect I need to change `ws://` to `wss://`. I think I'll try to do this locally with Caddy server. See if that works. 

If that works, it might be another flag. This is an interesting setup you have. But I think it is common and something that should be supported. 

I may send you a test image instead because it will take a while to make this work locally.

**Comment by amir20** [comment]
@kmlucy  I think I got it to work. I haven't used Nginx for a while so you'll have to convert whatever I did to Caddy. 

If I change `ws` to `wss` and use this proxy config, then it works. 


```

https://localhost:1234 {
    tls self_signed

    proxy / localhost:8080 {
        transparent
        websocket
    }
}
```

I can create a new flag called `-wss` (maybe) to enable wss instead. But I want to make sure the proxy idea works for you. According to the [documentation](https://caddyserver.com/docs/proxy), you have allow upgrade of websockets when doing proxy. 

Something like 

```
header_upstream Connection {>Connection}
header_upstream Upgrade {>Upgrade}
```

I am not sure what the equivalent of that is for Nginx. 

If that works for you, then I can get the flag working.

**Comment by kmlucy** [comment]
@amir20 There is a similar configuration for NGINX and it is what I've been using. Were you able to get it to work with Caddy without changing Dozzle?

I'd like to try to --wss flag (or whatever the flag ends up being). I could try it out and see if it fixes the problem I'm having.

**Comment by amir20** [comment]
@kmlucy Try with https://github.com/amir20/dozzle/releases/tag/v1.2.1. You need to use `--ssl` flag. You can do `docker run amir20/dozzle --help` if you want to see help. 

> Were you able to get it to work with Caddy without changing Dozzle?

I was able to get it to work by _only_ changing `ws` to `wss`.  

So this change should do that.

**Comment by amir20** [comment]
I was able to test this locally so I hope it works for you.

**Comment by amir20** [comment]
This time I tested it with `docker run -p 8080:8080 --volume=/var/run/docker.sock:/var/run/docker.sock amir20/dozzle --ssl` and using the Caddyfile above and it seemed to have work.

**Comment by kmlucy** [comment]
That fixed it; it's working great now. Thanks for the quick fix!

**Comment by amir20** [comment]
Woohoo
