### ISSUE TITLE
Views logs from a specific file inside a container

### ISSUE THREAD

**Issue by SalehCoder** [amir20/dozzle#611]
Some containers has specialize logs in specific files inside the container. It would be great if it's possible to integrate/view those logs. 

For example I'm using [LanCache!](https://github.com/lancachenet/monolithic) and I would love to be able to view real time logs of /data/logs/access.log instead of going to the shell and typing: 
```
docker exec -it lancache_monolithic_1 tail -f /data/logs/access.log.
```

Awesome project. Keep it up!

**Comment by amir20** [comment]
Dozzle won’t be able to do that. No logging system can. Docket API only has access to stout and stderr. 

You could always change the entry point and add `tail -f`. 

Though, it is recommended for all containers to print logs to stdout. That way other the infrastructure can figure out how to handle the logs.
