### ISSUE TITLE
Allow more than a single Docker host (remote)

### ISSUE THREAD

**Issue by GuyKh** [amir20/dozzle#693]
**Is your feature request related to a problem? Please describe.**
I have two docker hosts, one is local and the other is remote.
Issue #688 addresses the remote problem
Even when this feature will be ready - I'll have to choose either local or remote host.

**Describe the solution you'd like**
I'd really like to have an interface where I can see all containers from both local and remote hosts.

**Describe alternatives you've considered**
The alternative is to have two dozzle instances - one for the local and one for the remote.

**Additional context**
Some additional thoughts - grouping by host instead of a single list.

**Comment by amir20** [comment]
Hi @GuyKh,

As I wrote in #688, I don't plan to support this. It's a very niche use case with a lot of effort to implement. I think having two Dozzle instances is an easy workaround. 

The UI can also have a way to change `DOCKER_HOST`. 

You could always write a proxy to merge your remote and local server. But again, why not just run two instances?

**Comment by GuyKh** [comment]
@amir20 
I disagree but respectfuly accept your answer.
Thanks.

**Comment by amir20** [comment]
It is now possible to set up remote hosts. See https://github.com/amir20/dozzle/#connecting-to-remote-hosts and https://github.com/amir20/dozzle/pull/2059
