### ISSUE TITLE
Time Format/Zone option

### ISSUE THREAD

**Issue by stve-a** [amir20/dozzle#785]
Hi, 

Would it be possible to allow time format changes ?

Currently it is like this "today at 3:13 PM"
Would like an option to change it to "today at 15:13"

Thanks
S

**Comment by amir20** [comment]
@stve-a this is already implemented in https://github.com/amir20/dozzle/issues/523. Dozzle will automatically detect your browser's locale and formats the time using it. 

If it isn't working for you, then it might be a bug or you don't have the right timezone set that favors 24 hour format.

**Comment by stve-a** [comment]
Hi @amir20 
Thanks for the quick reply.
I do have correct time information in my browser.
When I look at logs of containers through SSH and directly in the log itself, it has correct time formats
So it must be Dozzle that reformats them.
I'm using Chromium Microsoft EDGE as my main browser.
I tried Mozilla Firefox and Opera and those show the time format wrong also in Dozzle

**Comment by amir20** [comment]
I'll need to more information to debug this. The locale of your browser has nothing to do with `TZ` or SSH. All the formatting is done in the browser. 

1. What country are you in? 
2. What does https://www.localeplanet.com/support/browser.html print for javascript? 
3. If you know javascript, open your browser's console and run 
```
JSON.stringify(new Intl.DateTimeFormat(undefined, {hour: "numeric"}).formatToParts(new Date(2020, 0, 1, 13)))
```

**Comment by stve-a** [comment]
I see now:

`navigator.browserLanguage: undefined
navigator.language: en-US
navigator.userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.51
date: Mon Oct 26 2020 01:11:48 GMT+0100 (Central European Standard Time)
date.toLocaleDateString(): 10/26/2020
date.toLocaleTimeString(): 1:11:48 AM
date.toLocaleString(): 10/26/2020, 1:11:48 AM
date.toUTCString(): Mon, 26 Oct 2020 00:11:48 GMT
date.getTimezoneOffset(): -60`

Since my Chrome is in ENGLISH language it'll show the en-US format.
Would it be possible to provide an environment option that we can use perhaps ?

Thanks

**Comment by amir20** [comment]
I think the right feature would be to add a setting to "force 24-hr format". 

I don't have the bandwidth to do this now. But if someone else wants to add it I can help them. 

For now, you can use Firefox en-GB edition. I just tested it.

**Comment by stve-a** [comment]
ok thanks
