### ISSUE TITLE
How do I connect dozzle to my currently running swarm?

### ISSUE THREAD

**Issue by nimaafraz** [amir20/dozzle#794]
I have a running Swarm with containers spread around multiple machines. How do I connect Dozzle to show all containers' logs?

**Comment by amir20** [comment]
Hi @nimaafraz. Sadly, Dozzle doesn't support Swarm services. This has been something that I have been wanting to work on. See #496. 

I haven't had time to do this. There is also a bug where swarm logs are broken.
