### ISSUE TITLE
Horizontal split

### ISSUE THREAD

**Issue by raoul-thill** [amir20/dozzle#813]
I wish to have as an alternative to the vertical split also a horizontal split, which allows me to see longer log lines in a single line instead of the wrapped output in the vertical log views.

**Comment by amir20** [comment]
Hi @raoul-thill. This isn't something I plan to implement personally. The library I use already has support for this, but I see no value in making the UI more complicated which could take a lot of effort. Dozzle has been simple. 

If you want to provide a PR, then that could be great. The UX would need some love to make sure that it is easy to use.
