### ISSUE TITLE
ASCII art support

### ISSUE THREAD

**Issue by Majlanky** [amir20/dozzle#838]
It looks like Dozzle does some kind of line trimming. 

It breaks ASCII art which is used for example by the Spring Boot banner.

I know that it is not essential in this kind of tool but a developer feels proud when he sees the logo of his/her application 💘 

Is there any possibility of not to trim/format the lines or it would break the essential functionality?

PS: Dozzle is a very nice project! GJ 👍

**Comment by amir20** [comment]
Do you have a screenshot? It would be nice if you follow the template when creating a bug. As far as I know, ASCII characters works as expected.

**Comment by Majlanky** [comment]
I am sorry about the template. I did not know how to fit the request into it 😭 because I created a feature request not bug. I will try harder next time.
In the picture below you can see the difference between console output (at the bottom) and dozzer. The output of `docker container logs` matches the console output...

I am not sure if I described it clearly. The request is about spaces creating art, not characters themselves 😳 

![screen](https://user-images.githubusercontent.com/7602762/99834806-0bd27d00-2b64-11eb-8cc7-e59f4357bcf9.jpg)

**Comment by amir20** [comment]
I did some research. I am not sure how to fix it. I am using https://fonts.google.com/specimen/Roboto+Mono font. Which should be rendering ASCII art correctly. But when I tested it, I saw what you saw. 

Does anybody else know what CSS to use?

**Comment by Majlanky** [comment]
I do not think the font is the issue. IMHO the issue are missing white spaces at the beginning of each line. I am not Go developer but can [this line](https://github.com/amir20/dozzle/blob/c3b8ce53d116eaa87369f51bfc2401565958f105/docker/client.go#L148) the one that cause erasing the missing white-spaces (based on the [documentation](https://golang.org/pkg/strings/#TrimSpace) I guess so)?

**Comment by amir20** [comment]
Oh I didn't think of that. I believe I do `trim` to save space. Let me look at that.

**Comment by amir20** [comment]
I think my latest commit will fix this. Thanks for the suggestion. I had no idea the trim was breaking this

**Comment by amir20** [comment]
Planning to release an official build Monday.

**Comment by amir20** [comment]
This is live now. 🎉
