### ISSUE TITLE
Compose Project View / Scale

### ISSUE THREAD

**Issue by loiu92** [amir20/dozzle#874]
I using docker-compose to run my services and anything working fine.

But when i scale a service (ex: 6), 6 containers will running with the same thing, and i wish to see all those 6 containers simultaneously.
For now, i can see every containers 1 by 1, but i can't combine them on the view.

Thanks,

**Comment by amir20** [comment]
Hi @loiu92, you are creating services. Dozzle only works on containers right now. Docker swarm is not supported right now. 

It is a lot of effort to add it, so I don't plan to do it unless someone else can help.

**Comment by loiu92** [comment]
Sorry my mistake if i wasn't clear enough.
I don't use swarm.

I'm talking about combining docker containers logs. 
I wish to see many containers in one time if i select many of them on the side bar. (Not to have SWARM or Compose Support)

Because like i said, i scale with docker compose to many containers so i don't know in which containers my request will going.

**Comment by amir20** [comment]
I see what you mean now. Dozzle has panes that can be sticky but I think what you mean is having all containers showing logs in one view? I guess between doing separate split panes or what you mention, it made sense to do split panes.

**Comment by loiu92** [comment]
![Screenshot](https://snipboard.io/irBLAs.jpg)

I see what you mean, sticky panes are really a nice feature.
But as you can see on screen shot, if i have many of them, like 6 or 8, it's hard to looking 8 panes at a time.

So if we can have something like this: 
```js

<button @click="handle($event)">

handle(e) {
  if (e.shiftKey) this.data += e.target.value
  else this.data = e.target.value
}
```
If your click handler can handle shift or ctrl button to combine them in the view, should be amazing to use :dancing_women:

**Comment by amir20** [comment]
There was a conversation about this a while back. I don't think it makes sense to do shift or keyboard shortcuts. Because then it would be very hard to discover these functionalities. In my opinion, UX should be simple and easy enough without requiring to reading documentation. 

Given no one has asked for this specific feature, I won't work on it until it becomes more popular. 

Perhaps, a better solution would be to replace panes. But then a group of other people would miss that.

**Comment by amir20** [comment]
I don't plan to work on this so closing.
