### ISSUE TITLE
Organization of Container List

### ISSUE THREAD

**Issue by kmlucy** [amir20/dozzle#9]
I have one bug, and two requests/questions for the list of containers on the left of the page. For the bug, when you have more containers than fit on the screen, there is no way to access the lower ones. Scrolling only scrolls the logs, not the container list. 

For the organization, it appears to be sorted by when the container was created. Is there a way to sort alphabetically? Also, each container name is preceded by a slash. Is there a reason behind that, or can it be removed. This also affects the title bar, ie the title is `/nginx - Dozzle` rather than `nginx - Dozzle`.

**Comment by amir20** [comment]
So three questions here: 

1. scrolling -- I haven't added any type of scrolling yet. Let me play with it and see if I can make it scroll. Being responsive is also a challenge. 

2. Sorting -- I am just taking order from Docker. Sorting wouldn't be hard. Do you think it's worth adding sorting options (a lot of work) or just sort always alphabetically? 

3. Slashes -- If you look at `/api/containers.json` you will see the data I get back from Docker. It looks like 

```json
{
    "Id": "9d4972a452131b5e9ef886c3314cfe787ab112982ca0c4181e200369fbb9208a",
    "Names": [
      "/dozzle"
    ],
    "Image": "amir20/dozzle:latest",
    "ImageID": "sha256:3de940096f8abc20be86669679c500db2eeca37784ec9f70bac2b770075bf8f5",
    "Command": "/dozzle",
    "Created": 1543259310,
    "Ports": [],
    "State": "running",
    "Status": "Up 2 hours",
    "HostConfig": {},
    "NetworkSettings": {},
    "Mounts": []
  },
```

I am not sure why Docker Engine by default returns slashes in the name. I can strip it. But I thought maybe it means something.

**Comment by kmlucy** [comment]
1. Ideally, I think it would work something like Netdata, where the body and menu scroll independently: [Example](https://atlanta.my-netdata.io/default.html#menu_system_submenu_load;theme=slate) and [GitHub](https://github.com/netdata/netdata)

2. Personally, always sorting alphabetically would be fine with me. I can see use cases for others where sorting options might be useful, but that might be something to consider down the road, or see if anyone else requests it.

3. I did a little research. Apparently the slash represents the Docker daemon being the parent container. The slash is stripped out for things like docker ps and the like, but left for inspect as it exposes the inner workings of the container. Since Dozzle has user interaction, it makes more sense to me to strip it out and match the Docker CLI tools.

**Comment by amir20** [comment]
Alright, with `dozzle:v1.3.1` I added two things. 

1. Docker containers are now sorted alphabetically. 
2. `/` from the beginning of names is removed. 

I tried adding a scrollbar, but then the tooltip is hidden. Which is not what I wanted. 👎 Seems to be a CSS bug I had never known about. So I have two options: 1. remove tooltips and just scroll. 2. Find a different way to show all like pagination. 

I had originally kept the tooltips because I use Dozzle in swarm which means sometimes the names very long. I am not sure what to do now. I'll keep thinking about it. 

How many containers are you running?

**Comment by amir20** [comment]
I am thinking of just removing tooltips since now on the iPad it is responsive. Thoughts?

**Comment by amir20** [comment]
@kmlucy Try `v1.3.2` https://github.com/amir20/dozzle/releases/tag/v1.3.2. I decided to just remove the tooltip as it added no values IMO. Now the left side should scroll. 

I can close if everything works for you.

**Comment by kmlucy** [comment]
That looks good. I agree, I don't think the tooltip added much value, and scrolling is definitely more valuable. The names and sorting looks good to me, thanks!

**Comment by amir20** [comment]
@kmlucy 🎂 

Thanks for your feedback so far!  How do you think I get more audience for Dozzle? I got some people on /r/docker. But I don't want to keep posting it there.

**Comment by kmlucy** [comment]
It's been super helpful to me, so I'm glad to help. 

I found it through r/docker, so I'm not sure the best places to post about it. You could try places that use a lot of Docker containers, like the Unraid or LinuxServer.io forums.
