### ISSUE TITLE
Support for Json logs 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#920]
**Is your feature request related to a problem? Please describe.**
Structured logging is more powerful than plain text. Dozzle should support JSON logs. 

**Describe the solution you'd like**
A way to map specific fields to timestamp, level and message. Support for opening showing more details per log line. 

**Describe alternatives you've considered**
None

**Additional context**
This is a placeholder. I'd like to get feedback from others.

**Comment by amir20** [comment]
Hi everybody, Dozzle is mature enough now to support other log formats. JSON is a popular format. Mongo container by default only spits our json logs. 

I'd like to get feedback from others.

1. Would this feature be useful?
2. How would you expect it to work?
3. What are you currently doing in Dozzle with structured logs?

**Comment by KarneAsada** [comment]
@amir20 I just started using Dozzle in my dev stack and it's been a great addition to our docker-compose development workflow. Support for JSON would be **really** useful! 

I'm currently not using JSON logs with Dozzle because they are hard to read. We use datadog in production, which parses our JSON format, so I would expect it to work similarly. Users could configure which properties they want displayed in Dozzle (like date/time, level, message) and then clicking a row could expand all of the json properties.

**Comment by amir20** [comment]
Hi @KarneAsada. Thanks for the feedback. I had similar thoughts as well. I am curious, how does Datadog let you configure the different properties.

**Comment by KarneAsada** [comment]
Agreed, datadog is very complex. They also have a lot of built in pattern recognition to recognize popular formats. I think letting users configure a few main fields would be helpful without being too complex.

**Comment by amir20** [comment]
@KarneAsada do you think the json properties should be configurable per container or globally? So for example, maybe Mongo uses `msg` property and another container uses `message`. 

Globally, the configuration can be use any of `['msg', 'message']` for message field. 
Per containers, it would be `msg` for `mongo:*` and `message` for another. 

Globally sounds easier. But I am not sure which is better.

**Comment by amir20** [comment]
All, doesn't look like enough people have expressed interest in this. I did some research and it would be a few days of coding. I don't plan to work on it anymore given the cost.

**Comment by erwinkramer** [comment]
@amir20 thanks for your response,

> @erwinkramer That's not valid JSON. Caddy (or whatever you are using) is passing string literal and not correct JSON. Dozzle can't do anything.

Yeah maybe that wasn't a good example. Caddy does output json in some logs, see below, that's a bit more readable:

![image](https://github.com/user-attachments/assets/f5acb98f-87ff-47d9-91fe-27d4215f91fe)

> That's pretty hard to do. I would have to parse the JSON and break after each key.

All i'm asking is for something like this, so a copy button for `level`, `ts`, `logger` etc ...  so no need to parse a JSON field individually:

![image](https://github.com/user-attachments/assets/3fa611e6-65c3-4f70-a553-3bdaa528b7de)


> > Third: If it's not json, but includes newline characters, there should be a pretty print view where are newlines are really newlines, not \n\ or t\ for example.
> 
> I am not processing them. It's whatever comes from Docker. It seems like it is escaped twice though, that's why you see it like this way.

You do display the value nicely in the log itself:

![image](https://github.com/user-attachments/assets/a0faeaf7-235f-44e7-ab65-02afd727de20)

but when you click on it, you get the escaped values with it: 

![image](https://github.com/user-attachments/assets/7229650b-5333-482c-869c-ad4606f34b4a)

**Comment by thdebay** [comment]
I'm not sure it would apply to this use case as well but I'm having issues with the logs produced by Monolog (on Symfony)

```json
{"message":"Matched route &#34;ping&#34;.","context":{"method":"GET","request_uri":"http://172.19.0.17/api/_ping","route":"ping","route_parameters":{"_controller":"App\\Controller\\PingController::index","_route":"ping"}},"level":200,"level_name":"INFO","channel":"request","datetime":"2025-01-16T13:03:40.824297+00:00","extra":{}}
```

The fields are detected but are not mapped correctly (level and level_name are interverted).

<img width="719" alt="Image" src="https://github.com/user-attachments/assets/005f1bdc-d8ed-46cc-a54d-4727bc620a41" />

Is that something the current issue relates to? I would be happy to submit a PR if something can be done to improve the user experience here.

**Comment by amir20** [comment]
@erwinkramer 

> All i'm asking is for something like this, so a copy button for level, ts, logger etc ... so no need to parse a JSON field individually

It would be great for the community to send PRs for simple things. I haven't seen a lot of people asking for this so less reason for me to spend time doing it. 

> You do display the value nicely in the log itself:

That's because I format everything with `JSON.strinfigy`. It's still not valid JSON. It just looks like it. But if you look at closely, the keys and values are not found.

**Comment by amir20** [comment]
@thdebay 

I don't see what's broken here. What do you mean "inverted"?

**Comment by amir20** [comment]
> But I still don't understand why I can't filter log messages by level. Perhaps the filter is effective on the level field and not level_name? 🤔

That's right. Dozzle looks for `level` to match that. `level_name` is not standard. You could use search to find "info", but if you want the benefit of using different log levels, you'll have to change the log level to use `level` as the key.
