### ISSUE TITLE
Feature request: service logs

### ISSUE THREAD

**Issue by moejetz** [amir20/dozzle#961]
Hi!
First of all, thank you for your fantastic work!

I have a feature request: an endpoint for docker service logs additionally to docker container logs.

Background:
If we deploy a service in a Docker swarm environment and the container cannot boot because there is a problem, Docker will boot and shutdown containers all the time. So, we cannot see container logs because the lifetime of the containers are too short. With service logs, you would see the aggregated logs of the containers which allows you to see the actual error that causes the containers to shutdown.

Would be nice to see this in the future, thanks in advance :)

**Comment by amir20** [comment]
Hi @moejetz,

You are welcome. 

If I understand correctly you mean [`docker service logs`](https://docs.docker.com/engine/reference/commandline/service_logs/). I have been wanting to add support for this. Dozzle will need to support Swarm to do this. 

However, this is a lot of work. I will have to essentially duplicate all APIs for Dockers and Services. 

I don't plan to work on this so if someone wants to help, PRs are welcomed.

**Comment by avaidyam** [comment]
@amir20 Where do you think in the code these changes would need to happen? I'm interested in implementing a basic version of this (service logs but also most importantly container logs across swam nodes).

**Comment by amir20** [comment]
@avaidyam There is a few places you would need to change for this to work. It start with go code first. 

1. Update the [client for docker](https://github.com/amir20/dozzle/blob/master/docker/client.go) to support swarm and services. Right now it's all based on containers. But there are methods like List, Find and GetLogs that need to be updated for services
2. Update the [web routes](https://github.com/amir20/dozzle/blob/master/web/routes.go) to fetch such services
3. Add settings to have support for services
4. Update Vue code to support it

I could help with you some things if you start it. I imagine it could take a couple weeks of focus.

**Comment by avaidyam** [comment]
Ah, I realize this is written mostly in Go now and I have limited experience there. Apologies, but thank you for sharing the steps!

**Comment by danielporto** [comment]
Thanks for your work.

I just want to add that you should make it more explicit that it wont work in swarm as people are expecting.
Even if the problem is not in dozzle itself, i think is a bad thing not being open about it and also close many issues unsolved. It doesnt convey a good message. 

I think it could be used as a selfhosted lightweight alternative to log stacks like graylog, elk, fluentd, for dev/staging deployments where logs from all containers could be visualized in a single place, like portainer do but more easily and feature rich.
it is not. 
not yet at least.
