### ISSUE TITLE
[FEATURE REQUEST] - Auto Refresh or reconnect if container is cycled

### ISSUE THREAD

**Issue by ondrovic** [amir20/dozzle#976]
**Is your feature request related to a problem? Please describe.**
If you restart a container you have to refresh in order to see the new logs

**Describe the solution you'd like**
The ability to toggle ui refresh and select the previous container not sure if you can have it fire automatically if it detects 'Container Stopped'

**Describe alternatives you've considered**
Manually Refreshing the ui

**Comment by amir20** [comment]
> Manually Refreshing the ui

The UI refresh automatically when new containers have been started. 

> The ability to toggle ui refresh and select the previous container

You need to go to settings and "show stopped containers"

> If you restart a container you have to refresh in order to see the new logs

The container ID changes so it's really hard to guess the container ID.
